import { SUPPORTED_APP_LOCALES, normalizeAppLocale } from '@/components/i18n/appLocale';

export const HUMAN_SUPPORT_DIRECTORY_VERSION = '2026-09-06.2';
export const SUPPORTED_HUMAN_SUPPORT_REGIONS = Object.freeze(['US', 'IL', 'ES', 'FR', 'DE', 'IT', 'PT']);

export const HUMAN_SUPPORT_SOURCES = Object.freeze({
  us988: 'https://988lifeline.org/', usImmediateDanger: 'https://988lifeline.org/contact-us/',
  israelMinistryOfHealth: 'https://me.health.gov.il/mental-health/therapy-rehabilitation/crisis-support/first-aid/',
  israelImmediateDanger: 'https://me.health.gov.il/mental-health/information-and-updates/prevention-of-suicide/how-to-talk-to-a-suicidal-person/',
  eran: 'https://www.eran.org.il/', spain024: 'https://www.sanidad.gob.es/linea024/home.htm',
  france3114: 'https://3114.fr/', germanyTelefonSeelsorge: 'https://www.telefonseelsorge.de/',
  italyTelefonoAmico: 'https://www.telefonoamico.it/',
  portugalSns24: 'https://www.sns24.gov.pt/pt/servico/aconselhamento-psicologico-no-sns-24/',
  portugalImmediateDanger: 'https://www.sns24.gov.pt/pt/tema/prevencao-e-cuidados-de-saude/prevencao-do-suicidio/',
  eu112: 'https://digital-strategy.ec.europa.eu/en/policies/112',
  internationalDirectory: 'https://www.iasp.info/crisis-centres-helplines/',
});

export const HUMAN_SUPPORT_REGION_LABELS = Object.freeze({
  en: Object.freeze({ US: 'United States', IL: 'Israel', ES: 'Spain', FR: 'France', DE: 'Germany', IT: 'Italy', PT: 'Portugal' }),
  he: Object.freeze({ US: 'ארצות הברית', IL: 'ישראל', ES: 'ספרד', FR: 'צרפת', DE: 'גרמניה', IT: 'איטליה', PT: 'פורטוגל' }),
  es: Object.freeze({ US: 'Estados Unidos', IL: 'Israel', ES: 'España', FR: 'Francia', DE: 'Alemania', IT: 'Italia', PT: 'Portugal' }),
  fr: Object.freeze({ US: 'États-Unis', IL: 'Israël', ES: 'Espagne', FR: 'France', DE: 'Allemagne', IT: 'Italie', PT: 'Portugal' }),
  de: Object.freeze({ US: 'Vereinigte Staaten', IL: 'Israel', ES: 'Spanien', FR: 'Frankreich', DE: 'Deutschland', IT: 'Italien', PT: 'Portugal' }),
  it: Object.freeze({ US: 'Stati Uniti', IL: 'Israele', ES: 'Spagna', FR: 'Francia', DE: 'Germania', IT: 'Italia', PT: 'Portogallo' }),
  pt: Object.freeze({ US: 'Estados Unidos', IL: 'Israel', ES: 'Espanha', FR: 'França', DE: 'Alemanha', IT: 'Itália', PT: 'Portugal' }),
});

export const HUMAN_SUPPORT_COPY = Object.freeze({
  en: Object.freeze({ buttonLabel: 'Human support', title: 'Human support', intro: 'Choose your current country to see the appropriate services. Language does not determine location.', countryLabel: 'Country or region', countryPrompt: 'Choose a country', privacyNote: 'Your choice is stored only on this device. The app does not request GPS location.', selectionRequired: 'Choose a country to display verified contact options.', immediateTitle: 'Immediate danger', immediateText: 'Do not rely on this app. Call emergency services now or go to the nearest emergency department.', urgentTitle: 'Emotional support now', urgentText: 'Contact a crisis or emotional-support service in the selected country.', otherTitle: 'More support', otherText: 'Use an official local resource or the international directory to find additional help.', verified: 'Last verified', source: 'Official source', always: 'Available 24/7', checkHours: 'Check current hours on the official site', disclaimer: 'Mindful Path provides CBT-informed self-help tools. It is not a crisis service and is not a replacement for licensed professional care.', productSupport: 'For technical support or app feedback only:', about: 'About', privacy: 'Privacy Policy', terms: 'Terms of Use' }),
  he: Object.freeze({ buttonLabel: 'עזרה אנושית', title: 'עזרה אנושית', intro: 'בחרו את המדינה שבה אתם נמצאים כעת כדי להציג שירותים מתאימים. שפת הממשק אינה קובעת את המיקום.', countryLabel: 'מדינה או אזור', countryPrompt: 'בחירת מדינה', privacyNote: 'הבחירה נשמרת במכשיר הזה בלבד. האפליקציה אינה מבקשת מיקום GPS.', selectionRequired: 'יש לבחור מדינה כדי להציג אפשרויות קשר מאומתות.', immediateTitle: 'סכנה מיידית', immediateText: 'אל תסתמכו על האפליקציה. התקשרו עכשיו לשירותי החירום או פנו לחדר המיון הקרוב.', urgentTitle: 'תמיכה רגשית עכשיו', urgentText: 'פנו לקו משבר או לשירות תמיכה רגשית במדינה שנבחרה.', otherTitle: 'תמיכה נוספת', otherText: 'השתמשו במשאב מקומי רשמי או בספרייה הבינלאומית למציאת עזרה נוספת.', verified: 'אומת לאחרונה', source: 'מקור רשמי', always: 'זמין 24/7', checkHours: 'יש לבדוק שעות פעילות עדכניות באתר הרשמי', disclaimer: 'Mindful Path מציעה כלי עזרה עצמית בגישת CBT. היא אינה שירות חירום ואינה תחליף לטיפול של איש או אשת מקצוע מורשים.', productSupport: 'לתמיכה טכנית או משוב על האפליקציה בלבד:', about: 'אודות', privacy: 'מדיניות פרטיות', terms: 'תנאי שימוש' }),
  es: Object.freeze({ buttonLabel: 'Ayuda humana', title: 'Ayuda humana', intro: 'Selecciona el país en el que te encuentras para ver los servicios adecuados. El idioma no determina la ubicación.', countryLabel: 'País o región', countryPrompt: 'Selecciona un país', privacyNote: 'La selección se guarda solo en este dispositivo. La aplicación no solicita la ubicación GPS.', selectionRequired: 'Selecciona un país para mostrar opciones de contacto verificadas.', immediateTitle: 'Peligro inmediato', immediateText: 'No dependas de esta aplicación. Llama ahora a emergencias o acude al servicio de urgencias más cercano.', urgentTitle: 'Apoyo emocional ahora', urgentText: 'Contacta con un servicio de crisis o apoyo emocional del país seleccionado.', otherTitle: 'Más apoyo', otherText: 'Usa un recurso local oficial o el directorio internacional para encontrar más ayuda.', verified: 'Última verificación', source: 'Fuente oficial', always: 'Disponible 24/7', checkHours: 'Consulta el horario actual en el sitio oficial', disclaimer: 'Mindful Path ofrece herramientas de autoayuda basadas en principios de TCC. No es un servicio de crisis ni sustituye la atención profesional autorizada.', productSupport: 'Solo para soporte técnico o comentarios sobre la aplicación:', about: 'Acerca de', privacy: 'Privacidad', terms: 'Términos de uso' }),
  fr: Object.freeze({ buttonLabel: 'Aide humaine', title: 'Aide humaine', intro: 'Sélectionnez le pays où vous vous trouvez pour afficher les services adaptés. La langue ne détermine pas le lieu.', countryLabel: 'Pays ou région', countryPrompt: 'Sélectionner un pays', privacyNote: "Le choix est enregistré uniquement sur cet appareil. L’application ne demande pas la position GPS.", selectionRequired: 'Sélectionnez un pays pour afficher des contacts vérifiés.', immediateTitle: 'Danger immédiat', immediateText: "Ne comptez pas sur cette application. Appelez les urgences maintenant ou rendez-vous au service d’urgence le plus proche.", urgentTitle: 'Soutien émotionnel immédiat', urgentText: 'Contactez un service de crise ou de soutien émotionnel dans le pays sélectionné.', otherTitle: 'Autres soutiens', otherText: "Utilisez une ressource locale officielle ou l’annuaire international pour trouver une aide supplémentaire.", verified: 'Dernière vérification', source: 'Source officielle', always: 'Disponible 24 h/24, 7 j/7', checkHours: 'Vérifiez les horaires actuels sur le site officiel', disclaimer: "Mindful Path propose des outils d’auto-assistance inspirés de la TCC. Ce n’est pas un service de crise et cela ne remplace pas les soins d’un professionnel agréé.", productSupport: "Uniquement pour l’assistance technique ou les commentaires sur l’application :", about: 'À propos', privacy: 'Confidentialité', terms: "Conditions d’utilisation" }),
  de: Object.freeze({ buttonLabel: 'Menschliche Hilfe', title: 'Menschliche Hilfe', intro: 'Wählen Sie das Land, in dem Sie sich gerade befinden. Die Sprache bestimmt nicht den Standort.', countryLabel: 'Land oder Region', countryPrompt: 'Land auswählen', privacyNote: 'Die Auswahl wird nur auf diesem Gerät gespeichert. Die App fragt keinen GPS-Standort ab.', selectionRequired: 'Wählen Sie ein Land, um geprüfte Kontaktmöglichkeiten anzuzeigen.', immediateTitle: 'Unmittelbare Gefahr', immediateText: 'Verlassen Sie sich nicht auf diese App. Rufen Sie jetzt den Notruf an oder gehen Sie zur nächsten Notaufnahme.', urgentTitle: 'Emotionale Unterstützung jetzt', urgentText: 'Kontaktieren Sie einen Krisen- oder Beratungsdienst im ausgewählten Land.', otherTitle: 'Weitere Unterstützung', otherText: 'Nutzen Sie eine offizielle lokale Ressource oder das internationale Verzeichnis für weitere Hilfe.', verified: 'Zuletzt geprüft', source: 'Offizielle Quelle', always: 'Rund um die Uhr verfügbar', checkHours: 'Aktuelle Zeiten auf der offiziellen Website prüfen', disclaimer: 'Mindful Path bietet CBT-orientierte Selbsthilfewerkzeuge. Die App ist kein Krisendienst und ersetzt keine Behandlung durch zugelassene Fachkräfte.', productSupport: 'Nur für technischen Support oder Feedback zur App:', about: 'Über uns', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen' }),
  it: Object.freeze({ buttonLabel: 'Aiuto umano', title: 'Aiuto umano', intro: 'Seleziona il Paese in cui ti trovi per vedere i servizi appropriati. La lingua non determina la posizione.', countryLabel: 'Paese o regione', countryPrompt: 'Seleziona un Paese', privacyNote: "La scelta viene salvata solo su questo dispositivo. L’app non richiede la posizione GPS.", selectionRequired: 'Seleziona un Paese per visualizzare contatti verificati.', immediateTitle: 'Pericolo immediato', immediateText: 'Non fare affidamento su questa app. Chiama subito i servizi di emergenza o recati al pronto soccorso più vicino.', urgentTitle: 'Supporto emotivo immediato', urgentText: 'Contatta un servizio di crisi o di supporto emotivo nel Paese selezionato.', otherTitle: 'Altro supporto', otherText: 'Usa una risorsa locale ufficiale o l’elenco internazionale per trovare ulteriore aiuto.', verified: 'Ultima verifica', source: 'Fonte ufficiale', always: 'Disponibile 24 ore su 24, 7 giorni su 7', checkHours: 'Verifica gli orari aggiornati sul sito ufficiale', disclaimer: 'Mindful Path offre strumenti di auto-aiuto ispirati alla TCC. Non è un servizio di crisi e non sostituisce le cure di un professionista abilitato.', productSupport: "Solo per assistenza tecnica o commenti sull’app:", about: 'Informazioni', privacy: 'Privacy', terms: "Termini d’uso" }),
  pt: Object.freeze({ buttonLabel: 'Ajuda humana', title: 'Ajuda humana', intro: 'Selecione o país onde se encontra para ver os serviços adequados. O idioma não determina a localização.', countryLabel: 'País ou região', countryPrompt: 'Selecionar um país', privacyNote: 'A seleção é guardada apenas neste dispositivo. A aplicação não solicita a localização GPS.', selectionRequired: 'Selecione um país para apresentar contactos verificados.', immediateTitle: 'Perigo imediato', immediateText: 'Não dependa desta aplicação. Ligue agora para a emergência ou dirija-se ao serviço de urgência mais próximo.', urgentTitle: 'Apoio emocional agora', urgentText: 'Contacte um serviço de crise ou apoio emocional no país selecionado.', otherTitle: 'Mais apoio', otherText: 'Use um recurso local oficial ou o diretório internacional para encontrar ajuda adicional.', verified: 'Última verificação', source: 'Fonte oficial', always: 'Disponível 24 horas por dia, 7 dias por semana', checkHours: 'Consulte o horário atual no site oficial', disclaimer: 'A Mindful Path oferece ferramentas de autoajuda baseadas em princípios de TCC. Não é um serviço de crise nem substitui cuidados de um profissional habilitado.', productSupport: 'Apenas para suporte técnico ou comentários sobre a aplicação:', about: 'Sobre', privacy: 'Privacidade', terms: 'Termos de utilização' }),
});

const verification = Object.freeze({ lastVerifiedAt: '2026-09-06', verificationOwner: 'Mindful Path content safety review' });
const entry = (country, resource) => Object.freeze({ ...verification, country, ...resource });
const globalDirectory = (country) => entry(country, { id: `${country.toLowerCase()}-international-directory`, urgency: 'non_emergency', name: 'IASP / Find a Helpline', availability: 'check_hours', channels: Object.freeze([{ type: 'web', label: 'IASP', href: HUMAN_SUPPORT_SOURCES.internationalDirectory }]), sourceUrl: HUMAN_SUPPORT_SOURCES.internationalDirectory });

export const HUMAN_SUPPORT_DIRECTORY_BY_REGION = Object.freeze({
  US: Object.freeze([
    entry('US', { id: 'us-emergency', urgency: 'immediate', name: '911', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '911', href: 'tel:911' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.usImmediateDanger }),
    entry('US', { id: 'us-988', urgency: 'urgent_support', name: '988 Suicide & Crisis Lifeline', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '988', href: 'tel:988' }, { type: 'web', label: '988 Lifeline', href: HUMAN_SUPPORT_SOURCES.us988 }]), sourceUrl: HUMAN_SUPPORT_SOURCES.us988 }), globalDirectory('US')]),
  IL: Object.freeze([
    entry('IL', { id: 'israel-police', urgency: 'immediate', name: 'משטרת ישראל / Israel Police', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '100', href: 'tel:100' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.israelImmediateDanger }),
    entry('IL', { id: 'magen-david-adom', urgency: 'immediate', name: 'מגן דוד אדום / Magen David Adom', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '101', href: 'tel:101' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.israelImmediateDanger }),
    entry('IL', { id: 'eran', urgency: 'urgent_support', name: 'ער״ן / ERAN', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '1201', href: 'tel:1201' }, { type: 'whatsapp', label: 'WhatsApp 052-8451201', href: 'https://wa.me/972528451201' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.eran }),
    entry('IL', { id: 'health-funds', urgency: 'non_emergency', name: 'קופות החולים / Health funds', availability: 'always', detail: 'Clalit *8703 · Maccabi *3555 · Meuhedet *3833 · Leumit *507', channels: Object.freeze([{ type: 'web', label: 'gov.il', href: HUMAN_SUPPORT_SOURCES.israelMinistryOfHealth }]), sourceUrl: HUMAN_SUPPORT_SOURCES.israelMinistryOfHealth }), globalDirectory('IL')]),
  ES: Object.freeze([entry('ES', { id: 'spain-emergency', urgency: 'immediate', name: '112', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '112', href: 'tel:112' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.spain024 }), entry('ES', { id: 'spain-024', urgency: 'urgent_support', name: 'Línea 024', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '024', href: 'tel:024' }, { type: 'web', label: 'sanidad.gob.es', href: HUMAN_SUPPORT_SOURCES.spain024 }]), sourceUrl: HUMAN_SUPPORT_SOURCES.spain024 }), globalDirectory('ES')]),
  FR: Object.freeze([entry('FR', { id: 'france-emergency', urgency: 'immediate', name: '112', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '112', href: 'tel:112' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.eu112 }), entry('FR', { id: 'france-3114', urgency: 'urgent_support', name: '3114 – Prévention du suicide', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '3114', href: 'tel:3114' }, { type: 'web', label: '3114.fr', href: HUMAN_SUPPORT_SOURCES.france3114 }]), sourceUrl: HUMAN_SUPPORT_SOURCES.france3114 }), globalDirectory('FR')]),
  DE: Object.freeze([entry('DE', { id: 'germany-emergency', urgency: 'immediate', name: '112', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '112', href: 'tel:112' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.eu112 }), entry('DE', { id: 'germany-telefonseelsorge', urgency: 'urgent_support', name: 'TelefonSeelsorge', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '116 123', href: 'tel:116123' }, { type: 'phone', label: '0800 111 0 111', href: 'tel:08001110111' }, { type: 'web', label: 'telefonseelsorge.de', href: HUMAN_SUPPORT_SOURCES.germanyTelefonSeelsorge }]), sourceUrl: HUMAN_SUPPORT_SOURCES.germanyTelefonSeelsorge }), globalDirectory('DE')]),
  IT: Object.freeze([entry('IT', { id: 'italy-emergency', urgency: 'immediate', name: '112', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '112', href: 'tel:112' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.eu112 }), entry('IT', { id: 'italy-telefono-amico', urgency: 'urgent_support', name: 'Telefono Amico Italia', availability: 'check_hours', channels: Object.freeze([{ type: 'phone', label: '02 2327 2327', href: 'tel:0223272327' }, { type: 'web', label: 'telefonoamico.it', href: HUMAN_SUPPORT_SOURCES.italyTelefonoAmico }]), sourceUrl: HUMAN_SUPPORT_SOURCES.italyTelefonoAmico }), globalDirectory('IT')]),
  PT: Object.freeze([entry('PT', { id: 'portugal-emergency', urgency: 'immediate', name: '112', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '112', href: 'tel:112' }]), sourceUrl: HUMAN_SUPPORT_SOURCES.portugalImmediateDanger }), entry('PT', { id: 'portugal-sns24', urgency: 'urgent_support', name: 'Aconselhamento Psicológico SNS 24', availability: 'always', channels: Object.freeze([{ type: 'phone', label: '808 24 24 24', href: 'tel:808242424' }, { type: 'web', label: 'sns24.gov.pt', href: HUMAN_SUPPORT_SOURCES.portugalSns24 }]), sourceUrl: HUMAN_SUPPORT_SOURCES.portugalSns24 }), globalDirectory('PT')]),
});

export function getHumanSupportCopy(locale) { return HUMAN_SUPPORT_COPY[normalizeAppLocale(locale, 'en')]; }
export function getHumanSupportRegionOptions(locale) { const normalized = normalizeAppLocale(locale, 'en'); return SUPPORTED_HUMAN_SUPPORT_REGIONS.map((value) => ({ value, label: HUMAN_SUPPORT_REGION_LABELS[normalized][value] })); }
export function getHumanSupportResources(region, urgency) { const resources = HUMAN_SUPPORT_DIRECTORY_BY_REGION[region] || []; return urgency ? resources.filter((resource) => resource.urgency === urgency) : resources; }
export function hasCompleteHumanSupportTranslations() { return SUPPORTED_APP_LOCALES.every((locale) => HUMAN_SUPPORT_COPY[locale] && HUMAN_SUPPORT_REGION_LABELS[locale]); }
