export const BATCH_2 = [
  {
    title: "Generalised Anxiety: Worry Postponement",
    topic: "anxiety",
    subtopic: "generalised anxiety",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "Worry postponement is a CBT technique for GAD in which clients schedule a specific 20\u201330 minute \u2018worry period\u2019 each day. When worry intrudes outside this window, the client notes the worry and postpones engaging with it until the scheduled time. This breaks the pattern of uncontrolled rumination throughout the day and teaches that worry can be deferred. During the scheduled period, the client engages with worries actively, often using problem-solving or cognitive restructuring. Research shows this reduces overall worry frequency and distress.",
    short_summary: "Describes scheduled worry postponement as a GAD technique to confine rumination to a daily window.",
    tags: ["GAD", "worry", "postponement", "anxiety", "rumination"],
    source_name: "Borkovec GAD Protocol",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Social Anxiety: Safety Behaviour Fading",
    topic: "anxiety",
    subtopic: "social anxiety",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "Safety behaviours are actions taken to prevent feared social catastrophes (e.g., avoiding eye contact, over-preparing scripts, sitting near exits). Although they reduce short-term anxiety, safety behaviours maintain social anxiety by preventing disconfirmation of feared outcomes and increasing self-focused attention. The CBT approach involves psychoeducation about safety behaviour function, collaborative identification of the client\u2019s specific safety behaviours, and systematic fading during graded exposure exercises. Drop experiments \u2014 comparing performance with and without safety behaviours \u2014 powerfully demonstrate their counterproductive effects.",
    short_summary: "Explains how safety behaviours maintain social anxiety and outlines a fading-via-drop-experiments approach.",
    tags: ["social anxiety", "safety behaviours", "exposure", "SAD"],
    source_name: "Clark & Wells Social Anxiety Model",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "OCD: ERP Hierarchy Construction",
    topic: "anxiety",
    subtopic: "OCD",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "Constructing an ERP hierarchy for OCD involves collaboratively listing feared situations, objects, or thoughts and rating each for subjective units of distress (SUDS, 0\u2013100). Items are ordered from least to most distressing. ERP begins at a manageable SUDS level (typically 40\u201360) and progresses up the hierarchy as the client habituates. Each exposure is held until anxiety naturally decreases by at least 50% or for a minimum of 45 minutes. Imaginal and in-vivo exposures are combined where appropriate. The hierarchy is revisited regularly to reflect progress and add new items.",
    short_summary: "Guides ERP hierarchy construction for OCD using SUDS ratings with graduated exposure from manageable starting points.",
    tags: ["OCD", "ERP", "hierarchy", "SUDS", "exposure"],
    source_name: "Foa & Kozak ERP Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Do not begin ERP during acute crisis or with active suicidal ideation.",
    contraindications: "Active suicidality; severe depression requiring stabilisation first.",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Trauma-Focused CBT: Psychoeducation Phase",
    topic: "trauma",
    subtopic: "PTSD",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "The psychoeducation phase of TF-CBT normalises trauma responses by explaining the neuroscience of the stress response, the role of avoidance in PTSD maintenance, and the rationale for treatment. Key messages include: trauma reactions are normal responses to abnormal events; the brain\u2019s threat system (amygdala) becomes hypersensitive after trauma; avoidance reduces short-term distress but maintains PTSD long-term. Clients receive a simplified model of PTSD and an explanation of how exposure-based treatment re-consolidates traumatic memories and reduces their emotional charge.",
    short_summary: "Covers the TF-CBT psychoeducation phase: normalising PTSD responses, amygdala sensitisation, and treatment rationale.",
    tags: ["trauma", "PTSD", "psychoeducation", "TF-CBT"],
    source_name: "Resick & Schnicke CPT Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Ensure safety and stabilisation before commencing trauma processing.",
    contraindications: "Active self-harm; ongoing abuse situation; severe dissociation without specialist support.",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Cognitive Processing Therapy: Stuck Points",
    topic: "trauma",
    subtopic: "CPT",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Stuck points are unhelpful beliefs about oneself, others, or the world that develop or are reinforced after trauma (e.g., \u2018The world is completely dangerous\u2019, \u2018It was my fault\u2019, \u2018I am permanently damaged\u2019). In Cognitive Processing Therapy (CPT), identifying and challenging stuck points is central. Clients complete impact statements describing the meaning of the trauma, then use Socratic questioning and structured worksheets to examine evidence and develop more balanced, accurate beliefs. The five themes of stuck points are safety, trust, power/control, esteem, and intimacy.",
    short_summary: "Defines CPT stuck points across five themes and outlines the worksheet-based Socratic process for challenging them.",
    tags: ["CPT", "trauma", "stuck points", "PTSD", "cognitive restructuring"],
    source_name: "Resick & Schnicke CPT Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Not suitable as standalone without trauma-informed framework.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Motivational Interviewing: Change Talk Elicitation",
    topic: "behavior change",
    subtopic: "motivational interviewing",
    population: "general",
    clinical_goal: "behavior change",
    content: "Change talk consists of client statements that favour movement toward change. Miller and Rollnick categorise change talk as DARN-CAT: Desire (\u2018I want to\u2026\u2019), Ability (\u2018I could\u2026\u2019), Reason (\u2018It would help me\u2026\u2019), Need (\u2018I have to\u2026\u2019), Commitment (\u2018I will\u2026\u2019), Activation (\u2018I am ready to\u2026\u2019), Taking steps (\u2018I have already\u2026\u2019). Therapists elicit change talk by asking evocative questions, exploring goals and values, and using the decisional balance. Sustain talk is acknowledged without reinforcement.",
    short_summary: "Explains the DARN-CAT change talk framework and MI strategies for eliciting client motivation.",
    tags: ["motivational interviewing", "change talk", "MI", "behaviour change"],
    source_name: "Miller & Rollnick MI Third Edition",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Acceptance and Commitment Therapy: Psychological Flexibility",
    topic: "anxiety",
    subtopic: "ACT",
    population: "general",
    clinical_goal: "behavior change",
    content: "Psychological flexibility in ACT involves six core processes: acceptance (allowing difficult thoughts/feelings without struggle), defusion (observing thoughts as thoughts), present-moment awareness, self-as-context (the observing self), values clarification, and committed action. Inflexibility \u2014 experiential avoidance, cognitive fusion, and values-inconsistent behaviour \u2014 underlies most psychological distress. ACT interventions use metaphors, mindfulness exercises, and values clarification tools to build flexibility. ACT is transdiagnostic and suitable across a wide range of presentations.",
    short_summary: "Introduces ACT\u2019s six psychological flexibility processes and their role in transdiagnostic treatment.",
    tags: ["ACT", "acceptance", "defusion", "values", "psychological flexibility"],
    source_name: "Hayes, Strosahl & Wilson ACT Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Dialectical Behaviour Therapy: Distress Tolerance TIPP",
    topic: "emotion regulation",
    subtopic: "DBT",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "TIPP skills are DBT distress tolerance techniques for rapidly reducing extreme emotional arousal: Temperature \u2014 applying cold water to the face activates the dive reflex, slowing heart rate; Intense exercise \u2014 20 minutes of vigorous activity burns off stress hormones; Paced breathing \u2014 slowing the breath activates the parasympathetic nervous system; Progressive muscle relaxation \u2014 systematically tensing and releasing muscle groups. TIPP skills are used in crisis moments to create enough physiological calm to access other skills.",
    short_summary: "Describes DBT TIPP skills (Temperature, Intense exercise, Paced breathing, Progressive relaxation) for acute distress reduction.",
    tags: ["DBT", "TIPP", "distress tolerance", "emotion regulation", "crisis"],
    source_name: "Linehan DBT Skills Training Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Cold water/ice not suitable for cardiovascular conditions.",
    contraindications: "Cardiovascular conditions; eating disorders (exercise); consult physician.",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "DBT Interpersonal Effectiveness: DEAR MAN",
    topic: "relationships",
    subtopic: "DBT",
    population: "adults",
    clinical_goal: "behavior change",
    content: "DEAR MAN is a DBT interpersonal effectiveness skill for making requests or setting limits effectively. Describe \u2014 state the facts objectively; Express \u2014 share feelings using \u2018I\u2019 statements; Assert \u2014 ask clearly for what you want; Reinforce \u2014 explain the positive outcome if your request is met; Mindfully \u2014 stay focused on goals; Appear confident \u2014 use tone, posture, and eye contact; Negotiate \u2014 offer alternatives if declined. DEAR MAN is practised via role-play and is particularly effective for clients with emotion dysregulation.",
    short_summary: "Details DBT DEAR MAN skill for assertive interpersonal communication with structured role-play practice.",
    tags: ["DBT", "DEAR MAN", "assertiveness", "communication", "relationships"],
    source_name: "Linehan DBT Skills Training Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Emotion Regulation: The Wave Metaphor",
    topic: "emotion regulation",
    subtopic: "urge surfing",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "The wave metaphor (urge surfing) teaches clients that emotions, like ocean waves, build to a peak and then naturally subside if not fed by avoidance or rumination. The therapist guides the client to observe an emotion as a physical sensation without acting on it or suppressing it. The client notices where the emotion is felt in the body, tracks its intensity rising and falling, and practises riding the wave to its natural conclusion. This technique is evidence-based for addiction urges, self-harm impulses, binge eating, and general emotion regulation.",
    short_summary: "Explains the wave/urge-surfing metaphor for riding emotions and impulses to their natural peak and subsidence.",
    tags: ["urge surfing", "emotion regulation", "mindfulness", "addiction", "self-harm"],
    source_name: "Marlatt & Gordon Relapse Prevention",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Active suicidality \u2014 do not use as sole intervention.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Self-Compassion in CBT: The Inner Critic",
    topic: "self-esteem",
    subtopic: "self-compassion",
    population: "general",
    clinical_goal: "challenge distortions",
    content: "The inner critic refers to an internalised harsh self-evaluative voice that amplifies distress, shame, and low self-worth. Drawing on Gilbert\u2019s Compassion-Focused Therapy (CFT) and Neff\u2019s self-compassion model, CBT therapists help clients: (1) notice the inner critic voice; (2) recognise it as a conditioned response; (3) develop an alternative compassionate inner voice; (4) practise self-compassion phrases. Physiological soothing techniques activate the mammalian caregiving system, shifting from threat mode to soothing mode.",
    short_summary: "Introduces the inner critic concept and CFT/self-compassion techniques for developing a compassionate self-voice.",
    tags: ["self-compassion", "inner critic", "CFT", "self-esteem", "shame"],
    source_name: "Neff Self-Compassion; Gilbert CFT",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Perfectionism: Cost-Benefit Analysis",
    topic: "perfectionism",
    subtopic: "cognitive restructuring",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Perfectionism is a multidimensional construct involving excessively high personal standards, concern over mistakes, doubts about actions, and self-critical evaluation. CBT addresses maladaptive perfectionism via: (1) psychoeducation on the costs and benefits; (2) behavioural experiments testing whether high standards lead to better outcomes; (3) restructuring dichotomous thinking; (4) graded exposure to \u2018good enough\u2019 performance. Self-monitoring forms track situations where perfectionism interferes.",
    short_summary: "Outlines CBT approach to maladaptive perfectionism via cost-benefit analysis, behavioural experiments, and dichotomous thinking work.",
    tags: ["perfectionism", "cost-benefit", "procrastination", "self-criticism"],
    source_name: "Shafran, Egan & Wade CBT for Perfectionism",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Health Anxiety: Attention Retraining",
    topic: "health anxiety",
    subtopic: "attention",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "In health anxiety, selective attention to bodily sensations amplifies symptom perception and triggers catastrophic misinterpretation. Attention retraining involves directing attention outward rather than inward (body monitoring). Techniques include scheduled body-scan periods limited to once daily, engagement in absorbing activities, and external attention exercises adapted from Wells\u2019s Attention Training Technique (ATT). Clients also reduce reassurance-seeking and repeated body checking, which function as safety behaviours that perpetuate health anxiety.",
    short_summary: "Describes attention retraining and safety behaviour reduction for health anxiety using externally-focused attention exercises.",
    tags: ["health anxiety", "attention retraining", "illness anxiety", "body scanning"],
    source_name: "Wells Metacognitive Therapy Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Genuine medical symptoms requiring investigation should be medically cleared first.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Anger Management: The Arousal Cycle",
    topic: "anger",
    subtopic: "anger management",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "The arousal cycle model illustrates how anger escalates from trigger through increasing physiological arousal to an expression peak and gradual recovery. CBT anger management teaches clients to: (1) identify personal early warning signs; (2) apply time-out at the early arousal phase; (3) use relaxation and controlled breathing during time-out; (4) use cognitive restructuring to challenge anger-escalating thoughts; (5) use assertive communication on returning. Anger diaries track triggers, cognitions, and outcomes.",
    short_summary: "Explains the arousal cycle of anger and CBT skills for early intervention via time-out, relaxation, and cognitive restructuring.",
    tags: ["anger", "arousal cycle", "time-out", "emotion regulation"],
    source_name: "Novaco Anger Treatment Protocol",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Screen for domestic violence; individual therapy recommended before group for perpetrators.",
    contraindications: "Active domestic violence situation \u2014 safety planning required first.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Grief and Loss: Dual Process Model",
    topic: "grief",
    subtopic: "bereavement",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "Stroebe and Schut\u2019s Dual Process Model (DPM) proposes that adaptive grieving involves oscillation between loss-oriented coping (confronting grief, emotional processing) and restoration-oriented coping (attending to life changes, developing new roles). Prolonged grief disorder involves being stuck in loss-oriented processing. CBT for grief includes facilitating loss processing, restoration activities, and cognitive work on unhelpful beliefs such as \u2018If I stop grieving, I am betraying them\u2019.",
    short_summary: "Introduces the Dual Process Model of grief and CBT interventions balancing loss-oriented and restoration-oriented coping.",
    tags: ["grief", "bereavement", "dual process model", "loss"],
    source_name: "Stroebe & Schut DPM; Shear Complicated Grief",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "Screen for complicated grief disorder and suicidality in bereaved clients.",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Eating Disorders: Cognitive Model Overview",
    topic: "eating disorders",
    subtopic: "CBT-E",
    population: "adults",
    clinical_goal: "behavior change",
    content: "Fairburn\u2019s Enhanced CBT (CBT-E) posits that over-evaluation of shape, weight, and their control is the central maintaining mechanism of eating disorders. CBT-E is organised in four stages: engagement and formulation; addressing key maintaining mechanisms (dietary restraint, body image, perfectionism, low self-esteem); broadening to address mood intolerance; and ending with relapse prevention. The model is transdiagnostic, applicable to anorexia, bulimia, and binge-eating disorder.",
    short_summary: "Describes Fairburn\u2019s CBT-E transdiagnostic model for eating disorders centred on over-evaluation of shape/weight.",
    tags: ["eating disorders", "CBT-E", "Fairburn", "bulimia", "anorexia"],
    source_name: "Fairburn CBT-E Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Medical monitoring required; liaise with GP/physician for clients below healthy weight.",
    contraindications: "BMI below 17.5 may require specialist or inpatient setting.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Substance Use: Functional Analysis",
    topic: "addiction",
    subtopic: "functional analysis",
    population: "adults",
    clinical_goal: "behavior change",
    content: "Functional analysis (FA) for substance use maps the antecedents, behaviours, and consequences (ABCs) of using episodes. Antecedents include high-risk situations (social pressure, locations, emotional states). Consequences include short-term positive reinforcement and long-term negative consequences. FA guides coping skills training: identifying triggers, developing urge management strategies, and planning alternative behaviours for high-risk moments.",
    short_summary: "Explains functional analysis (ABC model) for substance use to map triggers, use patterns, and guide coping skills training.",
    tags: ["addiction", "functional analysis", "CBT", "relapse prevention", "substance use"],
    source_name: "Carroll CBT for Substance Use Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Assess for medical withdrawal risk before commencing.",
    contraindications: "Active substance intoxication during session.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "ADHD: Cognitive Strategies for Planning",
    topic: "ADHD",
    subtopic: "executive function",
    population: "adults",
    clinical_goal: "behavior change",
    content: "CBT for adult ADHD targets executive function deficits that pharmacotherapy alone does not fully address. Strategies include: externalising memory (written lists, digital reminders, visible calendars); breaking tasks into micro-steps; using implementation intentions; prioritisation matrices; and time-blocking. Procrastination is addressed via motivational interviewing and the two-minute rule. Clients track completion using brief daily review forms.",
    short_summary: "Outlines CBT strategies for adult ADHD executive dysfunction: externalising memory, implementation intentions, and time-blocking.",
    tags: ["ADHD", "executive function", "planning", "procrastination", "CBT"],
    source_name: "Safren CBT for Adult ADHD Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Low Self-Esteem: The Negative Self-Belief Cycle",
    topic: "self-esteem",
    subtopic: "self-worth",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Melanie Fennell\u2019s CBT model of low self-esteem centres on a central negative belief formed in early experience and maintained by biased processing, unhelpful rules for living, avoidance, and depressed mood. Treatment involves surveying the evidence for the belief, behavioural experiments to test rules for living, developing a new accurate self-belief, and building a positive data log.",
    short_summary: "Describes Fennell\u2019s CBT maintenance model of low self-esteem and the positive data log intervention.",
    tags: ["self-esteem", "self-worth", "Fennell", "negative belief", "CBT"],
    source_name: "Fennell Overcoming Low Self-Esteem",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Chronic Pain: CBT Conceptualisation",
    topic: "chronic pain",
    subtopic: "pain management",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "The biopsychosocial CBT model of chronic pain recognises that pain perception is shaped by biological, psychological, and social factors. Psychological maintenance factors include: pain catastrophising, fear-avoidance, hypervigilance to pain signals, and low mood. CBT includes psychoeducation on the gate control model, graded activity increases to break the fear-avoidance cycle, cognitive restructuring of catastrophic pain beliefs, and pacing.",
    short_summary: "Presents the CBT biopsychosocial model of chronic pain including fear-avoidance, catastrophising, and graded activity.",
    tags: ["chronic pain", "pain management", "fear-avoidance", "catastrophising", "CBT"],
    source_name: "Turk & Gatchel CBT for Chronic Pain",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Coordinate with medical team; do not progress activity without medical clearance.",
    contraindications: "Undiagnosed or progressive pain conditions requiring medical investigation.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Assertiveness Training: The Assertiveness Continuum",
    topic: "relationships",
    subtopic: "assertiveness",
    population: "general",
    clinical_goal: "behavior change",
    content: "Assertiveness training places communication styles on a continuum from passive through assertive to aggressive. Passive communication leads to resentment; aggressive communication leads to conflict; assertive communication balances self-respect and respect for others. CBT assertiveness training involves identifying the client\u2019s current pattern, role-playing assertive responses to progressively difficult scenarios, and restructuring beliefs such as \u2018If I assert myself, people will reject me\u2019.",
    short_summary: "Describes the passive-assertive-aggressive continuum and CBT skills training for developing assertive communication.",
    tags: ["assertiveness", "communication", "relationships", "passive", "aggressive"],
    source_name: "Lange & Jakubowski Assertiveness Training",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Relapse Prevention: High-Risk Situations",
    topic: "relapse prevention",
    subtopic: "maintenance",
    population: "general",
    clinical_goal: "behavior change",
    content: "Marlatt and Gordon\u2019s relapse prevention model identifies high-risk situations as the primary precipitants of relapse: negative emotional states (35%), interpersonal conflict (16%), social pressure (20%). Clients are taught to identify their high-risk situations, develop coping plans, distinguish between a lapse and relapse, and use the abstinence violation effect reframe to prevent a lapse escalating to relapse.",
    short_summary: "Describes Marlatt\u2019s high-risk situations model and coping strategies including lapse-vs-relapse distinction and AVE reframing.",
    tags: ["relapse prevention", "high-risk situations", "lapse", "coping", "Marlatt"],
    source_name: "Marlatt & Gordon Relapse Prevention",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Bipolar Disorder: Psychoeducation and Mood Monitoring",
    topic: "bipolar disorder",
    subtopic: "psychoeducation",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "CBT for bipolar disorder (CBT-BD) begins with psychoeducation about the biological basis, the role of triggers, and the importance of medication adherence. Mood monitoring using daily life charts helps clients identify early warning signs of manic and depressive episodes. Action plans specify what to do at each level of mood escalation. CBT-BD also addresses schema-level beliefs about hypomanic states that create ambivalence about mood stability.",
    short_summary: "Covers CBT-BD psychoeducation, daily mood monitoring, early warning signs, and action plans for episode management.",
    tags: ["bipolar disorder", "psychoeducation", "mood monitoring", "early warning signs", "CBT"],
    source_name: "Lam, Jones & Bright CBT for Bipolar Disorder",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "CBT is adjunctive to medication; do not use as standalone without psychiatric oversight.",
    contraindications: "Active manic or mixed episode \u2014 stabilisation required before CBT engagement.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Behavioural Experiments in CBT",
    topic: "anxiety",
    subtopic: "behavioural experiments",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Behavioural experiments (BEs) are planned activities designed to test the validity of cognitions through direct experience rather than verbal disputation. Steps: (1) identify the belief to test; (2) design an experiment that directly tests the prediction; (3) identify obstacles and safeguards; (4) carry out the experiment; (5) review results and update belief rating. Types include active experiments, survey experiments, and observational experiments. BEs are the engine of schema change.",
    short_summary: "Describes the 5-step behavioural experiment protocol as the primary vehicle for experiential belief disconfirmation in CBT.",
    tags: ["behavioural experiments", "CBT", "schema change", "belief testing"],
    source_name: "Bennett-Levy et al. Oxford Guide to Behavioural Experiments",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 8,
    is_active: false
  }
];

export const BATCH_3 = [
  {
    title: "Psychoeducation: The CBT Model Overview",
    topic: "anxiety",
    subtopic: "psychoeducation",
    population: "general",
    clinical_goal: "challenge distortions",
    content: "The CBT model proposes that psychological distress arises not from situations themselves but from how people interpret those situations. The cognitive triad (Beck, 1979) describes negative automatic thoughts about the self, the world, and the future as central to depression. The model further identifies intermediate beliefs and underlying core beliefs that shape automatic thinking. CBT targets cognitions, behaviours, and physiological responses in an integrated way. Psychoeducation about this model helps clients become active agents in understanding and changing their own distress.",
    short_summary: "Introduces the CBT cognitive triad model and how psychoeducation empowers clients to understand the thought-emotion-behaviour link.",
    tags: ["CBT model", "psychoeducation", "cognitive triad", "automatic thoughts", "Beck"],
    source_name: "Beck Institute CBT Principles",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 9,
    is_active: false
  },
  {
    title: "Socratic Questioning in CBT",
    topic: "anxiety",
    subtopic: "cognitive restructuring",
    population: "general",
    clinical_goal: "challenge distortions",
    content: "Socratic questioning is the primary conversational technique through which CBT therapists guide clients to examine their thinking. Rather than directly challenging or correcting thoughts, the therapist asks guided discovery questions: \u2018What is the evidence for that?\u2019, \u2018What would you tell a friend in the same situation?\u2019, \u2018What is the worst / most realistic / best that could happen?\u2019. The goal is to promote metacognitive reflection and help clients arrive at more balanced perspectives independently.",
    short_summary: "Describes Socratic questioning as a guided discovery technique for collaborative cognitive restructuring in CBT.",
    tags: ["Socratic questioning", "guided discovery", "cognitive restructuring", "CBT technique"],
    source_name: "Beck Institute CBT Principles",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "CBT Case Formulation",
    topic: "anxiety",
    subtopic: "formulation",
    population: "general",
    clinical_goal: "challenge distortions",
    content: "A CBT case formulation organises information about a client into a coherent model that guides treatment. The 5 Ps framework covers: Presenting problems, Predisposing factors, Precipitating factors, Perpetuating factors, and Protective factors. The formulation identifies core beliefs, intermediate beliefs, compensatory strategies, and the typical cognitive-behavioural-physiological cycle maintaining distress. A good formulation is collaborative, parsimonious, and generates clear treatment targets.",
    short_summary: "Explains the CBT 5 Ps case formulation framework linking early experience to current maintaining cycles and treatment targets.",
    tags: ["formulation", "case conceptualisation", "5 Ps", "CBT", "core beliefs"],
    source_name: "Persons CBT Case Formulation",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Graded Task Assignment for Depression",
    topic: "depression",
    subtopic: "graded task assignment",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "Graded task assignment (GTA) is a CBT technique for depression in which a complex or overwhelming task is broken into small, sequential steps that progressively increase in difficulty. GTA directly addresses the depressive conviction \u2018I cannot do anything\u2019 by providing repeated mastery experiences. The therapist collaborates with the client to identify a meaningful target task, break it into micro-steps, predict likely obstacles, and debrief outcomes. Mastery and pleasure ratings are recorded after each step.",
    short_summary: "Describes graded task assignment as a step-by-step behavioural intervention targeting depressive helplessness through mastery experiences.",
    tags: ["depression", "graded task", "mastery", "activity scheduling", "helplessness"],
    source_name: "Beck Institute CBT Principles",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Severe psychomotor retardation or acute suicidality requires higher-level care first.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Mindfulness-Based Stress Reduction: Body Scan",
    topic: "stress",
    subtopic: "mindfulness",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "The body scan is a foundational MBSR practice developed by Jon Kabat-Zinn. The practitioner lies down and systematically directs non-judgmental awareness to different body regions, observing sensations without trying to change them. The body scan cultivates interoceptive awareness, reduces automatic tension patterns, and strengthens the capacity to observe uncomfortable sensations without reacting. Regular practice reduces perceived stress, cortisol reactivity, and somatic symptoms.",
    short_summary: "Introduces the MBSR body scan practice for developing non-judgmental interoceptive awareness and reducing stress reactivity.",
    tags: ["MBSR", "body scan", "mindfulness", "stress", "interoception"],
    source_name: "Kabat-Zinn MBSR Programme",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Trauma history \u2014 body-focused practices may trigger dissociation; use trauma-sensitive adaptations.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Progressive Muscle Relaxation",
    topic: "anxiety",
    subtopic: "relaxation",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "Progressive muscle relaxation (PMR), developed by Jacobson and refined by Wolpe, involves systematically tensing and releasing muscle groups to achieve deep muscular relaxation. The contrast between tension and relaxation heightens awareness of physiological arousal and provides voluntary control over it. PMR is effective for generalised anxiety, specific phobia, chronic pain, insomnia, and tension headaches. With practice, clients learn abbreviated versions for daily use.",
    short_summary: "Describes the PMR technique of systematic tension-release across muscle groups for anxiety and stress reduction.",
    tags: ["PMR", "relaxation", "anxiety", "muscle tension", "sleep"],
    source_name: "\u00d6st Applied Relaxation Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Musculoskeletal injuries \u2014 skip affected muscle groups.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Schema Therapy: Early Maladaptive Schemas",
    topic: "depression",
    subtopic: "schema therapy",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Young\u2019s Schema Therapy identifies 18 early maladaptive schemas (EMS) organised in five domains: Disconnection and Rejection; Impaired Autonomy and Performance; Impaired Limits; Other-Directedness; Overvigilance and Inhibition. EMS are identified via the Young Schema Questionnaire and addressed using cognitive, experiential, and behavioural interventions, including limited reparenting and imagery rescripting.",
    short_summary: "Introduces Young\u2019s 18 early maladaptive schemas across five domains and the multi-modal schema therapy intervention framework.",
    tags: ["schema therapy", "Young", "early maladaptive schemas", "EMS", "core beliefs"],
    source_name: "Young, Klosko & Weishaar Schema Therapy",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Schema therapy for personality disorder requires extended training; not for brief CBT episodes.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Imagery Rescripting for Trauma Memories",
    topic: "trauma",
    subtopic: "imagery rescripting",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Imagery rescripting (ImRs) involves guiding the client to revisit a distressing memory image and then actively modify it to create a more adaptive outcome. Stages include: (1) vividly reimagining the original scene; (2) identifying the key stuck-point meaning; (3) introducing a rescuer into the image to protect the younger self; (4) creating a new image where needs are met. ImRs reduces intrusive imagery, shame, and negative belief conviction in PTSD, social anxiety, depression, and eating disorders.",
    short_summary: "Describes imagery rescripting as a trauma memory modification technique that targets meaning and shame via adaptive new imagery.",
    tags: ["imagery rescripting", "trauma", "PTSD", "shame", "intrusive images"],
    source_name: "Arntz & Weertman Imagery Rescripting",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "Requires clinical training; can increase distress transiently.",
    contraindications: "Active psychosis; severe dissociation without specialist support.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Interoceptive Exposure for Panic Disorder",
    topic: "anxiety",
    subtopic: "panic disorder",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "Interoceptive exposure (IE) targets the feared bodily sensations in panic disorder by deliberately inducing them in a controlled setting. Common exercises include spinning (dizziness), breathing through a narrow straw (breathlessness), running on the spot (elevated heart rate), and hyperventilation (tingling). The rationale is that fear of sensations \u2014 not the sensations themselves \u2014 drives panic. IE combined with psychoeducation and cognitive restructuring produces rapid reduction in panic frequency and agoraphobic avoidance.",
    short_summary: "Explains interoceptive exposure for panic disorder: deliberately inducing feared sensations to disconfirm catastrophic misinterpretations.",
    tags: ["panic disorder", "interoceptive exposure", "bodily sensations", "agoraphobia"],
    source_name: "Barlow Panic Control Treatment Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Medical clearance required before hyperventilation exercises.",
    contraindications: "Cardiovascular conditions; asthma; pregnancy.",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "CBT for Insomnia: Sleep Restriction Therapy",
    topic: "sleep",
    subtopic: "sleep restriction",
    population: "adults",
    clinical_goal: "behavior change",
    content: "Sleep restriction therapy (SRT) involves initially limiting time in bed to the client\u2019s actual average sleep time to consolidate fragmented sleep and build homeostatic sleep drive. Sleep efficiency is calculated from sleep diaries. When SE exceeds 85% for five consecutive nights, time in bed is extended by 15\u201320 minutes. The process continues until optimal sleep duration is achieved. SRT produces durable insomnia remission superior to sleep medication.",
    short_summary: "Describes sleep restriction therapy (SRT) from CBT-I: limiting time in bed to build sleep drive, then titrating upward as efficiency improves.",
    tags: ["CBT-I", "sleep restriction", "insomnia", "sleep efficiency", "sleep diary"],
    source_name: "Spielman Sleep Restriction Therapy",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "Increases daytime sleepiness initially \u2014 caution with drivers and heavy machinery operators.",
    contraindications: "Bipolar disorder; seizure disorders; parasomnias \u2014 requires modification.",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Cognitive Defusion Techniques in ACT",
    topic: "anxiety",
    subtopic: "ACT",
    population: "general",
    clinical_goal: "challenge distortions",
    content: "Cognitive defusion in ACT refers to techniques that alter the function of thoughts rather than their content, reducing the literal believability and behavioural impact of thoughts. Defusion techniques include: the \u2018leaves on a stream\u2019 visualisation; singing the thought to a tune; adding \u2018I am having the thought that\u2026\u2019 prefix; thanking the mind; and word repetition until meaning dissolves. Defusion reduces emotional reactivity to difficult thoughts and increases values-based action.",
    short_summary: "Explains ACT cognitive defusion techniques that reduce thought believability and reactivity without challenging thought content.",
    tags: ["ACT", "defusion", "cognitive fusion", "mindfulness", "values"],
    source_name: "Hayes, Strosahl & Wilson ACT Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Values Clarification in ACT",
    topic: "behavior change",
    subtopic: "ACT",
    population: "general",
    clinical_goal: "behavior change",
    content: "Values in ACT are chosen life directions \u2014 not goals but ongoing qualities of action. Values clarification exercises help clients identify what truly matters to them. Common techniques include: the \u2018epitaph exercise\u2019; the \u2018dear friend\u2019 letter; the values card sort; and the \u2018life domains\u2019 matrix. Once values are clarified, committed action \u2014 small, concrete steps in valued directions even in the presence of discomfort \u2014 becomes the therapeutic focus.",
    short_summary: "Describes ACT values clarification exercises and how identified values drive committed action in the presence of difficult thoughts and feelings.",
    tags: ["ACT", "values", "committed action", "life domains", "meaning"],
    source_name: "Hayes, Strosahl & Wilson ACT Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "DBT Mindfulness: What and How Skills",
    topic: "emotion regulation",
    subtopic: "DBT",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "DBT core mindfulness skills are divided into What skills (Observe, Describe, Participate) and How skills (Non-judgmentally, One-mindfully, Effectively). What skills guide what you do with experience; How skills guide the manner of engagement. These skills build a mindful foundation for all other DBT modules. Short daily practices (2\u20133 minutes) are assigned as homework, with diary cards to track practice.",
    short_summary: "Describes DBT core mindfulness What skills (Observe, Describe, Participate) and How skills (Non-judgmentally, One-mindfully, Effectively).",
    tags: ["DBT", "mindfulness", "what skills", "how skills", "observe"],
    source_name: "Linehan DBT Skills Training Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "DBT Emotion Regulation: PLEASE Skills",
    topic: "emotion regulation",
    subtopic: "DBT",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "PLEASE skills are DBT emotion regulation skills targeting physical vulnerability to emotional dysregulation: treat PhysicaL illness; balance Eating; avoid mood-Altering substances; balance Sleep; get Exercise. Each skill is supported by psychoeducation on how physical factors amplify emotional reactivity. Clients complete PLEASE skill tracking cards. PLEASE skills are foundational \u2014 they reduce vulnerability to emotional crises, making other DBT skills more accessible.",
    short_summary: "Describes DBT PLEASE skills targeting physical health foundations (illness, eating, substances, sleep, exercise) that reduce emotional vulnerability.",
    tags: ["DBT", "PLEASE skills", "emotion regulation", "sleep", "exercise", "physical health"],
    source_name: "Linehan DBT Skills Training Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Compassion-Focused Therapy: Soothing Rhythm Breathing",
    topic: "anxiety",
    subtopic: "CFT",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "Soothing rhythm breathing (SRB) is a foundational CFT technique for activating the parasympathetic soothing/affiliative system. The client breathes slightly deeper and slower than normal (approximately 5\u20136 breath cycles per minute), with a gentle pause between exhale and inhale. The focus is on cultivating a quality of warmth and settling rather than achievement. SRB is taught at the beginning of each CFT session as a \u2018compassion doorway\u2019 to prime the nervous system.",
    short_summary: "Describes CFT soothing rhythm breathing (approx. 5\u20136 cycles/min) as a parasympathetic activation technique preceding compassion work.",
    tags: ["CFT", "soothing rhythm breathing", "parasympathetic", "self-compassion", "Gilbert"],
    source_name: "Gilbert Compassion-Focused Therapy",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Respiratory conditions \u2014 adapt pacing; severe dissociation \u2014 monitor carefully.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Narrative Exposure Therapy: Lifeline Technique",
    topic: "trauma",
    subtopic: "narrative therapy",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Narrative Exposure Therapy (NET) was developed for complex trauma and refugee populations. The lifeline technique is its opening phase: the client constructs a physical lifeline using stones (representing negative/traumatic events) and flowers (representing positive events) placed chronologically. This externalises the life story and orients the therapist to major trauma and resilience periods. Subsequent sessions involve narrating and documenting each major event in chronological order, integrating fragmented trauma memories into a coherent autobiographical narrative.",
    short_summary: "Introduces NET\u2019s lifeline technique as a chronological mapping of traumatic and positive life events that orients trauma narrative work.",
    tags: ["NET", "narrative exposure therapy", "lifeline", "complex trauma", "refugee"],
    source_name: "Schauer, Neuner & Elbert NET Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Trained NET therapist required; not suitable for self-guided work.",
    contraindications: "Active psychosis; acute suicidality requiring stabilisation.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Interpersonal Therapy: Grief Role",
    topic: "depression",
    subtopic: "IPT",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "Interpersonal Therapy (IPT) addresses four problem areas linked to depression: grief, role transitions, role disputes, and interpersonal deficits. The grief focus area targets complicated mourning following bereavement. IPT for grief involves: facilitating the normal mourning process; exploring ambivalent feelings; and gradually helping the client re-engage with social activities and rebuild relationships.",
    short_summary: "Describes IPT grief focus area: facilitating mourning, exploring ambivalence, and re-engaging socially after bereavement-linked depression.",
    tags: ["IPT", "grief", "depression", "bereavement", "interpersonal therapy"],
    source_name: "Klerman & Weissman IPT Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Interpersonal Therapy: Role Transitions",
    topic: "depression",
    subtopic: "IPT",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "In IPT, role transitions encompass major life changes that disrupt social roles and self-concept, triggering depression. Examples include job loss, relationship transitions, moving city, retirement, illness. IPT for role transitions involves: mourning the loss of the old role; exploring ambivalent feelings; identifying skills and supports needed in the new role; and building a social network appropriate to the new role.",
    short_summary: "Describes IPT role transitions focus area addressing depression triggered by major life changes through mourning old roles and building new ones.",
    tags: ["IPT", "role transition", "depression", "life change", "interpersonal therapy"],
    source_name: "Klerman & Weissman IPT Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Psychoeducation on the Stress Response",
    topic: "stress",
    subtopic: "psychoeducation",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "The fight-or-flight-freeze response is an evolutionarily conserved survival mechanism mediated by the sympathetic nervous system and HPA axis. Stressors activate the amygdala, triggering adrenaline and cortisol release, increasing heart rate and respiration, and sharpening threat attention. These changes are adaptive for acute physical threat but maladaptive when chronically activated by psychological stressors. CBT psychoeducation normalises stress responses and introduces the rationale for relaxation, mindfulness, and cognitive interventions.",
    short_summary: "Explains the fight-or-flight-freeze stress response, its adaptive and maladaptive aspects, and the rationale for CBT stress interventions.",
    tags: ["stress response", "fight-or-flight", "amygdala", "cortisol", "psychoeducation"],
    source_name: "Beck Institute CBT Principles",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Worry and Generalised Anxiety: Intolerance of Uncertainty",
    topic: "anxiety",
    subtopic: "generalised anxiety",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Intolerance of uncertainty (IU) is a core maintaining factor in GAD. Clients with high IU treat uncertainty as threatening, leading to chronic worry as an attempt to resolve every possible outcome. The CBT/IU model targets IU through: psychoeducation on the function of worry; uncertainty exposure (gradually approaching uncertain situations without resolving them prematurely); and cognitive restructuring of beliefs about the necessity of certainty.",
    short_summary: "Describes the intolerance of uncertainty (IU) model of GAD and cognitive-behavioural interventions targeting IU directly.",
    tags: ["GAD", "intolerance of uncertainty", "worry", "anxiety", "Dugas"],
    source_name: "Dugas & Robichaud GAD Treatment",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Body Image Interventions in CBT",
    topic: "self-esteem",
    subtopic: "body image",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Negative body image involves overvaluation of appearance, selective attention to disliked features, avoidance, and frequent body-checking behaviours. CBT body image interventions include: mirror exposure with descriptive (not evaluative) commentary; body-checking response prevention; activity exposure; and cognitive restructuring of appearance-based self-worth beliefs. Body image disturbance is central to eating disorders, social anxiety, and depression.",
    short_summary: "Describes CBT body image interventions including mirror exposure, checking response prevention, and restructuring appearance-based self-worth beliefs.",
    tags: ["body image", "mirror exposure", "eating disorders", "self-esteem", "CBT"],
    source_name: "Cash Cognitive-Behavioral Body Image Therapy",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Active eating disorder \u2014 body image work should be coordinated with comprehensive ED treatment.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Mindfulness-Based Cognitive Therapy: Relapse Prevention",
    topic: "depression",
    subtopic: "MBCT",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "MBCT was developed by Segal, Williams, and Teasdale specifically for relapse prevention in recurrent depression. It is delivered in an 8-week group programme combining mindfulness meditation with CBT psychoeducation. MBCT targets ruminative thinking style and depressive mood-thought reactivation patterns. The key mechanism is decentring \u2014 the capacity to observe depressive thoughts as passing mental events rather than facts. MBCT reduces relapse rates by approximately 50%.",
    short_summary: "Describes MBCT as an 8-week group programme combining mindfulness and CBT for recurrent depression relapse prevention via decentring.",
    tags: ["MBCT", "depression", "relapse prevention", "mindfulness", "rumination"],
    source_name: "Segal, Williams & Teasdale MBCT Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Active severe depression \u2014 individual therapy or pharmacotherapy may be needed first.",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Agoraphobia: Graduated In-Vivo Exposure",
    topic: "anxiety",
    subtopic: "agoraphobia",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "Agoraphobia is the fear and avoidance of situations perceived as difficult to escape during a panic attack. Graduated in-vivo exposure is the primary CBT intervention. A hierarchy of avoided situations is constructed (SUDS 0\u2013100), and the client progresses from least to most feared. Each exposure is held until anxiety reduces by at least 50%. Safety behaviours are systematically eliminated. Partner-assisted exposure is incorporated when avoidance involves accommodation by significant others.",
    short_summary: "Describes graduated in-vivo exposure for agoraphobia with safety behaviour elimination and partner-assisted protocols.",
    tags: ["agoraphobia", "exposure", "panic disorder", "in-vivo", "avoidance"],
    source_name: "Barlow Panic Control Treatment Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Severe avoidance may require therapist-accompanied exposure before independent practice.",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Emotion-Focused Couples Therapy: Cycle Interruption",
    topic: "relationships",
    subtopic: "couples therapy",
    population: "adults",
    clinical_goal: "behavior change",
    content: "EFT identifies negative interactional cycles \u2014 typically pursue-withdraw or criticise-defend patterns \u2014 that reflect unmet attachment needs. Cycle interruption involves: tracking the negative cycle as it unfolds; reflecting each partner\u2019s position and the emotion underneath their behaviour; accessing the primary emotion beneath secondary emotions; and re-framing the cycle as the problem, not the partner.",
    short_summary: "Describes EFT negative cycle interruption: tracking pursue-withdraw patterns and accessing primary attachment emotions beneath reactive responses.",
    tags: ["EFT", "couples therapy", "attachment", "relationship", "cycle interruption"],
    source_name: "Johnson EFT Couples Therapy Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Screen for domestic violence; couples therapy contraindicated in active abuse situations.",
    contraindications: "Active domestic violence; one partner with active untreated psychosis.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Parent-Child CBT: Managing Childhood Anxiety",
    topic: "anxiety",
    subtopic: "child anxiety",
    population: "adolescents",
    clinical_goal: "reduce avoidance",
    content: "CBT for childhood anxiety (e.g., the FRIENDS programme, Coping Cat) combines psychoeducation, cognitive restructuring, graded exposure, and parent training. Parents are included because parental accommodation maintains child anxiety. Parent training focuses on: modelling approach behaviour; withdrawing reassurance gradually; reinforcing brave behaviour. Exposure hierarchies are built collaboratively with child and parent and progressed via reward charts.",
    short_summary: "Outlines CBT for childhood anxiety including child-adapted formulation, parent training to reduce accommodation, and reward-supported exposure.",
    tags: ["child anxiety", "FRIENDS", "Coping Cat", "parent training", "exposure"],
    source_name: "Kendall Coping Cat Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Severe family dysfunction may require systemic intervention before individual CBT.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Metacognitive Therapy: CAS Interruption",
    topic: "anxiety",
    subtopic: "metacognitive therapy",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Wells\u2019s Metacognitive Therapy (MCT) proposes that the Cognitive Attentional Syndrome (CAS) \u2014 comprising worry, rumination, threat monitoring, and unhelpful coping \u2014 is maintained by positive metacognitive beliefs and negative metacognitive beliefs. MCT targets the CAS directly. Key techniques include: detached mindfulness; attention training (ATT); postponing worry; and challenging metacognitive beliefs via behavioural experiments.",
    short_summary: "Describes MCT\u2019s Cognitive Attentional Syndrome (CAS) model and interventions including detached mindfulness, ATT, and metacognitive belief challenging.",
    tags: ["MCT", "metacognitive therapy", "CAS", "GAD", "Wells", "worry"],
    source_name: "Wells Metacognitive Therapy Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Behavioural Activation: Activity Monitoring",
    topic: "depression",
    subtopic: "behavioural activation",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "Activity monitoring is the first step of behavioural activation for depression. The client records hourly activities over 7 days and rates each for mastery and pleasure (0\u201310). Analysis reveals: the current activity pattern; activities correlated with better mood; periods of inactivity or rumination. This baseline informs activity scheduling and challenges the belief \u2018Nothing gives me pleasure anymore\u2019 by finding genuine pleasure pockets.",
    short_summary: "Describes weekly activity monitoring in BA for depression: logging activities with mastery/pleasure ratings to identify mood-activity patterns.",
    tags: ["behavioural activation", "activity monitoring", "depression", "mastery", "pleasure"],
    source_name: "Martell, Dimidjian & Herman-Dunn",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Specific Phobia: Single-Session Intensive Exposure",
    topic: "anxiety",
    subtopic: "specific phobia",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "Intensive single-session treatment (SST) for specific phobia (Ost, 1989) delivers a complete graded exposure hierarchy in one 3-hour session, achieving outcomes equivalent to multi-session treatment. The protocol includes: psychoeducation; collaborative construction of a 10-step hierarchy; stepped in-vivo exposure with the therapist progressively withdrawing support; inhibitory learning principles; and post-session relapse prevention. SST is highly cost-effective and suitable for primary care.",
    short_summary: "Describes Ost\u2019s single-session intensive exposure treatment for specific phobia using a 3-hour graded hierarchy with inhibitory learning principles.",
    tags: ["specific phobia", "single-session treatment", "exposure", "in-vivo"],
    source_name: "Ost Single-Session Treatment Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Blood-injection-injury phobia \u2014 use applied tension technique to prevent vasovagal syncope.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Applied Tension for Blood-Injection-Injury Phobia",
    topic: "anxiety",
    subtopic: "specific phobia",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "Blood-injection-injury (BII) phobia has a unique two-phase physiological response: initial sympathetic activation followed by parasympathetic-driven vasovagal syncope (fainting). Applied tension involves the client tensing large muscle groups for 15 seconds, then releasing, and repeating 5 times. This raises blood pressure, preventing the vasovagal drop. Applied tension is combined with in-vivo exposure and achieves remission rates of 80\u201390%.",
    short_summary: "Explains applied tension technique for BII phobia: muscle tensing to prevent vasovagal fainting during blood/injury exposure.",
    tags: ["BII phobia", "applied tension", "vasovagal", "blood phobia", "fainting"],
    source_name: "Ost & Sterner Applied Tension",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "Screen for cardiovascular conditions before applying muscle tension.",
    contraindications: "Cardiovascular conditions \u2014 medical clearance required.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Psychoeducation on Cognitive Distortions",
    topic: "depression",
    subtopic: "cognitive distortions",
    population: "general",
    clinical_goal: "challenge distortions",
    content: "Burns (1980) popularised a taxonomy of cognitive distortions: All-or-nothing thinking; Overgeneralisation; Mental filter; Disqualifying the positive; Mind reading; Fortune telling; Magnification/Minimisation; Emotional reasoning; Should statements; Labelling; Personalisation. Naming distortions helps clients create distance from automatic thoughts and is a foundational step in cognitive restructuring.",
    short_summary: "Introduces Burns\u2019s 11 cognitive distortion categories as psychoeducational labels for identifying and distancing from automatic negative thoughts.",
    tags: ["cognitive distortions", "automatic thoughts", "Burns", "CBT", "psychoeducation"],
    source_name: "Burns Feeling Good; Beck Institute CBT Principles",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Safety Planning for Suicide Risk",
    topic: "crisis",
    subtopic: "safety planning",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "The Stanley-Brown Safety Planning Intervention (SPI) is a structured, collaborative tool for reducing suicidal crisis escalation. Components: (1) Warning signs; (2) Internal coping strategies; (3) Social contacts and settings for distraction; (4) People who can be asked for help; (5) Professionals and agencies to contact; (6) Making the environment safe via means restriction. The plan is written in the client\u2019s own words and kept accessible. SPI reduces suicide attempts in high-risk populations.",
    short_summary: "Describes the 6-component Stanley-Brown Safety Planning Intervention for suicidal crisis, including warning signs, coping strategies, and means restriction.",
    tags: ["safety planning", "suicide", "crisis", "Stanley-Brown", "means restriction"],
    source_name: "Stanley & Brown Safety Planning Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Not a substitute for comprehensive risk assessment. Refer to emergency services as indicated.",
    contraindications: "Imminent intent with plan and means \u2014 requires emergency intervention.",
    language: "en",
    priority_score: 9,
    is_active: false
  },
  {
    title: "Trauma: Window of Tolerance Model",
    topic: "trauma",
    subtopic: "stabilisation",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "The window of tolerance (WOT) describes the zone of arousal in which a person can effectively process experience. Hyperarousal (above WOT) involves sympathetic activation overwhelming cortical function. Hypoarousal (below WOT) involves dorsal vagal shutdown. Trauma stabilisation aims to widen the window through skills building so that trauma processing can occur within the WOT. This model is central to phase-based trauma treatment.",
    short_summary: "Introduces the window of tolerance model for trauma: optimal arousal zone for processing, with hyperarousal and hypoarousal outside windows.",
    tags: ["window of tolerance", "trauma", "arousal", "dissociation", "stabilisation"],
    source_name: "Ogden Sensorimotor Psychotherapy; Siegel",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Grounding Techniques for Dissociation",
    topic: "trauma",
    subtopic: "grounding",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "Grounding techniques anchor clients to the present moment during dissociative or overwhelmed states. Sensory grounding uses the 5-4-3-2-1 technique: name 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste. Physical grounding uses firm floor contact, cold water on the wrists, or holding an ice cube. Cognitive grounding uses orientation statements. Clients practise daily to build proficiency.",
    short_summary: "Describes sensory, physical, cognitive, and movement grounding techniques for managing dissociation and overwhelm in trauma treatment.",
    tags: ["grounding", "dissociation", "trauma", "5-4-3-2-1", "sensory"],
    source_name: "Najavits Seeking Safety; Generic CBT",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Acceptance of Emotions: The Emotion Regulation Framework",
    topic: "emotion regulation",
    subtopic: "emotion acceptance",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "Gross\u2019s process model identifies five emotion regulation strategy families: situation selection, situation modification, attentional deployment, cognitive change (reappraisal), and response modulation. Reappraisal is generally adaptive; suppression is generally maladaptive. CBT focuses primarily on reappraisal and acceptance. Acceptance-based strategies \u2014 allowing emotion without struggle \u2014 reduce secondary distress and are complementary to reappraisal.",
    short_summary: "Describes Gross\u2019s five emotion regulation strategy families and the evidence for reappraisal and acceptance over suppression.",
    tags: ["emotion regulation", "Gross", "reappraisal", "suppression", "acceptance"],
    source_name: "Gross Handbook of Emotion Regulation",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "EMDR: Phases Overview",
    topic: "trauma",
    subtopic: "EMDR",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "EMDR is an evidence-based trauma treatment recommended by NICE and WHO. The 8-phase protocol includes: (1) History-taking; (2) Preparation; (3) Assessment (target memory, negative cognition, positive cognition, SUDS and VOC ratings); (4) Desensitisation (bilateral stimulation); (5) Installation; (6) Body scan; (7) Closure; (8) Re-evaluation. Bilateral stimulation is hypothesised to facilitate adaptive information processing.",
    short_summary: "Outlines EMDR\u2019s 8-phase protocol for trauma: from history-taking through bilateral stimulation desensitisation to re-evaluation.",
    tags: ["EMDR", "trauma", "PTSD", "bilateral stimulation", "adaptive information processing"],
    source_name: "Shapiro EMDR Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "EMDR requires trained certified practitioner; premature activation without stabilisation can destabilise clients.",
    contraindications: "Active psychosis; severe dissociative disorder \u2014 specialist adaptation required.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Cognitive Restructuring: Decatastrophising",
    topic: "anxiety",
    subtopic: "cognitive restructuring",
    population: "general",
    clinical_goal: "challenge distortions",
    content: "Decatastrophising is a specific cognitive restructuring technique for catastrophic thinking. The therapist guides the client to: (1) identify the catastrophic prediction; (2) estimate the realistic probability of each step in the catastrophic chain; (3) examine the evidence; (4) generate the realistic most likely outcome; (5) conduct a coping appraisal. The coping appraisal shifts focus from outcome probability to coping confidence. Pie charts can illustrate how small the probability of the catastrophic outcome actually is.",
    short_summary: "Describes decatastrophising: probability estimation, evidence examination, realistic outcome generation, and coping appraisal for catastrophic thinking.",
    tags: ["decatastrophising", "catastrophizing", "cognitive restructuring", "coping appraisal", "anxiety"],
    source_name: "Beck Institute CBT Principles",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "DBT FAST Skills for Self-Respect",
    topic: "relationships",
    subtopic: "DBT",
    population: "adults",
    clinical_goal: "behavior change",
    content: "FAST skills in DBT are interpersonal effectiveness skills for maintaining self-respect: be Fair (to oneself as well as to others); no Apologies (for having opinions or making requests); Stick to values; be Truthful. FAST skills address patterns of excessive self-sacrifice and approval-seeking that erode self-esteem. They are used alongside DEAR MAN and GIVE skills.",
    short_summary: "Describes DBT FAST skills (Fair, no Apologies, Stick to values, Truthful) for maintaining self-respect in interpersonal interactions.",
    tags: ["DBT", "FAST", "self-respect", "assertiveness", "interpersonal"],
    source_name: "Linehan DBT Skills Training Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "DBT GIVE Skills for Relationship Maintenance",
    topic: "relationships",
    subtopic: "DBT",
    population: "adults",
    clinical_goal: "behavior change",
    content: "GIVE skills in DBT prioritise maintaining the quality and warmth of a relationship: be Gentle (no attacks or judgement); act Interested (listen actively); Validate (acknowledge the other person\u2019s feelings); use an Easy manner (lighten the interaction with humour or warmth). GIVE skills are used when preserving the relationship is the primary goal. Often used alongside DEAR MAN and FAST.",
    short_summary: "Describes DBT GIVE skills (Gentle, Interested, Validate, Easy manner) for maintaining relationship quality in interpersonal interactions.",
    tags: ["DBT", "GIVE", "relationship", "validation", "interpersonal effectiveness"],
    source_name: "Linehan DBT Skills Training Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Prolonged Grief Disorder: Revisiting Intervention",
    topic: "grief",
    subtopic: "prolonged grief",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "Prolonged grief disorder (PGD) is characterised by persistent intense yearning, difficulty accepting the death, bitterness, and functional impairment beyond 12 months. Shear\u2019s Complicated Grief Treatment (CGT) combines aspirational goals work (rebuilding a life with meaning); revisiting exercises (imaginal revisiting of the death scene); and situational revisiting (graduated exposure to avoided grief reminders). CGT is superior to standard IPT in reducing PGD severity.",
    short_summary: "Describes Shear\u2019s CGT for prolonged grief disorder using aspirational goals, imaginal revisiting of the death, and situational exposure to grief reminders.",
    tags: ["prolonged grief", "complicated grief", "CGT", "revisiting", "bereavement"],
    source_name: "Shear Complicated Grief Treatment",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Screen for suicidality; grief and depression frequently co-occur.",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Psychoeducation on Sleep Architecture",
    topic: "sleep",
    subtopic: "psychoeducation",
    population: "general",
    clinical_goal: "behavior change",
    content: "Normal adult sleep consists of 4\u20135 cycles of approximately 90 minutes, each progressing through NREM stages (N1 light, N2 intermediate, N3 slow-wave deep) and REM sleep. Deep slow-wave sleep predominates in the first half of the night; REM predominates in the second half. Brief awakenings between cycles are normal. Many \u2018sleep problems\u2019 are reframed as normal variation once clients understand sleep architecture, reducing sleep-related anxiety and hyperarousal.",
    short_summary: "Explains normal sleep architecture (NREM/REM cycles, stage distribution across the night) to correct sleep misconceptions in CBT-I.",
    tags: ["sleep architecture", "CBT-I", "psychoeducation", "REM", "NREM", "insomnia"],
    source_name: "NICE Guidelines for Insomnia",
    source_type: "guidelines",
    license_status: "open",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Stimulus Control for Insomnia",
    topic: "sleep",
    subtopic: "CBT for insomnia",
    population: "adults",
    clinical_goal: "behavior change",
    content: "Stimulus control (Bootzin, 1972) reconditions the bed and bedroom as cues for sleep rather than wakefulness. Instructions: (1) go to bed only when sleepy; (2) use the bed only for sleep and sex; (3) if unable to sleep within 20 minutes, get up and return only when sleepy; (4) maintain a consistent wake time regardless of sleep duration; (5) avoid daytime naps. Stimulus control is one of the most empirically supported components of CBT-I.",
    short_summary: "Describes Bootzin\u2019s stimulus control instructions for insomnia: reconditioning the bed as a sleep cue through consistent behavioural rules.",
    tags: ["stimulus control", "CBT-I", "insomnia", "sleep", "sleep hygiene"],
    source_name: "Bootzin Stimulus Control Instructions",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Parasomnias \u2014 getting out of bed during sleep may be unsafe; modify instructions.",
    language: "en",
    priority_score: 8,
    is_active: false
  },
  {
    title: "Interpersonal Effectiveness: Validation Strategies",
    topic: "relationships",
    subtopic: "validation",
    population: "general",
    clinical_goal: "behavior change",
    content: "Validation in DBT means communicating that a person\u2019s emotions, thoughts, or behaviours make sense given their history or the current situation. Linehan describes six levels: Level 1 (paying attention), Level 2 (accurate reflection), Level 3 (mind reading), Level 4 (validating in terms of history), Level 5 (validating in terms of the current situation), Level 6 (radical genuineness). Validation reduces emotional arousal and is a prerequisite for effective change strategies.",
    short_summary: "Describes Linehan\u2019s six validation levels from paying attention to radical genuineness as a de-escalating interpersonal technique.",
    tags: ["validation", "DBT", "interpersonal effectiveness", "emotion regulation", "Linehan"],
    source_name: "Linehan DBT Skills Training Manual",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Positive Psychology Interventions: Three Good Things",
    topic: "depression",
    subtopic: "positive psychology",
    population: "general",
    clinical_goal: "mood_improvement",
    content: "The Three Good Things exercise (Seligman, 2005) involves writing down three positive events that occurred each day and the cause of each event, for one week. Meta-analyses confirm reliable increases in happiness and decreases in depressive symptoms for up to six months. The exercise shifts attentional bias toward positive stimuli, increases savoring, and builds a more balanced self-narrative.",
    short_summary: "Describes the Three Good Things gratitude exercise: three positive events plus their causes daily for one week, with lasting wellbeing effects.",
    tags: ["gratitude", "positive psychology", "depression", "wellbeing", "Seligman"],
    source_name: "Seligman Positive Psychology Interventions",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Active severe depression \u2014 positive interventions may feel invalidating; introduce after initial BA phase.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Expressive Writing: Pennebaker Protocol",
    topic: "stress",
    subtopic: "expressive writing",
    population: "general",
    clinical_goal: "mood_improvement",
    content: "Pennebaker\u2019s expressive writing protocol involves writing continuously about the deepest thoughts and feelings related to a significant emotional or stressful event for 15\u201320 minutes on 3\u20134 consecutive days. Meta-analyses show significant reductions in anxiety, depression, PTSD symptoms, and improvements in immune function. Mechanisms include emotional processing, cognitive integration, and inhibition reduction.",
    short_summary: "Describes Pennebaker\u2019s expressive writing protocol (15-20 min/day x 3-4 days) and its evidence base for emotional processing and stress reduction.",
    tags: ["expressive writing", "Pennebaker", "journalling", "stress", "emotional processing"],
    source_name: "Pennebaker Opening Up; Smyth Meta-Analysis",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "Brief emotional distress increase during writing is normal and transient.",
    contraindications: "Acute trauma without therapeutic support; severe dissociation.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Social Skills Training",
    topic: "relationships",
    subtopic: "social skills",
    population: "general",
    clinical_goal: "behavior change",
    content: "Social skills training (SST) is a structured CBT intervention for clients whose distress is maintained by skills deficits. Components include: instruction and modelling of targeted skills; behaviour rehearsal via role-play; performance feedback; reinforcement; and generalisation practice. SST is indicated for social anxiety, autism spectrum conditions, schizophrenia, borderline personality disorder, and social isolation.",
    short_summary: "Describes SST components (instruction, modelling, role-play, feedback) for social skills deficits across social anxiety, ASD, and personality disorders.",
    tags: ["social skills", "SST", "role-play", "social anxiety", "CBT"],
    source_name: "Bellack Social Skills Training for Schizophrenia",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Postnatal Depression: CBT Formulation",
    topic: "depression",
    subtopic: "postnatal depression",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "Postnatal depression (PND) affects 10\u201315% of mothers and 5\u201310% of fathers. CBT formulation for PND incorporates biological (hormonal shifts, sleep deprivation), psychological (perfectionist parenting standards, identity shift, intrusive infant-harm thoughts), and social factors. Treatment includes normalising intrusive thoughts, behavioural activation, self-compassion work, and partner/systemic components.",
    short_summary: "Presents CBT formulation for postnatal depression covering biological, psychological, and social factors with normalising intrusive thought work.",
    tags: ["postnatal depression", "PND", "depression", "parenting", "intrusive thoughts"],
    source_name: "NICE Guidelines for Perinatal Mental Health",
    source_type: "guidelines",
    license_status: "open",
    safety_notes: "Screen for suicidality and infanticide risk; liaise with perinatal team.",
    contraindications: "Active psychosis (postpartum psychosis) \u2014 requires urgent psychiatric referral.",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Medically Unexplained Symptoms: CBT Approach",
    topic: "health anxiety",
    subtopic: "medically unexplained symptoms",
    population: "adults",
    clinical_goal: "reduce avoidance",
    content: "Medically unexplained symptoms (MUS) are persistent physical symptoms without adequate organic explanation. The CBT model identifies perpetuating factors: attentional amplification, catastrophic misinterpretation, illness behaviour, and social reinforcement. CBT for MUS includes: biopsychosocial psychoeducation; graded activity increase; attention retraining; challenging illness beliefs; and reducing safety behaviours.",
    short_summary: "Describes the CBT perpetuating cycle model for MUS and interventions: graded activity, attention retraining, and illness belief restructuring.",
    tags: ["MUS", "medically unexplained symptoms", "chronic fatigue", "IBS", "health anxiety", "CBT"],
    source_name: "Wessely & Sharpe CBT for MUS",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "Full medical investigation must precede MUS formulation to rule out organic pathology.",
    contraindications: "Undiagnosed progressive illness \u2014 medical work-up required first.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Resilience Building: Post-Traumatic Growth",
    topic: "trauma",
    subtopic: "post-traumatic growth",
    population: "general",
    clinical_goal: "mood_improvement",
    content: "Post-traumatic growth (PTG) refers to positive psychological change that emerges from the struggle with highly challenging life circumstances. Tedeschi and Calhoun identify five PTG domains: new possibilities; relating to others; personal strength; spiritual change; and appreciation of life. CBT facilitates PTG by creating a coherent trauma narrative, identifying growth narratives, exploring changed world assumptions, and fostering deliberate reflection on meaning-making.",
    short_summary: "Introduces post-traumatic growth (PTG) across five domains and how CBT facilitates growth through narrative, meaning-making, and assumption restructuring.",
    tags: ["post-traumatic growth", "PTG", "resilience", "meaning", "trauma"],
    source_name: "Tedeschi & Calhoun PTG Model",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Do not prematurely introduce PTG framing; ensure trauma processing is complete first.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Coping Strategies: Problem-Focused vs Emotion-Focused",
    topic: "stress",
    subtopic: "coping",
    population: "general",
    clinical_goal: "reduce avoidance",
    content: "Lazarus and Folkman\u2019s transactional stress-coping model distinguishes problem-focused coping (addressing the stressor directly, effective when controllable) from emotion-focused coping (managing emotional response, effective when uncontrollable). Flexible coping \u2014 matching strategy to situational appraisal \u2014 predicts better outcomes than rigid adherence to one style. CBT teaches clients to assess stressor controllability and build a broader coping repertoire.",
    short_summary: "Explains Lazarus and Folkman\u2019s problem-focused vs emotion-focused coping distinction and the importance of flexible coping matching.",
    tags: ["coping", "stress", "Lazarus", "problem-focused", "emotion-focused"],
    source_name: "Lazarus & Folkman Stress Appraisal and Coping",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 7,
    is_active: false
  },
  {
    title: "Mindful Eating for Disordered Eating Patterns",
    topic: "eating disorders",
    subtopic: "mindful eating",
    population: "general",
    clinical_goal: "behavior change",
    content: "Mindful eating involves bringing non-judgmental attention to the experience of eating: hunger and satiety cues, food texture, taste, smell, environmental triggers, and emotional states. Mindful eating interventions reduce binge eating and emotional eating by increasing interoceptive awareness, reducing automatic eating in response to external cues, and breaking eating-as-emotion-regulation patterns.",
    short_summary: "Describes mindful eating interventions for binge eating and emotional eating via interoceptive awareness and non-judgmental food exposure.",
    tags: ["mindful eating", "binge eating", "eating disorders", "emotional eating", "mindfulness"],
    source_name: "Kristeller Mindfulness-Based Eating Awareness Training",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "Active AN with medical instability \u2014 mindful eating is not a substitute for nutritional rehabilitation.",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Meaning-Making in Existential CBT",
    topic: "depression",
    subtopic: "existential CBT",
    population: "adults",
    clinical_goal: "mood_improvement",
    content: "Existential themes \u2014 death, freedom, isolation, and meaninglessness \u2014 can underlie chronic depression not fully addressed by symptom-focused CBT. Meaning-making interventions help clients identify and reconnect with sources of meaning: relationships, creative work, service to others, spiritual frameworks. Interventions include the \u2018meaning audit\u2019, values clarification, and narrative work. Meaning-focused work is particularly indicated in grief, chronic illness, and existential depression.",
    short_summary: "Integrates existential meaning-making (Frankl, logotherapy) with CBT for chronic depression, grief, and chronic illness via meaning audit and values work.",
    tags: ["existential", "meaning", "logotherapy", "Frankl", "depression", "purpose"],
    source_name: "Frankl Man\u2019s Search for Meaning; Wong Meaning Therapy",
    source_type: "clinical_manual",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 6,
    is_active: false
  },
  {
    title: "Attention Bias Modification for Anxiety",
    topic: "anxiety",
    subtopic: "attention bias",
    population: "adults",
    clinical_goal: "challenge distortions",
    content: "Attentional bias toward threat is a core cognitive feature of anxiety disorders. Attention Bias Modification (ABM) uses computerised dot-probe tasks to train attention away from threat and toward neutral stimuli across hundreds of trials. Meta-analyses show modest but consistent reductions in anxiety symptoms. ABM is most promising for social anxiety and PTSD hypervigilance, particularly as an adjunct to exposure-based CBT.",
    short_summary: "Describes ABM (attention bias modification) using dot-probe training to redirect threat attention in anxiety, with evidence and clinical limitations.",
    tags: ["attention bias", "ABM", "anxiety", "dot-probe", "threat attention"],
    source_name: "MacLeod & Mathews Attention Bias Research",
    source_type: "research_paper",
    license_status: "adapted",
    safety_notes: "",
    contraindications: "",
    language: "en",
    priority_score: 5,
    is_active: false
  }
];