const chatUiByLanguage = {
  en: {
    common: { back: 'Back', delete: 'Delete' },
    chat: {
      therapist_title: 'Your digital CBT companion', therapist_subtitle: 'A supportive space to reflect and practise',
      welcome: { title: 'Your conversation space', message: 'Share what is on your mind and explore practical CBT tools at your own pace. This AI companion does not replace professional care.', start_session: 'Start a conversation' },
      delete_session_title: 'Delete this session?', delete_session_desc: 'This action cannot be undone.',
      conversations_list: { select_all: 'Select all sessions', selected_count: '{{count}} selected', select_session: 'Select session {{name}}', bulk_delete_aria: 'Delete {{count}} selected sessions', bulk_delete_title_one: 'Delete 1 session?', bulk_delete_title_other: 'Delete {{count}} sessions?', bulk_delete_description_one: 'The selected session will be permanently deleted. This action cannot be undone.', bulk_delete_description_other: '{{count}} selected sessions will be permanently deleted. This action cannot be undone.' },
      proactive: { title: 'Personalised check-ins', ai_suggested: 'AI suggestion', dismiss_aria: 'Dismiss check-in', discuss: 'Discuss this', mood_title: 'Mood check-in', mood_message: 'Your mood has been lower lately. Would you like to talk about what has been happening?', mood_prompt: 'I have been feeling down lately and would like to talk about it.', positive_title: 'Positive progress', positive_message: 'Your mood has been positive this week. What has been helping?', positive_prompt: 'I would like to reflect on what has been going well.', goal_title: 'Goal progress review', goal_message: 'You have been working on “{{title}}” for {{days}} days. Let’s check in on your progress.', goal_prompt: 'I want to discuss my progress on my goal: {{title}}', pattern_title: 'Thinking-pattern insight', pattern_message: '“{{pattern}}” appeared in recent journal entries. Would you like to explore ways to respond?', pattern_prompt: 'I would like to work on my tendency toward {{pattern}}.', exercise_title: 'Practice follow-up', exercise_message: 'You tried “{{title}}” {{days}} days ago. How has it been going?', exercise_prompt: 'I want to discuss how the {{title}} exercise has been working for me.' },
      entry: { welcome: 'Welcome. I’m here to support you.', question: 'What would you like to do today?', option_1: 'I’m not feeling well and want support right now', option_2: 'I have a thought that is bothering me', option_3: 'I want to write or reflect', option_4: 'I want to work on a goal', option_5: 'I want something short and calming' },
      flow: { prompt_1: 'I’m here with you. What is happening right now?', prompt_2: 'Write the thought that is bothering you. One sentence is enough.', prompt_3: 'What would you like to reflect on today?', prompt_4: 'What is one goal you want to work on?', prompt_5: 'Choose calm, grounding or breathing—or write a short line.', type_here: 'Type here…', continue: 'Continue', confirm: 'Would you like help working with this now?', yes: 'Yes, continue', no: 'Not exactly', creating: 'Creating your entry…', alternatives_title: 'Alternative perspectives', alternatives_help: 'Which feels most helpful?', grounding_title: 'Let’s ground together', grounding_1: 'Breathe in slowly for 4 counts, hold for 4, and breathe out for 6.', grounding_2: 'Name 3 things you see, 2 you hear and 1 you can touch.', grounding_3: 'Place both feet on the floor and notice the support beneath you.', save_note: 'Save as a note', calming_exercise: 'Try a calming exercise', goal_created: 'Goal created', goal_saved: 'Your goal was saved. You can track progress at any time.', another: 'Do another', go_goals: 'Go to goals', entry_saved: 'Entry saved', journal_saved: 'Your thought was recorded in your journal.', go_journal: 'Go to journal', reflection: 'You wrote: “{{text}}”. Did I understand correctly?' },
      errors: { voice_unavailable_title: 'Voice recording is unavailable', voice_unavailable_desc: 'This browser or device does not support local microphone recording.', recording_failed_title: 'Voice recording failed', recording_failed_desc: 'Please retry and check microphone permissions.', no_audio_title: 'No audio captured', no_audio_desc: 'Please record again and check your microphone.', mic_denied_title: 'Microphone permission denied', mic_failed_title: 'Microphone access failed', mic_denied_desc: 'Allow microphone access in your settings and retry.', mic_failed_desc: 'Unable to start recording on this device. Please retry.', playback_failed_title: 'Playback failed', playback_failed_desc: 'Unable to play this voice draft.', transcript_added: 'Transcript added to the message.', audio_upload_title: 'Audio upload failed', audio_upload_desc: 'Retry or delete the voice draft.', transcription_title: 'Audio transcription failed', transcription_desc: 'No transcript was returned. Retry or delete the draft.', queue_title: 'Too many messages queued', queue_desc: 'Wait for the current response before sending another message.', file_upload_title: 'File upload failed', file_upload_desc: 'Retry or remove the attachment.' },
      generated_file: { download_error_title: 'Unable to download worksheet', download_error_desc: 'The file could not be downloaded. Please retry or contact support.' },
      document: { view: 'View full document', page_one: '1 page', page_other: '{{count}} pages' }
    },
    age_gate: { message: 'The AI conversation companion is intended for adults aged 18 and over. It offers self-help support and does not replace professional mental-health care.', teen_support_heading: 'If you are under 18, support is still available:', teen_support: { counselor: '• Talk with a parent, guardian, school counsellor or another trusted adult.', teen_line: '• If you may be in immediate danger, contact your local emergency services now.', crisis_text_line: '• Use a verified youth or crisis-support service available in your country or region.' } }
  },
  he: {
    common: { back: 'חזרה', delete: 'מחיקה' },
    chat: {
      therapist_title: 'המלווה הדיגיטלי שלכם ל־CBT', therapist_subtitle: 'מרחב תומך להתבוננות ולתרגול',
      welcome: { title: 'מרחב השיחה שלכם', message: 'שתפו במה שמעסיק אתכם וגלו כלי CBT מעשיים בקצב שלכם. המלווה מבוסס הבינה המלאכותית אינו תחליף לטיפול מקצועי.', start_session: 'התחלת שיחה' },
      delete_session_title: 'למחוק את השיחה?', delete_session_desc: 'לא ניתן לבטל פעולה זו.',
      conversations_list: { select_all: 'בחירת כל השיחות', selected_count: '{{count}} נבחרו', select_session: 'בחירת השיחה {{name}}', bulk_delete_aria: 'מחיקת {{count}} שיחות שנבחרו', bulk_delete_title_one: 'למחוק שיחה אחת?', bulk_delete_title_other: 'למחוק {{count}} שיחות?', bulk_delete_description_one: 'השיחה שנבחרה תימחק לצמיתות. לא ניתן לבטל פעולה זו.', bulk_delete_description_other: '{{count}} השיחות שנבחרו יימחקו לצמיתות. לא ניתן לבטל פעולה זו.' },
      proactive: { title: 'בדיקות אישיות', ai_suggested: 'הצעת AI', dismiss_aria: 'סגירת הבדיקה', discuss: 'לשוחח על כך', mood_title: 'בדיקת מצב רוח', mood_message: 'מצב הרוח שלכם היה נמוך לאחרונה. תרצו לדבר על מה שעובר עליכם?', mood_prompt: 'מצב הרוח שלי נמוך לאחרונה והייתי רוצה לדבר על כך.', positive_title: 'התקדמות חיובית', positive_message: 'מצב הרוח שלכם היה חיובי השבוע. מה עזר לכם?', positive_prompt: 'הייתי רוצה להתבונן במה שהצליח לאחרונה.', goal_title: 'בדיקת התקדמות במטרה', goal_message: 'אתם עובדים על „{{title}}” כבר {{days}} ימים. בואו נבדוק את ההתקדמות.', goal_prompt: 'אני רוצה לדבר על ההתקדמות שלי במטרה: {{title}}', pattern_title: 'תובנה על דפוס חשיבה', pattern_message: 'הדפוס „{{pattern}}” הופיע ברשומות האחרונות. תרצו לבחון דרכי תגובה?', pattern_prompt: 'הייתי רוצה לעבוד על הנטייה שלי לדפוס {{pattern}}.', exercise_title: 'מעקב אחר תרגול', exercise_message: 'ניסיתם את „{{title}}” לפני {{days}} ימים. איך זה מתקדם?', exercise_prompt: 'אני רוצה לדבר על האופן שבו התרגיל {{title}} עובד עבורי.' },
      entry: { welcome: 'ברוכים הבאים. אני כאן כדי לתמוך בכם.', question: 'מה תרצו לעשות היום?', option_1: 'אני לא מרגיש/ה טוב ורוצה תמיכה עכשיו', option_2: 'יש מחשבה שמטרידה אותי', option_3: 'אני רוצה לכתוב או להתבונן', option_4: 'אני רוצה לעבוד על מטרה', option_5: 'אני רוצה משהו קצר ומרגיע' },
      flow: { prompt_1: 'אני כאן איתכם. מה קורה עכשיו?', prompt_2: 'כתבו את המחשבה שמטרידה אתכם. משפט אחד מספיק.', prompt_3: 'על מה תרצו להתבונן היום?', prompt_4: 'על איזו מטרה תרצו לעבוד?', prompt_5: 'בחרו הרגעה, קרקוע או נשימה — או כתבו שורה קצרה.', type_here: 'כתבו כאן…', continue: 'המשך', confirm: 'תרצו עזרה בעבודה על הנושא עכשיו?', yes: 'כן, להמשיך', no: 'לא בדיוק', creating: 'יוצר את הרשומה…', alternatives_title: 'נקודות מבט חלופיות', alternatives_help: 'איזו מהן מועילה לכם ביותר?', grounding_title: 'בואו נתקרקע יחד', grounding_1: 'שאפו לאט במשך 4 ספירות, החזיקו 4 ונשפו במשך 6.', grounding_2: 'ציינו 3 דברים שאתם רואים, 2 שאתם שומעים ו־1 שאתם יכולים לגעת בו.', grounding_3: 'הניחו את שתי הרגליים על הרצפה ושימו לב לתמיכה שמתחתיכם.', save_note: 'שמירה כהערה', calming_exercise: 'ניסיון תרגיל מרגיע', goal_created: 'המטרה נוצרה', goal_saved: 'המטרה נשמרה. אפשר לעקוב אחר ההתקדמות בכל עת.', another: 'פעולה נוספת', go_goals: 'מעבר למטרות', entry_saved: 'הרשומה נשמרה', journal_saved: 'המחשבה נשמרה ביומן.', go_journal: 'מעבר ליומן', reflection: 'כתבתם: „{{text}}”. האם הבנתי נכון?' },
      errors: { voice_unavailable_title: 'הקלטה קולית אינה זמינה', voice_unavailable_desc: 'הדפדפן או המכשיר אינם תומכים בהקלטה מקומית.', recording_failed_title: 'ההקלטה נכשלה', recording_failed_desc: 'נסו שוב ובדקו את הרשאת המיקרופון.', no_audio_title: 'לא נקלט שמע', no_audio_desc: 'הקליטו שוב ובדקו את המיקרופון.', mic_denied_title: 'הגישה למיקרופון נדחתה', mic_failed_title: 'הגישה למיקרופון נכשלה', mic_denied_desc: 'אפשרו גישה למיקרופון בהגדרות ונסו שוב.', mic_failed_desc: 'לא ניתן להתחיל הקלטה במכשיר זה.', playback_failed_title: 'ההשמעה נכשלה', playback_failed_desc: 'לא ניתן להשמיע את טיוטת הקול.', transcript_added: 'התמלול נוסף להודעה.', audio_upload_title: 'העלאת השמע נכשלה', audio_upload_desc: 'נסו שוב או מחקו את טיוטת הקול.', transcription_title: 'תמלול השמע נכשל', transcription_desc: 'לא התקבל תמלול. נסו שוב או מחקו את הטיוטה.', queue_title: 'יותר מדי הודעות ממתינות', queue_desc: 'המתינו לתשובה הנוכחית לפני שליחת הודעה נוספת.', file_upload_title: 'העלאת הקובץ נכשלה', file_upload_desc: 'נסו שוב או הסירו את הקובץ.' },
      generated_file: { download_error_title: 'לא ניתן להוריד את דף העבודה', download_error_desc: 'הקובץ לא ירד. נסו שוב או פנו לתמיכה.' }, document: { view: 'הצגת המסמך המלא', page_one: 'עמוד אחד', page_other: '{{count}} עמודים' }
    },
    age_gate: { message: 'מלווה השיחה מבוסס הבינה המלאכותית מיועד לבני 18 ומעלה. הוא מספק תמיכה לעזרה עצמית ואינו תחליף לטיפול מקצועי בבריאות הנפש.', teen_support_heading: 'אם טרם מלאו לכם 18, עדיין אפשר לקבל תמיכה:', teen_support: { counselor: '• פנו להורה, לאפוטרופוס, ליועץ/ת בית הספר או למבוגר אמין אחר.', teen_line: '• אם נשקפת סכנה מיידית, פנו עכשיו לשירותי החירום המקומיים.', crisis_text_line: '• השתמשו בשירות מאומת לתמיכה בנוער או במשבר הזמין במדינה או באזור שלכם.' } }
  },
  es: {}, fr: {}, de: {}, it: {}, pt: {}
};

const localeCore = {
  es: { common: ['Volver','Eliminar'], title: 'Tu acompañante digital de TCC', subtitle: 'Un espacio de apoyo para reflexionar y practicar', welcome: ['Tu espacio de conversación','Comparte lo que te preocupa y explora herramientas prácticas de TCC a tu ritmo. Este acompañante de IA no sustituye la atención profesional.','Iniciar conversación'], entry: ['Te doy la bienvenida. Estoy aquí para apoyarte.','¿Qué te gustaría hacer hoy?','No me siento bien y quiero apoyo ahora','Tengo un pensamiento que me preocupa','Quiero escribir o reflexionar','Quiero trabajar en una meta','Quiero algo breve y calmante'], age: ['El acompañante de conversación con IA está destinado a mayores de 18 años. Ofrece autoayuda y no sustituye la atención profesional de salud mental.','Si eres menor de 18 años, aún puedes recibir apoyo:','Habla con un adulto de confianza.','Si existe peligro inmediato, contacta con los servicios de emergencia locales.','Usa un servicio juvenil o de crisis verificado en tu país o región.'] },
  fr: { common: ['Retour','Supprimer'], title: 'Votre compagnon TCC numérique', subtitle: 'Un espace de soutien pour réfléchir et pratiquer', welcome: ['Votre espace de conversation','Partagez ce qui vous préoccupe et explorez des outils TCC pratiques à votre rythme. Ce compagnon IA ne remplace pas les soins professionnels.','Commencer une conversation'], entry: ['Bienvenue. Je suis là pour vous soutenir.','Que souhaitez-vous faire aujourd’hui ?','Je ne me sens pas bien et je veux du soutien maintenant','Une pensée me préoccupe','Je veux écrire ou réfléchir','Je veux travailler sur un objectif','Je veux quelque chose de bref et apaisant'], age: ['Le compagnon de conversation IA est destiné aux personnes de 18 ans et plus. Il offre un soutien d’auto-aide et ne remplace pas les soins professionnels.','Si vous avez moins de 18 ans, du soutien reste disponible :','Parlez à un adulte de confiance.','En cas de danger immédiat, contactez les services d’urgence locaux.','Utilisez un service vérifié d’aide aux jeunes ou de crise dans votre pays ou région.'] },
  de: { common: ['Zurück','Löschen'], title: 'Ihr digitaler CBT-Begleiter', subtitle: 'Ein unterstützender Raum zum Nachdenken und Üben', welcome: ['Ihr Gesprächsraum','Teilen Sie, was Sie beschäftigt, und erkunden Sie praktische CBT-Werkzeuge in Ihrem Tempo. Dieser KI-Begleiter ersetzt keine professionelle Hilfe.','Gespräch beginnen'], entry: ['Willkommen. Ich bin hier, um Sie zu unterstützen.','Was möchten Sie heute tun?','Mir geht es nicht gut und ich möchte jetzt Unterstützung','Ein Gedanke belastet mich','Ich möchte schreiben oder nachdenken','Ich möchte an einem Ziel arbeiten','Ich möchte etwas Kurzes und Beruhigendes'], age: ['Der KI-Gesprächsbegleiter ist für Erwachsene ab 18 Jahren vorgesehen. Er bietet Selbsthilfe und ersetzt keine professionelle Versorgung.','Wenn du unter 18 bist, gibt es weiterhin Unterstützung:','Sprich mit einem vertrauten Erwachsenen.','Bei unmittelbarer Gefahr kontaktiere die örtlichen Notdienste.','Nutze einen geprüften Jugend- oder Krisendienst in deinem Land oder deiner Region.'] },
  it: { common: ['Indietro','Elimina'], title: 'Il tuo compagno digitale CBT', subtitle: 'Uno spazio di supporto per riflettere e fare pratica', welcome: ['Il tuo spazio di conversazione','Condividi ciò che ti preoccupa ed esplora strumenti CBT pratici al tuo ritmo. Questo compagno IA non sostituisce l’assistenza professionale.','Inizia una conversazione'], entry: ['Benvenuto. Sono qui per sostenerti.','Cosa vorresti fare oggi?','Non mi sento bene e voglio supporto ora','Ho un pensiero che mi preoccupa','Voglio scrivere o riflettere','Voglio lavorare su un obiettivo','Voglio qualcosa di breve e calmante'], age: ['Il compagno di conversazione IA è destinato agli adulti dai 18 anni in su. Offre auto-aiuto e non sostituisce l’assistenza professionale.','Se hai meno di 18 anni, puoi comunque ricevere supporto:','Parla con un adulto fidato.','In caso di pericolo immediato, contatta i servizi di emergenza locali.','Usa un servizio verificato di supporto giovanile o di crisi nel tuo paese o regione.'] },
  pt: { common: ['Voltar','Eliminar'], title: 'O seu companheiro digital de TCC', subtitle: 'Um espaço de apoio para refletir e praticar', welcome: ['O seu espaço de conversa','Partilhe o que o preocupa e explore ferramentas práticas de TCC ao seu ritmo. Este companheiro de IA não substitui cuidados profissionais.','Iniciar conversa'], entry: ['Bem-vindo. Estou aqui para o apoiar.','O que gostaria de fazer hoje?','Não me sinto bem e quero apoio agora','Tenho um pensamento que me preocupa','Quero escrever ou refletir','Quero trabalhar num objetivo','Quero algo breve e tranquilizante'], age: ['O companheiro de conversa com IA destina-se a adultos com 18 anos ou mais. Oferece autoajuda e não substitui cuidados profissionais.','Se tem menos de 18 anos, ainda há apoio disponível:','Fale com um adulto de confiança.','Em caso de perigo imediato, contacte os serviços de emergência locais.','Use um serviço verificado de apoio juvenil ou de crise no seu país ou região.'] }
};

const sharedSecondary = {
  es: { select_all:'Seleccionar todas las sesiones', selected:'{{count}} seleccionadas', select:'Seleccionar sesión {{name}}', del:'Eliminar {{count}} sesiones seleccionadas', one:'¿Eliminar 1 sesión?', many:'¿Eliminar {{count}} sesiones?', desc1:'La sesión seleccionada se eliminará permanentemente.', descN:'Las {{count}} sesiones seleccionadas se eliminarán permanentemente.', proactive:['Revisiones personalizadas','Sugerencia de IA','Cerrar revisión','Hablar de esto'], flow:['Escribe aquí…','Continuar','¿Quieres ayuda para trabajar en esto ahora?','Sí, continuar','No exactamente','Creando la entrada…','Perspectivas alternativas','¿Cuál resulta más útil?','Conectemos con el presente','Guardar como nota','Probar un ejercicio calmante','Objetivo creado','Tu objetivo se guardó.','Hacer otro','Ir a objetivos','Entrada guardada','Tu pensamiento se guardó en el diario.','Ir al diario'], errors:['Grabación de voz no disponible','Este dispositivo no admite grabación local.','La grabación falló','Inténtalo de nuevo y revisa el permiso del micrófono.','No se capturó audio','Graba de nuevo y comprueba el micrófono.','Permiso del micrófono denegado','No se pudo acceder al micrófono','La reproducción falló','No se pudo reproducir el borrador.','Transcripción añadida al mensaje.','La carga de audio falló','Reintenta o elimina el borrador.','La transcripción falló','No se recibió una transcripción.','Demasiados mensajes en espera','Espera la respuesta actual.','La carga del archivo falló','Reintenta o elimina el archivo.'], doc:['Ver documento completo','1 página','{{count}} páginas'] },
  fr: { select_all:'Sélectionner toutes les séances', selected:'{{count}} sélectionnées', select:'Sélectionner la séance {{name}}', del:'Supprimer {{count}} séances sélectionnées', one:'Supprimer 1 séance ?', many:'Supprimer {{count}} séances ?', desc1:'La séance sélectionnée sera supprimée définitivement.', descN:'Les {{count}} séances sélectionnées seront supprimées définitivement.', proactive:['Points de suivi personnalisés','Suggestion IA','Fermer le suivi','En parler'], flow:['Écrivez ici…','Continuer','Souhaitez-vous de l’aide maintenant ?','Oui, continuer','Pas exactement','Création de l’entrée…','Perspectives alternatives','Laquelle est la plus utile ?','Revenons au moment présent','Enregistrer comme note','Essayer un exercice apaisant','Objectif créé','Votre objectif a été enregistré.','En faire un autre','Voir les objectifs','Entrée enregistrée','Votre pensée a été enregistrée dans le journal.','Voir le journal'], errors:['Enregistrement vocal indisponible','Cet appareil ne prend pas en charge l’enregistrement local.','Échec de l’enregistrement','Réessayez et vérifiez le microphone.','Aucun son capturé','Enregistrez à nouveau et vérifiez le microphone.','Accès au microphone refusé','Échec de l’accès au microphone','Échec de la lecture','Impossible de lire le brouillon.','Transcription ajoutée au message.','Échec de l’envoi audio','Réessayez ou supprimez le brouillon.','Échec de la transcription','Aucune transcription reçue.','Trop de messages en attente','Attendez la réponse actuelle.','Échec de l’envoi du fichier','Réessayez ou retirez le fichier.'], doc:['Voir le document complet','1 page','{{count}} pages'] },
  de: { select_all:'Alle Sitzungen auswählen', selected:'{{count}} ausgewählt', select:'Sitzung {{name}} auswählen', del:'{{count}} ausgewählte Sitzungen löschen', one:'1 Sitzung löschen?', many:'{{count}} Sitzungen löschen?', desc1:'Die ausgewählte Sitzung wird dauerhaft gelöscht.', descN:'{{count}} ausgewählte Sitzungen werden dauerhaft gelöscht.', proactive:['Persönliche Check-ins','KI-Vorschlag','Check-in schließen','Darüber sprechen'], flow:['Hier schreiben…','Weiter','Möchten Sie jetzt Hilfe dabei?','Ja, weiter','Nicht ganz','Eintrag wird erstellt…','Alternative Perspektiven','Welche ist am hilfreichsten?','Kommen wir im Moment an','Als Notiz speichern','Beruhigende Übung versuchen','Ziel erstellt','Ihr Ziel wurde gespeichert.','Noch einmal','Zu den Zielen','Eintrag gespeichert','Ihr Gedanke wurde im Tagebuch gespeichert.','Zum Tagebuch'], errors:['Sprachaufnahme nicht verfügbar','Dieses Gerät unterstützt keine lokale Aufnahme.','Aufnahme fehlgeschlagen','Versuchen Sie es erneut und prüfen Sie das Mikrofon.','Kein Ton aufgenommen','Nehmen Sie erneut auf und prüfen Sie das Mikrofon.','Mikrofonzugriff verweigert','Mikrofonzugriff fehlgeschlagen','Wiedergabe fehlgeschlagen','Der Entwurf konnte nicht abgespielt werden.','Transkript zur Nachricht hinzugefügt.','Audio-Upload fehlgeschlagen','Versuchen Sie es erneut oder löschen Sie den Entwurf.','Transkription fehlgeschlagen','Kein Transkript erhalten.','Zu viele wartende Nachrichten','Warten Sie auf die aktuelle Antwort.','Datei-Upload fehlgeschlagen','Versuchen Sie es erneut oder entfernen Sie die Datei.'], doc:['Vollständiges Dokument anzeigen','1 Seite','{{count}} Seiten'] },
  it: { select_all:'Seleziona tutte le sessioni', selected:'{{count}} selezionate', select:'Seleziona sessione {{name}}', del:'Elimina {{count}} sessioni selezionate', one:'Eliminare 1 sessione?', many:'Eliminare {{count}} sessioni?', desc1:'La sessione selezionata verrà eliminata definitivamente.', descN:'Le {{count}} sessioni selezionate verranno eliminate definitivamente.', proactive:['Check-in personalizzati','Suggerimento IA','Chiudi check-in','Parlane'], flow:['Scrivi qui…','Continua','Vuoi aiuto per lavorarci ora?','Sì, continua','Non esattamente','Creazione della voce…','Prospettive alternative','Quale è più utile?','Radichiamoci nel presente','Salva come nota','Prova un esercizio calmante','Obiettivo creato','Il tuo obiettivo è stato salvato.','Fanne un altro','Vai agli obiettivi','Voce salvata','Il pensiero è stato salvato nel diario.','Vai al diario'], errors:['Registrazione vocale non disponibile','Questo dispositivo non supporta la registrazione locale.','Registrazione non riuscita','Riprova e verifica il microfono.','Nessun audio acquisito','Registra di nuovo e controlla il microfono.','Permesso microfono negato','Accesso al microfono non riuscito','Riproduzione non riuscita','Impossibile riprodurre la bozza.','Trascrizione aggiunta al messaggio.','Caricamento audio non riuscito','Riprova o elimina la bozza.','Trascrizione non riuscita','Nessuna trascrizione ricevuta.','Troppi messaggi in attesa','Attendi la risposta corrente.','Caricamento file non riuscito','Riprova o rimuovi il file.'], doc:['Visualizza documento completo','1 pagina','{{count}} pagine'] },
  pt: { select_all:'Selecionar todas as sessões', selected:'{{count}} selecionadas', select:'Selecionar sessão {{name}}', del:'Eliminar {{count}} sessões selecionadas', one:'Eliminar 1 sessão?', many:'Eliminar {{count}} sessões?', desc1:'A sessão selecionada será eliminada permanentemente.', descN:'As {{count}} sessões selecionadas serão eliminadas permanentemente.', proactive:['Acompanhamentos personalizados','Sugestão de IA','Fechar acompanhamento','Falar sobre isto'], flow:['Escreva aqui…','Continuar','Gostaria de ajuda para trabalhar nisto agora?','Sim, continuar','Não exatamente','A criar a entrada…','Perspetivas alternativas','Qual é a mais útil?','Vamos ancorar no presente','Guardar como nota','Experimentar um exercício calmante','Objetivo criado','O seu objetivo foi guardado.','Fazer outro','Ir para objetivos','Entrada guardada','O pensamento foi guardado no diário.','Ir para o diário'], errors:['Gravação de voz indisponível','Este dispositivo não suporta gravação local.','Falha na gravação','Tente novamente e verifique o microfone.','Nenhum áudio captado','Grave novamente e verifique o microfone.','Permissão do microfone recusada','Falha no acesso ao microfone','Falha na reprodução','Não foi possível reproduzir o rascunho.','Transcrição adicionada à mensagem.','Falha no envio do áudio','Tente novamente ou elimine o rascunho.','Falha na transcrição','Não foi recebida transcrição.','Demasiadas mensagens em espera','Aguarde a resposta atual.','Falha no envio do ficheiro','Tente novamente ou remova o ficheiro.'], doc:['Ver documento completo','1 página','{{count}} páginas'] }
};

Object.entries(localeCore).forEach(([lng, x]) => {
  const s = sharedSecondary[lng];
  chatUiByLanguage[lng] = {
    common: { back: x.common[0], delete: x.common[1] },
    chat: {
      therapist_title: x.title, therapist_subtitle: x.subtitle,
      welcome: { title:x.welcome[0], message:x.welcome[1], start_session:x.welcome[2] },
      delete_session_title:s.one, delete_session_desc:s.desc1,
      conversations_list:{ select_all:s.select_all, selected_count:s.selected, select_session:s.select, bulk_delete_aria:s.del, bulk_delete_title_one:s.one, bulk_delete_title_other:s.many, bulk_delete_description_one:s.desc1, bulk_delete_description_other:s.descN },
      proactive:{ title:s.proactive[0], ai_suggested:s.proactive[1], dismiss_aria:s.proactive[2], discuss:s.proactive[3] },
      entry:{ welcome:x.entry[0], question:x.entry[1], option_1:x.entry[2], option_2:x.entry[3], option_3:x.entry[4], option_4:x.entry[5], option_5:x.entry[6] },
      flow:{ type_here:s.flow[0], continue:s.flow[1], confirm:s.flow[2], yes:s.flow[3], no:s.flow[4], creating:s.flow[5], alternatives_title:s.flow[6], alternatives_help:s.flow[7], grounding_title:s.flow[8], save_note:s.flow[9], calming_exercise:s.flow[10], goal_created:s.flow[11], goal_saved:s.flow[12], another:s.flow[13], go_goals:s.flow[14], entry_saved:s.flow[15], journal_saved:s.flow[16], go_journal:s.flow[17], reflection:'“{{text}}”' },
      errors:{ voice_unavailable_title:s.errors[0], voice_unavailable_desc:s.errors[1], recording_failed_title:s.errors[2], recording_failed_desc:s.errors[3], no_audio_title:s.errors[4], no_audio_desc:s.errors[5], mic_denied_title:s.errors[6], mic_failed_title:s.errors[7], mic_denied_desc:s.errors[3], mic_failed_desc:s.errors[3], playback_failed_title:s.errors[8], playback_failed_desc:s.errors[9], transcript_added:s.errors[10], audio_upload_title:s.errors[11], audio_upload_desc:s.errors[12], transcription_title:s.errors[13], transcription_desc:s.errors[14], queue_title:s.errors[15], queue_desc:s.errors[16], file_upload_title:s.errors[17], file_upload_desc:s.errors[18] },
      generated_file:{ download_error_title:s.errors[17], download_error_desc:s.errors[18] }, document:{ view:s.doc[0], page_one:s.doc[1], page_other:s.doc[2] }
    },
    age_gate:{ message:x.age[0], teen_support_heading:x.age[1], teen_support:{ counselor:`• ${x.age[2]}`, teen_line:`• ${x.age[3]}`, crisis_text_line:`• ${x.age[4]}` } }
  };
});

const localeDynamic = {
  es: {
    proactive:['Revisión del estado de ánimo','Tu estado de ánimo ha estado más bajo. ¿Quieres hablar de ello?','Últimamente me siento decaído y quiero hablar de ello.','Progreso positivo','Tu estado de ánimo ha sido positivo. ¿Qué te ha ayudado?','Quiero reflexionar sobre lo que ha ido bien.','Revisión del objetivo','Llevas {{days}} días trabajando en «{{title}}». Revisemos tu progreso.','Quiero hablar de mi progreso en el objetivo: {{title}}','Patrón de pensamiento','«{{pattern}}» apareció en entradas recientes. ¿Quieres explorar cómo responder?','Quiero trabajar mi tendencia hacia {{pattern}}.','Seguimiento de práctica','Probaste «{{title}}» hace {{days}} días. ¿Cómo va?','Quiero hablar de cómo me funciona el ejercicio {{title}}.'],
    prompts:['Estoy aquí contigo. ¿Qué está pasando ahora?','Escribe el pensamiento que te preocupa. Una frase basta.','¿Sobre qué te gustaría reflexionar hoy?','¿En qué objetivo te gustaría trabajar?','Elige calma, conexión con el presente o respiración.'], ground:['Inhala lentamente durante 4 tiempos, mantén 4 y exhala durante 6.','Nombra 3 cosas que ves, 2 que oyes y 1 que puedes tocar.','Apoya ambos pies en el suelo y nota el soporte.']
  },
  fr: {
    proactive:['Point sur l’humeur','Votre humeur semble plus basse. Souhaitez-vous en parler ?','Mon humeur est basse et je souhaite en parler.','Progrès positif','Votre humeur a été positive. Qu’est-ce qui vous a aidé ?','Je souhaite réfléchir à ce qui s’est bien passé.','Suivi de l’objectif','Vous travaillez sur « {{title}} » depuis {{days}} jours. Faisons le point.','Je veux parler de mes progrès sur l’objectif : {{title}}','Schéma de pensée','« {{pattern}} » apparaît dans vos notes récentes. Souhaitez-vous explorer comment y répondre ?','Je souhaite travailler sur ma tendance à {{pattern}}.','Suivi de la pratique','Vous avez essayé « {{title}} » il y a {{days}} jours. Comment cela se passe-t-il ?','Je veux parler de la façon dont l’exercice {{title}} fonctionne pour moi.'],
    prompts:['Je suis là avec vous. Que se passe-t-il maintenant ?','Écrivez la pensée qui vous préoccupe. Une phrase suffit.','Sur quoi souhaitez-vous réfléchir aujourd’hui ?','Sur quel objectif souhaitez-vous travailler ?','Choisissez calme, ancrage ou respiration.'], ground:['Inspirez lentement pendant 4 temps, retenez 4 et expirez pendant 6.','Nommez 3 choses que vous voyez, 2 que vous entendez et 1 que vous pouvez toucher.','Posez les deux pieds au sol et sentez le support.']
  },
  de: {
    proactive:['Stimmungs-Check-in','Ihre Stimmung war niedriger. Möchten Sie darüber sprechen?','Ich fühle mich niedergeschlagen und möchte darüber sprechen.','Positive Entwicklung','Ihre Stimmung war positiv. Was hat geholfen?','Ich möchte darüber nachdenken, was gut gelaufen ist.','Zielfortschritt','Sie arbeiten seit {{days}} Tagen an „{{title}}“. Sehen wir uns den Fortschritt an.','Ich möchte über meinen Fortschritt beim Ziel sprechen: {{title}}','Denkmuster','„{{pattern}}“ tauchte in jüngsten Einträgen auf. Möchten Sie Reaktionen erkunden?','Ich möchte an meiner Tendenz zu {{pattern}} arbeiten.','Übungsnachverfolgung','Sie haben „{{title}}“ vor {{days}} Tagen ausprobiert. Wie läuft es?','Ich möchte besprechen, wie die Übung {{title}} für mich funktioniert.'],
    prompts:['Ich bin hier bei Ihnen. Was passiert gerade?','Schreiben Sie den belastenden Gedanken auf. Ein Satz genügt.','Worüber möchten Sie heute nachdenken?','An welchem Ziel möchten Sie arbeiten?','Wählen Sie Beruhigung, Erdung oder Atmung.'], ground:['Atmen Sie 4 Zählzeiten ein, halten Sie 4 und atmen Sie 6 aus.','Nennen Sie 3 Dinge, die Sie sehen, 2, die Sie hören, und 1, das Sie berühren können.','Stellen Sie beide Füße auf den Boden und spüren Sie den Halt.']
  },
  it: {
    proactive:['Controllo dell’umore','Il tuo umore è stato più basso. Vuoi parlarne?','Ultimamente mi sento giù e vorrei parlarne.','Progresso positivo','Il tuo umore è stato positivo. Cosa ti ha aiutato?','Vorrei riflettere su ciò che è andato bene.','Verifica dell’obiettivo','Lavori su “{{title}}” da {{days}} giorni. Verifichiamo i progressi.','Voglio parlare dei progressi sul mio obiettivo: {{title}}','Schema di pensiero','“{{pattern}}” è apparso nelle note recenti. Vuoi esplorare come rispondere?','Vorrei lavorare sulla mia tendenza a {{pattern}}.','Verifica della pratica','Hai provato “{{title}}” {{days}} giorni fa. Come sta andando?','Voglio parlare di come funziona per me l’esercizio {{title}}.'],
    prompts:['Sono qui con te. Cosa sta succedendo ora?','Scrivi il pensiero che ti preoccupa. Basta una frase.','Su cosa vorresti riflettere oggi?','Su quale obiettivo vorresti lavorare?','Scegli calma, radicamento o respirazione.'], ground:['Inspira lentamente per 4 tempi, trattieni per 4 ed espira per 6.','Nomina 3 cose che vedi, 2 che senti e 1 che puoi toccare.','Appoggia entrambi i piedi a terra e nota il sostegno.']
  },
  pt: {
    proactive:['Acompanhamento do humor','O seu humor tem estado mais baixo. Gostaria de falar sobre isso?','Tenho-me sentido em baixo e gostaria de falar sobre isso.','Progresso positivo','O seu humor esteve positivo. O que ajudou?','Gostaria de refletir sobre o que correu bem.','Revisão do objetivo','Trabalha em “{{title}}” há {{days}} dias. Vamos rever o progresso.','Quero falar sobre o meu progresso no objetivo: {{title}}','Padrão de pensamento','“{{pattern}}” apareceu em registos recentes. Gostaria de explorar como responder?','Gostaria de trabalhar a minha tendência para {{pattern}}.','Acompanhamento da prática','Experimentou “{{title}}” há {{days}} dias. Como está a correr?','Quero falar sobre como o exercício {{title}} funciona para mim.'],
    prompts:['Estou aqui consigo. O que está a acontecer agora?','Escreva o pensamento que o preocupa. Uma frase basta.','Sobre o que gostaria de refletir hoje?','Em que objetivo gostaria de trabalhar?','Escolha calma, ancoragem ou respiração.'], ground:['Inspire lentamente durante 4 tempos, segure 4 e expire durante 6.','Diga 3 coisas que vê, 2 que ouve e 1 que pode tocar.','Coloque os dois pés no chão e note o apoio.']
  }
};

Object.entries(localeDynamic).forEach(([lng, x]) => {
  const p = x.proactive;
  Object.assign(chatUiByLanguage[lng].chat.proactive, { mood_title:p[0], mood_message:p[1], mood_prompt:p[2], positive_title:p[3], positive_message:p[4], positive_prompt:p[5], goal_title:p[6], goal_message:p[7], goal_prompt:p[8], pattern_title:p[9], pattern_message:p[10], pattern_prompt:p[11], exercise_title:p[12], exercise_message:p[13], exercise_prompt:p[14] });
  Object.assign(chatUiByLanguage[lng].chat.flow, { prompt_1:x.prompts[0], prompt_2:x.prompts[1], prompt_3:x.prompts[2], prompt_4:x.prompts[3], prompt_5:x.prompts[4], grounding_1:x.ground[0], grounding_2:x.ground[1], grounding_3:x.ground[2] });
});

const flowFallbacks = {
  en:['This thought may not reflect the full picture.','I can approach this from another angle.','I am doing my best in these circumstances.','Identified during a conversation','Reflection from a conversation','Grounding practice'],
  he:['ייתכן שהמחשבה הזו אינה משקפת את התמונה המלאה.','אפשר להתבונן בכך מזווית אחרת.','אני עושה כמיטב יכולתי בנסיבות האלה.','זוהה במהלך שיחה','התבוננות מתוך שיחה','תרגול קרקוע'],
  es:['Este pensamiento quizá no refleje toda la situación.','Puedo verlo desde otro ángulo.','Estoy haciendo lo mejor posible en estas circunstancias.','Identificado durante una conversación','Reflexión de una conversación','Práctica de conexión con el presente'],
  fr:['Cette pensée ne reflète peut-être pas toute la situation.','Je peux l’aborder sous un autre angle.','Je fais de mon mieux dans ces circonstances.','Identifié pendant une conversation','Réflexion issue d’une conversation','Exercice d’ancrage'],
  de:['Dieser Gedanke zeigt möglicherweise nicht das ganze Bild.','Ich kann es aus einem anderen Blickwinkel betrachten.','Ich tue unter diesen Umständen mein Bestes.','Während eines Gesprächs erkannt','Reflexion aus einem Gespräch','Erdungsübung'],
  it:['Questo pensiero potrebbe non riflettere l’intera situazione.','Posso guardarlo da un’altra prospettiva.','Sto facendo del mio meglio in queste circostanze.','Individuato durante una conversazione','Riflessione da una conversazione','Pratica di radicamento'],
  pt:['Este pensamento pode não refletir toda a situação.','Posso olhar para isto de outra perspetiva.','Estou a fazer o melhor possível nestas circunstâncias.','Identificado durante uma conversa','Reflexão de uma conversa','Prática de ancoragem']
};
Object.entries(flowFallbacks).forEach(([lng, x]) => Object.assign(chatUiByLanguage[lng].chat.flow, { fallback_1:x[0], fallback_2:x[1], fallback_3:x[2], situation_thought:x[3], situation_reflection:x[4], situation_grounding:x[5] }));

const conversationToolsByLanguage = {
  en: ['Search conversations', 'No conversations match your search.', 'Rename', 'Pin', 'Unpin', 'Conversation actions for {{name}}', 'Pinned', 'Conversation name', 'Save name', 'Could not update conversation', 'Please try again.', 'File is too large', 'Choose a file up to 10 MB.', 'Unsupported file type', 'Choose an image, PDF, Word document, text file or CSV.'],
  he: ['חיפוש בשיחות', 'לא נמצאו שיחות התואמות לחיפוש.', 'שינוי שם', 'הצמדה', 'ביטול הצמדה', 'פעולות עבור השיחה {{name}}', 'מוצמדת', 'שם השיחה', 'שמירת השם', 'לא ניתן לעדכן את השיחה', 'נסו שוב.', 'הקובץ גדול מדי', 'בחרו קובץ בגודל של עד 10 MB.', 'סוג הקובץ אינו נתמך', 'בחרו תמונה, PDF, מסמך Word, קובץ טקסט או CSV.'],
  es: ['Buscar conversaciones', 'Ninguna conversación coincide con la búsqueda.', 'Cambiar nombre', 'Fijar', 'Desfijar', 'Acciones de la conversación {{name}}', 'Fijada', 'Nombre de la conversación', 'Guardar nombre', 'No se pudo actualizar la conversación', 'Inténtalo de nuevo.', 'El archivo es demasiado grande', 'Elige un archivo de hasta 10 MB.', 'Tipo de archivo no compatible', 'Elige una imagen, PDF, documento Word, archivo de texto o CSV.'],
  fr: ['Rechercher des conversations', 'Aucune conversation ne correspond à la recherche.', 'Renommer', 'Épingler', 'Désépingler', 'Actions pour la conversation {{name}}', 'Épinglée', 'Nom de la conversation', 'Enregistrer le nom', 'Impossible de mettre à jour la conversation', 'Veuillez réessayer.', 'Fichier trop volumineux', 'Choisissez un fichier de 10 Mo maximum.', 'Type de fichier non pris en charge', 'Choisissez une image, un PDF, un document Word, un fichier texte ou CSV.'],
  de: ['Gespräche durchsuchen', 'Keine Gespräche entsprechen der Suche.', 'Umbenennen', 'Anheften', 'Loslösen', 'Aktionen für Gespräch {{name}}', 'Angeheftet', 'Gesprächsname', 'Namen speichern', 'Gespräch konnte nicht aktualisiert werden', 'Bitte versuchen Sie es erneut.', 'Datei ist zu groß', 'Wählen Sie eine Datei bis 10 MB.', 'Nicht unterstützter Dateityp', 'Wählen Sie ein Bild, PDF, Word-Dokument, eine Text- oder CSV-Datei.'],
  it: ['Cerca conversazioni', 'Nessuna conversazione corrisponde alla ricerca.', 'Rinomina', 'Fissa', 'Rimuovi', 'Azioni per la conversazione {{name}}', 'Fissata', 'Nome della conversazione', 'Salva nome', 'Impossibile aggiornare la conversazione', 'Riprova.', 'Il file è troppo grande', 'Scegli un file fino a 10 MB.', 'Tipo di file non supportato', 'Scegli un’immagine, PDF, documento Word, file di testo o CSV.'],
  pt: ['Pesquisar conversas', 'Nenhuma conversa corresponde à pesquisa.', 'Mudar nome', 'Fixar', 'Desafixar', 'Ações da conversa {{name}}', 'Fixada', 'Nome da conversa', 'Guardar nome', 'Não foi possível atualizar a conversa', 'Tente novamente.', 'O ficheiro é demasiado grande', 'Escolha um ficheiro até 10 MB.', 'Tipo de ficheiro não suportado', 'Escolha uma imagem, PDF, documento Word, ficheiro de texto ou CSV.']
};

Object.entries(conversationToolsByLanguage).forEach(([lng, x]) => {
  Object.assign(chatUiByLanguage[lng].chat.conversations_list, {
    search_placeholder:x[0], no_search_results:x[1], rename_aria:x[2], pin_aria:x[3], unpin_aria:x[4], actions_aria:x[5], pinned_label:x[6], rename_placeholder:x[7], save_name:x[8], update_error_title:x[9], update_error_desc:x[10]
  });
  Object.assign(chatUiByLanguage[lng].chat.errors, {
    file_too_large_title:x[11], file_too_large_desc:x[12], unsupported_file_title:x[13], unsupported_file_desc:x[14]
  });
});

function merge(target = {}, source = {}) {
  const result = { ...target };
  Object.entries(source).forEach(([key, value]) => {
    result[key] = value && typeof value === 'object' && !Array.isArray(value)
      ? merge(target?.[key] || {}, value)
      : value;
  });
  return result;
}

export function applyChatUiTranslations(translations) {
  Object.entries(chatUiByLanguage).forEach(([language, values]) => {
    translations[language].translation = merge(translations[language]?.translation || {}, values);
  });
  return translations;
}

export { chatUiByLanguage };
