const languages = ['en', 'he', 'es', 'fr', 'de', 'it', 'pt'];

const rows = [
  ['loading', 'Loading coaching sessions…', 'טוען מפגשי אימון…', 'Cargando sesiones de coaching…', 'Chargement des séances de coaching…', 'Coaching-Sitzungen werden geladen…', 'Caricamento delle sessioni di coaching…', 'A carregar sessões de coaching…'],
  ['load_error', 'We could not load your coaching sessions.', 'לא הצלחנו לטעון את מפגשי האימון שלכם.', 'No pudimos cargar tus sesiones de coaching.', 'Impossible de charger vos séances de coaching.', 'Ihre Coaching-Sitzungen konnten nicht geladen werden.', 'Non è stato possibile caricare le sessioni di coaching.', 'Não foi possível carregar as suas sessões de coaching.'],
  ['retry', 'Try again', 'נסו שוב', 'Intentar de nuevo', 'Réessayer', 'Erneut versuchen', 'Riprova', 'Tentar novamente'],
  ['delete_confirm', 'Delete this coaching session? This cannot be undone.', 'למחוק את מפגש האימון? לא ניתן לבטל פעולה זו.', '¿Eliminar esta sesión de coaching? Esta acción no se puede deshacer.', 'Supprimer cette séance de coaching ? Cette action est irréversible.', 'Diese Coaching-Sitzung löschen? Dies kann nicht rückgängig gemacht werden.', 'Eliminare questa sessione di coaching? L’azione è irreversibile.', 'Eliminar esta sessão de coaching? Esta ação não pode ser anulada.'],
  ['delete_error', 'The session could not be deleted. Please try again.', 'לא ניתן היה למחוק את המפגש. נסו שוב.', 'No se pudo eliminar la sesión. Inténtalo de nuevo.', 'La séance n’a pas pu être supprimée. Réessayez.', 'Die Sitzung konnte nicht gelöscht werden. Bitte versuchen Sie es erneut.', 'Non è stato possibile eliminare la sessione. Riprova.', 'Não foi possível eliminar a sessão. Tente novamente.'],
  ['welcome.title', 'Welcome to AI coaching', 'ברוכים הבאים לאימון האישי עם AI', 'Te damos la bienvenida al coaching con IA', 'Bienvenue dans le coaching avec l’IA', 'Willkommen beim KI-Coaching', 'Benvenuto nel coaching con IA', 'Bem-vindo ao coaching com IA'],
  ['welcome.description', 'Work step by step with your coach to clarify challenges, set focused goals and move forward with confidence.', 'עבדו צעד אחר צעד עם המאמן כדי להבהיר את האתגרים, להציב מטרות ממוקדות ולהתקדם בביטחון.', 'Trabaja paso a paso con tu coach para aclarar retos, fijar metas concretas y avanzar con confianza.', 'Avancez étape par étape avec votre coach pour clarifier vos défis, définir des objectifs précis et progresser avec confiance.', 'Arbeiten Sie Schritt für Schritt mit Ihrem Coach, um Herausforderungen zu klären, klare Ziele zu setzen und sicher voranzukommen.', 'Lavora passo dopo passo con il coach per chiarire le sfide, definire obiettivi mirati e procedere con fiducia.', 'Trabalhe passo a passo com o coach para clarificar desafios, definir objetivos concretos e avançar com confiança.'],
  ['welcome.bullet_1', 'Turn overwhelming thoughts into clear actions', 'הפכו מחשבות מציפות לפעולות ברורות', 'Convierte pensamientos abrumadores en acciones claras', 'Transformez les pensées envahissantes en actions claires', 'Verwandeln Sie überwältigende Gedanken in klare Schritte', 'Trasforma i pensieri opprimenti in azioni chiare', 'Transforme pensamentos avassaladores em ações claras'],
  ['welcome.bullet_2', 'Receive structured guidance tailored to you', 'קבלו הכוונה מובנית המותאמת לכם', 'Recibe orientación estructurada y adaptada a ti', 'Recevez un accompagnement structuré et personnalisé', 'Erhalten Sie strukturierte, persönliche Anleitung', 'Ricevi una guida strutturata e personalizzata', 'Receba orientação estruturada e personalizada'],
  ['welcome.bullet_3', 'Build momentum from one session to the next', 'בנו תנופה ממפגש למפגש', 'Gana impulso de una sesión a la siguiente', 'Créez une dynamique d’une séance à l’autre', 'Bauen Sie von Sitzung zu Sitzung Schwung auf', 'Crea slancio da una sessione all’altra', 'Ganhe impulso de uma sessão para a seguinte'],
  ['welcome.bullet_4', 'Identify what matters most right now', 'זהו מה חשוב ביותר עכשיו', 'Identifica lo que más importa ahora', 'Identifiez ce qui compte le plus maintenant', 'Erkennen Sie, was jetzt am wichtigsten ist', 'Individua ciò che conta di più adesso', 'Identifique o que mais importa agora'],
  ['welcome.bullet_5', 'Turn stress into a practical plan', 'הפכו מתח לתוכנית מעשית', 'Convierte el estrés en un plan práctico', 'Transformez le stress en plan concret', 'Machen Sie aus Stress einen praktischen Plan', 'Trasforma lo stress in un piano concreto', 'Transforme o stress num plano prático'],
  ['welcome.start', 'Start your first session', 'התחילו את המפגש הראשון', 'Iniciar tu primera sesión', 'Commencer votre première séance', 'Erste Sitzung starten', 'Inizia la prima sessione', 'Iniciar a primeira sessão'],
  ['personalized_insights', 'Your personalised insights', 'התובנות האישיות שלכם', 'Tus perspectivas personalizadas', 'Vos éclairages personnalisés', 'Ihre persönlichen Einblicke', 'I tuoi approfondimenti personalizzati', 'As suas perspetivas personalizadas'],

  ['session.none', 'No sessions here yet', 'עדיין אין כאן מפגשים', 'Aún no hay sesiones aquí', 'Aucune séance ici pour le moment', 'Hier gibt es noch keine Sitzungen', 'Non ci sono ancora sessioni qui', 'Ainda não há sessões aqui'],
  ['session.open_aria', 'Open coaching session {{title}}', 'פתיחת מפגש האימון {{title}}', 'Abrir la sesión de coaching {{title}}', 'Ouvrir la séance de coaching {{title}}', 'Coaching-Sitzung {{title}} öffnen', 'Apri la sessione di coaching {{title}}', 'Abrir a sessão de coaching {{title}}'],
  ['session.started', 'Started {{date}}', 'התחיל ב־{{date}}', 'Iniciada el {{date}}', 'Commencée le {{date}}', 'Begonnen am {{date}}', 'Iniziata il {{date}}', 'Iniciada em {{date}}'],
  ['session.stage', 'Stage', 'שלב', 'Etapa', 'Étape', 'Phase', 'Fase', 'Etapa'],
  ['session.progress', 'Progress', 'התקדמות', 'Progreso', 'Progression', 'Fortschritt', 'Progresso', 'Progresso'],
  ['session.actions', '{{completed}} of {{total}} actions', '{{completed}} מתוך {{total}} פעולות', '{{completed}} de {{total}} acciones', '{{completed}} actions sur {{total}}', '{{completed}} von {{total}} Schritten', '{{completed}} azioni su {{total}}', '{{completed}} de {{total}} ações'],
  ['session.completed', 'Completed', 'הושלם', 'Completada', 'Terminée', 'Abgeschlossen', 'Completata', 'Concluída'],
  ['session.delete', 'Delete', 'מחיקה', 'Eliminar', 'Supprimer', 'Löschen', 'Elimina', 'Eliminar'],
  ['session.delete_aria', 'Delete coaching session {{title}}', 'מחיקת מפגש האימון {{title}}', 'Eliminar la sesión de coaching {{title}}', 'Supprimer la séance de coaching {{title}}', 'Coaching-Sitzung {{title}} löschen', 'Elimina la sessione di coaching {{title}}', 'Eliminar a sessão de coaching {{title}}'],
  ['stage.discovery', 'Discovery', 'היכרות והבנה', 'Exploración', 'Exploration', 'Erkundung', 'Esplorazione', 'Exploração'],
  ['stage.planning', 'Planning', 'תכנון', 'Planificación', 'Planification', 'Planung', 'Pianificazione', 'Planeamento'],
  ['stage.action', 'Taking action', 'יציאה לפעולה', 'En acción', 'Passage à l’action', 'Umsetzung', 'Azione', 'Em ação'],
  ['stage.review', 'Review', 'סקירה', 'Revisión', 'Bilan', 'Rückblick', 'Revisione', 'Revisão'],
  ['stage.completed', 'Completed', 'הושלם', 'Completada', 'Terminée', 'Abgeschlossen', 'Completata', 'Concluída'],

  ['wizard.title', 'Start a new coaching session', 'פתיחת מפגש אימון חדש', 'Iniciar una nueva sesión de coaching', 'Commencer une nouvelle séance de coaching', 'Neue Coaching-Sitzung starten', 'Inizia una nuova sessione di coaching', 'Iniciar uma nova sessão de coaching'],
  ['wizard.step', 'Step {{step}} of 3', 'שלב {{step}} מתוך 3', 'Paso {{step}} de 3', 'Étape {{step}} sur 3', 'Schritt {{step}} von 3', 'Passaggio {{step}} di 3', 'Passo {{step}} de 3'],
  ['wizard.close_aria', 'Close session setup', 'סגירת הגדרת המפגש', 'Cerrar la configuración', 'Fermer la configuration', 'Einrichtung schließen', 'Chiudi la configurazione', 'Fechar a configuração'],
  ['wizard.back_aria', 'Go to the previous step', 'חזרה לשלב הקודם', 'Ir al paso anterior', 'Revenir à l’étape précédente', 'Zum vorherigen Schritt', 'Vai al passaggio precedente', 'Voltar ao passo anterior'],
  ['wizard.focus_title', 'What would you like to work on?', 'על מה תרצו לעבוד?', '¿En qué te gustaría trabajar?', 'Sur quoi souhaitez-vous travailler ?', 'Woran möchten Sie arbeiten?', 'Su cosa vorresti lavorare?', 'Em que gostaria de trabalhar?'],
  ['wizard.focus_description', 'Choose the area you want to focus on.', 'בחרו את התחום שבו תרצו להתמקד.', 'Elige el área en la que quieres centrarte.', 'Choisissez le domaine sur lequel vous souhaitez vous concentrer.', 'Wählen Sie den Bereich, auf den Sie sich konzentrieren möchten.', 'Scegli l’area su cui vuoi concentrarti.', 'Escolha a área em que se quer concentrar.'],
  ['wizard.mood_insight', 'Your recent mood has been low. A coaching session may help you explore what is happening.', 'מצב הרוח שלכם היה נמוך לאחרונה. מפגש אימון עשוי לעזור לברר מה קורה.', 'Tu estado de ánimo ha sido bajo últimamente. Una sesión puede ayudarte a explorar qué ocurre.', 'Votre humeur a été basse récemment. Une séance peut vous aider à explorer ce qui se passe.', 'Ihre Stimmung war zuletzt niedrig. Eine Sitzung kann helfen, die Situation zu verstehen.', 'Il tuo umore è stato basso di recente. Una sessione può aiutarti a capire cosa sta accadendo.', 'O seu humor tem estado baixo. Uma sessão pode ajudar a explorar o que se passa.'],
  ['wizard.details_title', 'Tell your coach a little more', 'ספרו למאמן קצת יותר', 'Cuéntale un poco más a tu coach', 'Dites-en un peu plus à votre coach', 'Erzählen Sie Ihrem Coach etwas mehr', 'Racconta qualcosa in più al coach', 'Conte um pouco mais ao coach'],
  ['wizard.details_description', 'A few details will help make the guidance more useful.', 'כמה פרטים יעזרו להפוך את ההכוונה למועילה יותר.', 'Algunos detalles harán que la orientación sea más útil.', 'Quelques détails rendront l’accompagnement plus utile.', 'Einige Details machen die Anleitung hilfreicher.', 'Alcuni dettagli renderanno la guida più utile.', 'Alguns detalhes tornarão a orientação mais útil.'],
  ['wizard.challenge_label', 'What specific challenge are you facing?', 'מהו האתגר המסוים שאתם מתמודדים איתו?', '¿Qué reto concreto estás afrontando?', 'Quel défi précis rencontrez-vous ?', 'Vor welcher konkreten Herausforderung stehen Sie?', 'Quale sfida specifica stai affrontando?', 'Que desafio específico está a enfrentar?'],
  ['wizard.challenge_placeholder', 'Describe the situation or difficulty in your own words…', 'תארו במילים שלכם את המצב או הקושי…', 'Describe la situación o dificultad con tus propias palabras…', 'Décrivez la situation ou la difficulté avec vos propres mots…', 'Beschreiben Sie die Situation oder Schwierigkeit mit eigenen Worten…', 'Descrivi la situazione o la difficoltà con parole tue…', 'Descreva a situação ou dificuldade pelas suas palavras…'],
  ['wizard.outcome_label', 'What would you like to achieve or change?', 'מה הייתם רוצים להשיג או לשנות?', '¿Qué te gustaría conseguir o cambiar?', 'Que souhaitez-vous atteindre ou changer ?', 'Was möchten Sie erreichen oder verändern?', 'Cosa vorresti ottenere o cambiare?', 'O que gostaria de alcançar ou mudar?'],
  ['wizard.outcome_placeholder', 'Describe the outcome you hope for or how you would like to feel…', 'תארו את התוצאה הרצויה או כיצד הייתם רוצים להרגיש…', 'Describe el resultado que esperas o cómo te gustaría sentirte…', 'Décrivez le résultat souhaité ou la façon dont vous aimeriez vous sentir…', 'Beschreiben Sie das gewünschte Ergebnis oder wie Sie sich fühlen möchten…', 'Descrivi il risultato desiderato o come vorresti sentirti…', 'Descreva o resultado desejado ou como gostaria de se sentir…'],
  ['wizard.related_goals', 'Link existing goals (optional)', 'קישור למטרות קיימות (רשות)', 'Vincular metas existentes (opcional)', 'Associer des objectifs existants (facultatif)', 'Bestehende Ziele verknüpfen (optional)', 'Collega obiettivi esistenti (facoltativo)', 'Associar objetivos existentes (opcional)'],
  ['wizard.selected', 'Selected', 'נבחר', 'Seleccionada', 'Sélectionné', 'Ausgewählt', 'Selezionato', 'Selecionado'],
  ['wizard.almost_title', 'Almost ready', 'כמעט מוכנים', 'Casi listo', 'Presque prêt', 'Fast fertig', 'Quasi pronto', 'Quase pronto'],
  ['wizard.almost_description', 'Give this coaching session a clear name.', 'תנו למפגש האימון שם ברור.', 'Ponle un nombre claro a esta sesión.', 'Donnez un nom clair à cette séance.', 'Geben Sie dieser Sitzung einen klaren Namen.', 'Dai un nome chiaro alla sessione.', 'Dê um nome claro a esta sessão.'],
  ['wizard.session_title', 'Session title', 'שם המפגש', 'Título de la sesión', 'Titre de la séance', 'Sitzungstitel', 'Titolo della sessione', 'Título da sessão'],
  ['wizard.session_title_placeholder', 'For example: Managing work stress', 'לדוגמה: התמודדות עם לחץ בעבודה', 'Por ejemplo: Gestionar el estrés laboral', 'Par exemple : Gérer le stress au travail', 'Zum Beispiel: Arbeitsstress bewältigen', 'Ad esempio: Gestire lo stress sul lavoro', 'Por exemplo: Gerir o stress no trabalho'],
  ['wizard.overview', 'Session overview', 'סקירת המפגש', 'Resumen de la sesión', 'Aperçu de la séance', 'Sitzungsübersicht', 'Riepilogo della sessione', 'Resumo da sessão'],
  ['wizard.focus', 'Focus', 'מוקד', 'Enfoque', 'Thème', 'Schwerpunkt', 'Focus', 'Foco'],
  ['wizard.related_goals_count', 'Related goals', 'מטרות מקושרות', 'Metas relacionadas', 'Objectifs associés', 'Verknüpfte Ziele', 'Obiettivi collegati', 'Objetivos associados'],
  ['wizard.next_title', 'What happens next?', 'מה יקרה בהמשך?', '¿Qué ocurrirá después?', 'Que se passe-t-il ensuite ?', 'Wie geht es weiter?', 'Cosa succede dopo?', 'O que acontece a seguir?'],
  ['wizard.next_description', 'Your AI coach will guide you through understanding the challenge, choosing a clear goal, building an action plan and reviewing progress.', 'מאמן ה־AI ינחה אתכם בהבנת האתגר, בבחירת מטרה ברורה, בבניית תוכנית פעולה ובסקירת ההתקדמות.', 'Tu coach de IA te guiará para comprender el reto, elegir una meta clara, crear un plan de acción y revisar el progreso.', 'Votre coach IA vous guidera pour comprendre le défi, choisir un objectif clair, créer un plan d’action et suivre vos progrès.', 'Ihr KI-Coach begleitet Sie beim Verstehen der Herausforderung, bei einem klaren Ziel, einem Aktionsplan und der Fortschrittsprüfung.', 'Il coach IA ti guiderà nella comprensione della sfida, nella scelta di un obiettivo, nel piano d’azione e nella verifica dei progressi.', 'O coach de IA irá orientá-lo na compreensão do desafio, na escolha de um objetivo, no plano de ação e na revisão do progresso.'],
  ['wizard.back', 'Back', 'חזרה', 'Atrás', 'Retour', 'Zurück', 'Indietro', 'Voltar'],
  ['wizard.next', 'Next', 'הבא', 'Siguiente', 'Suivant', 'Weiter', 'Avanti', 'Seguinte'],
  ['wizard.starting', 'Starting session…', 'פותח את המפגש…', 'Iniciando sesión…', 'Démarrage de la séance…', 'Sitzung wird gestartet…', 'Avvio della sessione…', 'A iniciar a sessão…'],
  ['wizard.start', 'Start session', 'התחלת המפגש', 'Iniciar sesión', 'Démarrer la séance', 'Sitzung starten', 'Inizia la sessione', 'Iniciar sessão'],
  ['wizard.create_error', 'The session could not be created. Check your connection and try again.', 'לא ניתן היה ליצור את המפגש. בדקו את החיבור ונסו שוב.', 'No se pudo crear la sesión. Comprueba la conexión e inténtalo de nuevo.', 'La séance n’a pas pu être créée. Vérifiez votre connexion et réessayez.', 'Die Sitzung konnte nicht erstellt werden. Prüfen Sie die Verbindung und versuchen Sie es erneut.', 'Non è stato possibile creare la sessione. Controlla la connessione e riprova.', 'Não foi possível criar a sessão. Verifique a ligação e tente novamente.'],
  ['wizard.ai_opening', 'I would like to begin a coaching session. My focus is {{focus}}.\n\nCurrent challenge: {{challenge}}\n\nDesired outcome: {{outcome}}\n\nPlease help me build a structured plan.', 'אני רוצה להתחיל מפגש אימון. המוקד שלי הוא {{focus}}.\n\nהאתגר הנוכחי: {{challenge}}\n\nהתוצאה הרצויה: {{outcome}}\n\nאנא עזור לי לבנות תוכנית מובנית.', 'Quiero iniciar una sesión de coaching. Mi enfoque es {{focus}}.\n\nReto actual: {{challenge}}\n\nResultado deseado: {{outcome}}\n\nAyúdame a crear un plan estructurado.', 'Je souhaite commencer une séance de coaching. Mon thème est {{focus}}.\n\nDéfi actuel : {{challenge}}\n\nRésultat souhaité : {{outcome}}\n\nAidez-moi à construire un plan structuré.', 'Ich möchte eine Coaching-Sitzung beginnen. Mein Schwerpunkt ist {{focus}}.\n\nAktuelle Herausforderung: {{challenge}}\n\nGewünschtes Ergebnis: {{outcome}}\n\nBitte helfen Sie mir, einen strukturierten Plan zu erstellen.', 'Vorrei iniziare una sessione di coaching. Il mio focus è {{focus}}.\n\nSfida attuale: {{challenge}}\n\nRisultato desiderato: {{outcome}}\n\nAiutami a costruire un piano strutturato.', 'Gostaria de iniciar uma sessão de coaching. O meu foco é {{focus}}.\n\nDesafio atual: {{challenge}}\n\nResultado desejado: {{outcome}}\n\nAjude-me a criar um plano estruturado.'],

  ['focus.mood_improvement.label', 'Improve mood', 'שיפור מצב הרוח', 'Mejorar el ánimo', 'Améliorer l’humeur', 'Stimmung verbessern', 'Migliorare l’umore', 'Melhorar o humor'],
  ['focus.mood_improvement.description', 'Feel better in everyday life', 'להרגיש טוב יותר ביום־יום', 'Sentirte mejor cada día', 'Se sentir mieux au quotidien', 'Sich im Alltag besser fühlen', 'Sentirsi meglio ogni giorno', 'Sentir-se melhor no dia a dia'],
  ['focus.stress_management.label', 'Manage stress', 'ניהול מתח', 'Gestionar el estrés', 'Gérer le stress', 'Stress bewältigen', 'Gestire lo stress', 'Gerir o stress'],
  ['focus.stress_management.description', 'Reduce stress and cope effectively', 'להפחית מתח ולהתמודד ביעילות', 'Reducir el estrés y afrontarlo mejor', 'Réduire le stress et mieux y faire face', 'Stress reduzieren und besser bewältigen', 'Ridurre lo stress e affrontarlo meglio', 'Reduzir o stress e lidar melhor com ele'],
  ['focus.goal_achievement.label', 'Achieve goals', 'השגת מטרות', 'Alcanzar metas', 'Atteindre des objectifs', 'Ziele erreichen', 'Raggiungere obiettivi', 'Alcançar objetivos'],
  ['focus.goal_achievement.description', 'Move toward a specific result', 'להתקדם לעבר תוצאה מסוימת', 'Avanzar hacia un resultado concreto', 'Avancer vers un résultat précis', 'Auf ein konkretes Ergebnis hinarbeiten', 'Procedere verso un risultato specifico', 'Avançar para um resultado concreto'],
  ['focus.behavior_change.label', 'Change habits', 'שינוי הרגלים', 'Cambiar hábitos', 'Changer les habitudes', 'Gewohnheiten ändern', 'Cambiare abitudini', 'Mudar hábitos'],
  ['focus.behavior_change.description', 'Build supportive new routines', 'לבנות שגרות חדשות ומקדמות', 'Crear nuevas rutinas positivas', 'Créer de nouvelles habitudes positives', 'Hilfreiche neue Routinen aufbauen', 'Creare nuove routine positive', 'Criar novas rotinas positivas'],
  ['focus.relationship.label', 'Relationships', 'מערכות יחסים', 'Relaciones', 'Relations', 'Beziehungen', 'Relazioni', 'Relações'],
  ['focus.relationship.description', 'Strengthen important connections', 'לחזק קשרים חשובים', 'Fortalecer vínculos importantes', 'Renforcer les liens importants', 'Wichtige Beziehungen stärken', 'Rafforzare i legami importanti', 'Fortalecer relações importantes'],
  ['focus.self_esteem.label', 'Self-esteem', 'הערכה עצמית', 'Autoestima', 'Estime de soi', 'Selbstwert', 'Autostima', 'Autoestima'],
  ['focus.self_esteem.description', 'Build confidence and self-trust', 'לבנות ביטחון ואמון עצמי', 'Desarrollar confianza en ti', 'Développer la confiance en soi', 'Selbstvertrauen aufbauen', 'Sviluppare fiducia in sé', 'Desenvolver confiança em si'],
  ['focus.general.label', 'General support', 'תמיכה כללית', 'Apoyo general', 'Soutien général', 'Allgemeine Unterstützung', 'Supporto generale', 'Apoio geral'],
  ['focus.general.description', 'Support your overall wellbeing', 'לתמוך ברווחה הכללית שלכם', 'Apoyar tu bienestar general', 'Soutenir votre bien-être global', 'Das allgemeine Wohlbefinden stärken', 'Sostenere il benessere generale', 'Apoiar o bem-estar geral'],

  ['chat.back', 'Back to sessions', 'חזרה למפגשים', 'Volver a las sesiones', 'Retour aux séances', 'Zurück zu den Sitzungen', 'Torna alle sessioni', 'Voltar às sessões'],
  ['chat.thinking', 'Thinking…', 'חושב…', 'Pensando…', 'Réflexion…', 'Denkt nach…', 'Sto pensando…', 'A pensar…'],
  ['chat.quick_prompts', 'Quick prompts', 'הצעות מהירות', 'Sugerencias rápidas', 'Suggestions rapides', 'Schnelle Impulse', 'Spunti rapidi', 'Sugestões rápidas'],
  ['chat.placeholder', 'Share a thought, an update or ask for guidance…', 'שתפו מחשבה, עדכון או בקשו הכוונה…', 'Comparte un pensamiento, una novedad o pide orientación…', 'Partagez une pensée, une avancée ou demandez conseil…', 'Teilen Sie einen Gedanken, ein Update oder bitten Sie um Orientierung…', 'Condividi un pensiero, un aggiornamento o chiedi una guida…', 'Partilhe um pensamento, uma novidade ou peça orientação…'],
  ['chat.send_aria', 'Send message', 'שליחת הודעה', 'Enviar mensaje', 'Envoyer le message', 'Nachricht senden', 'Invia messaggio', 'Enviar mensagem'],
  ['chat.send_error', 'The message could not be sent. Please try again.', 'לא ניתן היה לשלוח את ההודעה. נסו שוב.', 'No se pudo enviar el mensaje. Inténtalo de nuevo.', 'Le message n’a pas pu être envoyé. Réessayez.', 'Die Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es erneut.', 'Non è stato possibile inviare il messaggio. Riprova.', 'Não foi possível enviar a mensagem. Tente novamente.'],
  ['chat.action_plan', 'Action plan', 'תוכנית פעולה', 'Plan de acción', 'Plan d’action', 'Aktionsplan', 'Piano d’azione', 'Plano de ação'],
  ['chat.prompt.discovery_1', 'Help me understand the root cause', 'עזור לי להבין את שורש הקושי', 'Ayúdame a comprender la causa de fondo', 'Aidez-moi à comprendre la cause profonde', 'Helfen Sie mir, die Ursache zu verstehen', 'Aiutami a capire la causa principale', 'Ajude-me a compreender a causa principal'],
  ['chat.prompt.discovery_2', 'Which patterns should I notice?', 'לאילו דפוסים כדאי לשים לב?', '¿Qué patrones debería observar?', 'Quels schémas devrais-je remarquer ?', 'Auf welche Muster sollte ich achten?', 'Quali schemi dovrei notare?', 'Que padrões devo observar?'],
  ['chat.prompt.discovery_3', 'Help me identify my triggers', 'עזור לי לזהות את הטריגרים שלי', 'Ayúdame a identificar mis desencadenantes', 'Aidez-moi à identifier mes déclencheurs', 'Helfen Sie mir, meine Auslöser zu erkennen', 'Aiutami a riconoscere i miei fattori scatenanti', 'Ajude-me a identificar os meus gatilhos'],
  ['chat.prompt.planning_1', 'Help me create an action plan', 'עזור לי ליצור תוכנית פעולה', 'Ayúdame a crear un plan de acción', 'Aidez-moi à créer un plan d’action', 'Helfen Sie mir, einen Aktionsplan zu erstellen', 'Aiutami a creare un piano d’azione', 'Ajude-me a criar um plano de ação'],
  ['chat.prompt.planning_2', 'What is a realistic first step?', 'מהו צעד ראשון מציאותי?', '¿Cuál es un primer paso realista?', 'Quelle serait une première étape réaliste ?', 'Was ist ein realistischer erster Schritt?', 'Qual è un primo passo realistico?', 'Qual é um primeiro passo realista?'],
  ['chat.prompt.planning_3', 'How can I break this into smaller steps?', 'איך אפשר לפרק זאת לצעדים קטנים?', '¿Cómo puedo dividirlo en pasos más pequeños?', 'Comment le décomposer en petites étapes ?', 'Wie kann ich das in kleinere Schritte aufteilen?', 'Come posso dividerlo in passi più piccoli?', 'Como posso dividir isto em passos menores?'],
  ['chat.prompt.action_1', 'I completed an action. What comes next?', 'השלמתי פעולה. מה הצעד הבא?', 'He completado una acción. ¿Qué sigue?', 'J’ai terminé une action. Quelle est la suite ?', 'Ich habe einen Schritt abgeschlossen. Wie geht es weiter?', 'Ho completato un’azione. Qual è il prossimo passo?', 'Concluí uma ação. Qual é o próximo passo?'],
  ['chat.prompt.action_2', 'I am having difficulty with my plan', 'אני מתקשה עם התוכנית שלי', 'Tengo dificultades con mi plan', 'J’ai des difficultés avec mon plan', 'Ich habe Schwierigkeiten mit meinem Plan', 'Sto incontrando difficoltà con il mio piano', 'Estou com dificuldades no meu plano'],
  ['chat.prompt.action_3', 'Help me restore my motivation', 'עזור לי לחזק מחדש את המוטיבציה', 'Ayúdame a recuperar la motivación', 'Aidez-moi à retrouver ma motivation', 'Helfen Sie mir, neue Motivation zu finden', 'Aiutami a ritrovare la motivazione', 'Ajude-me a recuperar a motivação'],
  ['chat.prompt.review_1', 'Review my progress with me', 'סקור איתי את ההתקדמות', 'Revisa mi progreso conmigo', 'Faisons le point sur mes progrès', 'Gehen Sie meine Fortschritte mit mir durch', 'Rivedi con me i miei progressi', 'Reveja comigo o meu progresso'],
  ['chat.prompt.review_2', 'What have I achieved?', 'מה כבר השגתי?', '¿Qué he logrado?', 'Qu’ai-je accompli ?', 'Was habe ich erreicht?', 'Che cosa ho raggiunto?', 'O que já alcancei?'],
  ['chat.prompt.review_3', 'What should I focus on next?', 'במה כדאי להתמקד עכשיו?', '¿En qué debería centrarme ahora?', 'Sur quoi devrais-je me concentrer ensuite ?', 'Worauf sollte ich mich als Nächstes konzentrieren?', 'Su cosa dovrei concentrarmi adesso?', 'Em que devo concentrar-me a seguir?'],

  ['action_plan.title', 'Action plan', 'תוכנית פעולה', 'Plan de acción', 'Plan d’action', 'Aktionsplan', 'Piano d’azione', 'Plano de ação'],
  ['action_plan.close_aria', 'Close action plan', 'סגירת תוכנית הפעולה', 'Cerrar el plan de acción', 'Fermer le plan d’action', 'Aktionsplan schließen', 'Chiudi il piano d’azione', 'Fechar o plano de ação'],
  ['action_plan.remove_aria', 'Remove action {{number}}', 'הסרת פעולה {{number}}', 'Eliminar la acción {{number}}', 'Supprimer l’action {{number}}', 'Schritt {{number}} entfernen', 'Rimuovi l’azione {{number}}', 'Remover a ação {{number}}'],
  ['action_plan.action_placeholder', 'Action step…', 'צעד לביצוע…', 'Paso de acción…', 'Étape à réaliser…', 'Handlungsschritt…', 'Azione da svolgere…', 'Passo de ação…'],
  ['action_plan.timeline_placeholder', 'Target date or timing (optional)', 'תאריך יעד או תזמון (רשות)', 'Fecha o plazo (opcional)', 'Date ou échéance (facultatif)', 'Termin oder Zeitraum (optional)', 'Data o tempistica (facoltativa)', 'Data ou prazo (opcional)'],
  ['action_plan.add', 'Add', 'הוספה', 'Añadir', 'Ajouter', 'Hinzufügen', 'Aggiungi', 'Adicionar'],
  ['action_plan.cancel', 'Cancel', 'ביטול', 'Cancelar', 'Annuler', 'Abbrechen', 'Annulla', 'Cancelar'],
  ['action_plan.add_action', 'Add an action', 'הוספת פעולה', 'Añadir una acción', 'Ajouter une action', 'Schritt hinzufügen', 'Aggiungi un’azione', 'Adicionar uma ação'],
  ['action_plan.none', 'No actions yet', 'עדיין אין פעולות', 'Aún no hay acciones', 'Aucune action pour le moment', 'Noch keine Schritte', 'Non ci sono ancora azioni', 'Ainda não há ações'],
  ['action_plan.none_help', 'Work with your coach to build your plan.', 'עבדו עם המאמן כדי לבנות את התוכנית.', 'Trabaja con tu coach para crear tu plan.', 'Travaillez avec votre coach pour créer votre plan.', 'Erarbeiten Sie den Plan mit Ihrem Coach.', 'Lavora con il coach per creare il tuo piano.', 'Trabalhe com o coach para criar o seu plano.'],
  ['action_plan.update_error', 'The action plan could not be updated. Please try again.', 'לא ניתן היה לעדכן את תוכנית הפעולה. נסו שוב.', 'No se pudo actualizar el plan. Inténtalo de nuevo.', 'Le plan n’a pas pu être mis à jour. Réessayez.', 'Der Aktionsplan konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.', 'Non è stato possibile aggiornare il piano. Riprova.', 'Não foi possível atualizar o plano. Tente novamente.'],

  ['insights.activity_title', 'Activity reminder', 'תזכורת לפעילות', 'Recordatorio de actividad', 'Rappel d’activité', 'Aktivitätserinnerung', 'Promemoria attività', 'Lembrete de atividade'],
  ['insights.journal_days', '{{count}} days since your last journal entry', '{{count}} ימים מאז הרשומה האחרונה ביומן', '{{count}} días desde tu última entrada del diario', '{{count}} jours depuis votre dernière note', '{{count}} Tage seit Ihrem letzten Tagebucheintrag', '{{count}} giorni dall’ultima nota nel diario', '{{count}} dias desde o último registo no diário'],
  ['insights.mood_days', '{{count}} days since your last mood check-in', '{{count}} ימים מאז בדיקת מצב הרוח האחרונה', '{{count}} días desde tu último registro de ánimo', '{{count}} jours depuis votre dernier suivi d’humeur', '{{count}} Tage seit Ihrem letzten Stimmungs-Check-in', '{{count}} giorni dall’ultimo controllo dell’umore', '{{count}} dias desde o último registo de humor'],
  ['insights.goals_stale', '{{count}} goals may need an update', 'ייתכן ש־{{count}} מטרות זקוקות לעדכון', '{{count}} metas pueden necesitar una actualización', '{{count}} objectifs pourraient nécessiter une mise à jour', '{{count}} Ziele könnten ein Update benötigen', '{{count}} obiettivi potrebbero richiedere un aggiornamento', '{{count}} objetivos podem precisar de atualização'],
  ['insights.title', 'Get personalised coaching insights', 'קבלת תובנות אימון אישיות', 'Obtén perspectivas de coaching personalizadas', 'Obtenez des éclairages de coaching personnalisés', 'Persönliche Coaching-Einblicke erhalten', 'Ottieni approfondimenti di coaching personalizzati', 'Obtenha perspetivas de coaching personalizadas'],
  ['insights.description', 'Review patterns in your journal, goals and mood to receive tailored suggestions.', 'נתחו דפוסים ביומן, במטרות ובמצב הרוח כדי לקבל הצעות מותאמות.', 'Analiza patrones de tu diario, metas y ánimo para recibir sugerencias adaptadas.', 'Analysez les tendances de votre journal, de vos objectifs et de votre humeur pour recevoir des suggestions adaptées.', 'Analysieren Sie Muster in Tagebuch, Zielen und Stimmung für passende Vorschläge.', 'Analizza gli schemi di diario, obiettivi e umore per ricevere suggerimenti personalizzati.', 'Analise padrões no diário, nos objetivos e no humor para receber sugestões personalizadas.'],
  ['insights.generate', 'Generate insights', 'יצירת תובנות', 'Generar perspectivas', 'Générer les éclairages', 'Einblicke erstellen', 'Genera approfondimenti', 'Gerar perspetivas'],
  ['insights.analyzing', 'Analysing your wellbeing journey…', 'מנתח את מסע הרווחה שלכם…', 'Analizando tu recorrido de bienestar…', 'Analyse de votre parcours de bien-être…', 'Ihr Wohlbefinden wird analysiert…', 'Analisi del tuo percorso di benessere…', 'A analisar o seu percurso de bem-estar…'],
  ['insights.error', 'Insights could not be generated. Please try again.', 'לא ניתן היה ליצור תובנות. נסו שוב.', 'No se pudieron generar las perspectivas. Inténtalo de nuevo.', 'Impossible de générer les éclairages. Réessayez.', 'Die Einblicke konnten nicht erstellt werden. Bitte versuchen Sie es erneut.', 'Non è stato possibile generare gli approfondimenti. Riprova.', 'Não foi possível gerar as perspetivas. Tente novamente.'],
  ['insights.progress', 'Progress worth noticing', 'התקדמות שכדאי לשים לב אליה', 'Progreso que merece atención', 'Des progrès à souligner', 'Bemerkenswerte Fortschritte', 'Progressi da riconoscere', 'Progresso a reconhecer'],
  ['insights.patterns', 'Thought patterns identified', 'דפוסי חשיבה שזוהו', 'Patrones de pensamiento identificados', 'Schémas de pensée repérés', 'Erkannte Denkmuster', 'Schemi di pensiero individuati', 'Padrões de pensamento identificados'],
  ['insights.recommendations', 'Recommended CBT techniques', 'טכניקות CBT מומלצות', 'Técnicas de TCC recomendadas', 'Techniques de TCC recommandées', 'Empfohlene KVT-Techniken', 'Tecniche CBT consigliate', 'Técnicas de TCC recomendadas'],
  ['insights.try', 'Try', 'כדאי לנסות', 'Prueba', 'À essayer', 'Ausprobieren', 'Prova', 'Experimente'],
  ['insights.goal_alignment', 'Goal alignment', 'חיבור למטרות', 'Conexión con tus metas', 'Lien avec vos objectifs', 'Verbindung zu Ihren Zielen', 'Collegamento con gli obiettivi', 'Ligação aos objetivos'],
  ['insights.reminders', 'Gentle reminders', 'תזכורות עדינות', 'Recordatorios amables', 'Rappels bienveillants', 'Sanfte Erinnerungen', 'Promemoria gentili', 'Lembretes gentis'],
  ['insights.refresh', 'Refresh insights', 'רענון התובנות', 'Actualizar perspectivas', 'Actualiser les éclairages', 'Einblicke aktualisieren', 'Aggiorna approfondimenti', 'Atualizar perspetivas'],
  ['insights.language_name', 'English', 'Hebrew', 'Spanish', 'French', 'German', 'Italian', 'Portuguese']
];

function setNested(target, path, value) {
  const parts = path.split('.');
  let node = target;
  parts.forEach((part, index) => {
    if (index === parts.length - 1) node[part] = value;
    else node = node[part] ||= {};
  });
}

export function applyCoachUiTranslations(translations) {
  languages.forEach((language, languageIndex) => {
    const coach = {};
    rows.forEach((row) => setNested(coach, row[0], row[languageIndex + 1]));
    translations[language].translation.coach = {
      ...(translations[language]?.translation?.coach || {}),
      ...coach,
      tabs: {
        ...(translations[language]?.translation?.coach?.tabs || {}),
        ...(coach.tabs || {})
      }
    };
  });
  return translations;
}
