// Help/tutorial translations for every Mind Game
// Used by GameInfoModal to show purpose, how-to-play, benefits, and technique label.

export const mindGamesHelpStrings = {
  // ── shared labels ───────────────────────────────────────────────────
  purpose_label:    "What is it for?",
  how_to_play_label:"How to play",
  benefits_label:   "Benefits",
  play_button:      "Start Game",
  technique_label:  "Technique",

  // ── per-game help ───────────────────────────────────────────────────
  thought_quiz: {
    technique:   "CBT",
    purpose:     "Trains you to recognise common cognitive distortions — unhelpful thinking patterns — so you can catch them in real life.",
    how_to_play: "Read the thought or situation, then choose the cognitive distortion that best describes it. You'll get instant feedback and a brief explanation.",
    benefits: ["Builds self-awareness of thinking traps", "Practise spotting distortions in 60 seconds", "Each round uses different scenarios"]
  },
  reframe_pick: {
    technique:   "CBT",
    purpose:     "Practises cognitive reframing — replacing unhelpful automatic thoughts with more balanced alternatives.",
    how_to_play: "You'll see a situation and an automatic thought. Pick the most balanced response from three options, then see why it works.",
    benefits: ["Strengthens flexible thinking", "Reduces emotional reactivity", "Builds a library of balanced responses"]
  },
  value_compass: {
    technique:   "ACT",
    purpose:     "Reconnects you with what truly matters to you and identifies one concrete, values-aligned action you can take right now.",
    how_to_play: "Choose a personal value from the list. Then pick one small action that expresses that value today.",
    benefits: ["Clarifies personal direction", "Builds intrinsic motivation", "Bridges gap between values and behaviour"]
  },
  tiny_experiment: {
    technique:   "CBT Behavioural Experiment",
    purpose:     "Tests a limiting belief with a tiny, low-risk action — gathering real evidence instead of assuming the worst.",
    how_to_play: "You'll see a belief to test. Choose a small experiment (2 min max) to run, then reflect on what you noticed.",
    benefits: ["Challenges unhelpful assumptions", "Builds evidence-based thinking", "Reduces avoidance one small step at a time"]
  },
  quick_win: {
    technique:   "Behavioural Activation",
    purpose:     "Logs a small daily win to break a negative mood cycle and build momentum, however minor it seems.",
    how_to_play: "Type your own win or tap one of the preset options. It's saved instantly as a reminder of your progress.",
    benefits: ["Breaks rumination loops", "Activates reward pathways", "Builds positive self-evidence over time"]
  },
  calm_bingo: {
    technique:   "DBT Distress Tolerance",
    purpose:     "Provides a playful menu of calming micro-actions to interrupt distress and shift your state quickly.",
    how_to_play: "Mark two actions you'll do right now. Each tile is a simple wellness behaviour you can complete in minutes.",
    benefits: ["Fast distress interruption", "Encourages healthy coping habits", "Adds a sense of accomplishment"]
  },
  dbt_stop: {
    technique:   "DBT STOP Skill",
    purpose:     "Applies the DBT STOP skill — Stop, Take a step back, Observe, Proceed mindfully — to a real trigger.",
    how_to_play: "You'll see a trigger scenario. Step through S-T-O-P, then choose one wise next action from three options.",
    benefits: ["Prevents impulsive reactions", "Builds pause-and-respond habit", "Works on any strong emotional trigger"]
  },
  opposite_action: {
    technique:   "DBT Emotion Regulation",
    purpose:     "Practises acting opposite to the urge an emotion creates, which is the DBT antidote to emotion-driven behaviour.",
    how_to_play: "You'll see an emotion and its typical urge. Read the opposite action, then pick one concrete step you can take.",
    benefits: ["Reduces intensity of painful emotions", "Breaks unhelpful behaviour patterns", "Grounded in clinical evidence"]
  },
  urge_surfing: {
    technique:   "DBT / Mindfulness",
    purpose:     "Teaches you to observe an urge as a wave — without acting on it — until it naturally peaks and subsides.",
    how_to_play: "Follow the guided or independent steps to observe your urge without acting. After completing the steps, choose how to continue.",
    benefits: ["Increases tolerance of discomfort", "Reduces automatic urge-driven behaviour", "Strengthens mindful awareness"]
  },
  worry_time: {
    technique:   "CBT Worry Postponement",
    purpose:     "Schedules worry for a later 'worry time', freeing the present moment from rumination.",
    how_to_play: "Read the current worry shown. Choose where to 'park' it, then pick one tiny present-moment action to do instead.",
    benefits: ["Reduces chronic worry", "Improves present-moment attention", "Gives worry a container rather than eliminating it"]
  },
  evidence_balance: {
    technique:   "CBT Thought Record",
    purpose:     "Examines evidence both for and against a negative thought to reach a more balanced, realistic perspective.",
    how_to_play: "You'll see a negative thought plus evidence for and against it. Tap 'Show Balanced Conclusion' to see the reframe.",
    benefits: ["Reduces all-or-nothing thinking", "Builds realistic appraisal skills", "Foundation of classical CBT"]
  },
  defusion_cards: {
    technique:   "ACT Cognitive Defusion",
    purpose:     "Creates psychological distance from sticky thoughts so they lose their power over your behaviour.",
    how_to_play: "You'll see a common sticky thought. Choose a defusion phrase to try, then notice how the thought feels from a distance.",
    benefits: ["Reduces thought fusion", "Increases observer perspective", "Works quickly in stressful moments"]
  },
  tipp_skills: {
    technique:   "DBT TIPP Skills",
    purpose:     "Changes body chemistry rapidly through Temperature, Intense exercise, Paced breathing, and Paired muscle relaxation to reduce crisis-level emotions.",
    how_to_play: "Read the TIPP overview, then pick one physical action from the list to try immediately.",
    benefits: ["Fast physiological regulation", "Works when other skills feel impossible", "Grounded in neuroscience"]
  },
  accepts: {
    technique:   "DBT Distress Tolerance",
    purpose:     "Offers seven distraction strategies (Activities, Contributing, Comparisons, Emotions, Pushing away, Thoughts, Sensations) for overwhelming emotions.",
    how_to_play: "Tap any ACCEPTS letter to see its strategy and a specific action you can try right now.",
    benefits: ["Wide menu of distraction options", "Crisis-safe coping strategies", "Easily adapted to any situation"]
  },
  willing_hands: {
    technique:   "DBT Radical Acceptance",
    purpose:     "Uses a physical gesture — open, upturned palms — to signal willingness and acceptance to your nervous system.",
    how_to_play: "Follow the five steps: turn palms up, relax hands, soften face, breathe and say 'I am willing', hold for 30 seconds.",
    benefits: ["Body-based acceptance practice", "Reduces fighting-reality tension", "Can be done anywhere, anytime"]
  },
  half_smile: {
    technique:   "DBT Radical Acceptance",
    purpose:     "Uses a gentle facial micro-expression to signal safety to the nervous system and shift emotional state.",
    how_to_play: "Select your current emotion, then practise the half-smile for 30 seconds following the four instructions. Rate how you feel after.",
    benefits: ["Fast mood micro-shift", "Grounded in facial-feedback research", "Discrete — can be used in public"]
  },
  improve: {
    technique:   "DBT Distress Tolerance",
    purpose:     "Offers seven crisis-moment strategies to IMPROVE the moment: Imagery, Meaning, Prayer, Relaxation, One thing, Vacation, Encouragement.",
    how_to_play: "Tap any IMPROVE letter to see its strategy and a quick action you can take right now.",
    benefits: ["Wide range of in-the-moment tools", "Applicable during high-distress situations", "Can be combined freely"]
  },
  leaves_on_stream: {
    technique:   "ACT Defusion / Mindfulness",
    purpose:     "Practises observing thoughts without attachment by imagining placing them on leaves floating down a stream.",
    how_to_play: "Type the thought that is hooking you. Tap 'Place on Leaf' and visualise it slowly floating away. Practise not grabbing it back.",
    benefits: ["Reduces cognitive fusion", "Calming visualisation", "Easy mindfulness entry point"]
  },
  expansion: {
    technique:   "ACT Acceptance",
    purpose:     "Practises making psychological room for difficult emotions — rather than suppressing or fighting them — so they carry less burden.",
    how_to_play: "Name the emotion present right now. Work through five brief steps to breathe into it, create space around it, and allow it.",
    benefits: ["Reduces emotional avoidance", "Increases psychological flexibility", "Complements exposure-based approaches"]
  },
  values_check: {
    technique:   "ACT Values",
    purpose:     "Quickly checks whether your current actions are aligned with your deepest personal values, then points to one corrective step.",
    how_to_play: "Pick the value most important to you right now. Answer whether recent actions aligned with it. Read your personalised feedback.",
    benefits: ["Fast values recalibration", "Bridges knowing and doing", "Builds meaning and direction"]
  },
  pros_and_cons: {
    technique:   "DBT Decision Making",
    purpose:     "Evaluates a difficult decision or crisis behaviour by weighing short-term pros against long-term cons to support wise action.",
    how_to_play: "Type the decision you're facing. Enter pros (short-term benefits), then cons (long-term costs). See the full balance and a guiding conclusion.",
    benefits: ["Slows impulsive decision-making", "Clarifies long-term impact", "Supports values-consistent choices"]
  },
  check_the_facts: {
    technique:   "DBT Check the Facts",
    purpose:     "Determines whether an emotion fits the actual facts of a situation — if not, working to change it becomes possible.",
    how_to_play: "Select the emotion you're feeling. Read the prompts specific to that emotion and honestly check whether the facts support it.",
    benefits: ["Reduces emotion misfits", "Supports opposite action decisions", "Practises evidence-based emotional reasoning"]
  },
  self_soothe: {
    technique:   "DBT Self-Soothe",
    purpose:     "Creates comfort and safety through each of the five senses to soothe the nervous system during distress.",
    how_to_play: "Tap any of the five senses. Choose an action that appeals to you, and take a moment to fully experience it.",
    benefits: ["Activates parasympathetic nervous system", "Provides immediate comfort", "Builds a personalised soothing toolkit"]
  },
  mountain_meditation: {
    technique:   "Mindfulness / Metaphor",
    purpose:     "Uses the mountain metaphor to cultivate a stable inner presence — the ability to remain grounded as thoughts and emotions pass like weather.",
    how_to_play: "Progress through seven guided steps. Read each slowly and let the metaphor settle. No input required — just presence.",
    benefits: ["Deepens equanimity and groundedness", "Builds observer self", "Calming and accessible for beginners"]
  },
  memory_match: {
    technique:   "Cognitive Training",
    purpose:     "Trains working memory and focused attention — cognitive resources linked to better emotional regulation.",
    how_to_play: "Flip cards to find matching pairs. Remember positions and work efficiently to complete the board in as few moves as possible.",
    benefits: ["Improves working memory", "Promotes focused present-moment attention", "Positive cognitive engagement breaks rumination"]
  },
  focus_flow: {
    technique:   "Attention Training",
    purpose:     "Trains sequential attention and short-term recall by requiring you to observe and then reproduce colour sequences.",
    how_to_play: "Watch the colour sequence carefully, then tap the colours in the same order. Each level adds one more step.",
    benefits: ["Strengthens attention span", "Builds short-term sequential memory", "Increases cognitive flexibility under pressure"]
  },
  pattern_shift: {
    technique:   "Cognitive Flexibility",
    purpose:     "Exercises pattern recognition and cognitive flexibility — skills tied to problem-solving and adaptive thinking.",
    how_to_play: "Read each pattern question and select the option that correctly continues it. Work through as many as you can.",
    benefits: ["Improves abstract reasoning", "Trains flexible thinking", "Engaging distraction that requires full attention"]
  },
  word_association: {
    technique:   "Creative / Mindfulness",
    purpose:     "Activates associative thinking and present-moment engagement through a rapid-fire word-chaining exercise.",
    how_to_play: "A word appears on screen. Type the first related word that comes to mind and submit. Chain five associations in a row.",
    benefits: ["Reduces analytical rumination", "Promotes creative, flexible thinking", "Fast and accessible flow-state entry"]
  },
  number_sequence: {
    technique:   "Cognitive Training",
    purpose:     "Exercises logical reasoning and pattern detection — cognitive skills that support structured problem-solving.",
    how_to_play: "You'll see a number sequence with one missing. Identify the rule, then type the next number. Check your answer immediately.",
    benefits: ["Strengthens logical reasoning", "Engages focus and analytical skills", "Progressive difficulty maintains challenge"]
  },
};

// ── per-language overrides ──────────────────────────────────────────────────
export const mindGamesHelpByLanguage = {
  he: {
    purpose_label:    "למה זה טוב?",
    how_to_play_label:"איך משחקים",
    benefits_label:   "יתרונות",
    play_button:      "התחל משחק",
    technique_label:  "טכניקה",
    thought_quiz: { technique:"CBT", purpose:"מאמן אותך לזהות דפוסי חשיבה מוטים נפוצים כדי שתוכל לתפוס אותם בחיי היומיום.", how_to_play:"קרא את המחשבה או המצב ובחר את עיוות הקוגניציה המתאים ביותר. תקבל משוב מיידי והסבר קצר.", benefits:["בונה מודעות עצמית לפחים קוגניטיביים","תרגול זיהוי עיוותים ב-60 שניות","כל סיבוב משתמש בתרחישים שונים"] },
    reframe_pick: { technique:"CBT", purpose:"מתרגל שינוי מסגור קוגניטיבי – החלפת מחשבות אוטומטיות לא מועילות באלטרנטיבות מאוזנות יותר.", how_to_play:"תראה מצב ומחשבה אוטומטית. בחר את התגובה המאוזנת ביותר מבין שלוש אפשרויות, ואז ראה מדוע היא עובדת.", benefits:["מחזק חשיבה גמישה","מפחית תגובתיות רגשית","בונה מאגר של תגובות מאוזנות"] },
    value_compass: { technique:"ACT", purpose:"מחבר אותך מחדש עם מה שחשוב לך באמת ומזהה פעולה אחת קונקרטית מיושרת לערכים שתוכל לנקוט עכשיו.", how_to_play:"בחר ערך אישי מהרשימה. ואז בחר פעולה קטנה אחת שמבטאת את הערך הזה היום.", benefits:["מבהיר כיוון אישי","בונה מוטיבציה פנימית","גושר בין ערכים להתנהגות"] },
    tiny_experiment: { technique:"ניסוי התנהגותי CBT", purpose:"בודק אמונה מגבילה עם פעולה קטנה ובסיכון נמוך – אוסף ראיות אמיתיות במקום להניח את הגרוע ביותר.", how_to_play:"תראה אמונה לבדיקה. בחר ניסוי קטן (מקסימום 2 דקות) לביצוע, ואז חשוב על מה שהבחנת.", benefits:["מאתגר הנחות לא מועילות","בונה חשיבה מבוססת ראיות","מפחית הימנעות צעד קטן בכל פעם"] },
    quick_win: { technique:"הפעלה התנהגותית", purpose:"רושם ניצחון יומי קטן כדי לשבור מחזור מצב רוח שלילי ולבנות תנופה, כהוא שיהיה.", how_to_play:"הקלד את הניצחון שלך או הקש על אחת מהאפשרויות המוגדרות מראש. הוא נשמר מיידית כתזכורת להתקדמות שלך.", benefits:["שובר לולאות של הרהור","מפעיל מסלולי תגמול","בונה ראיות עצמיות חיוביות לאורך זמן"] },
    calm_bingo: { technique:"סבילות מצוקה DBT", purpose:"מספק תפריט משחקי של פעולות מרגיעות זעירות כדי להפריע למצוקה ולשנות את מצבך במהירות.", how_to_play:"סמן שתי פעולות שתעשה עכשיו. כל משבצת היא התנהגות רווחה פשוטה שניתן להשלים תוך דקות.", benefits:["הפרעה מהירה למצוקה","מעודד הרגלי התמודדות בריאים","מוסיף תחושת הישג"] },
    dbt_stop: { technique:"מיומנות STOP של DBT", purpose:"מיישם את מיומנות ה-STOP של DBT – עצור, קח צעד אחורה, צפה, המשך בתשומת לב – לטריגר אמיתי.", how_to_play:"תראה תרחיש טריגר. עבור דרך S-T-O-P, ואז בחר פעולה חכמה אחת הבאה מבין שלוש אפשרויות.", benefits:["מונע תגובות אימפולסיביות","בונה הרגל של עצור-והגב","עובד על כל טריגר רגשי חזק"] },
    opposite_action: { technique:"ויסות רגשי DBT", purpose:"מתרגל פעולה הפוכה לדחף שרגש יוצר – שזה התרופה של DBT להתנהגות מונעת-רגש.", how_to_play:"תראה רגש ואת הדחף הטיפוסי שלו. קרא את הפעולה ההפוכה, ואז בחר צעד קונקרטי אחד שתוכל לנקוט.", benefits:["מפחית עוצמת רגשות כואבים","שובר דפוסי התנהגות לא מועילים","מבוסס על ראיות קליניות"] },
    urge_surfing: { technique:"DBT / מיינדפולנס", purpose:"מלמד אותך להתבונן בדחף כגל – מבלי לפעול לפיו – עד שהוא מגיע לשיאו באופן טבעי ושוקט.", how_to_play:"עקוב אחר השלבים המודרכים או העצמאיים כדי להתבונן בדחף שלך מבלי לפעול. לאחר השלמת השלבים, בחר כיצד להמשיך.", benefits:["מגביר סבילות לאי-נוחות","מפחית התנהגות אוטומטית מונעת דחפים","מחזק מודעות מיינדפולנס"] },
    worry_time: { technique:"דחיית דאגה CBT", purpose:"מתזמן את הדאגה לאוחר יותר לזמן 'דאגה' ייעודי, ומשחרר את הרגע הנוכחי מהרהור.", how_to_play:"קרא את הדאגה הנוכחית המוצגת. בחר היכן 'לחנות' אותה, ואז בחר פעולה קטנה אחת ברגע הנוכחי לעשות במקום.", benefits:["מפחית דאגה כרונית","משפר תשומת לב לרגע הנוכחי","נותן לדאגה מיכל במקום לבטל אותה"] },
    evidence_balance: { technique:"רישום מחשבות CBT", purpose:"בוחן ראיות בעד ונגד מחשבה שלילית כדי להגיע לפרספקטיבה מאוזנת ומציאותית יותר.", how_to_play:"תראה מחשבה שלילית עם ראיות בעד ונגד. הקש 'הצג מסקנה מאוזנת' כדי לראות את השינוי.", benefits:["מפחית חשיבה הכל-או-כלום","בונה כישורי הערכה מציאותיים","יסוד ה-CBT הקלאסי"] },
    defusion_cards: { technique:"דפיוזן קוגניטיבי ACT", purpose:"יוצר מרחק פסיכולוגי ממחשבות דביקות כדי שיאבדו את כוחן על ההתנהגות שלך.", how_to_play:"תראה מחשבה דביקה נפוצה. בחר משפט דפיוזן לנסות, ואז שים לב איך המחשבה מרגישה מרחוק.", benefits:["מפחית היתוך קוגניטיבי","מגביר פרספקטיבת המתבונן","עובד מהר ברגעי לחץ"] },
    tipp_skills: { technique:"מיומנויות TIPP של DBT", purpose:"משנה את כימיית הגוף במהירות באמצעות טמפרטורה, פעילות גופנית אינטנסיבית, נשימה מקוצבת והרפיית שרירים מזווגת.", how_to_play:"קרא את סקירת TIPP, ואז בחר פעולה גופנית אחת מהרשימה לנסות מיד.", benefits:["ויסות פיזיולוגי מהיר","עובד כשמיומנויות אחרות מרגישות בלתי אפשריות","מבוסס על מדעי המוח"] },
    accepts: { technique:"סבילות מצוקה DBT", purpose:"מציע שבע אסטרטגיות הסחה לרגשות מכריעים.", how_to_play:"הקש על כל אות ב-ACCEPTS לראות את האסטרטגיה שלה ופעולה ספציפית שתוכל לנסות עכשיו.", benefits:["תפריט רחב של אפשרויות הסחה","אסטרטגיות התמודדות בטוחות במשבר","ניתנות להתאמה לכל מצב"] },
    willing_hands: { technique:"קבלה רדיקלית DBT", purpose:"משתמש במחווה גופנית – כפות ידיים פתוחות פונות כלפי מעלה – לאותת נכונות וקבלה למערכת העצבים.", how_to_play:"עקוב אחר חמשת השלבים: הפוך כפות ידיים כלפי מעלה, הרפה ידיים, רכך פנים, נשם ואמור 'אני מוכן', החזק 30 שניות.", benefits:["תרגול קבלה מבוסס גוף","מפחית מתח הנאבק-במציאות","ניתן לביצוע בכל מקום ובכל זמן"] },
    half_smile: { technique:"קבלה רדיקלית DBT", purpose:"משתמש בביטוי פנים קל כדי לאותת בטחות למערכת העצבים ולשנות מצב רגשי.", how_to_play:"בחר את רגשך הנוכחי, ואז תרגל חצי חיוך ל-30 שניות לפי ארבעת ההנחיות. דרג איך אתה מרגיש אחרי כן.", benefits:["שינוי מיקרו-מצב רוח מהיר","מבוסס על מחקר משוב פנים","דיסקרטי – ניתן לשימוש בציבור"] },
    improve: { technique:"סבילות מצוקה DBT", purpose:"מציע שבע אסטרטגיות לרגע המשבר כדי לשפר את הרגע.", how_to_play:"הקש על כל אות ב-IMPROVE לראות את האסטרטגיה שלה ופעולה מהירה שתוכל לנקוט עכשיו.", benefits:["מגוון כלים רחב ברגע","ישים במצבי מצוקה גבוהה","ניתנים לשילוב חופשי"] },
    leaves_on_stream: { technique:"דפיוזן ACT / מיינדפולנס", purpose:"מתרגל התבוננות במחשבות ללא היצמדות על ידי דמיון הנחתן על עלים הצפים בנחל.", how_to_play:"הקלד את המחשבה שאוחזת בך. הקש 'הנח על עלה' ודמיין אותה שטה לאט. תרגל לא לאחוז בה חזרה.", benefits:["מפחית היתוך קוגניטיבי","ויזואליזציה מרגיעה","נקודת כניסה קלה למיינדפולנס"] },
    expansion: { technique:"קבלה ACT", purpose:"מתרגל יצירת מקום פסיכולוגי לרגשות קשים – במקום לדכא אותם – כדי שישאו פחות עול.", how_to_play:"תן שם לרגש הנוכחי. עבור דרך חמישה שלבים קצרים לנשום לתוכו, לצור מרחב סביבו ולהרשות לו.", benefits:["מפחית הימנעות רגשית","מגביר גמישות פסיכולוגית","משלים גישות מבוססות חשיפה"] },
    values_check: { technique:"ערכי ACT", purpose:"בודק במהירות אם הפעולות הנוכחיות שלך מיושרות עם הערכים האישיים העמוקים שלך, ומצביע על צעד תיקון אחד.", how_to_play:"בחר את הערך החשוב לך ביותר עכשיו. ענה אם הפעולות האחרונות מיושרות אתו. קרא את המשוב האישי שלך.", benefits:["כיול ערכים מהיר","גושר בין ידיעה לעשייה","בונה משמעות וכיוון"] },
    pros_and_cons: { technique:"קבלת החלטות DBT", purpose:"מעריך החלטה קשה או התנהגות במשבר על ידי שקילת יתרונות לטווח קצר מול חסרונות לטווח ארוך.", how_to_play:"הקלד את ההחלטה שאתה מתמודד איתה. הזן יתרונות (תועלות לטווח קצר), ואז חסרונות (עלויות לטווח ארוך). ראה את המאזן המלא.", benefits:["מאט קבלת החלטות אימפולסיבית","מבהיר השפעה ארוכת טווח","תומך בבחירות עקביות עם ערכים"] },
    check_the_facts: { technique:"בדוק את העובדות DBT", purpose:"קובע אם רגש מתאים לעובדות בפועל של מצב – אם לא, ניתן לעבוד על שינויו.", how_to_play:"בחר את הרגש שאתה חש. קרא את ההנחיות הספציפיות לרגש הזה ובדוק בכנות אם העובדות תומכות בו.", benefits:["מפחית אי-התאמות רגשיות","תומך בהחלטות פעולה הפוכה","מתרגל חשיבה רגשית מבוססת ראיות"] },
    self_soothe: { technique:"הרגעה עצמית DBT", purpose:"יוצר נוחות ובטחות דרך כל אחד מחמשת החושים כדי להרגיע את מערכת העצבים בזמן מצוקה.", how_to_play:"הקש על כל אחד מחמשת החושים. בחר פעולה שמושכת אותך, וקח רגע לחוות אותה במלואה.", benefits:["מפעיל מערכת העצבים הפרא-סימפתטית","מספק נוחות מיידית","בונה ערכת כלים להרגעה אישית"] },
    mountain_meditation: { technique:"מיינדפולנס / מטאפורה", purpose:"משתמש במטאפורת ההר כדי לטפח נוכחות פנימית יציבה – היכולת להישאר מאוזן כשמחשבות ורגשות עוברים כמו מזג אוויר.", how_to_play:"התקדם דרך שבעה שלבים מודרכים. קרא כל אחד לאט ותן למטאפורה להתייצב. לא נדרש קלט – רק נוכחות.", benefits:["מעמיק שוויון נפש ויציבות","בונה עצמי מתבונן","מרגיע ונגיש למתחילים"] },
    memory_match: { technique:"אימון קוגניטיבי", purpose:"מאמן זיכרון עבודה ותשומת לב ממוקדת – משאבים קוגניטיביים הקשורים לוויסות רגשי טוב יותר.", how_to_play:"הפוך קלפים כדי למצוא זוגות תואמים. זכור מיקומים ועבוד ביעילות כדי להשלים את הלוח במינימום מהלכים.", benefits:["משפר זיכרון עבודה","מקדם תשומת לב ממוקדת לרגע הנוכחי","מעסיק קוגניטיבית ושובר הרהור"] },
    focus_flow: { technique:"אימון תשומת לב", purpose:"מאמן תשומת לב רצופה וזכירה לטווח קצר על ידי דרישה לצפות ברצפי צבעים ולשחזרם.", how_to_play:"צפה ברצף הצבעים בזהירות, ואז הקש את הצבעים באותו הסדר. כל רמה מוסיפה עוד שלב.", benefits:["מחזק טווח תשומת לב","בונה זיכרון רצפי לטווח קצר","מגביר גמישות קוגניטיבית תחת לחץ"] },
    pattern_shift: { technique:"גמישות קוגניטיבית", purpose:"מפעיל זיהוי דפוסים וגמישות קוגניטיבית – כישורים הקשורים לפתרון בעיות וחשיבה אדפטיבית.", how_to_play:"קרא כל שאלת דפוס ובחר את האפשרות שממשיכה אותו נכון. עבוד דרך כמה שיותר.", benefits:["משפר חשיבה אבסטרקטית","מאמן חשיבה גמישה","הסחה מעסיקה הדורשת קשב מלא"] },
    word_association: { technique:"יצירתי / מיינדפולנס", purpose:"מפעיל חשיבה אסוציאטיבית ומעורבות ברגע הנוכחי דרך תרגיל שרשור מילים מהיר.", how_to_play:"מילה מופיעה על המסך. הקלד את המילה הקשורה הראשונה שעולה בדעתך ושלח. שרשר חמישה קישורים ברצף.", benefits:["מפחית הרהור אנליטי","מקדם חשיבה יצירתית וגמישה","כניסה מהירה ונגישה למצב זרימה"] },
    number_sequence: { technique:"אימון קוגניטיבי", purpose:"מפעיל חשיבה לוגית וזיהוי דפוסים – כישורים קוגניטיביים התומכים בפתרון בעיות מובנה.", how_to_play:"תראה רצף מספרים עם מספר חסר אחד. זהה את הכלל, ואז הקלד את המספר הבא. בדוק את תשובתך מיידית.", benefits:["מחזק חשיבה לוגית","מעסיק מיקוד וכישורים אנליטיים","רמות קושי הולכות ועולות שומרות על אתגר"] }
  },
  es: {
    purpose_label:    "¿Para qué sirve?",
    how_to_play_label:"Cómo jugar",
    benefits_label:   "Beneficios",
    play_button:      "Iniciar juego",
    technique_label:  "Técnica",
    thought_quiz: { technique:"TCC", purpose:"Te entrena para reconocer distorsiones cognitivas comunes para que puedas detectarlas en la vida real.", how_to_play:"Lee el pensamiento o situación y elige la distorsión cognitiva que mejor lo describe. Recibirás retroalimentación instantánea.", benefits:["Desarrolla autoconciencia sobre trampas de pensamiento","Práctica en 60 segundos","Cada ronda usa escenarios diferentes"] },
    reframe_pick: { technique:"TCC", purpose:"Practica el reencuadre cognitivo — reemplazar pensamientos automáticos por alternativas más equilibradas.", how_to_play:"Verás una situación y un pensamiento automático. Elige la respuesta más equilibrada entre tres opciones.", benefits:["Fortalece el pensamiento flexible","Reduce la reactividad emocional","Construye un repertorio de respuestas equilibradas"] },
    value_compass: { technique:"ACT", purpose:"Te reconecta con lo que realmente importa e identifica una acción concreta alineada con tus valores.", how_to_play:"Elige un valor personal de la lista. Luego selecciona una pequeña acción que exprese ese valor hoy.", benefits:["Clarifica la dirección personal","Construye motivación intrínseca","Une valores y comportamiento"] },
    tiny_experiment: { technique:"Experimento conductual TCC", purpose:"Pone a prueba una creencia limitante con una acción pequeña y de bajo riesgo para recopilar evidencia real.", how_to_play:"Verás una creencia a probar. Elige un experimento pequeño (máx. 2 min) y luego reflexiona sobre lo que observaste.", benefits:["Desafía suposiciones poco útiles","Construye pensamiento basado en evidencia","Reduce la evitación poco a poco"] },
    quick_win: { technique:"Activación conductual", purpose:"Registra una pequeña victoria diaria para romper un ciclo de estado de ánimo negativo y construir impulso.", how_to_play:"Escribe tu propio triunfo o toca una de las opciones predefinidas. Se guarda al instante.", benefits:["Rompe bucles de rumiación","Activa circuitos de recompensa","Construye evidencia positiva con el tiempo"] },
    calm_bingo: { technique:"Tolerancia al malestar DBT", purpose:"Proporciona un menú lúdico de micro-acciones calmantes para interrumpir la angustia rápidamente.", how_to_play:"Marca dos acciones que harás ahora mismo. Cada casilla es un comportamiento de bienestar simple.", benefits:["Interrupción rápida del malestar","Fomenta hábitos de afrontamiento saludables","Añade sensación de logro"] },
    dbt_stop: { technique:"Habilidad STOP de DBT", purpose:"Aplica la habilidad STOP de DBT — Parar, Dar un paso atrás, Observar, Proceder con atención plena — a un desencadenante real.", how_to_play:"Verás un escenario desencadenante. Avanza por S-T-O-P y elige una acción sabia entre tres opciones.", benefits:["Previene reacciones impulsivas","Construye el hábito de pausar-y-responder","Funciona con cualquier desencadenante emocional fuerte"] },
    opposite_action: { technique:"Regulación emocional DBT", purpose:"Practica actuar de manera opuesta al impulso que crea una emoción — el antídoto DBT al comportamiento impulsado por emociones.", how_to_play:"Verás una emoción y su impulso típico. Lee la acción opuesta y elige un paso concreto que puedas dar.", benefits:["Reduce la intensidad de las emociones dolorosas","Rompe patrones de comportamiento poco útiles","Respaldo clínico sólido"] },
    urge_surfing: { technique:"DBT / Mindfulness", purpose:"Te enseña a observar un impulso como una ola — sin actuar en consecuencia — hasta que disminuye naturalmente.", how_to_play:"Sigue los pasos guiados o independientes para observar tu impulso sin actuar. Después elige cómo continuar.", benefits:["Aumenta la tolerancia a la incomodidad","Reduce el comportamiento automático","Fortalece la conciencia plena"] },
    worry_time: { technique:"Postergación de la preocupación TCC", purpose:"Programa la preocupación para un 'momento de preocupación' posterior, liberando el presente de la rumiación.", how_to_play:"Lee la preocupación mostrada. Elige dónde 'aparcarla' y luego elige una pequeña acción presente.", benefits:["Reduce la preocupación crónica","Mejora la atención al momento presente","Da un contenedor a la preocupación"] },
    evidence_balance: { technique:"Registro de pensamientos TCC", purpose:"Examina la evidencia a favor y en contra de un pensamiento negativo para llegar a una perspectiva más equilibrada.", how_to_play:"Verás un pensamiento negativo con evidencia a favor y en contra. Toca 'Mostrar conclusión equilibrada' para ver el reencuadre.", benefits:["Reduce el pensamiento todo-o-nada","Construye habilidades de evaluación realista","Base de la TCC clásica"] },
    defusion_cards: { technique:"Defusión cognitiva ACT", purpose:"Crea distancia psicológica de los pensamientos pegajosos para que pierdan su poder sobre tu comportamiento.", how_to_play:"Verás un pensamiento pegajoso común. Elige una frase de defusión para probar y observa cómo se siente desde la distancia.", benefits:["Reduce la fusión cognitiva","Aumenta la perspectiva del observador","Funciona rápidamente en momentos de estrés"] },
    tipp_skills: { technique:"Habilidades TIPP de DBT", purpose:"Cambia la química corporal rápidamente mediante Temperatura, ejercicio Intenso, respiración rítmica y relajación muscular.", how_to_play:"Lee el resumen TIPP y luego elige una acción física de la lista para intentar de inmediato.", benefits:["Regulación fisiológica rápida","Funciona cuando otras habilidades parecen imposibles","Respaldo neurocientífico"] },
    accepts: { technique:"Tolerancia al malestar DBT", purpose:"Ofrece siete estrategias de distracción para emociones abrumadoras.", how_to_play:"Toca cualquier letra de ACCEPTS para ver su estrategia y una acción específica que puedes probar ahora.", benefits:["Amplio menú de opciones de distracción","Estrategias de afrontamiento seguras en crisis","Fácilmente adaptables a cualquier situación"] },
    willing_hands: { technique:"Aceptación radical DBT", purpose:"Usa un gesto físico — palmas abiertas hacia arriba — para señalar disposición y aceptación al sistema nervioso.", how_to_play:"Sigue los cinco pasos: voltea las palmas hacia arriba, relaja las manos, suaviza el rostro, respira y di 'Estoy dispuesto/a', mantén 30 segundos.", benefits:["Práctica de aceptación basada en el cuerpo","Reduce la tensión de luchar contra la realidad","Se puede hacer en cualquier lugar"] },
    half_smile: { technique:"Aceptación radical DBT", purpose:"Usa una micro-expresión facial suave para señalar seguridad al sistema nervioso y cambiar el estado emocional.", how_to_play:"Selecciona tu emoción actual, practica la media sonrisa 30 segundos siguiendo las cuatro instrucciones y valora cómo te sientes después.", benefits:["Micro-cambio de estado de ánimo rápido","Basado en la investigación de retroalimentación facial","Discreto — se puede usar en público"] },
    improve: { technique:"Tolerancia al malestar DBT", purpose:"Ofrece siete estrategias para el momento de crisis para MEJORAR el momento.", how_to_play:"Toca cualquier letra de IMPROVE para ver su estrategia y una acción rápida que puedes tomar ahora.", benefits:["Gran variedad de herramientas en el momento","Aplicable durante situaciones de alta angustia","Se pueden combinar libremente"] },
    leaves_on_stream: { technique:"Defusión ACT / Mindfulness", purpose:"Practica observar pensamientos sin apego imaginando colocarlos en hojas que flotan por un arroyo.", how_to_play:"Escribe el pensamiento que te está enganchando. Toca 'Colocar en una hoja' y visualízalo flotando. Practica no tomarlo de vuelta.", benefits:["Reduce la fusión cognitiva","Visualización calmante","Punto de entrada fácil al mindfulness"] },
    expansion: { technique:"Aceptación ACT", purpose:"Practica hacer espacio psicológico para emociones difíciles — en lugar de suprimirlas — para que carguen menos peso.", how_to_play:"Nombra la emoción presente ahora. Trabaja cinco breves pasos para respirar hacia ella, crear espacio a su alrededor y permitirla.", benefits:["Reduce la evitación emocional","Aumenta la flexibilidad psicológica","Complementa los enfoques basados en la exposición"] },
    values_check: { technique:"Valores ACT", purpose:"Verifica rápidamente si tus acciones actuales están alineadas con tus valores personales más profundos y señala un paso correctivo.", how_to_play:"Elige el valor más importante para ti ahora. Responde si las acciones recientes se alinearon con él. Lee tu retroalimentación personalizada.", benefits:["Recalibración rápida de valores","Une conocimiento y acción","Construye significado y dirección"] },
    pros_and_cons: { technique:"Toma de decisiones DBT", purpose:"Evalúa una decisión difícil sopesando los pros a corto plazo contra los contras a largo plazo para apoyar una acción sabia.", how_to_play:"Escribe la decisión que enfrentas. Ingresa pros (beneficios a corto plazo) y luego contras (costos a largo plazo). Ve el balance completo.", benefits:["Frena la toma de decisiones impulsiva","Aclara el impacto a largo plazo","Apoya elecciones consistentes con los valores"] },
    check_the_facts: { technique:"DBT Verificar los hechos", purpose:"Determina si una emoción se ajusta a los hechos reales de una situación — si no, cambiarla se vuelve posible.", how_to_play:"Selecciona la emoción que sientes. Lee los indicadores específicos para esa emoción y verifica honestamente si los hechos la sustentan.", benefits:["Reduce desajustes emocionales","Apoya decisiones de acción opuesta","Practica el razonamiento emocional basado en evidencia"] },
    self_soothe: { technique:"Autocalmado DBT", purpose:"Crea comodidad y seguridad a través de cada uno de los cinco sentidos para calmar el sistema nervioso durante la angustia.", how_to_play:"Toca cualquiera de los cinco sentidos. Elige una acción que te atraiga y tómate un momento para experimentarla plenamente.", benefits:["Activa el sistema nervioso parasimpático","Proporciona comodidad inmediata","Construye un kit de herramientas de calmado personalizado"] },
    mountain_meditation: { technique:"Mindfulness / Metáfora", purpose:"Usa la metáfora de la montaña para cultivar una presencia interior estable — la capacidad de permanecer anclado mientras los pensamientos y emociones pasan.", how_to_play:"Avanza por siete pasos guiados. Lee cada uno lentamente y deja que la metáfora se asiente. No se requiere entrada — solo presencia.", benefits:["Profundiza la ecuanimidad y el arraigo","Construye el yo observador","Calmante y accesible para principiantes"] },
    memory_match: { technique:"Entrenamiento cognitivo", purpose:"Entrena la memoria de trabajo y la atención enfocada — recursos cognitivos relacionados con una mejor regulación emocional.", how_to_play:"Voltea cartas para encontrar pares coincidentes. Recuerda posiciones y trabaja eficientemente para completar el tablero.", benefits:["Mejora la memoria de trabajo","Promueve atención al momento presente","El engagement cognitivo rompe la rumiación"] },
    focus_flow: { technique:"Entrenamiento de atención", purpose:"Entrena la atención secuencial y la memoria a corto plazo requiriéndote observar y reproducir secuencias de colores.", how_to_play:"Observa la secuencia de colores con cuidado, luego toca los colores en el mismo orden. Cada nivel añade un paso más.", benefits:["Fortalece el lapso de atención","Construye memoria secuencial a corto plazo","Aumenta la flexibilidad cognitiva bajo presión"] },
    pattern_shift: { technique:"Flexibilidad cognitiva", purpose:"Ejercita el reconocimiento de patrones y la flexibilidad cognitiva — habilidades relacionadas con la resolución de problemas.", how_to_play:"Lee cada pregunta de patrón y selecciona la opción que lo continúa correctamente. Trabaja a través de tantas como puedas.", benefits:["Mejora el razonamiento abstracto","Entrena el pensamiento flexible","Distracción atractiva que requiere atención completa"] },
    word_association: { technique:"Creativo / Mindfulness", purpose:"Activa el pensamiento asociativo y el compromiso con el momento presente a través de un ejercicio rápido de encadenamiento de palabras.", how_to_play:"Aparece una palabra en pantalla. Escribe la primera palabra relacionada que te venga a la mente y envíala. Encadena cinco asociaciones seguidas.", benefits:["Reduce la rumiación analítica","Promueve el pensamiento creativo y flexible","Entrada rápida y accesible al estado de flujo"] },
    number_sequence: { technique:"Entrenamiento cognitivo", purpose:"Ejercita el razonamiento lógico y la detección de patrones — habilidades cognitivas que apoyan la resolución estructurada de problemas.", how_to_play:"Verás una secuencia numérica con un número faltante. Identifica la regla y escribe el siguiente número. Verifica tu respuesta inmediatamente.", benefits:["Fortalece el razonamiento lógico","Involucra el enfoque y las habilidades analíticas","Dificultad progresiva que mantiene el desafío"] }
  },
  fr: {
    purpose_label:    "À quoi ça sert ?",
    how_to_play_label:"Comment jouer",
    benefits_label:   "Bénéfices",
    play_button:      "Démarrer le jeu",
    technique_label:  "Technique",
    thought_quiz: { technique:"TCC", purpose:"Vous entraîne à reconnaître les distorsions cognitives courantes pour les repérer dans la vie réelle.", how_to_play:"Lisez la pensée ou la situation et choisissez la distorsion cognitive qui la décrit le mieux. Vous recevrez un retour instantané.", benefits:["Développe la conscience des pièges de pensée","Pratique en 60 secondes","Chaque partie utilise des scénarios différents"] },
    reframe_pick: { technique:"TCC", purpose:"Pratique la restructuration cognitive — remplacer les pensées automatiques par des alternatives plus équilibrées.", how_to_play:"Vous verrez une situation et une pensée automatique. Choisissez la réponse la plus équilibrée parmi trois options.", benefits:["Renforce la pensée flexible","Réduit la réactivité émotionnelle","Construit un répertoire de réponses équilibrées"] },
    value_compass: { technique:"ACT", purpose:"Vous reconnecte à ce qui vous importe vraiment et identifie une action concrète alignée sur vos valeurs.", how_to_play:"Choisissez une valeur personnelle dans la liste. Puis sélectionnez une petite action qui exprime cette valeur aujourd'hui.", benefits:["Clarifie la direction personnelle","Construit la motivation intrinsèque","Relie valeurs et comportement"] },
    tiny_experiment: { technique:"Expérience comportementale TCC", purpose:"Teste une croyance limitante avec une action petite et à faible risque pour collecter des preuves réelles.", how_to_play:"Vous verrez une croyance à tester. Choisissez une petite expérience (max. 2 min) et réfléchissez ensuite à ce que vous avez observé.", benefits:["Remet en question les suppositions néfastes","Construit une pensée basée sur les preuves","Réduit l'évitement pas à pas"] },
    quick_win: { technique:"Activation comportementale", purpose:"Enregistre une petite victoire quotidienne pour briser un cycle d'humeur négatif et construire de l'élan.", how_to_play:"Saisissez votre propre victoire ou appuyez sur l'une des options prédéfinies. Elle est sauvegardée instantanément.", benefits:["Brise les boucles de rumination","Active les circuits de récompense","Construit des preuves positives au fil du temps"] },
    calm_bingo: { technique:"Tolérance à la détresse DBT", purpose:"Offre un menu ludique de micro-actions apaisantes pour interrompre la détresse rapidement.", how_to_play:"Cochez deux actions que vous ferez maintenant. Chaque case est un comportement de bien-être simple.", benefits:["Interruption rapide de la détresse","Encourage des habitudes d'adaptation saines","Ajoute un sentiment d'accomplissement"] },
    dbt_stop: { technique:"Compétence STOP DBT", purpose:"Applique la compétence STOP de la DBT — Stopper, Prendre du recul, Observer, Procéder en pleine conscience — à un déclencheur réel.", how_to_play:"Vous verrez un scénario déclencheur. Progressez à travers S-T-O-P et choisissez une sage prochaine étape parmi trois options.", benefits:["Prévient les réactions impulsives","Construit l'habitude de faire une pause","Fonctionne avec tout déclencheur émotionnel fort"] },
    opposite_action: { technique:"Régulation émotionnelle DBT", purpose:"Pratique l'action opposée à l'impulsion créée par une émotion — l'antidote DBT aux comportements émotionnellement motivés.", how_to_play:"Vous verrez une émotion et son impulsion typique. Lisez l'action opposée et choisissez une étape concrète que vous pouvez faire.", benefits:["Réduit l'intensité des émotions douloureuses","Brise les schémas comportementaux néfastes","Soutenu par des preuves cliniques"] },
    urge_surfing: { technique:"DBT / Pleine conscience", purpose:"Vous apprend à observer une impulsion comme une vague — sans agir dessus — jusqu'à ce qu'elle diminue naturellement.", how_to_play:"Suivez les étapes guidées ou indépendantes pour observer votre impulsion sans agir. Choisissez ensuite comment continuer.", benefits:["Augmente la tolérance à l'inconfort","Réduit le comportement automatique","Renforce la conscience en pleine conscience"] },
    worry_time: { technique:"Report des inquiétudes TCC", purpose:"Programme l'inquiétude pour un 'temps d'inquiétude' ultérieur, libérant le moment présent de la rumination.", how_to_play:"Lisez l'inquiétude affichée. Choisissez où la 'garer' et puis choisissez une petite action présente.", benefits:["Réduit l'inquiétude chronique","Améliore l'attention au moment présent","Donne un contenant à l'inquiétude"] },
    evidence_balance: { technique:"Journal de pensées TCC", purpose:"Examine les preuves pour et contre une pensée négative pour parvenir à une perspective plus équilibrée.", how_to_play:"Vous verrez une pensée négative avec des preuves pour et contre. Tapez 'Afficher la conclusion équilibrée' pour voir le recadrage.", benefits:["Réduit la pensée tout-ou-rien","Construit des compétences d'évaluation réaliste","Base de la TCC classique"] },
    defusion_cards: { technique:"Défusion cognitive ACT", purpose:"Crée une distance psychologique avec les pensées collantes pour qu'elles perdent leur emprise sur votre comportement.", how_to_play:"Vous verrez une pensée collante courante. Choisissez une phrase de défusion à essayer et observez comment la pensée semble de loin.", benefits:["Réduit la fusion cognitive","Augmente la perspective de l'observateur","Fonctionne rapidement dans les moments de stress"] },
    tipp_skills: { technique:"Compétences TIPP DBT", purpose:"Modifie rapidement la chimie corporelle via Température, exercice Intense, respiration rythmée et relaxation musculaire pairée.", how_to_play:"Lisez le résumé TIPP et choisissez une action physique de la liste à essayer immédiatement.", benefits:["Régulation physiologique rapide","Fonctionne quand d'autres compétences semblent impossibles","Fondé sur les neurosciences"] },
    accepts: { technique:"Tolérance à la détresse DBT", purpose:"Offre sept stratégies de distraction pour les émotions accablantes.", how_to_play:"Tapez n'importe quelle lettre d'ACCEPTS pour voir sa stratégie et une action spécifique que vous pouvez essayer maintenant.", benefits:["Large menu d'options de distraction","Stratégies d'adaptation sûres en crise","Facilement adaptables à n'importe quelle situation"] },
    willing_hands: { technique:"Acceptation radicale DBT", purpose:"Utilise un geste physique — paumes ouvertes vers le haut — pour signaler la disposition et l'acceptation au système nerveux.", how_to_play:"Suivez les cinq étapes : tournez les paumes vers le haut, relâchez les mains, adoucissez le visage, respirez et dites 'Je suis prêt(e)', maintenez 30 secondes.", benefits:["Pratique d'acceptation basée sur le corps","Réduit la tension de lutter contre la réalité","Peut être pratiqué n'importe où"] },
    half_smile: { technique:"Acceptation radicale DBT", purpose:"Utilise une micro-expression faciale douce pour signaler la sécurité au système nerveux et changer l'état émotionnel.", how_to_play:"Sélectionnez votre émotion actuelle, pratiquez le demi-sourire 30 secondes en suivant les quatre instructions et évaluez comment vous vous sentez après.", benefits:["Micro-changement d'humeur rapide","Basé sur la recherche en rétroaction faciale","Discret — utilisable en public"] },
    improve: { technique:"Tolérance à la détresse DBT", purpose:"Offre sept stratégies pour le moment de crise pour AMÉLIORER le moment.", how_to_play:"Tapez n'importe quelle lettre d'IMPROVE pour voir sa stratégie et une action rapide que vous pouvez faire maintenant.", benefits:["Large gamme d'outils en temps réel","Applicable dans les situations de haute détresse","Peuvent être combinés librement"] },
    leaves_on_stream: { technique:"Défusion ACT / Pleine conscience", purpose:"Pratique l'observation des pensées sans attachement en imaginant les placer sur des feuilles flottant dans un ruisseau.", how_to_play:"Saisissez la pensée qui vous accroche. Appuyez sur 'Placer sur une feuille' et visualisez-la s'éloigner doucement. Pratiquez à ne pas la reprendre.", benefits:["Réduit la fusion cognitive","Visualisation apaisante","Point d'entrée facile à la pleine conscience"] },
    expansion: { technique:"Acceptation ACT", purpose:"Pratique la création d'espace psychologique pour les émotions difficiles — plutôt que de les supprimer — pour qu'elles portent moins de fardeau.", how_to_play:"Nommez l'émotion présente maintenant. Travaillez cinq brèves étapes pour y respirer, créer de l'espace autour d'elle et la permettre.", benefits:["Réduit l'évitement émotionnel","Augmente la flexibilité psychologique","Complète les approches basées sur l'exposition"] },
    values_check: { technique:"Valeurs ACT", purpose:"Vérifie rapidement si vos actions actuelles sont alignées avec vos valeurs personnelles les plus profondes et indique une étape corrective.", how_to_play:"Choisissez la valeur qui vous importe le plus maintenant. Répondez si les actions récentes y étaient alignées. Lisez votre retour personnalisé.", benefits:["Recalibration rapide des valeurs","Relie la connaissance à l'action","Construit le sens et la direction"] },
    pros_and_cons: { technique:"Prise de décision DBT", purpose:"Évalue une décision difficile en pesant les avantages à court terme contre les inconvénients à long terme.", how_to_play:"Saisissez la décision à laquelle vous êtes confronté. Entrez les avantages puis les inconvénients. Voyez l'équilibre complet.", benefits:["Ralentit la prise de décision impulsive","Clarifie l'impact à long terme","Soutient des choix cohérents avec les valeurs"] },
    check_the_facts: { technique:"DBT Vérifier les faits", purpose:"Détermine si une émotion correspond aux faits réels d'une situation — sinon, il devient possible de travailler à la changer.", how_to_play:"Sélectionnez l'émotion que vous ressentez. Lisez les questions spécifiques à cette émotion et vérifiez honnêtement si les faits la soutiennent.", benefits:["Réduit les inadéquations émotionnelles","Soutient les décisions d'action opposée","Pratique le raisonnement émotionnel basé sur les preuves"] },
    self_soothe: { technique:"Auto-apaisement DBT", purpose:"Crée du confort et de la sécurité à travers chacun des cinq sens pour apaiser le système nerveux.", how_to_play:"Tapez sur l'un des cinq sens. Choisissez une action qui vous attire et prenez un moment pour la vivre pleinement.", benefits:["Active le système nerveux parasympathique","Fournit un confort immédiat","Construit une boîte à outils d'apaisement personnalisée"] },
    mountain_meditation: { technique:"Pleine conscience / Métaphore", purpose:"Utilise la métaphore de la montagne pour cultiver une présence intérieure stable — la capacité à rester ancré pendant que pensées et émotions passent.", how_to_play:"Progressez à travers sept étapes guidées. Lisez chacune lentement et laissez la métaphore s'installer. Aucune saisie requise.", benefits:["Approfondit l'équanimité et l'ancrage","Construit le soi observateur","Apaisant et accessible aux débutants"] },
    memory_match: { technique:"Entraînement cognitif", purpose:"Entraîne la mémoire de travail et l'attention focalisée — des ressources cognitives liées à une meilleure régulation émotionnelle.", how_to_play:"Retournez des cartes pour trouver des paires correspondantes. Mémorisez les positions et travaillez efficacement.", benefits:["Améliore la mémoire de travail","Favorise l'attention au moment présent","L'engagement cognitif brise la rumination"] },
    focus_flow: { technique:"Entraînement de l'attention", purpose:"Entraîne l'attention séquentielle et la mémoire à court terme en vous demandant d'observer et reproduire des séquences de couleurs.", how_to_play:"Observez attentivement la séquence de couleurs, puis tapez les couleurs dans le même ordre. Chaque niveau ajoute une étape.", benefits:["Renforce la durée de l'attention","Construit la mémoire séquentielle à court terme","Augmente la flexibilité cognitive sous pression"] },
    pattern_shift: { technique:"Flexibilité cognitive", purpose:"Exerce la reconnaissance des formes et la flexibilité cognitive — des compétences liées à la résolution de problèmes.", how_to_play:"Lisez chaque question de motif et sélectionnez l'option qui le continue correctement. Travaillez sur autant que possible.", benefits:["Améliore le raisonnement abstrait","Entraîne la pensée flexible","Distraction attrayante nécessitant une attention complète"] },
    word_association: { technique:"Créatif / Pleine conscience", purpose:"Active la pensée associative et l'engagement au moment présent à travers un exercice rapide d'enchaînement de mots.", how_to_play:"Un mot apparaît à l'écran. Tapez le premier mot connexe qui vous vient à l'esprit et envoyez-le. Enchaînez cinq associations.", benefits:["Réduit la rumination analytique","Favorise la pensée créative et flexible","Entrée rapide et accessible à l'état de flux"] },
    number_sequence: { technique:"Entraînement cognitif", purpose:"Exerce le raisonnement logique et la détection de motifs — des compétences cognitives qui soutiennent la résolution structurée de problèmes.", how_to_play:"Vous verrez une séquence numérique avec un nombre manquant. Identifiez la règle et saisissez le nombre suivant.", benefits:["Renforce le raisonnement logique","Engage la concentration et les compétences analytiques","La difficulté progressive maintient le défi"] }
  },
  de: {
    purpose_label:    "Wofür ist das?",
    how_to_play_label:"Wie man spielt",
    benefits_label:   "Vorteile",
    play_button:      "Spiel starten",
    technique_label:  "Technik",
    thought_quiz: { technique:"KVT", purpose:"Trainiert Sie, häufige kognitive Verzerrungen zu erkennen, um sie im echten Leben zu entdecken.", how_to_play:"Lesen Sie den Gedanken oder die Situation und wählen Sie die kognitive Verzerrung, die ihn am besten beschreibt. Sie erhalten sofortiges Feedback.", benefits:["Entwickelt Selbstwahrnehmung für Denkmuster","Übung in 60 Sekunden","Jede Runde verwendet andere Szenarien"] },
    reframe_pick: { technique:"KVT", purpose:"Übt kognitive Umstrukturierung — das Ersetzen unhilfreicher automatischer Gedanken durch ausgewogenere Alternativen.", how_to_play:"Sie sehen eine Situation und einen automatischen Gedanken. Wählen Sie die ausgewogenste Antwort aus drei Optionen.", benefits:["Stärkt flexibles Denken","Reduziert emotionale Reaktivität","Baut ein Repertoire ausgewogener Antworten auf"] },
    value_compass: { technique:"ACT", purpose:"Verbindet Sie wieder mit dem, was Ihnen wirklich wichtig ist, und identifiziert eine konkrete wertebasierte Handlung.", how_to_play:"Wählen Sie einen persönlichen Wert aus der Liste. Wählen Sie dann eine kleine Handlung, die diesen Wert heute ausdrückt.", benefits:["Klärt persönliche Richtung","Baut intrinsische Motivation auf","Verbindet Werte und Verhalten"] },
    tiny_experiment: { technique:"KVT Verhaltensexperiment", purpose:"Testet eine einschränkende Überzeugung mit einer kleinen, risikoarmen Handlung, um echte Beweise zu sammeln.", how_to_play:"Sie sehen eine Überzeugung zum Testen. Wählen Sie ein kleines Experiment (max. 2 Min.) und reflektieren Sie dann, was Sie beobachtet haben.", benefits:["Fordert unförderliche Annahmen heraus","Baut evidenzbasiertes Denken auf","Reduziert Vermeidung Schritt für Schritt"] },
    quick_win: { technique:"Verhaltensaktivierung", purpose:"Zeichnet einen kleinen täglichen Erfolg auf, um einen negativen Stimmungskreislauf zu unterbrechen und Schwung aufzubauen.", how_to_play:"Geben Sie Ihren eigenen Erfolg ein oder tippen Sie auf eine der voreingestellten Optionen. Er wird sofort gespeichert.", benefits:["Unterbricht Grübelschleifen","Aktiviert Belohnungspfade","Baut positive Selbstevidenz im Laufe der Zeit auf"] },
    calm_bingo: { technique:"DBT Stresstoleranz", purpose:"Bietet ein spielerisches Menü von beruhigenden Mikro-Aktionen, um Stress schnell zu unterbrechen.", how_to_play:"Markieren Sie zwei Aktionen, die Sie jetzt ausführen werden. Jedes Feld ist ein einfaches Wellness-Verhalten.", benefits:["Schnelle Stressunterbrechung","Fördert gesunde Bewältigungsgewohnheiten","Fügt ein Gefühl der Leistung hinzu"] },
    dbt_stop: { technique:"DBT STOP-Fertigkeit", purpose:"Wendet die DBT STOP-Fertigkeit — Stoppen, Einen Schritt zurücktreten, Beobachten, Achtsam vorgehen — auf einen echten Auslöser an.", how_to_play:"Sie sehen ein Auslöserszenario. Gehen Sie durch S-T-O-P und wählen Sie einen weisen nächsten Schritt aus drei Optionen.", benefits:["Verhindert impulsive Reaktionen","Baut die Pause-und-Antwort-Gewohnheit auf","Funktioniert bei jedem starken emotionalen Auslöser"] },
    opposite_action: { technique:"DBT Emotionsregulation", purpose:"Übt das Handeln entgegen dem Impuls, den eine Emotion erzeugt — das DBT-Gegenmittel gegen emotionsgesteuertes Verhalten.", how_to_play:"Sie sehen eine Emotion und ihren typischen Impuls. Lesen Sie die entgegengesetzte Handlung und wählen Sie einen konkreten Schritt.", benefits:["Reduziert die Intensität schmerzhafter Emotionen","Durchbricht unförderliche Verhaltensmuster","Klinisch belegt"] },
    urge_surfing: { technique:"DBT / Achtsamkeit", purpose:"Lehrt Sie, einen Drang wie eine Welle zu beobachten — ohne darauf zu reagieren — bis er von selbst abklingt.", how_to_play:"Folgen Sie den geführten oder eigenständigen Schritten, um Ihren Drang zu beobachten ohne zu handeln. Wählen Sie dann, wie Sie weitermachen.", benefits:["Erhöht die Toleranz gegenüber Unbehagen","Reduziert automatisches dranggesteuertes Verhalten","Stärkt achtsames Gewahrsein"] },
    worry_time: { technique:"KVT Sorgenaufschub", purpose:"Plant Sorgen für eine spätere 'Sorgenzeit' ein, wodurch der gegenwärtige Moment frei von Grübeln wird.", how_to_play:"Lesen Sie die angezeigte Sorge. Wählen Sie, wo Sie sie 'parken' können, und wählen Sie dann eine kleine Gegenwartshandlung.", benefits:["Reduziert chronisches Sorgen","Verbessert die Aufmerksamkeit auf den gegenwärtigen Moment","Gibt der Sorge einen Behälter"] },
    evidence_balance: { technique:"KVT Gedankenprotokoll", purpose:"Untersucht Beweise für und gegen einen negativen Gedanken, um zu einer ausgewogeneren Perspektive zu gelangen.", how_to_play:"Sie sehen einen negativen Gedanken mit Beweisen dafür und dagegen. Tippen Sie auf 'Ausgewogene Schlussfolgerung anzeigen'.", benefits:["Reduziert Alles-oder-Nichts-Denken","Baut realistische Bewertungsfähigkeiten auf","Grundlage der klassischen KVT"] },
    defusion_cards: { technique:"ACT Kognitive Defusion", purpose:"Schafft psychologischen Abstand von klebrigen Gedanken, damit sie ihre Macht über Ihr Verhalten verlieren.", how_to_play:"Sie sehen einen häufigen klebrigen Gedanken. Wählen Sie eine Defusionsphrase zum Ausprobieren und beobachten Sie, wie der Gedanke aus der Distanz wirkt.", benefits:["Reduziert kognitive Fusion","Erhöht die Beobachterperspektive","Funktioniert schnell in stressigen Momenten"] },
    tipp_skills: { technique:"DBT TIPP-Fertigkeiten", purpose:"Verändert die Körperchemie schnell durch Temperatur, intensive Übung, rhythmische Atmung und gepaarte Muskelentspannung.", how_to_play:"Lesen Sie die TIPP-Übersicht und wählen Sie dann eine körperliche Aktion aus der Liste, die Sie sofort ausprobieren möchten.", benefits:["Schnelle physiologische Regulation","Funktioniert, wenn andere Fertigkeiten unmöglich scheinen","Neurowissenschaftlich fundiert"] },
    accepts: { technique:"DBT Stresstoleranz", purpose:"Bietet sieben Ablenkungsstrategien für überwältigende Emotionen.", how_to_play:"Tippen Sie auf einen ACCEPTS-Buchstaben, um seine Strategie und eine spezifische Aktion zu sehen, die Sie jetzt ausprobieren können.", benefits:["Breites Menü an Ablenkungsoptionen","Krisen-sichere Bewältigungsstrategien","Leicht an jede Situation anpassbar"] },
    willing_hands: { technique:"DBT Radikale Akzeptanz", purpose:"Verwendet eine körperliche Geste — offene, nach oben gekehrte Handflächen — um dem Nervensystem Bereitschaft und Akzeptanz zu signalisieren.", how_to_play:"Folgen Sie den fünf Schritten: Handflächen nach oben drehen, Hände entspannen, Gesicht entspannen, atmen und sagen 'Ich bin bereit', 30 Sekunden halten.", benefits:["Körperbasierte Akzeptanzübung","Reduziert die Spannung des Kampfes gegen die Realität","Überall und jederzeit durchführbar"] },
    half_smile: { technique:"DBT Radikale Akzeptanz", purpose:"Verwendet einen sanften Gesichtsausdruck, um dem Nervensystem Sicherheit zu signalisieren und den emotionalen Zustand zu verändern.", how_to_play:"Wählen Sie Ihre aktuelle Emotion, üben Sie das halbe Lächeln 30 Sekunden lang nach den vier Anweisungen und bewerten Sie, wie Sie sich danach fühlen.", benefits:["Schnelle Stimmungs-Mikro-Verschiebung","Basierend auf Gesichts-Feedback-Forschung","Diskret — in der Öffentlichkeit nutzbar"] },
    improve: { technique:"DBT Stresstoleranz", purpose:"Bietet sieben Krisenmoment-Strategien, um den Moment zu VERBESSERN.", how_to_play:"Tippen Sie auf einen IMPROVE-Buchstaben, um seine Strategie und eine schnelle Aktion zu sehen, die Sie jetzt ergreifen können.", benefits:["Große Auswahl an Werkzeugen im Moment","Anwendbar in Hochstress-Situationen","Können frei kombiniert werden"] },
    leaves_on_stream: { technique:"ACT Defusion / Achtsamkeit", purpose:"Übt das Beobachten von Gedanken ohne Anhaftung, indem man sie sich auf Blättern vorstellt, die einen Bach hinuntertreiben.", how_to_play:"Geben Sie den Gedanken ein, der Sie festhält. Tippen Sie auf 'Auf Blatt legen' und visualisieren Sie ihn langsam davontreibend. Üben Sie, ihn nicht zurückzuholen.", benefits:["Reduziert kognitive Fusion","Beruhigende Visualisierung","Einfacher Einstieg in die Achtsamkeit"] },
    expansion: { technique:"ACT Akzeptanz", purpose:"Übt das Schaffen psychologischen Raums für schwierige Emotionen — anstatt sie zu unterdrücken — damit sie weniger belasten.", how_to_play:"Benennen Sie die aktuell vorhandene Emotion. Arbeiten Sie fünf kurze Schritte durch, um in sie hineinzuatmen, Raum darum zu schaffen und sie zuzulassen.", benefits:["Reduziert emotionale Vermeidung","Erhöht psychologische Flexibilität","Ergänzt expositionsbasierte Ansätze"] },
    values_check: { technique:"ACT Werte", purpose:"Überprüft schnell, ob Ihre aktuellen Handlungen mit Ihren tiefsten persönlichen Werten übereinstimmen, und zeigt einen Korrekturschritt auf.", how_to_play:"Wählen Sie den Wert, der Ihnen gerade am wichtigsten ist. Beantworten Sie, ob die letzten Handlungen damit übereinstimmten. Lesen Sie Ihr persönliches Feedback.", benefits:["Schnelle Werterekalibrierung","Verbindet Wissen und Handeln","Baut Bedeutung und Richtung auf"] },
    pros_and_cons: { technique:"DBT Entscheidungsfindung", purpose:"Bewertet eine schwierige Entscheidung, indem kurzfristige Vor- gegen langfristige Nachteile abgewogen werden.", how_to_play:"Geben Sie die Entscheidung ein, der Sie gegenüberstehen. Geben Sie Vorteile und dann Nachteile ein. Sehen Sie die vollständige Bilanz.", benefits:["Verlangsamt impulsive Entscheidungsfindung","Klärt langfristige Auswirkungen","Unterstützt wertekongruente Entscheidungen"] },
    check_the_facts: { technique:"DBT Fakten prüfen", purpose:"Bestimmt, ob eine Emotion zu den tatsächlichen Fakten einer Situation passt — wenn nicht, wird es möglich, daran zu arbeiten.", how_to_play:"Wählen Sie die Emotion, die Sie fühlen. Lesen Sie die emotionsspezifischen Fragen und prüfen Sie ehrlich, ob die Fakten sie unterstützen.", benefits:["Reduziert emotionale Fehlanpassungen","Unterstützt Entscheidungen zur entgegengesetzten Handlung","Übt evidenzbasiertes emotionales Denken"] },
    self_soothe: { technique:"DBT Selbstberuhigung", purpose:"Schafft Komfort und Sicherheit durch jeden der fünf Sinne, um das Nervensystem bei Stress zu beruhigen.", how_to_play:"Tippen Sie auf einen der fünf Sinne. Wählen Sie eine Aktion, die Sie anspricht, und nehmen Sie sich einen Moment, um sie vollständig zu erleben.", benefits:["Aktiviert das parasympathische Nervensystem","Bietet sofortige Beruhigung","Baut ein persönliches Selbstberuhigungs-Toolkit auf"] },
    mountain_meditation: { technique:"Achtsamkeit / Metapher", purpose:"Verwendet die Bergmetapher, um eine stabile innere Präsenz zu kultivieren — die Fähigkeit, geerdet zu bleiben, während Gedanken und Emotionen wie Wetter vorüberziehen.", how_to_play:"Schreiten Sie durch sieben geführte Schritte. Lesen Sie jeden langsam und lassen Sie die Metapher einwirken. Keine Eingabe erforderlich.", benefits:["Vertieft Gleichmut und Geerdet-Sein","Baut das Beobachter-Selbst auf","Beruhigend und zugänglich für Anfänger"] },
    memory_match: { technique:"Kognitives Training", purpose:"Trainiert das Arbeitsgedächtnis und die fokussierte Aufmerksamkeit — kognitive Ressourcen, die mit besserer Emotionsregulation verbunden sind.", how_to_play:"Drehen Sie Karten um, um passende Paare zu finden. Merken Sie sich Positionen und arbeiten Sie effizient.", benefits:["Verbessert das Arbeitsgedächtnis","Fördert fokussierte Gegenwarts-Aufmerksamkeit","Kognitive Beschäftigung unterbricht Grübeln"] },
    focus_flow: { technique:"Aufmerksamkeitstraining", purpose:"Trainiert sequenzielle Aufmerksamkeit und Kurzzeitgedächtnis, indem es Sie auffordert, Farbsequenzen zu beobachten und zu reproduzieren.", how_to_play:"Beobachten Sie die Farbsequenz sorgfältig und tippen Sie dann die Farben in derselben Reihenfolge. Jede Ebene fügt einen weiteren Schritt hinzu.", benefits:["Stärkt die Aufmerksamkeitsspanne","Baut sequenzielles Kurzzeitgedächtnis auf","Erhöht kognitive Flexibilität unter Druck"] },
    pattern_shift: { technique:"Kognitive Flexibilität", purpose:"Trainiert Mustererkennung und kognitive Flexibilität — Fähigkeiten, die mit Problemlösung verbunden sind.", how_to_play:"Lesen Sie jede Musterfrage und wählen Sie die Option, die sie korrekt fortsetzt. Arbeiten Sie durch so viele wie möglich.", benefits:["Verbessert abstraktes Denken","Trainiert flexibles Denken","Ansprechende Ablenkung, die volle Aufmerksamkeit erfordert"] },
    word_association: { technique:"Kreativ / Achtsamkeit", purpose:"Aktiviert assoziatives Denken und Gegenwartsbeschäftigung durch eine schnelle Wortketten-Übung.", how_to_play:"Ein Wort erscheint auf dem Bildschirm. Tippen Sie das erste verwandte Wort ein, das Ihnen einfällt, und senden Sie es. Verketten Sie fünf Assoziationen.", benefits:["Reduziert analytisches Grübeln","Fördert kreatives, flexibles Denken","Schneller und zugänglicher Flow-Zustand-Einstieg"] },
    number_sequence: { technique:"Kognitives Training", purpose:"Trainiert logisches Denken und Mustererkennung — kognitive Fähigkeiten, die strukturiertes Problemlösen unterstützen.", how_to_play:"Sie sehen eine Zahlenfolge mit einer fehlenden Zahl. Identifizieren Sie die Regel und geben Sie die nächste Zahl ein.", benefits:["Stärkt logisches Denken","Engagiert Fokus und analytische Fähigkeiten","Fortschreitende Schwierigkeit hält die Herausforderung aufrecht"] }
  },
  it: {
    purpose_label:    "A cosa serve?",
    how_to_play_label:"Come si gioca",
    benefits_label:   "Benefici",
    play_button:      "Inizia il gioco",
    technique_label:  "Tecnica",
    thought_quiz: { technique:"TCC", purpose:"Ti allena a riconoscere le distorsioni cognitive comuni per poterle individuare nella vita reale.", how_to_play:"Leggi il pensiero o la situazione e scegli la distorsione cognitiva che lo descrive meglio. Riceverai un feedback immediato.", benefits:["Sviluppa la consapevolezza delle trappole del pensiero","Pratica in 60 secondi","Ogni round usa scenari diversi"] },
    reframe_pick: { technique:"TCC", purpose:"Pratica la ristrutturazione cognitiva — sostituire i pensieri automatici con alternative più equilibrate.", how_to_play:"Vedrai una situazione e un pensiero automatico. Scegli la risposta più equilibrata tra tre opzioni.", benefits:["Rafforza il pensiero flessibile","Riduce la reattività emotiva","Costruisce un repertorio di risposte equilibrate"] },
    value_compass: { technique:"ACT", purpose:"Ti riconnette con ciò che conta davvero e identifica un'azione concreta allineata ai tuoi valori.", how_to_play:"Scegli un valore personale dall'elenco. Poi seleziona una piccola azione che esprima quel valore oggi.", benefits:["Chiarisce la direzione personale","Costruisce motivazione intrinseca","Collega valori e comportamento"] },
    tiny_experiment: { technique:"Esperimento comportamentale TCC", purpose:"Mette alla prova una credenza limitante con un'azione piccola e a basso rischio per raccogliere prove reali.", how_to_play:"Vedrai una credenza da testare. Scegli un piccolo esperimento (max. 2 min) e poi rifletti su cosa hai osservato.", benefits:["Sfida assunzioni poco utili","Costruisce pensiero basato sulle prove","Riduce l'evitamento passo dopo passo"] },
    quick_win: { technique:"Attivazione comportamentale", purpose:"Registra una piccola vittoria quotidiana per interrompere un ciclo di umore negativo e costruire slancio.", how_to_play:"Digita la tua vittoria o tocca una delle opzioni predefinite. Viene salvata istantaneamente.", benefits:["Rompe i cicli di ruminazione","Attiva i circuiti di ricompensa","Costruisce prove positive nel tempo"] },
    calm_bingo: { technique:"Tolleranza alla sofferenza DBT", purpose:"Offre un menu ludico di micro-azioni calmanti per interrompere rapidamente la sofferenza.", how_to_play:"Segna due azioni che farai adesso. Ogni casella è un semplice comportamento di benessere.", benefits:["Interruzione rapida della sofferenza","Incoraggia abitudini di coping sane","Aggiunge un senso di realizzazione"] },
    dbt_stop: { technique:"Abilità STOP DBT", purpose:"Applica l'abilità STOP della DBT — Fermarsi, Fare un passo indietro, Osservare, Procedere con consapevolezza — a un trigger reale.", how_to_play:"Vedrai uno scenario scatenante. Procedi attraverso S-T-O-P e scegli una saggia azione successiva tra tre opzioni.", benefits:["Previene le reazioni impulsive","Costruisce l'abitudine di fermarsi e rispondere","Funziona con qualsiasi forte trigger emotivo"] },
    opposite_action: { technique:"Regolazione emotiva DBT", purpose:"Pratica l'azione opposta all'impulso creato da un'emozione — l'antidoto DBT ai comportamenti guidati dalle emozioni.", how_to_play:"Vedrai un'emozione e il suo tipico impulso. Leggi l'azione opposta e scegli un passo concreto che puoi fare.", benefits:["Riduce l'intensità delle emozioni dolorose","Rompe schemi comportamentali poco utili","Supporto clinico solido"] },
    urge_surfing: { technique:"DBT / Mindfulness", purpose:"Ti insegna a osservare un impulso come un'onda — senza agire — finché non diminuisce naturalmente.", how_to_play:"Segui i passaggi guidati o indipendenti per osservare il tuo impulso senza agire. Poi scegli come continuare.", benefits:["Aumenta la tolleranza al disagio","Riduce il comportamento automatico","Rafforza la consapevolezza mindful"] },
    worry_time: { technique:"Posticipazione delle preoccupazioni TCC", purpose:"Programma la preoccupazione per un 'tempo delle preoccupazioni' successivo, liberando il momento presente dalla ruminazione.", how_to_play:"Leggi la preoccupazione mostrata. Scegli dove 'parcheggiarla' e poi scegli una piccola azione presente.", benefits:["Riduce la preoccupazione cronica","Migliora l'attenzione al momento presente","Dà un contenitore alla preoccupazione"] },
    evidence_balance: { technique:"Registro dei pensieri TCC", purpose:"Esamina le prove a favore e contro un pensiero negativo per raggiungere una prospettiva più equilibrata.", how_to_play:"Vedrai un pensiero negativo con prove a favore e contro. Tocca 'Mostra conclusione equilibrata' per vedere la ristrutturazione.", benefits:["Riduce il pensiero tutto-o-niente","Costruisce abilità di valutazione realistica","Base della TCC classica"] },
    defusion_cards: { technique:"Defusione cognitiva ACT", purpose:"Crea distanza psicologica dai pensieri appiccicosi in modo che perdano il loro potere sul comportamento.", how_to_play:"Vedrai un pensiero appiccicoso comune. Scegli una frase di defusione da provare e osserva come sembra il pensiero da lontano.", benefits:["Riduce la fusione cognitiva","Aumenta la prospettiva dell'osservatore","Funziona rapidamente nei momenti di stress"] },
    tipp_skills: { technique:"Abilità TIPP DBT", purpose:"Cambia rapidamente la chimica corporea tramite Temperatura, esercizio Intenso, respirazione ritmica e rilassamento muscolare accoppiato.", how_to_play:"Leggi il riepilogo TIPP e poi scegli un'azione fisica dall'elenco da provare immediatamente.", benefits:["Regolazione fisiologica rapida","Funziona quando altre abilità sembrano impossibili","Fondamento neuroscientific"] },
    accepts: { technique:"Tolleranza alla sofferenza DBT", purpose:"Offre sette strategie di distrazione per le emozioni travolgenti.", how_to_play:"Tocca qualsiasi lettera di ACCEPTS per vedere la sua strategia e un'azione specifica che puoi provare ora.", benefits:["Ampio menu di opzioni di distrazione","Strategie di coping sicure in crisi","Facilmente adattabili a qualsiasi situazione"] },
    willing_hands: { technique:"Accettazione radicale DBT", purpose:"Usa un gesto fisico — palme aperte verso l'alto — per segnalare disponibilità e accettazione al sistema nervoso.", how_to_play:"Segui i cinque passi: gira le palme verso l'alto, rilassa le mani, ammorbidisci il viso, respira e di' 'Sono disposto/a', mantieni 30 secondi.", benefits:["Pratica di accettazione basata sul corpo","Riduce la tensione del lottare contro la realtà","Può essere praticata ovunque"] },
    half_smile: { technique:"Accettazione radicale DBT", purpose:"Usa una micro-espressione facciale gentile per segnalare sicurezza al sistema nervoso e cambiare lo stato emotivo.", how_to_play:"Seleziona la tua emozione attuale, pratica il mezzo sorriso per 30 secondi seguendo le quattro istruzioni e valuta come ti senti dopo.", benefits:["Micro-cambiamento rapido dell'umore","Basato sulla ricerca sul feedback facciale","Discreto — utilizzabile in pubblico"] },
    improve: { technique:"Tolleranza alla sofferenza DBT", purpose:"Offre sette strategie per il momento di crisi per MIGLIORARE il momento.", how_to_play:"Tocca qualsiasi lettera di IMPROVE per vedere la sua strategia e un'azione rapida che puoi intraprendere ora.", benefits:["Ampia gamma di strumenti nel momento","Applicabile in situazioni di alta sofferenza","Possono essere combinati liberamente"] },
    leaves_on_stream: { technique:"Defusione ACT / Mindfulness", purpose:"Pratica l'osservazione dei pensieri senza attaccamento immaginando di posizionarli su foglie che galleggiano in un ruscello.", how_to_play:"Digita il pensiero che ti sta agganciando. Tocca 'Metti su una foglia' e visualizzalo allontanarsi lentamente. Pratica il non riprenderlo.", benefits:["Riduce la fusione cognitiva","Visualizzazione calmante","Punto di ingresso facile alla mindfulness"] },
    expansion: { technique:"Accettazione ACT", purpose:"Pratica la creazione di spazio psicologico per le emozioni difficili — invece di sopprimerle — in modo che portino meno peso.", how_to_play:"Nomina l'emozione presente ora. Lavora attraverso cinque brevi passi per respirarci dentro, creare spazio intorno ad essa e permetterla.", benefits:["Riduce l'evitamento emotivo","Aumenta la flessibilità psicologica","Complementa gli approcci basati sull'esposizione"] },
    values_check: { technique:"Valori ACT", purpose:"Verifica rapidamente se le azioni attuali sono allineate con i valori personali più profondi e indica un passo correttivo.", how_to_play:"Scegli il valore più importante per te ora. Rispondi se le azioni recenti vi si sono allineate. Leggi il tuo feedback personalizzato.", benefits:["Ricalibrazione rapida dei valori","Collega conoscenza e azione","Costruisce significato e direzione"] },
    pros_and_cons: { technique:"Processo decisionale DBT", purpose:"Valuta una decisione difficile soppesando i pro a breve termine contro i contro a lungo termine.", how_to_play:"Digita la decisione che stai affrontando. Inserisci pro e poi contro. Guarda il bilancio completo.", benefits:["Rallenta il processo decisionale impulsivo","Chiarisce l'impatto a lungo termine","Supporta scelte coerenti con i valori"] },
    check_the_facts: { technique:"DBT Verifica i fatti", purpose:"Determina se un'emozione corrisponde ai fatti reali di una situazione — se no, diventa possibile lavorare per cambiarla.", how_to_play:"Seleziona l'emozione che senti. Leggi le domande specifiche per quell'emozione e verifica onestamente se i fatti la supportano.", benefits:["Riduce le discordanze emotive","Supporta le decisioni di azione opposta","Pratica il ragionamento emotivo basato sulle prove"] },
    self_soothe: { technique:"Auto-calmante DBT", purpose:"Crea comfort e sicurezza attraverso ognuno dei cinque sensi per calmare il sistema nervoso durante la sofferenza.", how_to_play:"Tocca uno dei cinque sensi. Scegli un'azione che ti attira e prenditi un momento per viverla pienamente.", benefits:["Attiva il sistema nervoso parasimpatico","Fornisce conforto immediato","Costruisce un kit di strumenti di auto-calmante personalizzato"] },
    mountain_meditation: { technique:"Mindfulness / Metafora", purpose:"Usa la metafora della montagna per coltivare una presenza interiore stabile — la capacità di restare radicati mentre pensieri ed emozioni passano come il meteo.", how_to_play:"Avanza attraverso sette passi guidati. Leggi ognuno lentamente e lascia che la metafora si assesti. Nessun input richiesto.", benefits:["Approfondisce equanimità e radicamento","Costruisce il sé osservatore","Calmante e accessibile ai principianti"] },
    memory_match: { technique:"Allenamento cognitivo", purpose:"Allena la memoria di lavoro e l'attenzione focalizzata — risorse cognitive legate a una migliore regolazione emotiva.", how_to_play:"Capovolgi le carte per trovare coppie corrispondenti. Ricorda le posizioni e lavora in modo efficiente.", benefits:["Migliora la memoria di lavoro","Promuove l'attenzione al momento presente","Il coinvolgimento cognitivo rompe la ruminazione"] },
    focus_flow: { technique:"Allenamento dell'attenzione", purpose:"Allena l'attenzione sequenziale e la memoria a breve termine richiedendoti di osservare e riprodurre sequenze di colori.", how_to_play:"Osserva attentamente la sequenza di colori, poi tocca i colori nello stesso ordine. Ogni livello aggiunge un altro passo.", benefits:["Rafforza la durata dell'attenzione","Costruisce memoria sequenziale a breve termine","Aumenta la flessibilità cognitiva sotto pressione"] },
    pattern_shift: { technique:"Flessibilità cognitiva", purpose:"Esercita il riconoscimento dei pattern e la flessibilità cognitiva — abilità legate alla risoluzione dei problemi.", how_to_play:"Leggi ogni domanda di pattern e seleziona l'opzione che lo continua correttamente. Lavora su quante più possibile.", benefits:["Migliora il ragionamento astratto","Allena il pensiero flessibile","Distrazione coinvolgente che richiede piena attenzione"] },
    word_association: { technique:"Creativo / Mindfulness", purpose:"Attiva il pensiero associativo e il coinvolgimento nel momento presente attraverso un rapido esercizio di concatenamento di parole.", how_to_play:"Una parola appare sullo schermo. Digita la prima parola correlata che ti viene in mente e inviala. Concatena cinque associazioni.", benefits:["Riduce la ruminazione analitica","Promuove pensiero creativo e flessibile","Ingresso rapido e accessibile allo stato di flusso"] },
    number_sequence: { technique:"Allenamento cognitivo", purpose:"Esercita il ragionamento logico e il rilevamento di pattern — abilità cognitive che supportano la risoluzione strutturata dei problemi.", how_to_play:"Vedrai una sequenza numerica con un numero mancante. Identifica la regola e digita il numero successivo.", benefits:["Rafforza il ragionamento logico","Coinvolge la concentrazione e le abilità analitiche","La difficoltà progressiva mantiene la sfida"] }
  },
  pt: {
    purpose_label:    "Para que serve?",
    how_to_play_label:"Como jogar",
    benefits_label:   "Benefícios",
    play_button:      "Iniciar jogo",
    technique_label:  "Técnica",
    thought_quiz: { technique:"TCC", purpose:"Treina você a reconhecer distorções cognitivas comuns para que possa detectá-las na vida real.", how_to_play:"Leia o pensamento ou situação e escolha a distorção cognitiva que melhor o descreve. Você receberá feedback instantâneo.", benefits:["Desenvolve autoconsciência sobre armadilhas de pensamento","Prática em 60 segundos","Cada rodada usa cenários diferentes"] },
    reframe_pick: { technique:"TCC", purpose:"Pratica a reestruturação cognitiva — substituir pensamentos automáticos por alternativas mais equilibradas.", how_to_play:"Você verá uma situação e um pensamento automático. Escolha a resposta mais equilibrada entre três opções.", benefits:["Fortalece o pensamento flexível","Reduz a reatividade emocional","Constrói um repertório de respostas equilibradas"] },
    value_compass: { technique:"ACT", purpose:"Reconecta você com o que realmente importa e identifica uma ação concreta alinhada aos seus valores.", how_to_play:"Escolha um valor pessoal da lista. Em seguida, selecione uma pequena ação que expresse esse valor hoje.", benefits:["Clarifica a direção pessoal","Constrói motivação intrínseca","Une valores e comportamento"] },
    tiny_experiment: { technique:"Experimento comportamental TCC", purpose:"Testa uma crença limitante com uma ação pequena e de baixo risco para coletar evidências reais.", how_to_play:"Você verá uma crença a ser testada. Escolha um pequeno experimento (máx. 2 min) e reflita sobre o que observou.", benefits:["Desafia suposições pouco úteis","Constrói pensamento baseado em evidências","Reduz a evitação passo a passo"] },
    quick_win: { technique:"Ativação comportamental", purpose:"Registra uma pequena vitória diária para quebrar um ciclo de humor negativo e construir impulso.", how_to_play:"Digite sua própria vitória ou toque em uma das opções predefinidas. É salva instantaneamente.", benefits:["Quebra loops de ruminação","Ativa circuitos de recompensa","Constrói evidências positivas ao longo do tempo"] },
    calm_bingo: { technique:"Tolerância ao sofrimento DBT", purpose:"Oferece um menu lúdico de micro-ações calmantes para interromper o sofrimento rapidamente.", how_to_play:"Marque duas ações que você fará agora. Cada célula é um comportamento de bem-estar simples.", benefits:["Interrupção rápida do sofrimento","Incentiva hábitos de enfrentamento saudáveis","Adiciona sensação de realização"] },
    dbt_stop: { technique:"Habilidade STOP DBT", purpose:"Aplica a habilidade STOP da DBT — Parar, Dar um passo atrás, Observar, Prosseguir com atenção plena — a um gatilho real.", how_to_play:"Você verá um cenário desencadeador. Avance pelo S-T-O-P e escolha uma sábia próxima ação entre três opções.", benefits:["Previne reações impulsivas","Constrói o hábito de pausar-e-responder","Funciona com qualquer gatilho emocional forte"] },
    opposite_action: { technique:"Regulação emocional DBT", purpose:"Pratica agir de forma oposta ao impulso que uma emoção cria — o antídoto DBT para comportamentos impulsionados por emoções.", how_to_play:"Você verá uma emoção e seu impulso típico. Leia a ação oposta e escolha um passo concreto que pode dar.", benefits:["Reduz a intensidade de emoções dolorosas","Quebra padrões comportamentais pouco úteis","Suporte clínico sólido"] },
    urge_surfing: { technique:"DBT / Mindfulness", purpose:"Ensina você a observar um impulso como uma onda — sem agir — até que diminua naturalmente.", how_to_play:"Siga os passos guiados ou independentes para observar seu impulso sem agir. Depois escolha como continuar.", benefits:["Aumenta a tolerância ao desconforto","Reduz comportamento automático","Fortalece a consciência mindful"] },
    worry_time: { technique:"Adiamento da preocupação TCC", purpose:"Agenda a preocupação para um 'tempo de preocupação' posterior, liberando o momento presente da ruminação.", how_to_play:"Leia a preocupação mostrada. Escolha onde 'estacioná-la' e depois escolha uma pequena ação presente.", benefits:["Reduz a preocupação crônica","Melhora a atenção ao momento presente","Dá um contêiner à preocupação"] },
    evidence_balance: { technique:"Registro de pensamentos TCC", purpose:"Examina as evidências a favor e contra um pensamento negativo para chegar a uma perspectiva mais equilibrada.", how_to_play:"Você verá um pensamento negativo com evidências a favor e contra. Toque 'Mostrar conclusão equilibrada' para ver a reestruturação.", benefits:["Reduz o pensamento tudo-ou-nada","Constrói habilidades de avaliação realista","Base da TCC clássica"] },
    defusion_cards: { technique:"Defusão cognitiva ACT", purpose:"Cria distância psicológica de pensamentos grudientos para que percam seu poder sobre o comportamento.", how_to_play:"Você verá um pensamento grudenco comum. Escolha uma frase de defusão para experimentar e observe como o pensamento parece à distância.", benefits:["Reduz a fusão cognitiva","Aumenta a perspectiva do observador","Funciona rapidamente em momentos de estresse"] },
    tipp_skills: { technique:"Habilidades TIPP DBT", purpose:"Muda a química corporal rapidamente por meio de Temperatura, exercício Intenso, respiração rítmica e relaxamento muscular.", how_to_play:"Leia o resumo TIPP e escolha uma ação física da lista para tentar imediatamente.", benefits:["Regulação fisiológica rápida","Funciona quando outras habilidades parecem impossíveis","Base neurocientífica"] },
    accepts: { technique:"Tolerância ao sofrimento DBT", purpose:"Oferece sete estratégias de distração para emoções avassaladoras.", how_to_play:"Toque em qualquer letra de ACCEPTS para ver sua estratégia e uma ação específica que pode tentar agora.", benefits:["Amplo menu de opções de distração","Estratégias de enfrentamento seguras em crise","Facilmente adaptáveis a qualquer situação"] },
    willing_hands: { technique:"Aceitação radical DBT", purpose:"Usa um gesto físico — palmas abertas voltadas para cima — para sinalizar disposição e aceitação ao sistema nervoso.", how_to_play:"Siga os cinco passos: vire as palmas para cima, relaxe as mãos, suavize o rosto, respire e diga 'Estou disposto/a', mantenha 30 segundos.", benefits:["Prática de aceitação baseada no corpo","Reduz a tensão de lutar contra a realidade","Pode ser praticada em qualquer lugar"] },
    half_smile: { technique:"Aceitação radical DBT", purpose:"Usa uma micro-expressão facial suave para sinalizar segurança ao sistema nervoso e mudar o estado emocional.", how_to_play:"Selecione sua emoção atual, pratique o meio sorriso por 30 segundos seguindo as quatro instruções e avalie como se sente depois.", benefits:["Micro-mudança rápida de humor","Baseado em pesquisa de feedback facial","Discreto — pode ser usado em público"] },
    improve: { technique:"Tolerância ao sofrimento DBT", purpose:"Oferece sete estratégias para o momento de crise para MELHORAR o momento.", how_to_play:"Toque em qualquer letra de IMPROVE para ver sua estratégia e uma ação rápida que pode tomar agora.", benefits:["Grande variedade de ferramentas no momento","Aplicável em situações de alto sofrimento","Podem ser combinadas livremente"] },
    leaves_on_stream: { technique:"Defusão ACT / Mindfulness", purpose:"Pratica observar pensamentos sem apego imaginando colocá-los em folhas flutuando em um riacho.", how_to_play:"Digite o pensamento que está te prendendo. Toque 'Colocar numa folha' e visualize-o flutuando devagar. Pratique não pegá-lo de volta.", benefits:["Reduz a fusão cognitiva","Visualização calmante","Ponto de entrada fácil ao mindfulness"] },
    expansion: { technique:"Aceitação ACT", purpose:"Pratica criar espaço psicológico para emoções difíceis — em vez de suprimi-las — para que carreguem menos peso.", how_to_play:"Nomeie a emoção presente agora. Trabalhe cinco breves passos para respirar nela, criar espaço ao redor e permitir.", benefits:["Reduz a evitação emocional","Aumenta a flexibilidade psicológica","Complementa abordagens baseadas em exposição"] },
    values_check: { technique:"Valores ACT", purpose:"Verifica rapidamente se as ações atuais estão alinhadas com os valores pessoais mais profundos e aponta um passo corretivo.", how_to_play:"Escolha o valor mais importante para você agora. Responda se as ações recentes se alinharam com ele. Leia seu feedback personalizado.", benefits:["Recalibração rápida de valores","Une conhecimento e ação","Constrói significado e direção"] },
    pros_and_cons: { technique:"Tomada de decisão DBT", purpose:"Avalia uma decisão difícil pesando os prós a curto prazo contra os contras a longo prazo.", how_to_play:"Digite a decisão que enfrenta. Insira prós e depois contras. Veja o balanço completo.", benefits:["Desacelera a tomada de decisão impulsiva","Clarifica o impacto a longo prazo","Apoia escolhas consistentes com os valores"] },
    check_the_facts: { technique:"DBT Verificar os fatos", purpose:"Determina se uma emoção se encaixa nos fatos reais de uma situação — se não, torna-se possível trabalhar para mudá-la.", how_to_play:"Selecione a emoção que sente. Leia as perguntas específicas para essa emoção e verifique honestamente se os fatos a suportam.", benefits:["Reduz discordâncias emocionais","Apoia decisões de ação oposta","Pratica raciocínio emocional baseado em evidências"] },
    self_soothe: { technique:"Auto-acalmar DBT", purpose:"Cria conforto e segurança através de cada um dos cinco sentidos para acalmar o sistema nervoso durante o sofrimento.", how_to_play:"Toque em um dos cinco sentidos. Escolha uma ação que lhe atraia e reserve um momento para vivenciá-la plenamente.", benefits:["Ativa o sistema nervoso parassimpático","Fornece conforto imediato","Constrói um kit de ferramentas de auto-acalmar personalizado"] },
    mountain_meditation: { technique:"Mindfulness / Metáfora", purpose:"Usa a metáfora da montanha para cultivar uma presença interior estável — a capacidade de permanecer enraizado enquanto pensamentos e emoções passam como o clima.", how_to_play:"Avance por sete passos guiados. Leia cada um lentamente e deixe a metáfora se assentar. Nenhuma entrada necessária.", benefits:["Aprofunda equanimidade e enraizamento","Constrói o eu observador","Calmante e acessível para iniciantes"] },
    memory_match: { technique:"Treinamento cognitivo", purpose:"Treina a memória de trabalho e a atenção focada — recursos cognitivos ligados a uma melhor regulação emocional.", how_to_play:"Vire cartas para encontrar pares correspondentes. Lembre-se das posições e trabalhe eficientemente.", benefits:["Melhora a memória de trabalho","Promove atenção ao momento presente","O envolvimento cognitivo quebra a ruminação"] },
    focus_flow: { technique:"Treinamento de atenção", purpose:"Treina atenção sequencial e memória de curto prazo exigindo que você observe e reproduza sequências de cores.", how_to_play:"Observe a sequência de cores com cuidado, depois toque as cores na mesma ordem. Cada nível adiciona mais um passo.", benefits:["Fortalece o intervalo de atenção","Constrói memória sequencial de curto prazo","Aumenta a flexibilidade cognitiva sob pressão"] },
    pattern_shift: { technique:"Flexibilidade cognitiva", purpose:"Exercita o reconhecimento de padrões e a flexibilidade cognitiva — habilidades ligadas à resolução de problemas.", how_to_play:"Leia cada pergunta de padrão e selecione a opção que o continua corretamente. Trabalhe em tantas quanto puder.", benefits:["Melhora o raciocínio abstrato","Treina pensamento flexível","Distração envolvente que requer atenção total"] },
    word_association: { technique:"Criativo / Mindfulness", purpose:"Ativa o pensamento associativo e o envolvimento no momento presente através de um exercício rápido de encadeamento de palavras.", how_to_play:"Uma palavra aparece na tela. Digite a primeira palavra relacionada que vem à mente e envie. Encadeie cinco associações.", benefits:["Reduz a ruminação analítica","Promove pensamento criativo e flexível","Entrada rápida e acessível ao estado de fluxo"] },
    number_sequence: { technique:"Treinamento cognitivo", purpose:"Exercita o raciocínio lógico e a detecção de padrões — habilidades cognitivas que apoiam a resolução estruturada de problemas.", how_to_play:"Você verá uma sequência numérica com um número faltando. Identifique a regra e digite o próximo número.", benefits:["Fortalece o raciocínio lógico","Envolve foco e habilidades analíticas","Dificuldade progressiva mantém o desafio"] }
  }
};