const languages = ['en', 'he', 'es', 'fr', 'de', 'it', 'pt'];

const rows = [
  ['starter_path.premium.badge', 'Guided 7-day plan', 'תוכנית מודרכת ל־7 ימים', 'Plan guiado de 7 días', 'Programme guidé de 7 jours', 'Geführter 7-Tage-Plan', 'Percorso guidato di 7 giorni', 'Plano guiado de 7 dias'],
  ['starter_path.premium.panel_label', '7-day starter path details', 'פרטי מסלול הפתיחה ל־7 ימים', 'Detalles del camino inicial de 7 días', 'Détails du parcours de démarrage de 7 jours', 'Details zum 7-Tage-Einstiegspfad', 'Dettagli del percorso iniziale di 7 giorni', 'Detalhes do caminho inicial de 7 dias'],
  ['starter_path.premium.heading_new', 'A calm start, one day at a time', 'התחלה רגועה, יום אחד בכל פעם', 'Un comienzo tranquilo, día a día', 'Un départ serein, un jour à la fois', 'Ein ruhiger Start, Tag für Tag', 'Un inizio sereno, un giorno alla volta', 'Um começo tranquilo, um dia de cada vez'],
  ['starter_path.premium.heading_continue', 'Ready for day {{day}}?', 'מוכנים ליום {{day}}?', '¿Preparado para el día {{day}}?', 'Prêt pour le jour {{day}} ?', 'Bereit für Tag {{day}}?', 'Pronto per il giorno {{day}}?', 'Pronto para o dia {{day}}?'],
  ['starter_path.premium.heading_completed', 'Your foundation is ready', 'הבסיס שלכם מוכן', 'Tu base está preparada', 'Vos bases sont solides', 'Ihr Fundament steht', 'Le tue basi sono pronte', 'A sua base está pronta'],
  ['starter_path.premium.description_new', 'Seven short, guided CBT practices designed to build awareness, balance and everyday confidence.', 'שבעה תרגולי CBT קצרים ומודרכים לבניית מודעות, איזון וביטחון בחיי היום־יום.', 'Siete prácticas breves y guiadas de TCC para desarrollar conciencia, equilibrio y confianza cotidiana.', 'Sept courtes pratiques guidées de TCC pour renforcer la conscience, l’équilibre et la confiance au quotidien.', 'Sieben kurze, geführte KVT-Übungen für mehr Achtsamkeit, Balance und Sicherheit im Alltag.', 'Sette brevi pratiche guidate di CBT per sviluppare consapevolezza, equilibrio e fiducia quotidiana.', 'Sete práticas curtas e guiadas de TCC para desenvolver consciência, equilíbrio e confiança no dia a dia.'],
  ['starter_path.premium.description_continue', 'Continue from where you stopped. Your progress and daily reflections are saved securely.', 'המשיכו בדיוק מהמקום שבו עצרתם. ההתקדמות והתובנות היומיות נשמרות בבטחה.', 'Continúa exactamente donde lo dejaste. Tu progreso y reflexiones diarias se guardan de forma segura.', 'Reprenez exactement où vous vous êtes arrêté. Votre progression et vos réflexions quotidiennes sont enregistrées en toute sécurité.', 'Machen Sie genau dort weiter, wo Sie aufgehört haben. Fortschritt und tägliche Reflexionen sind sicher gespeichert.', 'Continua esattamente da dove ti sei fermato. Progressi e riflessioni quotidiane sono salvati in modo sicuro.', 'Continue exatamente de onde parou. O seu progresso e as reflexões diárias ficam guardados em segurança.'],
  ['starter_path.premium.description_completed', 'You completed all seven days. Review the path or reset it whenever you want a fresh start.', 'השלמתם את כל שבעת הימים. תוכלו לעיין במסלול או לאפס אותו כשתרצו להתחיל מחדש.', 'Has completado los siete días. Revisa el camino o reinícialo cuando quieras empezar de nuevo.', 'Vous avez terminé les sept jours. Revoyez le parcours ou réinitialisez-le quand vous souhaitez recommencer.', 'Sie haben alle sieben Tage abgeschlossen. Wiederholen oder setzen Sie den Pfad für einen Neustart zurück.', 'Hai completato tutti e sette i giorni. Rivedi il percorso o azzeralo quando vuoi ricominciare.', 'Concluiu os sete dias. Reveja o caminho ou reinicie-o quando quiser começar de novo.'],
  ['starter_path.premium.progress_label', '{{completed}} of 7 completed', '{{completed}} מתוך 7 הושלמו', '{{completed}} de 7 completados', '{{completed}} sur 7 terminés', '{{completed}} von 7 abgeschlossen', '{{completed}} di 7 completati', '{{completed}} de 7 concluídos'],
  ['starter_path.premium.days_label', 'Seven-day progress', 'התקדמות בשבעת ימי המסלול', 'Progreso de siete días', 'Progression sur sept jours', 'Fortschritt über sieben Tage', 'Progresso nei sette giorni', 'Progresso dos sete dias'],
  ['starter_path.premium.day_label', 'Day {{day}}', 'יום {{day}}', 'Día {{day}}', 'Jour {{day}}', 'Tag {{day}}', 'Giorno {{day}}', 'Dia {{day}}'],
  ['starter_path.premium.completed_status', 'Completed', 'הושלם', 'Completado', 'Terminé', 'Abgeschlossen', 'Completato', 'Concluído'],
  ['starter_path.premium.watch_intro', 'Watch the guided introduction', 'צפו בסרטון ההיכרות המודרך', 'Ver la introducción guiada', 'Voir l’introduction guidée', 'Geführte Einführung ansehen', 'Guarda l’introduzione guidata', 'Ver a introdução guiada'],
  ['starter_path.premium.expand_aria', 'Open the 7-day path details', 'פתיחת פרטי המסלול ל־7 ימים', 'Abrir los detalles del camino de 7 días', 'Ouvrir les détails du parcours de 7 jours', 'Details des 7-Tage-Pfads öffnen', 'Apri i dettagli del percorso di 7 giorni', 'Abrir os detalhes do caminho de 7 dias'],
  ['starter_path.premium.collapse_aria', 'Close the 7-day path details', 'סגירת פרטי המסלול ל־7 ימים', 'Cerrar los detalles del camino de 7 días', 'Fermer les détails du parcours de 7 jours', 'Details des 7-Tage-Pfads schließen', 'Chiudi i dettagli del percorso di 7 giorni', 'Fechar os detalhes do caminho de 7 dias'],
  ['starter_path.premium.protected_title', 'Your choices remain yours', 'הבחירות שלכם נשארות איתכם', 'Tus elecciones siguen siendo tuyas', 'Vos choix restent les vôtres', 'Ihre Auswahl bleibt erhalten', 'Le tue scelte restano salvate', 'As suas escolhas permanecem guardadas'],
  ['starter_path.premium.protected_note', 'Resetting clears path progress and daily responses, but keeps your personalization preferences.', 'האיפוס מנקה את ההתקדמות והתשובות היומיות, אך שומר את העדפות ההתאמה האישית.', 'El reinicio borra el progreso y las respuestas diarias, pero conserva tus preferencias de personalización.', 'La réinitialisation efface la progression et les réponses quotidiennes, mais conserve vos préférences de personnalisation.', 'Beim Zurücksetzen werden Fortschritt und tägliche Antworten gelöscht; Ihre Personalisierung bleibt erhalten.', 'L’azzeramento cancella progressi e risposte giornaliere, ma conserva le preferenze personali.', 'A reposição apaga o progresso e as respostas diárias, mas mantém as preferências de personalização.'],
  ['starter_path.premium.reset_button', 'Reset path', 'איפוס המסלול', 'Reiniciar camino', 'Réinitialiser le parcours', 'Pfad zurücksetzen', 'Azzera percorso', 'Reiniciar caminho'],
  ['starter_path.premium.reset_aria', 'Reset the 7-day starter path', 'איפוס מסלול הפתיחה ל־7 ימים', 'Reiniciar el camino inicial de 7 días', 'Réinitialiser le parcours de démarrage de 7 jours', 'Den 7-Tage-Einstiegspfad zurücksetzen', 'Azzera il percorso iniziale di 7 giorni', 'Reiniciar o caminho inicial de 7 dias'],
  ['starter_path.premium.reset_title', 'Start the path again?', 'להתחיל את המסלול מחדש?', '¿Empezar de nuevo el camino?', 'Recommencer le parcours ?', 'Den Pfad neu starten?', 'Ricominciare il percorso?', 'Começar o caminho novamente?'],
  ['starter_path.premium.reset_description', 'Your completed days and daily responses will be cleared, and the path will return to day 1. Your personalization preferences will stay saved.', 'הימים שהושלמו והתשובות היומיות יימחקו, והמסלול יחזור ליום 1. העדפות ההתאמה האישית יישארו שמורות.', 'Se borrarán los días completados y las respuestas diarias, y el camino volverá al día 1. Tus preferencias de personalización seguirán guardadas.', 'Les jours terminés et les réponses quotidiennes seront effacés, puis le parcours reviendra au jour 1. Vos préférences de personnalisation resteront enregistrées.', 'Abgeschlossene Tage und tägliche Antworten werden gelöscht, und der Pfad kehrt zu Tag 1 zurück. Ihre Personalisierung bleibt gespeichert.', 'I giorni completati e le risposte giornaliere verranno cancellati e il percorso tornerà al giorno 1. Le preferenze personali resteranno salvate.', 'Os dias concluídos e as respostas diárias serão apagados e o caminho voltará ao dia 1. As preferências de personalização continuarão guardadas.'],
  ['starter_path.premium.reset_cancel', 'Keep my progress', 'שמירת ההתקדמות', 'Conservar mi progreso', 'Conserver ma progression', 'Fortschritt behalten', 'Mantieni i progressi', 'Manter o progresso'],
  ['starter_path.premium.reset_confirm', 'Yes, reset path', 'כן, אפסו את המסלול', 'Sí, reiniciar', 'Oui, réinitialiser', 'Ja, zurücksetzen', 'Sì, azzera', 'Sim, reiniciar'],
  ['starter_path.premium.resetting', 'Resetting…', 'מאפסים…', 'Reiniciando…', 'Réinitialisation…', 'Wird zurückgesetzt…', 'Azzeramento…', 'A reiniciar…'],
  ['starter_path.premium.reset_success', 'The path was reset. You are ready for day 1.', 'המסלול אופס. אתם מוכנים ליום 1.', 'El camino se reinició. Ya estás listo para el día 1.', 'Le parcours a été réinitialisé. Vous êtes prêt pour le jour 1.', 'Der Pfad wurde zurückgesetzt. Sie sind bereit für Tag 1.', 'Il percorso è stato azzerato. Sei pronto per il giorno 1.', 'O caminho foi reiniciado. Está pronto para o dia 1.'],
  ['starter_path.premium.reset_error', 'We could not reset the path. Your previous progress was preserved. Please try again.', 'לא הצלחנו לאפס את המסלול. ההתקדמות הקודמת נשמרה. נסו שוב.', 'No pudimos reiniciar el camino. Se conservó tu progreso anterior. Inténtalo de nuevo.', 'Impossible de réinitialiser le parcours. Votre progression précédente a été conservée. Réessayez.', 'Der Pfad konnte nicht zurückgesetzt werden. Ihr bisheriger Fortschritt blieb erhalten. Bitte erneut versuchen.', 'Non è stato possibile azzerare il percorso. I progressi precedenti sono stati conservati. Riprova.', 'Não foi possível reiniciar o caminho. O progresso anterior foi preservado. Tente novamente.'],
  ['starter_path.premium.started_success', 'Your path has started. Welcome to day 1.', 'המסלול התחיל. ברוכים הבאים ליום 1.', 'Tu camino ha comenzado. Bienvenido al día 1.', 'Votre parcours a commencé. Bienvenue au jour 1.', 'Ihr Pfad hat begonnen. Willkommen bei Tag 1.', 'Il tuo percorso è iniziato. Benvenuto al giorno 1.', 'O seu caminho começou. Bem-vindo ao dia 1.'],
  ['starter_path.premium.start_error', 'We could not start the path. Please try again.', 'לא הצלחנו להתחיל את המסלול. נסו שוב.', 'No pudimos iniciar el camino. Inténtalo de nuevo.', 'Impossible de démarrer le parcours. Réessayez.', 'Der Pfad konnte nicht gestartet werden. Bitte erneut versuchen.', 'Non è stato possibile avviare il percorso. Riprova.', 'Não foi possível iniciar o caminho. Tente novamente.'],
  ['starter_path.premium.load_error', 'We could not load your path right now.', 'לא הצלחנו לטעון את המסלול כרגע.', 'No pudimos cargar tu camino en este momento.', 'Impossible de charger votre parcours pour le moment.', 'Ihr Pfad konnte gerade nicht geladen werden.', 'Non è stato possibile caricare il percorso.', 'Não foi possível carregar o caminho agora.']
];

function setNested(target, path, value) {
  const parts = path.split('.');
  let cursor = target;
  for (let index = 0; index < parts.length - 1; index += 1) {
    cursor[parts[index]] = cursor[parts[index]] || {};
    cursor = cursor[parts[index]];
  }
  cursor[parts[parts.length - 1]] = value;
}

export function applyStarterPathUiTranslations(translations) {
  rows.forEach((row) => {
    languages.forEach((language, index) => {
      const root = translations[language]?.translation;
      if (root) setNested(root, row[0], row[index + 1]);
    });
  });
}
