const makeCopy = (language, common, privacy, terms, consent) => ({
  language,
  direction: 'ltr',
  common: { appName: 'Mindful Path', ...common },
  privacy,
  terms,
  consent,
});

export const additionalLegalCopies = {
  es: makeCopy('es',
    { effectiveDateLabel: 'Fecha de entrada en vigor', back: 'Volver a Mindful Path', privacy: 'Aviso de privacidad', terms: 'Términos de uso', contact: 'Contacto', important: 'Importante' },
    {
      title: 'Aviso de privacidad',
      intro: 'Este aviso explica qué información trata Mindful Path, para qué se utiliza y qué opciones tienes. Mindful Path es un servicio de bienestar y autoayuda; no es un servicio médico ni de emergencias.',
      sections: [
        { title: 'Responsable y contacto', paragraphs: ['El operador de Mindful Path es responsable del tratamiento descrito. Las solicitudes de acceso, exportación, rectificación o eliminación pueden enviarse a support@mindful-path.app.'] },
        { title: 'Información que tratamos', bullets: ['Datos de cuenta, como nombre, correo electrónico, idioma, preferencias e identificadores de autenticación.', 'Contenido de bienestar que decidas facilitar, como registros de ánimo, objetivos, diarios, progreso en ejercicios y conversaciones con funciones de IA.', 'Señales de seguridad cuando el contenido pueda indicar un riesgo inmediato de daño.', 'Información técnica y de uso necesaria para seguridad, fiabilidad, diagnóstico y prevención del fraude.', 'Estado de suscripción e identificadores de transacción. Los datos de tarjeta son tratados por la tienda de aplicaciones o el proveedor de pagos.'] },
        { title: 'Cómo y por qué usamos la información', bullets: ['Prestar las funciones solicitadas y mantener la continuidad entre sesiones.', 'Personalizar ejercicios, recomendaciones, recordatorios y progreso.', 'Aplicar controles de seguridad y mostrar recursos de emergencia.', 'Proteger, mantener, diagnosticar y mejorar el servicio.', 'Cumplir obligaciones legales y responder a solicitudes válidas.'] },
        { title: 'IA y limitaciones importantes', paragraphs: ['El contenido enviado a funciones de IA puede ser tratado por Mindful Path, Base44 y los proveedores de IA configurados para prestar y proteger la función solicitada. La IA puede equivocarse y no debe considerarse diagnóstico, tratamiento ni instrucción de emergencia.', 'No incluyas información confidencial de otra persona sin autorización.'] },
        { title: 'Proveedores y transferencias internacionales', paragraphs: ['Proveedores de alojamiento, autenticación, IA, analítica, soporte, comunicaciones, pagos y seguridad pueden tratar información únicamente para prestar sus servicios y con las salvaguardas aplicables.', 'Algunos proveedores pueden tratar información fuera de tu país. Mindful Path no vende información personal.'] },
        { title: 'Conservación, exportación y eliminación', paragraphs: ['Los controles de conservación de Ajustes limitan el tiempo de conservación de los registros compatibles. Copias de seguridad, registros de seguridad, transacciones o datos exigidos por ley pueden seguir plazos limitados distintos.', 'Puedes solicitar una exportación o eliminar tu cuenta desde Ajustes. La propagación a copias de seguridad y servicios gestionados puede requerir tiempo.'] },
        { title: 'Tus derechos y opciones', bullets: ['Acceder y exportar tus datos.', 'Rectificar datos y preferencias.', 'Elegir un periodo de conservación compatible.', 'Eliminar el historial de bienestar o la cuenta.', 'Oponerte o limitar determinados tratamientos cuando proceda.', 'Retirar el consentimiento sin afectar al tratamiento previo lícito.', 'Reclamar ante la autoridad de protección de datos competente.'] },
        { title: 'Seguridad y edad', paragraphs: ['Usamos controles de acceso, autenticación, conexiones cifradas, minimización de datos y supervisión. Ningún servicio en línea puede garantizar seguridad absoluta.', 'El chat de IA es solo para mayores de 18 años. Las demás herramientas no están destinadas a menores de 13; de 13 a 17 años deben usarse con un progenitor o tutor cuando corresponda.'] },
        { title: 'Cambios', paragraphs: ['Los cambios importantes se indicarán mediante una nueva fecha de entrada en vigor y, cuando proceda, un aviso en la aplicación. Si la ley exige un nuevo consentimiento, el uso continuado no lo sustituye.'] },
      ],
    },
    {
      title: 'Términos de uso',
      intro: 'Estos términos regulan el uso de Mindful Path. Al utilizar el servicio aceptas estos términos y el Aviso de privacidad.',
      sections: [
        { title: 'Bienestar, no atención médica', paragraphs: ['Mindful Path ofrece educación, mindfulness, diarios y autoayuda inspirada en la TCC. No ofrece diagnóstico, psicoterapia, tratamiento médico ni servicios profesionales de emergencia, y no crea una relación terapeuta-paciente.'] },
        { title: 'Emergencias', paragraphs: ['No dependas de Mindful Path en una emergencia. Si puedes hacerte daño o dañar a otra persona, estás en peligro inmediato o necesitas atención urgente, contacta ahora con los servicios locales de emergencia o un profesional cualificado.'] },
        { title: 'Edad y acceso', paragraphs: ['El chat de IA es para mayores de 18 años. Las demás herramientas no están destinadas a menores de 13; los usuarios de 13 a 17 años deben usarlas con un progenitor o tutor cuando corresponda.'] },
        { title: 'Limitaciones de la IA', paragraphs: ['Las respuestas pueden ser inexactas, repetitivas, inadecuadas o incompletas. No retrases ni sustituyas una evaluación o tratamiento profesional por información del servicio.'] },
        { title: 'Uso aceptable', bullets: ['No accedas a cuentas o información ajena.', 'No alteres, sondees, sobrecargues ni eludas el servicio o sus controles.', 'No generes contenido ilícito, abusivo, engañoso o dañino.', 'No subas contenido sin derecho a utilizarlo.'] },
        { title: 'Seguridad de la cuenta', paragraphs: ['Protege tu cuenta y dispositivo e informa a soporte si sospechas un acceso indebido.'] },
        { title: 'Suscripciones y pagos', paragraphs: ['Los precios, pruebas, renovaciones, cancelaciones y reembolsos se muestran antes de la compra y pueden variar por plataforma y país. También se aplican las condiciones de la tienda.'] },
        { title: 'Disponibilidad y propiedad intelectual', paragraphs: ['Las funciones pueden cambiar, suspenderse o dejar de estar disponibles. Mindful Path y su software y contenido original están protegidos; conservas tus derechos sobre el contenido que aportas.'] },
        { title: 'Responsabilidad, ley y contacto', paragraphs: ['Nada excluye derechos o responsabilidades que no puedan excluirse legalmente. Las condiciones adicionales y la identidad jurídica del operador deben confirmarse para cada país. Contacto: support@mindful-path.app.'] },
      ],
    },
    {
      title: 'Antes de empezar', description: 'Revisa estos límites importantes antes de usar el chat de IA.',
      wellnessTitle: 'Autoayuda, no tratamiento profesional', wellnessBody: 'El acompañante de IA ofrece apoyo de bienestar inspirado en la TCC. No es terapeuta, no diagnostica y no sustituye la atención médica o de salud mental.',
      aiTitle: 'La IA puede equivocarse', aiBody: 'Las respuestas pueden ser incompletas o inadecuadas. Usa tu criterio y consulta a un profesional cualificado para decisiones clínicas.',
      privacyTitle: 'Tus mensajes se tratan para prestar el chat', privacyBody: 'Mindful Path, Base44 y los proveedores de IA configurados pueden tratar los mensajes. Evita compartir información que no quieras que sea tratada.',
      crisisTitle: 'No es para emergencias', crisisBody: 'Si puedes hacerte daño o dañar a alguien, o estás en peligro inmediato, contacta ahora con los servicios locales de emergencia o crisis.',
      acknowledgement: 'Al continuar confirmas que tienes 18 años o más, comprendes estos límites y aceptas los Términos de uso y el Aviso de privacidad.',
      accept: 'Entiendo y acepto', leave: 'Ahora no',
    }
  ),
  fr: makeCopy('fr',
    { effectiveDateLabel: 'Date d’entrée en vigueur', back: 'Retour à Mindful Path', privacy: 'Avis de confidentialité', terms: 'Conditions d’utilisation', contact: 'Contact', important: 'Important' },
    {
      title: 'Avis de confidentialité',
      intro: 'Cet avis explique quelles informations Mindful Path traite, pourquoi elles sont utilisées et quels choix vous sont proposés. Mindful Path est un service de bien-être et d’auto-assistance, pas un service médical ou d’urgence.',
      sections: [
        { title: 'Responsable et contact', paragraphs: ['L’opérateur de Mindful Path est responsable du traitement décrit. Les demandes d’accès, d’exportation, de rectification ou de suppression peuvent être envoyées à support@mindful-path.app.'] },
        { title: 'Informations traitées', bullets: ['Données de compte : nom, e-mail, langue, préférences et identifiants d’authentification.', 'Contenu de bien-être fourni volontairement : humeur, objectifs, journal, progression et conversations avec les fonctions d’IA.', 'Signaux de sécurité lorsque le contenu peut indiquer un risque immédiat.', 'Données techniques et d’usage nécessaires à la sécurité, la fiabilité, au diagnostic et à la prévention de la fraude.', 'Statut d’abonnement et identifiants de transaction. Les données de carte sont traitées par la boutique ou le prestataire de paiement.'] },
        { title: 'Utilisation des informations', bullets: ['Fournir les fonctions demandées et assurer la continuité entre les sessions.', 'Personnaliser exercices, recommandations, rappels et progression.', 'Mettre en œuvre les contrôles de sécurité et afficher les ressources d’urgence.', 'Sécuriser, maintenir, diagnostiquer et améliorer le service.', 'Respecter les obligations légales et répondre aux demandes valides.'] },
        { title: 'IA et limites importantes', paragraphs: ['Le contenu envoyé aux fonctions d’IA peut être traité par Mindful Path, Base44 et les fournisseurs d’IA configurés afin de fournir et protéger la fonction. L’IA peut se tromper et ne constitue ni un diagnostic, ni un traitement, ni une consigne d’urgence.', 'Ne communiquez pas les informations confidentielles d’une autre personne sans autorisation.'] },
        { title: 'Prestataires et transferts internationaux', paragraphs: ['Des prestataires d’hébergement, d’authentification, d’IA, d’analyse, de support, de communication, de paiement et de sécurité peuvent traiter les données uniquement pour leurs services et avec les garanties applicables.', 'Certains traitements peuvent avoir lieu hors de votre pays. Mindful Path ne vend pas les données personnelles.'] },
        { title: 'Conservation, exportation et suppression', paragraphs: ['Les réglages de conservation limitent la durée de certains dossiers de bien-être. Les sauvegardes, journaux de sécurité, transactions ou données imposées par la loi peuvent suivre d’autres durées limitées.', 'Vous pouvez exporter vos données ou supprimer votre compte dans Réglages. La propagation aux sauvegardes et services gérés peut prendre du temps.'] },
        { title: 'Vos droits et choix', bullets: ['Accéder à vos données et les exporter.', 'Rectifier vos informations et préférences.', 'Choisir une durée de conservation prise en charge.', 'Supprimer l’historique ou le compte.', 'Vous opposer à certains traitements ou les limiter lorsque la loi le prévoit.', 'Retirer votre consentement sans affecter le traitement antérieur licite.', 'Saisir l’autorité de protection des données compétente.'] },
        { title: 'Sécurité et âge', paragraphs: ['Nous utilisons contrôles d’accès, authentification, connexions chiffrées, minimisation et surveillance. Aucun service en ligne ne garantit une sécurité absolue.', 'Le chat IA est réservé aux personnes de 18 ans et plus. Les autres outils ne sont pas destinés aux moins de 13 ans ; les 13–17 ans doivent les utiliser avec un parent ou tuteur lorsque nécessaire.'] },
        { title: 'Modifications', paragraphs: ['Les changements importants seront signalés par une nouvelle date d’entrée en vigueur et, si nécessaire, un avis dans l’application. Un nouveau consentement sera demandé lorsqu’il est légalement requis.'] },
      ],
    },
    {
      title: 'Conditions d’utilisation',
      intro: 'Ces conditions régissent l’utilisation de Mindful Path. En utilisant le service, vous acceptez ces conditions et l’Avis de confidentialité.',
      sections: [
        { title: 'Bien-être, pas des soins médicaux', paragraphs: ['Mindful Path propose des contenus éducatifs, de pleine conscience, de journal et d’auto-assistance inspirés de la TCC. Il ne fournit ni diagnostic, ni psychothérapie, ni traitement médical, ni urgence professionnelle et ne crée pas de relation thérapeute-patient.'] },
        { title: 'Urgences', paragraphs: ['Ne comptez pas sur Mindful Path en cas d’urgence. Si vous risquez de vous faire du mal ou d’en faire à autrui, êtes en danger immédiat ou avez besoin de soins urgents, contactez immédiatement les services d’urgence locaux ou un professionnel qualifié.'] },
        { title: 'Âge et accès', paragraphs: ['Le chat IA est réservé aux personnes de 18 ans et plus. Les autres outils ne sont pas destinés aux moins de 13 ans ; les 13–17 ans doivent les utiliser avec un parent ou tuteur lorsque nécessaire.'] },
        { title: 'Limites de l’IA', paragraphs: ['Les réponses peuvent être inexactes, répétitives, inadaptées ou incomplètes. Ne retardez ni ne remplacez une évaluation ou un traitement professionnel sur la base du service.'] },
        { title: 'Usage acceptable', bullets: ['N’accédez pas au compte ou aux informations d’autrui.', 'Ne perturbez, sondez, surchargez ou contournez pas le service ou ses contrôles.', 'Ne générez pas de contenu illégal, abusif, trompeur ou nuisible.', 'Ne téléversez que du contenu que vous êtes autorisé à utiliser.'] },
        { title: 'Sécurité du compte', paragraphs: ['Protégez votre compte et votre appareil et prévenez le support en cas de suspicion d’accès non autorisé.'] },
        { title: 'Abonnements et paiements', paragraphs: ['Prix, essais, renouvellements, annulations et remboursements sont affichés avant achat et peuvent varier selon la plateforme et le pays. Les conditions de la boutique s’appliquent également.'] },
        { title: 'Disponibilité et propriété intellectuelle', paragraphs: ['Les fonctions peuvent changer, être suspendues ou devenir indisponibles. Mindful Path, son logiciel et son contenu original sont protégés ; vous conservez vos droits sur le contenu fourni.'] },
        { title: 'Responsabilité, droit et contact', paragraphs: ['Aucun droit ou responsabilité ne pouvant légalement être exclu ne l’est. Les conditions complémentaires et l’identité juridique de l’opérateur doivent être confirmées pour chaque pays. Contact : support@mindful-path.app.'] },
      ],
    },
    {
      title: 'Avant de commencer', description: 'Veuillez lire ces limites importantes avant d’utiliser le chat IA.',
      wellnessTitle: 'Auto-assistance, pas un traitement professionnel', wellnessBody: 'Le compagnon IA offre un soutien de bien-être inspiré de la TCC. Il n’est pas thérapeute, ne pose pas de diagnostic et ne remplace pas des soins médicaux ou psychologiques.',
      aiTitle: 'L’IA peut se tromper', aiBody: 'Les réponses peuvent être incomplètes ou inadaptées. Faites preuve de discernement et consultez un professionnel qualifié pour les décisions cliniques.',
      privacyTitle: 'Vos messages sont traités pour fournir le chat', privacyBody: 'Mindful Path, Base44 et les fournisseurs d’IA configurés peuvent traiter les messages. Évitez les informations que vous ne souhaitez pas voir traitées.',
      crisisTitle: 'Pas pour les urgences', crisisBody: 'Si vous risquez de vous faire du mal ou d’en faire à quelqu’un, ou êtes en danger immédiat, contactez les services locaux d’urgence ou de crise.',
      acknowledgement: 'En continuant, vous confirmez avoir au moins 18 ans, comprendre ces limites et accepter les Conditions d’utilisation et l’Avis de confidentialité.',
      accept: 'Je comprends et j’accepte', leave: 'Pas maintenant',
    }
  ),
  de: makeCopy('de',
    { effectiveDateLabel: 'Gültig ab', back: 'Zurück zu Mindful Path', privacy: 'Datenschutzhinweis', terms: 'Nutzungsbedingungen', contact: 'Kontakt', important: 'Wichtig' },
    {
      title: 'Datenschutzhinweis',
      intro: 'Dieser Hinweis erklärt, welche Informationen Mindful Path verarbeitet, wofür sie verwendet werden und welche Wahlmöglichkeiten Sie haben. Mindful Path ist ein Angebot für Wohlbefinden und Selbsthilfe, kein medizinischer oder Notfalldienst.',
      sections: [
        { title: 'Verantwortlicher und Kontakt', paragraphs: ['Der Betreiber von Mindful Path ist für die beschriebene Verarbeitung verantwortlich. Anfragen zu Auskunft, Export, Berichtigung oder Löschung senden Sie an support@mindful-path.app.'] },
        { title: 'Verarbeitete Informationen', bullets: ['Kontodaten wie Name, E-Mail, Sprache, Einstellungen und Authentifizierungskennungen.', 'Freiwillig bereitgestellte Wohlbefindensdaten wie Stimmung, Ziele, Tagebuch, Übungsfortschritt und KI-Unterhaltungen.', 'Sicherheitssignale, wenn Inhalte auf eine unmittelbare Gefahr hindeuten können.', 'Technische und Nutzungsdaten für Sicherheit, Zuverlässigkeit, Fehleranalyse und Betrugsprävention.', 'Abonnementstatus und Transaktionskennungen. Kartendaten verarbeitet der App-Store oder Zahlungsdienstleister.'] },
        { title: 'Zwecke der Verarbeitung', bullets: ['Angeforderte Funktionen bereitstellen und Sitzungen fortführen.', 'Übungen, Empfehlungen, Erinnerungen und Fortschritt personalisieren.', 'Sicherheitskontrollen betreiben und Notfallhilfen anzeigen.', 'Den Dienst schützen, warten, diagnostizieren und verbessern.', 'Gesetzliche Pflichten erfüllen und gültige Anfragen beantworten.'] },
        { title: 'KI und wichtige Grenzen', paragraphs: ['Inhalte für KI-Funktionen können von Mindful Path, Base44 und konfigurierten KI-Anbietern verarbeitet werden, um die Funktion bereitzustellen und zu schützen. KI kann Fehler machen und ist keine Diagnose, Behandlung oder Notfallanweisung.', 'Geben Sie vertrauliche Daten anderer Personen nur mit Berechtigung an.'] },
        { title: 'Dienstleister und internationale Verarbeitung', paragraphs: ['Anbieter für Hosting, Anmeldung, KI, Analyse, Support, Kommunikation, Zahlung und Sicherheit dürfen Daten nur für ihre Dienste und mit anwendbaren Schutzmaßnahmen verarbeiten.', 'Verarbeitung kann außerhalb Ihres Landes stattfinden. Mindful Path verkauft keine personenbezogenen Daten.'] },
        { title: 'Speicherung, Export und Löschung', paragraphs: ['Die Einstellungen zur Aufbewahrung begrenzen die Dauer unterstützter Wohlbefindensdaten. Sicherungen, Sicherheitsprotokolle, Transaktionen oder gesetzlich erforderliche Daten können anderen begrenzten Fristen unterliegen.', 'Sie können Daten exportieren oder Ihr Konto in den Einstellungen löschen. Die Umsetzung in Sicherungen und verwalteten Diensten kann Zeit benötigen.'] },
        { title: 'Ihre Rechte und Wahlmöglichkeiten', bullets: ['Daten einsehen und exportieren.', 'Kontodaten und Einstellungen berichtigen.', 'Eine unterstützte Aufbewahrungsdauer wählen.', 'Wohlbefindensverlauf oder Konto löschen.', 'Bestimmten Verarbeitungen widersprechen oder sie einschränken, soweit anwendbar.', 'Einwilligung mit Wirkung für die Zukunft widerrufen.', 'Sich bei der zuständigen Datenschutzbehörde beschweren.'] },
        { title: 'Sicherheit und Alter', paragraphs: ['Wir nutzen Zugriffskontrollen, Authentifizierung, verschlüsselte Verbindungen, Datenminimierung und Überwachung. Kein Onlinedienst kann absolute Sicherheit garantieren.', 'Der KI-Chat ist nur ab 18 Jahren. Andere Werkzeuge sind nicht für Kinder unter 13 bestimmt; 13- bis 17-Jährige sollen sie gegebenenfalls mit Eltern oder Sorgeberechtigten nutzen.'] },
        { title: 'Änderungen', paragraphs: ['Wesentliche Änderungen werden durch ein neues Gültigkeitsdatum und gegebenenfalls einen Hinweis in der App kenntlich gemacht. Erforderliche neue Einwilligungen werden gesondert eingeholt.'] },
      ],
    },
    {
      title: 'Nutzungsbedingungen',
      intro: 'Diese Bedingungen regeln die Nutzung von Mindful Path. Mit der Nutzung stimmen Sie ihnen und dem Datenschutzhinweis zu.',
      sections: [
        { title: 'Wohlbefinden, keine medizinische Versorgung', paragraphs: ['Mindful Path bietet Bildung, Achtsamkeit, Tagebuch und CBT-orientierte Selbsthilfe. Es bietet keine Diagnose, Psychotherapie, medizinische Behandlung oder professionelle Notfallhilfe und begründet kein Therapeut-Patient-Verhältnis.'] },
        { title: 'Notfälle', paragraphs: ['Verlassen Sie sich im Notfall nicht auf Mindful Path. Wenn Sie sich oder andere verletzen könnten, unmittelbar gefährdet sind oder dringende Hilfe benötigen, kontaktieren Sie sofort örtliche Notfalldienste oder qualifiziertes Fachpersonal.'] },
        { title: 'Alter und Zugang', paragraphs: ['Der KI-Chat ist ab 18 Jahren. Andere Werkzeuge sind nicht für Kinder unter 13 bestimmt; 13- bis 17-Jährige sollen sie gegebenenfalls mit Eltern oder Sorgeberechtigten nutzen.'] },
        { title: 'Grenzen der KI', paragraphs: ['Antworten können falsch, wiederholend, ungeeignet oder unvollständig sein. Verschieben oder ersetzen Sie keine professionelle Beurteilung oder Behandlung aufgrund von Informationen des Dienstes.'] },
        { title: 'Zulässige Nutzung', bullets: ['Greifen Sie nicht auf fremde Konten oder Informationen zu.', 'Stören, prüfen, überlasten oder umgehen Sie den Dienst oder seine Kontrollen nicht.', 'Erzeugen Sie keine rechtswidrigen, missbräuchlichen, täuschenden oder schädlichen Inhalte.', 'Laden Sie nur Inhalte hoch, zu deren Nutzung Sie berechtigt sind.'] },
        { title: 'Kontosicherheit', paragraphs: ['Schützen Sie Konto und Gerät und informieren Sie den Support bei Verdacht auf unbefugten Zugriff.'] },
        { title: 'Abonnements und Zahlungen', paragraphs: ['Preise, Testzeiträume, Verlängerung, Kündigung und Erstattung werden vor dem Kauf angezeigt und können je nach Plattform und Land variieren. Auch die Store-Bedingungen gelten.'] },
        { title: 'Verfügbarkeit und geistiges Eigentum', paragraphs: ['Funktionen können geändert, ausgesetzt oder eingestellt werden. Mindful Path, Software und Originalinhalte sind geschützt; Rechte an Ihren Inhalten verbleiben bei Ihnen.'] },
        { title: 'Haftung, Recht und Kontakt', paragraphs: ['Unabdingbare Rechte oder Pflichten werden nicht ausgeschlossen. Zusätzliche Bedingungen und die rechtliche Identität des Betreibers sind für jedes Land zu bestätigen. Kontakt: support@mindful-path.app.'] },
      ],
    },
    {
      title: 'Bevor wir beginnen', description: 'Bitte lesen Sie diese wichtigen Grenzen, bevor Sie den KI-Chat nutzen.',
      wellnessTitle: 'Selbsthilfe, keine professionelle Behandlung', wellnessBody: 'Der KI-Begleiter bietet CBT-orientierte Unterstützung für das Wohlbefinden. Er ist kein Therapeut, stellt keine Diagnosen und ersetzt keine medizinische oder psychische Versorgung.',
      aiTitle: 'KI kann Fehler machen', aiBody: 'Antworten können unvollständig oder ungeeignet sein. Nutzen Sie Ihr Urteilsvermögen und wenden Sie sich bei klinischen Entscheidungen an qualifiziertes Fachpersonal.',
      privacyTitle: 'Ihre Nachrichten werden für den Chat verarbeitet', privacyBody: 'Mindful Path, Base44 und konfigurierte KI-Anbieter können Nachrichten verarbeiten. Teilen Sie keine Informationen, deren Verarbeitung Sie nicht wünschen.',
      crisisTitle: 'Nicht für Notfälle', crisisBody: 'Wenn Sie sich oder andere verletzen könnten oder unmittelbar gefährdet sind, kontaktieren Sie jetzt örtliche Notfall- oder Krisendienste.',
      acknowledgement: 'Mit dem Fortfahren bestätigen Sie, mindestens 18 Jahre alt zu sein, diese Grenzen zu verstehen und den Nutzungsbedingungen sowie dem Datenschutzhinweis zuzustimmen.',
      accept: 'Ich verstehe und stimme zu', leave: 'Nicht jetzt',
    }
  ),
  it: makeCopy('it',
    { effectiveDateLabel: 'Data di efficacia', back: 'Torna a Mindful Path', privacy: 'Informativa sulla privacy', terms: 'Termini di utilizzo', contact: 'Contatti', important: 'Importante' },
    {
      title: 'Informativa sulla privacy',
      intro: 'Questa informativa spiega quali informazioni tratta Mindful Path, perché vengono utilizzate e quali scelte hai. Mindful Path è un servizio di benessere e auto-aiuto, non un servizio medico o di emergenza.',
      sections: [
        { title: 'Titolare e contatti', paragraphs: ['Il gestore di Mindful Path è responsabile del trattamento descritto. Le richieste di accesso, esportazione, rettifica o cancellazione possono essere inviate a support@mindful-path.app.'] },
        { title: 'Informazioni trattate', bullets: ['Dati dell’account come nome, e-mail, lingua, preferenze e identificativi di autenticazione.', 'Contenuti di benessere forniti volontariamente: umore, obiettivi, diario, progressi e conversazioni con funzioni IA.', 'Segnali di sicurezza quando un contenuto può indicare un rischio immediato.', 'Dati tecnici e di utilizzo necessari per sicurezza, affidabilità, diagnosi e prevenzione delle frodi.', 'Stato dell’abbonamento e identificativi delle transazioni. I dati della carta sono trattati dallo store o dal fornitore di pagamento.'] },
        { title: 'Finalità del trattamento', bullets: ['Fornire le funzioni richieste e la continuità tra sessioni.', 'Personalizzare esercizi, consigli, promemoria e progressi.', 'Applicare controlli di sicurezza e mostrare risorse di emergenza.', 'Proteggere, mantenere, diagnosticare e migliorare il servizio.', 'Rispettare obblighi di legge e richieste valide.'] },
        { title: 'IA e limiti importanti', paragraphs: ['I contenuti inviati alle funzioni IA possono essere trattati da Mindful Path, Base44 e dai fornitori IA configurati per offrire e proteggere la funzione. L’IA può sbagliare e non è una diagnosi, un trattamento o un’istruzione di emergenza.', 'Non condividere informazioni riservate di altre persone senza autorizzazione.'] },
        { title: 'Fornitori e trasferimenti internazionali', paragraphs: ['Fornitori di hosting, autenticazione, IA, analisi, assistenza, comunicazioni, pagamenti e sicurezza possono trattare dati solo per i loro servizi e con le garanzie applicabili.', 'Il trattamento può avvenire fuori dal tuo Paese. Mindful Path non vende dati personali.'] },
        { title: 'Conservazione, esportazione e cancellazione', paragraphs: ['Le impostazioni di conservazione limitano la durata dei dati di benessere supportati. Backup, log di sicurezza, transazioni o dati richiesti dalla legge possono seguire periodi limitati diversi.', 'Puoi esportare i dati o eliminare l’account dalle Impostazioni. La propagazione a backup e servizi gestiti può richiedere tempo.'] },
        { title: 'Diritti e scelte', bullets: ['Accedere ed esportare i dati.', 'Rettificare dati e preferenze.', 'Scegliere un periodo di conservazione supportato.', 'Eliminare cronologia o account.', 'Opporti o limitare alcuni trattamenti quando applicabile.', 'Revocare il consenso senza pregiudicare il trattamento precedente lecito.', 'Rivolgerti all’autorità competente per la protezione dei dati.'] },
        { title: 'Sicurezza ed età', paragraphs: ['Usiamo controlli di accesso, autenticazione, connessioni cifrate, minimizzazione e monitoraggio. Nessun servizio online garantisce sicurezza assoluta.', 'La chat IA è riservata ai maggiori di 18 anni. Gli altri strumenti non sono destinati ai minori di 13 anni; tra 13 e 17 anni vanno usati con un genitore o tutore quando necessario.'] },
        { title: 'Modifiche', paragraphs: ['Le modifiche importanti saranno indicate con una nuova data di efficacia e, se opportuno, un avviso nell’app. Un nuovo consenso sarà richiesto quando previsto dalla legge.'] },
      ],
    },
    {
      title: 'Termini di utilizzo',
      intro: 'Questi termini regolano l’uso di Mindful Path. Utilizzando il servizio accetti i termini e l’Informativa sulla privacy.',
      sections: [
        { title: 'Benessere, non assistenza medica', paragraphs: ['Mindful Path offre contenuti educativi, mindfulness, diario e auto-aiuto ispirato alla CBT. Non offre diagnosi, psicoterapia, cure mediche o emergenze professionali e non crea un rapporto terapeuta-paziente.'] },
        { title: 'Emergenze', paragraphs: ['Non fare affidamento su Mindful Path in emergenza. Se potresti fare del male a te o ad altri, sei in pericolo immediato o necessiti cure urgenti, contatta subito i servizi di emergenza locali o un professionista qualificato.'] },
        { title: 'Età e accesso', paragraphs: ['La chat IA è riservata ai maggiori di 18 anni. Gli altri strumenti non sono destinati ai minori di 13 anni; tra 13 e 17 anni vanno usati con un genitore o tutore quando necessario.'] },
        { title: 'Limiti dell’IA', paragraphs: ['Le risposte possono essere inesatte, ripetitive, inadatte o incomplete. Non rinviare o sostituire una valutazione o cura professionale sulla base del servizio.'] },
        { title: 'Uso accettabile', bullets: ['Non accedere ad account o informazioni altrui.', 'Non interrompere, sondare, sovraccaricare o aggirare il servizio o i suoi controlli.', 'Non generare contenuti illegali, abusivi, ingannevoli o dannosi.', 'Carica solo contenuti che hai diritto di usare.'] },
        { title: 'Sicurezza dell’account', paragraphs: ['Proteggi account e dispositivo e informa l’assistenza se sospetti un accesso non autorizzato.'] },
        { title: 'Abbonamenti e pagamenti', paragraphs: ['Prezzi, prove, rinnovi, cancellazioni e rimborsi sono mostrati prima dell’acquisto e possono variare per piattaforma e Paese. Si applicano anche i termini dello store.'] },
        { title: 'Disponibilità e proprietà intellettuale', paragraphs: ['Le funzioni possono cambiare, essere sospese o diventare indisponibili. Mindful Path, il software e i contenuti originali sono protetti; mantieni i diritti sui contenuti forniti.'] },
        { title: 'Responsabilità, legge e contatti', paragraphs: ['Non vengono esclusi diritti o responsabilità inderogabili. Termini aggiuntivi e identità giuridica del gestore devono essere confermati per ogni Paese. Contatti: support@mindful-path.app.'] },
      ],
    },
    {
      title: 'Prima di iniziare', description: 'Leggi questi limiti importanti prima di usare la chat IA.',
      wellnessTitle: 'Auto-aiuto, non trattamento professionale', wellnessBody: 'L’accompagnatore IA offre supporto al benessere ispirato alla CBT. Non è un terapeuta, non formula diagnosi e non sostituisce cure mediche o psicologiche.',
      aiTitle: 'L’IA può sbagliare', aiBody: 'Le risposte possono essere incomplete o inadatte. Usa il tuo giudizio e consulta un professionista qualificato per decisioni cliniche.',
      privacyTitle: 'I messaggi vengono trattati per offrire la chat', privacyBody: 'Mindful Path, Base44 e i fornitori IA configurati possono trattare i messaggi. Evita informazioni che non vuoi siano trattate.',
      crisisTitle: 'Non per emergenze', crisisBody: 'Se potresti fare del male a te o a qualcuno, o sei in pericolo immediato, contatta subito i servizi locali di emergenza o crisi.',
      acknowledgement: 'Continuando confermi di avere almeno 18 anni, comprendere questi limiti e accettare i Termini di utilizzo e l’Informativa sulla privacy.',
      accept: 'Comprendo e accetto', leave: 'Non ora',
    }
  ),
  pt: makeCopy('pt',
    { effectiveDateLabel: 'Data de entrada em vigor', back: 'Voltar ao Mindful Path', privacy: 'Aviso de privacidade', terms: 'Termos de utilização', contact: 'Contacto', important: 'Importante' },
    {
      title: 'Aviso de privacidade',
      intro: 'Este aviso explica que informações o Mindful Path trata, por que são utilizadas e que escolhas estão disponíveis. O Mindful Path é um serviço de bem-estar e autoajuda, não um serviço médico ou de emergência.',
      sections: [
        { title: 'Responsável e contacto', paragraphs: ['O operador do Mindful Path é responsável pelo tratamento descrito. Pedidos de acesso, exportação, correção ou eliminação podem ser enviados para support@mindful-path.app.'] },
        { title: 'Informações tratadas', bullets: ['Dados da conta, como nome, e-mail, idioma, preferências e identificadores de autenticação.', 'Conteúdo de bem-estar fornecido voluntariamente: humor, objetivos, diário, progresso e conversas com funcionalidades de IA.', 'Sinais de segurança quando o conteúdo pode indicar risco imediato.', 'Dados técnicos e de utilização necessários para segurança, fiabilidade, diagnóstico e prevenção de fraude.', 'Estado da subscrição e identificadores de transação. Os dados do cartão são tratados pela loja ou pelo prestador de pagamentos.'] },
        { title: 'Como e por que usamos as informações', bullets: ['Prestar as funcionalidades pedidas e manter continuidade entre sessões.', 'Personalizar exercícios, recomendações, lembretes e progresso.', 'Aplicar controlos de segurança e mostrar recursos de emergência.', 'Proteger, manter, diagnosticar e melhorar o serviço.', 'Cumprir obrigações legais e responder a pedidos válidos.'] },
        { title: 'IA e limites importantes', paragraphs: ['O conteúdo enviado às funcionalidades de IA pode ser tratado pelo Mindful Path, Base44 e fornecedores de IA configurados para prestar e proteger a funcionalidade. A IA pode errar e não constitui diagnóstico, tratamento ou instrução de emergência.', 'Não partilhe informações confidenciais de outra pessoa sem autorização.'] },
        { title: 'Prestadores e transferências internacionais', paragraphs: ['Prestadores de alojamento, autenticação, IA, análise, apoio, comunicações, pagamentos e segurança podem tratar dados apenas para os respetivos serviços e com as salvaguardas aplicáveis.', 'O tratamento pode ocorrer fora do seu país. O Mindful Path não vende informações pessoais.'] },
        { title: 'Conservação, exportação e eliminação', paragraphs: ['As definições de conservação limitam a duração dos registos de bem-estar suportados. Cópias de segurança, registos de segurança, transações ou dados exigidos por lei podem seguir outros prazos limitados.', 'Pode exportar dados ou eliminar a conta nas Definições. A propagação para cópias de segurança e serviços geridos pode demorar.'] },
        { title: 'Direitos e escolhas', bullets: ['Aceder e exportar os dados.', 'Corrigir dados e preferências.', 'Escolher um período de conservação suportado.', 'Eliminar o histórico ou a conta.', 'Opor-se ou limitar determinados tratamentos quando aplicável.', 'Retirar o consentimento sem afetar o tratamento anterior lícito.', 'Contactar a autoridade de proteção de dados competente.'] },
        { title: 'Segurança e idade', paragraphs: ['Usamos controlos de acesso, autenticação, ligações cifradas, minimização e monitorização. Nenhum serviço online garante segurança absoluta.', 'O chat de IA é apenas para maiores de 18 anos. As restantes ferramentas não se destinam a menores de 13; dos 13 aos 17 anos devem ser usadas com um progenitor ou tutor quando necessário.'] },
        { title: 'Alterações', paragraphs: ['Alterações importantes serão indicadas por uma nova data de entrada em vigor e, quando apropriado, um aviso na aplicação. Um novo consentimento será pedido quando exigido por lei.'] },
      ],
    },
    {
      title: 'Termos de utilização',
      intro: 'Estes termos regem a utilização do Mindful Path. Ao utilizar o serviço, aceita os termos e o Aviso de privacidade.',
      sections: [
        { title: 'Bem-estar, não cuidados médicos', paragraphs: ['O Mindful Path oferece educação, mindfulness, diário e autoajuda informada pela TCC. Não presta diagnóstico, psicoterapia, tratamento médico ou emergência profissional e não cria uma relação terapeuta-paciente.'] },
        { title: 'Emergências', paragraphs: ['Não dependa do Mindful Path numa emergência. Se puder magoar-se ou magoar alguém, estiver em perigo imediato ou precisar de cuidados urgentes, contacte já os serviços locais de emergência ou um profissional qualificado.'] },
        { title: 'Idade e acesso', paragraphs: ['O chat de IA é apenas para maiores de 18 anos. As restantes ferramentas não se destinam a menores de 13; dos 13 aos 17 anos devem ser usadas com um progenitor ou tutor quando necessário.'] },
        { title: 'Limites da IA', paragraphs: ['As respostas podem ser incorretas, repetitivas, inadequadas ou incompletas. Não adie nem substitua uma avaliação ou tratamento profissional com base no serviço.'] },
        { title: 'Utilização aceitável', bullets: ['Não aceda a contas ou informações de outras pessoas.', 'Não perturbe, teste, sobrecarregue ou contorne o serviço ou os seus controlos.', 'Não gere conteúdo ilegal, abusivo, enganador ou prejudicial.', 'Carregue apenas conteúdo que tem direito de usar.'] },
        { title: 'Segurança da conta', paragraphs: ['Proteja a conta e o dispositivo e informe o apoio se suspeitar de acesso não autorizado.'] },
        { title: 'Subscrições e pagamentos', paragraphs: ['Preços, testes, renovações, cancelamentos e reembolsos são mostrados antes da compra e podem variar por plataforma e país. Também se aplicam os termos da loja.'] },
        { title: 'Disponibilidade e propriedade intelectual', paragraphs: ['As funcionalidades podem mudar, ser suspensas ou ficar indisponíveis. O Mindful Path, o software e o conteúdo original estão protegidos; mantém os direitos sobre o conteúdo fornecido.'] },
        { title: 'Responsabilidade, lei e contacto', paragraphs: ['Não são excluídos direitos ou responsabilidades que legalmente não possam ser excluídos. Termos adicionais e a identidade jurídica do operador devem ser confirmados para cada país. Contacto: support@mindful-path.app.'] },
      ],
    },
    {
      title: 'Antes de começar', description: 'Leia estes limites importantes antes de utilizar o chat de IA.',
      wellnessTitle: 'Autoajuda, não tratamento profissional', wellnessBody: 'O acompanhante de IA oferece apoio ao bem-estar informado pela TCC. Não é terapeuta, não diagnostica e não substitui cuidados médicos ou de saúde mental.',
      aiTitle: 'A IA pode errar', aiBody: 'As respostas podem ser incompletas ou inadequadas. Use o seu discernimento e consulte um profissional qualificado para decisões clínicas.',
      privacyTitle: 'As mensagens são tratadas para prestar o chat', privacyBody: 'O Mindful Path, Base44 e fornecedores de IA configurados podem tratar mensagens. Evite informações que não deseja que sejam tratadas.',
      crisisTitle: 'Não se destina a emergências', crisisBody: 'Se puder magoar-se ou magoar alguém, ou estiver em perigo imediato, contacte já os serviços locais de emergência ou crise.',
      acknowledgement: 'Ao continuar, confirma que tem 18 anos ou mais, compreende estes limites e aceita os Termos de utilização e o Aviso de privacidade.',
      accept: 'Compreendo e aceito', leave: 'Agora não',
    }
  ),
};
