export const EXERCISE_CONTENT_BATCH_5B_IDS = [
  "69519590cc9f81fd9daed0b0",
  "69519590cc9f81fd9daed0af",
  "69519590cc9f81fd9daed0b7",
  "69519590cc9f81fd9daed0ba",
  "69b11c0f9b78b21b9c2351f0",
  "69b11c0f9b78b21b9c2351ed",
  "69b11c0f9b78b21b9c2351ef"
];

const item = (title, description, tags, steps, benefits, tips) => ({ title, description, tags, steps, benefits, tips });
const steps = (values) => values.map(([title, description]) => ({ title, description }));

export const EXERCISE_CONTENT_TRANSLATIONS_BATCH_5B = {
  "69519590cc9f81fd9daed0b0": {
    en: item("Mindful Listening Practice","Develop presence by giving full, nonjudgmental attention to sounds.",["mindfulness","listening","presence","awareness"],steps([["Settle","Sit comfortably and take a few natural breaths."],["Open to sound","Let nearby and distant sounds come to you without searching."],["Notice without labels","Experience volume, rhythm and vibration without deciding whether sounds are good or bad."],["Return","Notice silence, reconnect with the body and gently open your eyes."]]),["Builds concentration","Reduces rumination","Supports attentive listening"],["Do not use while driving or when attention to hazards is required.","If a sound is distressing, open your eyes and return attention to the room."]),
    he: item("תרגול הקשבה מודעת","פתחו נוכחות באמצעות הקשבה מלאה ולא שיפוטית לצלילים.",["קשיבות","הקשבה","נוכחות","מודעות"],steps([["התמקמות","שבו בנוחות וקחו כמה נשימות טבעיות."],["פתיחות לצליל","אפשרו לצלילים קרובים ורחוקים להגיע אליכם בלי לחפש אותם."],["ללא תוויות","חוו עוצמה, קצב ורטט בלי לקבוע אם הצליל טוב או רע."],["חזרה","הבחינו בשקט, התחברו לגוף ופקחו עיניים בעדינות."]]),["שיפור ריכוז","הפחתת הרהור חוזר","תמיכה בהקשבה לאחרים"],["אין לתרגל בזמן נהיגה או כשנדרשת תשומת לב לסכנות.","אם צליל מעורר מצוקה, פקחו עיניים והחזירו קשב לחדר."]),
    es: item("Práctica de escucha consciente","Desarrolla presencia prestando atención plena y sin juicio a los sonidos.",["atención plena","escucha","presencia","conciencia"],steps([["Acomódate","Siéntate cómodamente y respira con naturalidad."],["Ábrete al sonido","Deja que los sonidos cercanos y lejanos lleguen sin buscarlos."],["Sin etiquetas","Percibe volumen, ritmo y vibración sin juzgar."],["Regresa","Observa el silencio, siente el cuerpo y abre los ojos."]]),["Mejora concentración","Reduce rumiación","Favorece escucha atenta"],["No practiques conduciendo ni donde debas vigilar peligros.","Si un sonido angustia, abre los ojos y vuelve a la habitación."]),
    fr: item("Écoute en pleine conscience","Développez la présence en accueillant les sons avec une attention entière et sans jugement.",["pleine conscience","écoute","présence","conscience"],steps([["S’installer","Asseyez-vous confortablement et respirez naturellement."],["S’ouvrir aux sons","Laissez les sons proches et lointains venir à vous."],["Sans étiquette","Percevez volume, rythme et vibration sans juger."],["Revenir","Remarquez le silence, sentez le corps et ouvrez les yeux."]]),["Améliore la concentration","Réduit la rumination","Soutient l’écoute attentive"],["Ne pratiquez pas en conduisant ou près d’un danger.","Si un son est pénible, ouvrez les yeux et revenez à la pièce."]),
    de: item("Achtsames Zuhören","Entwickle Präsenz durch volle, wertfreie Aufmerksamkeit für Geräusche.",["Achtsamkeit","Zuhören","Präsenz","Wahrnehmung"],steps([["Ankommen","Setze dich bequem hin und atme natürlich."],["Für Klänge öffnen","Lass nahe und ferne Geräusche zu dir kommen."],["Ohne Etikett","Nimm Lautstärke, Rhythmus und Schwingung wertfrei wahr."],["Zurückkehren","Bemerke Stille, spüre den Körper und öffne die Augen."]]),["Stärkt Konzentration","Verringert Grübeln","Fördert Zuhören"],["Nicht beim Fahren oder bei erforderlicher Gefahrenaufmerksamkeit üben.","Bei belastenden Geräuschen Augen öffnen und im Raum orientieren."]),
    it: item("Ascolto consapevole","Sviluppa presenza dando attenzione piena e non giudicante ai suoni.",["consapevolezza","ascolto","presenza","attenzione"],steps([["Preparati","Siediti comodamente e respira naturalmente."],["Apriti ai suoni","Lascia arrivare i suoni vicini e lontani."],["Senza etichette","Percepisci volume, ritmo e vibrazione senza giudizio."],["Ritorna","Nota il silenzio, senti il corpo e apri gli occhi."]]),["Migliora concentrazione","Riduce ruminazione","Favorisce ascolto attento"],["Non praticare guidando o dove serve attenzione ai pericoli.","Se un suono turba, apri gli occhi e orientati nella stanza."]),
    pt: item("Escuta consciente","Desenvolva presença dando atenção plena e sem julgamento aos sons.",["atenção plena","escuta","presença","consciência"],steps([["Acomode-se","Sente-se confortavelmente e respire de modo natural."],["Abra-se aos sons","Deixe sons próximos e distantes chegarem até você."],["Sem rótulos","Perceba volume, ritmo e vibração sem julgar."],["Retorne","Observe o silêncio, sinta o corpo e abra os olhos."]]),["Melhora concentração","Reduz ruminação","Apoia escuta atenta"],["Não pratique dirigindo ou quando precisar vigiar riscos.","Se um som causar aflição, abra os olhos e volte ao ambiente."])
  },
  "69519590cc9f81fd9daed0af": {
    en: item("Mindful Breathing Anchor","Use natural breathing as a steady anchor for returning to the present.",["mindfulness","breathing","focus","calm"],steps([["Find posture","Sit comfortably with a supported, unforced posture."],["Locate breath","Notice breathing at the nose, chest or belly without changing it."],["Stay and return","Follow each breath; when attention wanders, return gently."],["Expand","Let the breath remain in awareness while noticing the whole body."]]),["Supports calm focus","Builds attention regulation","Increases self-awareness"],["Observe rather than force the breath; never restrict breathing.","If breath focus increases panic, stop and ground through sight, touch or sound."]),
    he: item("עוגן נשימה מודעת","השתמשו בנשימה הטבעית כעוגן יציב לחזרה להווה.",["קשיבות","נשימה","מיקוד","רוגע"],steps([["מציאת תנוחה","שבו בנוחות בתנוחה נתמכת ולא מאומצת."],["איתור הנשימה","הבחינו בנשימה באף, בחזה או בבטן בלי לשנות אותה."],["שהייה וחזרה","עקבו אחר הנשימה וכשהקשב נודד החזירו אותו בעדינות."],["הרחבה","השאירו את הנשימה במודעות והבחינו בגוף כולו."]]),["תמיכה ברוגע ובמיקוד","ויסות קשב","הגברת מודעות עצמית"],["התבוננו בנשימה ואל תכריחו אותה; לעולם אל תגבילו נשימה.","אם מיקוד בנשימה מגביר בהלה, עצרו והתקרקעו בעזרת ראייה, מגע או קול."]),
    es: item("Ancla de respiración consciente","Usa la respiración natural como ancla estable para volver al presente.",["atención plena","respiración","enfoque","calma"],steps([["Postura","Siéntate con comodidad y apoyo."],["Localiza","Siente la respiración en nariz, pecho o vientre sin cambiarla."],["Permanece y vuelve","Sigue cada respiración y regresa con suavidad si te distraes."],["Amplía","Mantén la respiración presente mientras notas todo el cuerpo."]]),["Favorece enfoque sereno","Regula atención","Aumenta autoconciencia"],["Observa sin forzar; nunca restrinjas la respiración.","Si aumenta el pánico, detente y usa vista, tacto o sonidos para anclarte."]),
    fr: item("Ancrage par la respiration","Utilisez la respiration naturelle comme ancrage stable vers le présent.",["pleine conscience","respiration","attention","calme"],steps([["Posture","Asseyez-vous confortablement, sans effort."],["Localiser","Sentez le souffle au nez, à la poitrine ou au ventre sans le modifier."],["Rester et revenir","Suivez le souffle et revenez doucement après une distraction."],["Élargir","Gardez le souffle présent tout en sentant le corps entier."]]),["Favorise une attention calme","Régule l’attention","Renforce la conscience de soi"],["Observez sans forcer et ne limitez jamais la respiration.","Si la panique augmente, arrêtez et ancrez-vous par la vue, le toucher ou les sons."]),
    de: item("Achtsamer Atemanker","Nutze den natürlichen Atem als stabilen Anker für die Gegenwart.",["Achtsamkeit","Atmung","Fokus","Ruhe"],steps([["Haltung","Sitze bequem, gestützt und ohne Anstrengung."],["Atem finden","Spüre ihn an Nase, Brust oder Bauch, ohne ihn zu verändern."],["Bleiben und zurückkehren","Folge dem Atem und kehre nach Ablenkung sanft zurück."],["Erweitern","Behalte den Atem im Bewusstsein und spüre den ganzen Körper."]]),["Fördert ruhigen Fokus","Reguliert Aufmerksamkeit","Stärkt Selbstwahrnehmung"],["Beobachte ohne Zwang und schränke den Atem nie ein.","Wenn Panik steigt, stoppe und orientiere dich über Sehen, Tasten oder Hören."]),
    it: item("Ancora del respiro consapevole","Usa il respiro naturale come ancora stabile per tornare al presente.",["consapevolezza","respiro","concentrazione","calma"],steps([["Postura","Siediti comodo, sostenuto e senza sforzo."],["Trova il respiro","Sentilo al naso, petto o addome senza modificarlo."],["Rimani e ritorna","Segui il respiro e torna dolcemente dopo una distrazione."],["Amplia","Mantieni il respiro presente sentendo tutto il corpo."]]),["Favorisce concentrazione calma","Regola attenzione","Aumenta autoconsapevolezza"],["Osserva senza forzare e non limitare mai il respiro.","Se aumenta il panico, fermati e usa vista, tatto o suoni per radicarti."]),
    pt: item("Âncora da respiração consciente","Use a respiração natural como âncora estável para voltar ao presente.",["atenção plena","respiração","foco","calma"],steps([["Postura","Sente-se com conforto, apoio e sem esforço."],["Localize","Sinta a respiração no nariz, peito ou abdômen sem mudá-la."],["Fique e retorne","Acompanhe cada ciclo e volte suavemente após distrações."],["Amplie","Mantenha a respiração na consciência e perceba o corpo todo."]]),["Favorece foco sereno","Regula atenção","Aumenta autoconsciência"],["Observe sem forçar e nunca restrinja a respiração.","Se o pânico aumentar, pare e use visão, toque ou sons para se ancorar."])
  },
  "69519590cc9f81fd9daed0b7": {
    en: item("Positive Data Log","Counter negative bias by recording concrete positive evidence each day.",["CBT","positive evidence","mood","gratitude"],steps([["Choose a time","Set a brief, consistent daily review time."],["Find three","Identify up to three positive or helpful moments, however small."],["Describe evidence","Write what happened and your contribution, using facts."],["Review","Read the entries weekly and notice meaningful patterns."]]),["Balances negative bias","Supports realistic optimism","Builds positive recall"],["Small facts count; do not pressure yourself to feel positive.","This complements, rather than dismisses, real difficulties."]),
    he: item("יומן נתונים חיוביים","אזנו הטיה שלילית באמצעות רישום ראיות חיוביות וממשיות בכל יום.",["CBT","ראיות חיוביות","מצב רוח","הכרת תודה"],steps([["בחירת זמן","קבעו זמן קצר וקבוע לבדיקה יומית."],["מציאת שלושה","זהו עד שלושה רגעים חיוביים או מועילים, גם אם קטנים."],["תיאור ראיות","כתבו מה קרה ומה הייתה תרומתכם, בעזרת עובדות."],["סקירה","קראו את הרשומות מדי שבוע וזהו דפוסים משמעותיים."]]),["איזון הטיה שלילית","תמיכה באופטימיות מציאותית","חיזוק זיכרון חיובי"],["גם עובדות קטנות נחשבות; אין להכריח את עצמכם להרגיש חיובי.","התרגיל משלים קשיים אמיתיים ואינו מבטל אותם."]),
    es: item("Registro de datos positivos","Compensa el sesgo negativo anotando pruebas positivas concretas cada día.",["TCC","evidencia positiva","ánimo","gratitud"],steps([["Elige un momento","Fija una revisión diaria breve."],["Encuentra tres","Identifica hasta tres momentos positivos, aunque sean pequeños."],["Describe pruebas","Anota hechos y tu contribución."],["Revisa","Lee semanalmente y observa patrones significativos."]]),["Equilibra sesgo negativo","Apoya optimismo realista","Refuerza recuerdos positivos"],["Los hechos pequeños cuentan; no te obligues a sentirte positivo.","Complementa las dificultades reales, no las niega."]),
    fr: item("Journal des éléments positifs","Compensez le biais négatif en notant chaque jour des faits positifs concrets.",["TCC","preuves positives","humeur","gratitude"],steps([["Choisir un moment","Fixez une courte révision quotidienne."],["En trouver trois","Repérez jusqu’à trois moments positifs, même petits."],["Décrire les faits","Notez ce qui s’est passé et votre contribution."],["Réviser","Relisez chaque semaine et observez les tendances."]]),["Équilibre le biais négatif","Soutient un optimisme réaliste","Renforce le rappel positif"],["Les petits faits comptent; ne forcez pas une émotion positive.","L’exercice complète les difficultés réelles sans les nier."]),
    de: item("Tagebuch positiver Daten","Gleiche Negativitätsfokus durch tägliche konkrete positive Belege aus.",["KVT","positive Belege","Stimmung","Dankbarkeit"],steps([["Zeit wählen","Lege eine kurze tägliche Rückschau fest."],["Drei finden","Finde bis zu drei positive oder hilfreiche Momente."],["Belege beschreiben","Notiere Fakten und deinen Anteil."],["Prüfen","Lies wöchentlich und erkenne bedeutsame Muster."]]),["Gleicht Negativitätsfokus aus","Fördert realistischen Optimismus","Stärkt positive Erinnerung"],["Auch kleine Fakten zählen; erzwinge kein positives Gefühl.","Die Übung ergänzt reale Schwierigkeiten und leugnet sie nicht."]),
    it: item("Registro dei dati positivi","Contrasta il pregiudizio negativo annotando ogni giorno prove positive concrete.",["CBT","prove positive","umore","gratitudine"],steps([["Scegli un momento","Stabilisci una breve revisione quotidiana."],["Trova tre","Individua fino a tre momenti positivi, anche piccoli."],["Descrivi le prove","Annota i fatti e il tuo contributo."],["Rivedi","Leggi ogni settimana e nota schemi significativi."]]),["Bilancia il pregiudizio negativo","Sostiene ottimismo realistico","Rafforza ricordi positivi"],["Anche i piccoli fatti contano; non forzare emozioni positive.","Integra le difficoltà reali, non le nega."]),
    pt: item("Registro de dados positivos","Contrabalance o viés negativo anotando evidências positivas concretas diariamente.",["TCC","evidência positiva","humor","gratidão"],steps([["Escolha um horário","Defina uma revisão diária breve."],["Encontre três","Identifique até três momentos positivos, mesmo pequenos."],["Descreva evidências","Registre fatos e sua contribuição."],["Revise","Leia semanalmente e observe padrões importantes."]]),["Equilibra viés negativo","Apoia otimismo realista","Fortalece lembranças positivas"],["Pequenos fatos contam; não force sentimentos positivos.","Complementa dificuldades reais, sem negá-las."])
  },
  "69519590cc9f81fd9daed0ba": {
    en: item("Approach Instead of Avoidance","Identify avoidance and approach one safe, manageable situation in gradual steps.",["behavioral activation","avoidance","anxiety","courage"],steps([["Choose safely","Select a non-dangerous situation that matters and is moderately difficult."],["Build steps","Create a gradual ladder from easiest to harder actions."],["Practice","Try one step, stay long enough to learn, and record anxiety before and after."],["Review","Repeat or adjust the step; progress without rushing."]]),["Reduces avoidance","Builds confidence","Expands daily functioning"],["Do not approach abuse, violence, medical danger or objectively unsafe situations.","For trauma, severe panic or high-risk exposure, work with a qualified clinician."]),
    he: item("התקרבות במקום הימנעות","זהו הימנעות והתקרבו בהדרגה למצב בטוח ובר־ניהול.",["הפעלה התנהגותית","הימנעות","חרדה","אומץ"],steps([["בחירה בטוחה","בחרו מצב שאינו מסוכן, חשוב עבורכם ובקושי בינוני."],["בניית צעדים","צרו סולם הדרגתי מפעולה קלה לקשה יותר."],["תרגול","נסו צעד אחד, הישארו כדי ללמוד ורשמו חרדה לפני ואחרי."],["סקירה","חזרו על הצעד או התאימו אותו, ללא חיפזון."]]),["הפחתת הימנעות","חיזוק ביטחון","הרחבת התפקוד היומיומי"],["אין להתקרב להתעללות, אלימות, סכנה רפואית או מצב שאינו בטוח באופן ממשי.","בטראומה, בהלה חמורה או חשיפה בסיכון גבוה יש לעבוד עם איש מקצוע מוסמך."]),
    es: item("Acercamiento en vez de evitación","Identifica evitación y acércate gradualmente a una situación segura y manejable.",["activación conductual","evitación","ansiedad","valentía"],steps([["Elige con seguridad","Escoge una situación no peligrosa, importante y moderadamente difícil."],["Crea pasos","Construye una escala gradual de fácil a difícil."],["Practica","Prueba un paso y registra ansiedad antes y después."],["Revisa","Repite o ajusta sin apresurarte."]]),["Reduce evitación","Aumenta confianza","Amplía funcionamiento diario"],["No te acerques a abuso, violencia, peligro médico o situaciones objetivamente inseguras.","Para trauma, pánico grave o alto riesgo, trabaja con un profesional cualificado."]),
    fr: item("S’approcher plutôt qu’éviter","Repérez l’évitement et approchez progressivement une situation sûre et gérable.",["activation comportementale","évitement","anxiété","courage"],steps([["Choisir prudemment","Prenez une situation non dangereuse, importante et modérément difficile."],["Créer des étapes","Construisez une progression du plus facile au plus difficile."],["Pratiquer","Essayez une étape et notez l’anxiété avant et après."],["Réviser","Répétez ou ajustez sans vous presser."]]),["Réduit l’évitement","Renforce la confiance","Élargit le fonctionnement quotidien"],["N’approchez pas abus, violence, danger médical ou situation réellement dangereuse.","Pour traumatisme, panique sévère ou haut risque, travaillez avec un clinicien qualifié."]),
    de: item("Annäherung statt Vermeidung","Erkenne Vermeidung und nähere dich schrittweise einer sicheren, machbaren Situation.",["Verhaltensaktivierung","Vermeidung","Angst","Mut"],steps([["Sicher wählen","Wähle eine ungefährliche, wichtige und mäßig schwierige Situation."],["Schritte bilden","Erstelle eine Leiter von leicht zu schwerer."],["Üben","Probiere einen Schritt und notiere Angst davor und danach."],["Prüfen","Wiederhole oder passe an, ohne zu eilen."]]),["Verringert Vermeidung","Stärkt Vertrauen","Erweitert Alltagsfunktion"],["Nicht an Missbrauch, Gewalt, medizinische Gefahr oder objektiv unsichere Situationen annähern.","Bei Trauma, schwerer Panik oder hohem Risiko mit Fachpersonal arbeiten."]),
    it: item("Avvicinarsi invece di evitare","Riconosci l’evitamento e avvicinati gradualmente a una situazione sicura e gestibile.",["attivazione comportamentale","evitamento","ansia","coraggio"],steps([["Scegli in sicurezza","Scegli una situazione non pericolosa, importante e moderatamente difficile."],["Crea passi","Costruisci una scala dal più facile al più difficile."],["Pratica","Prova un passo e registra l’ansia prima e dopo."],["Rivedi","Ripeti o modifica senza fretta."]]),["Riduce evitamento","Aumenta fiducia","Amplia funzionamento quotidiano"],["Non affrontare abuso, violenza, pericolo medico o situazioni realmente insicure.","Per trauma, panico grave o alto rischio lavora con un professionista qualificato."]),
    pt: item("Aproximação em vez de evitação","Identifique a evitação e aproxime-se gradualmente de uma situação segura e administrável.",["ativação comportamental","evitação","ansiedade","coragem"],steps([["Escolha com segurança","Selecione situação não perigosa, importante e moderadamente difícil."],["Crie etapas","Monte uma escada gradual do fácil ao mais difícil."],["Pratique","Tente uma etapa e registre a ansiedade antes e depois."],["Revise","Repita ou ajuste sem pressa."]]),["Reduz evitação","Fortalece confiança","Amplia funcionamento diário"],["Não se aproxime de abuso, violência, perigo médico ou situações realmente inseguras.","Para trauma, pânico grave ou alto risco, trabalhe com profissional qualificado."])
  },
  "69b11c0f9b78b21b9c2351f0": {
    en: item("Post-Setback Reset Plan","Recover from a setback without turning it into shame or abandonment of the goal.",["setback","resilience","reset","self-compassion"],steps([["Acknowledge","Describe what happened plainly and without insults."],["Separate","Remind yourself that an event is not your identity."],["Learn briefly","Name one trigger or lesson without prolonged rumination."],["Take one step","Choose the smallest useful next action and do it."]]),["Prevents shame spirals","Builds resilience","Restores momentum"],["A setback does not erase previous progress.","If shame or hopelessness becomes intense or unsafe, seek immediate human support."]),
    he: item("תוכנית איפוס לאחר נסיגה","התאוששו מנסיגה בלי להפוך אותה לבושה או לוויתור על המטרה.",["נסיגה","חוסן","איפוס","חמלה עצמית"],steps([["הכרה","תארו בפשטות מה קרה, בלי עלבונות עצמיים."],["הפרדה","הזכירו לעצמכם שאירוע אינו הזהות שלכם."],["למידה קצרה","זהו גורם אחד או לקח אחד בלי לשקוע בהרהור."],["צעד אחד","בחרו את הפעולה המועילה הקטנה ביותר ובצעו אותה."]]),["מניעת מעגל בושה","בניית חוסן","חידוש תנופה"],["נסיגה אינה מוחקת התקדמות קודמת.","אם הבושה או חוסר התקווה נעשים עזים או לא בטוחים, פנו מיד לתמיכה אנושית."]),
    es: item("Plan de reinicio tras un tropiezo","Recupérate sin convertir un tropiezo en vergüenza o abandono de la meta.",["tropiezo","resiliencia","reinicio","autocompasión"],steps([["Reconoce","Describe lo ocurrido sin insultarte."],["Separa","Recuerda que un hecho no es tu identidad."],["Aprende brevemente","Nombra un desencadenante o aprendizaje sin rumiar."],["Da un paso","Elige la acción útil más pequeña y hazla."]]),["Evita espirales de vergüenza","Desarrolla resiliencia","Recupera impulso"],["Un tropiezo no borra el progreso anterior.","Si vergüenza o desesperanza se vuelven intensas o inseguras, busca apoyo humano inmediato."]),
    fr: item("Plan de reprise après un revers","Reprenez après un revers sans le transformer en honte ni abandon de l’objectif.",["revers","résilience","reprise","autocompassion"],steps([["Reconnaître","Décrivez les faits sans vous insulter."],["Séparer","Rappelez-vous qu’un événement n’est pas votre identité."],["Apprendre brièvement","Nommez un déclencheur ou une leçon sans ruminer."],["Faire un pas","Choisissez la plus petite action utile et faites-la."]]),["Prévient la spirale de honte","Développe la résilience","Relance l’élan"],["Un revers n’efface pas les progrès antérieurs.","Si honte ou désespoir deviennent intenses ou dangereux, cherchez immédiatement un soutien humain."]),
    de: item("Neustart nach einem Rückschlag","Erhole dich, ohne einen Rückschlag in Scham oder Zielaufgabe zu verwandeln.",["Rückschlag","Resilienz","Neustart","Selbstmitgefühl"],steps([["Anerkennen","Beschreibe sachlich, was passiert ist."],["Trennen","Ein Ereignis ist nicht deine Identität."],["Kurz lernen","Benenne einen Auslöser oder eine Lehre ohne Grübeln."],["Ein Schritt","Wähle die kleinste hilfreiche Handlung und tue sie."]]),["Verhindert Schamspiralen","Stärkt Resilienz","Stellt Schwung her"],["Ein Rückschlag löscht Fortschritt nicht.","Bei intensiver oder unsicherer Scham oder Hoffnungslosigkeit sofort menschliche Hilfe suchen."]),
    it: item("Piano di ripresa dopo una battuta d’arresto","Riprenditi senza trasformare l’evento in vergogna o abbandono dell’obiettivo.",["battuta d’arresto","resilienza","ripresa","autocompassione"],steps([["Riconosci","Descrivi l’accaduto senza insultarti."],["Separa","Ricorda che un evento non è la tua identità."],["Impara brevemente","Nomina un fattore o una lezione senza ruminare."],["Un passo","Scegli la più piccola azione utile e falla."]]),["Previene spirali di vergogna","Sviluppa resilienza","Ripristina slancio"],["Una battuta d’arresto non cancella i progressi.","Se vergogna o disperazione diventano intense o pericolose, cerca subito sostegno umano."]),
    pt: item("Plano de retomada após um revés","Recupere-se sem transformar o revés em vergonha ou abandono da meta.",["revés","resiliência","retomada","autocompaixão"],steps([["Reconheça","Descreva o ocorrido sem insultar a si mesmo."],["Separe","Lembre que um evento não é sua identidade."],["Aprenda brevemente","Nomeie um gatilho ou lição sem ruminar."],["Um passo","Escolha a menor ação útil e faça."]]),["Previne espirais de vergonha","Fortalece resiliência","Restaura impulso"],["Um revés não apaga o progresso.","Se vergonha ou desesperança ficarem intensas ou inseguras, busque apoio humano imediato."])
  },
  "69b11c0f9b78b21b9c2351ed": {
    en: item("Self-Compassion Break","Offer yourself mindful, realistic kindness during self-criticism or difficulty.",["self-compassion","shame","kindness","mindfulness"],steps([["Acknowledge","Name the difficulty: this is hard right now."],["Connect","Remember that struggle is part of shared human experience."],["Offer kindness","Use one caring phrase that feels natural and believable."],["Breathe","Take one gentle breath and notice what you need next."]]),["Reduces harsh self-criticism","Builds emotional resilience","Supports recovery"],["You do not need to force belief or immediate relief.","If touch is uncomfortable, omit the hand-on-chest gesture."]),
    he: item("הפסקת חמלה עצמית","הציעו לעצמכם יחס קשוב, מציאותי וטוב ברגעי קושי או ביקורת עצמית.",["חמלה עצמית","בושה","טוב לב","קשיבות"],steps([["הכרה","תנו שם לקושי: קשה לי עכשיו."],["חיבור","זכרו שהתמודדות היא חלק מהחוויה האנושית."],["טוב לב","בחרו משפט אכפתי שמרגיש טבעי ואמין."],["נשימה","קחו נשימה עדינה ושימו לב למה שנחוץ כעת."]]),["הפחתת ביקורת עצמית קשה","בניית חוסן רגשי","תמיכה בהתאוששות"],["אין צורך להכריח אמונה או הקלה מיידית.","אם מגע אינו נעים, ותרו על הנחת יד על החזה."]),
    es: item("Pausa de autocompasión","Ofrécete amabilidad consciente y realista durante la autocrítica o la dificultad.",["autocompasión","vergüenza","amabilidad","atención plena"],steps([["Reconoce","Nombra la dificultad: esto es duro ahora."],["Conecta","Recuerda que luchar forma parte de ser humano."],["Sé amable","Usa una frase afectuosa, natural y creíble."],["Respira","Toma una respiración suave y nota qué necesitas."]]),["Reduce autocrítica dura","Aumenta resiliencia emocional","Apoya recuperación"],["No fuerces creencia ni alivio inmediato.","Si el contacto incomoda, omite la mano en el pecho."]),
    fr: item("Pause d’autocompassion","Offrez-vous une bienveillance attentive et réaliste pendant la difficulté.",["autocompassion","honte","bienveillance","pleine conscience"],steps([["Reconnaître","Nommez la difficulté : c’est dur maintenant."],["Relier","Rappelez-vous que lutter fait partie de l’expérience humaine."],["Être bienveillant","Choisissez une phrase douce, naturelle et crédible."],["Respirer","Prenez un souffle doux et observez votre besoin."]]),["Réduit l’autocritique sévère","Développe la résilience","Soutient la reprise"],["Ne forcez ni conviction ni soulagement immédiat.","Si le toucher gêne, omettez la main sur la poitrine."]),
    de: item("Pause für Selbstmitgefühl","Begegne dir bei Selbstkritik oder Schwierigkeit achtsam und realistisch freundlich.",["Selbstmitgefühl","Scham","Freundlichkeit","Achtsamkeit"],steps([["Anerkennen","Benenne: Das ist gerade schwer."],["Verbinden","Erinnere dich, dass Kämpfen menschlich ist."],["Freundlichkeit","Nutze einen fürsorglichen, glaubwürdigen Satz."],["Atmen","Atme sanft und bemerke, was du jetzt brauchst."]]),["Verringert harte Selbstkritik","Stärkt emotionale Resilienz","Unterstützt Erholung"],["Erzwinge weder Glauben noch sofortige Erleichterung.","Wenn Berührung unangenehm ist, lass die Hand auf der Brust weg."]),
    it: item("Pausa di autocompassione","Offriti gentilezza consapevole e realistica durante autocritica o difficoltà.",["autocompassione","vergogna","gentilezza","consapevolezza"],steps([["Riconosci","Nomina la difficoltà: ora è dura."],["Connettiti","Ricorda che la fatica è parte dell’esperienza umana."],["Offri gentilezza","Usa una frase premurosa, naturale e credibile."],["Respira","Fai un respiro gentile e nota ciò che ti serve."]]),["Riduce autocritica severa","Sviluppa resilienza emotiva","Sostiene il recupero"],["Non forzare convinzione o sollievo immediato.","Se il contatto è scomodo, ometti la mano sul petto."]),
    pt: item("Pausa de autocompaixão","Ofereça a si mesmo gentileza consciente e realista na dificuldade.",["autocompaixão","vergonha","gentileza","atenção plena"],steps([["Reconheça","Nomeie: isto está difícil agora."],["Conecte","Lembre que enfrentar dificuldades é humano."],["Seja gentil","Use uma frase cuidadosa, natural e crível."],["Respire","Respire suavemente e perceba o que precisa."]]),["Reduz autocrítica severa","Fortalece resiliência emocional","Apoia recuperação"],["Não force crença nem alívio imediato.","Se o toque incomodar, omita a mão no peito."])
  },
  "69b11c0f9b78b21b9c2351ef": {
    en: item("Safe Place Visualization","Use gentle imagery to build an internal sense of calm and safety.",["visualization","calm","safety","mindfulness"],steps([["Orient","Stay aware of the room and choose whether to close or soften your eyes."],["Imagine","Picture a real or imagined place that feels calm enough."],["Explore","Notice safe details through sight, sound, texture and temperature."],["Anchor and return","Choose a cue for the place, then return attention slowly to the room."]]),["Builds a calming resource","Reduces overwhelm","Supports emotional settling"],["Stop, open your eyes and orient to the room if imagery increases distress or dissociation.","A calm color or sensation can replace an image; do not force a place to appear."]),
    he: item("דמיון מודרך של מקום בטוח","השתמשו בדמיון עדין כדי לבנות תחושה פנימית של רוגע וביטחון.",["דמיון מודרך","רוגע","ביטחון","קשיבות"],steps([["התמצאות","הישארו מודעים לחדר ובחרו אם לעצום עיניים או לרכך מבט."],["דמיון","דמיינו מקום אמיתי או מומצא שמרגיש רגוע במידה מספקת."],["חקירה","שימו לב לפרטים בטוחים דרך ראייה, קול, מרקם וטמפרטורה."],["עיגון וחזרה","בחרו סימן למקום והחזירו את הקשב לחדר באיטיות."]]),["בניית משאב מרגיע","הפחתת הצפה","תמיכה בהתייצבות רגשית"],["אם הדמיון מגביר מצוקה או ניתוק, עצרו, פקחו עיניים והתמצאו בחדר.","אפשר להשתמש בצבע או בתחושה רגועה במקום תמונה; אין להכריח מקום להופיע."]),
    es: item("Visualización de un lugar seguro","Usa imágenes suaves para crear una sensación interna de calma y seguridad.",["visualización","calma","seguridad","atención plena"],steps([["Oriéntate","Mantente consciente de la habitación y decide si cerrar los ojos."],["Imagina","Visualiza un lugar real o imaginado suficientemente tranquilo."],["Explora","Nota detalles seguros mediante vista, sonido, textura y temperatura."],["Ancla y vuelve","Elige una señal y regresa lentamente a la habitación."]]),["Crea un recurso calmante","Reduce agobio","Favorece regulación emocional"],["Si aumenta angustia o desconexión, detente, abre los ojos y oriéntate.","Puedes usar un color o sensación; no fuerces una imagen."]),
    fr: item("Visualisation d’un lieu sûr","Utilisez une imagerie douce pour créer un sentiment intérieur de calme et de sécurité.",["visualisation","calme","sécurité","pleine conscience"],steps([["S’orienter","Restez conscient de la pièce et choisissez de fermer ou non les yeux."],["Imaginer","Imaginez un lieu réel ou inventé suffisamment calme."],["Explorer","Repérez des détails sûrs par la vue, le son, la texture et la température."],["Ancrer et revenir","Choisissez un repère puis revenez lentement à la pièce."]]),["Crée une ressource apaisante","Réduit la surcharge","Soutient l’apaisement émotionnel"],["Si détresse ou dissociation augmente, arrêtez, ouvrez les yeux et orientez-vous.","Une couleur ou sensation peut remplacer l’image; ne forcez rien."]),
    de: item("Visualisierung eines sicheren Ortes","Nutze sanfte Vorstellung, um ein inneres Gefühl von Ruhe und Sicherheit aufzubauen.",["Visualisierung","Ruhe","Sicherheit","Achtsamkeit"],steps([["Orientieren","Bleibe dir des Raums bewusst und entscheide über offene oder geschlossene Augen."],["Vorstellen","Stelle dir einen realen oder erfundenen, ausreichend ruhigen Ort vor."],["Erkunden","Bemerke sichere Details über Sehen, Hören, Textur und Temperatur."],["Verankern und zurück","Wähle ein Signal und kehre langsam in den Raum zurück."]]),["Schafft eine Beruhigungsressource","Verringert Überforderung","Unterstützt emotionale Stabilisierung"],["Bei mehr Belastung oder Dissoziation stoppen, Augen öffnen und im Raum orientieren.","Farbe oder Empfindung kann ein Bild ersetzen; nichts erzwingen."]),
    it: item("Visualizzazione di un luogo sicuro","Usa immagini delicate per creare una sensazione interna di calma e sicurezza.",["visualizzazione","calma","sicurezza","consapevolezza"],steps([["Orientati","Resta consapevole della stanza e scegli se chiudere gli occhi."],["Immagina","Visualizza un luogo reale o inventato abbastanza tranquillo."],["Esplora","Nota dettagli sicuri con vista, suono, consistenza e temperatura."],["Ancora e ritorna","Scegli un segnale e torna lentamente alla stanza."]]),["Crea una risorsa calmante","Riduce sovraccarico","Sostiene stabilità emotiva"],["Se aumenta disagio o dissociazione, fermati, apri gli occhi e orientati.","Puoi usare un colore o sensazione; non forzare un’immagine."]),
    pt: item("Visualização de um lugar seguro","Use imagens suaves para criar uma sensação interna de calma e segurança.",["visualização","calma","segurança","atenção plena"],steps([["Oriente-se","Mantenha consciência do ambiente e escolha se fecha os olhos."],["Imagine","Visualize um lugar real ou imaginado suficientemente tranquilo."],["Explore","Perceba detalhes seguros por visão, som, textura e temperatura."],["Ancore e retorne","Escolha um sinal e volte lentamente ao ambiente."]]),["Cria recurso calmante","Reduz sobrecarga","Apoia estabilização emocional"],["Se aflição ou dissociação aumentar, pare, abra os olhos e oriente-se.","Uma cor ou sensação pode substituir a imagem; não force."])
  }
};
