const makeContent = (title, description, tags, steps, benefits, tips) => ({
  title, description, tags,
  steps: steps.map(([stepTitle, stepDescription]) => ({ title: stepTitle, description: stepDescription })),
  benefits, tips
});

const EXERCISE_CONTENT_TRANSLATIONS_BATCH_4B_BY_LOCALE = {
  en: {
    'local-sleep-hygiene': makeContent('Sleep Hygiene Routine','Build environmental and behavioral cues that support restful sleep.',['sleep','routine','environment','wellbeing'],[['Begin winding down','Start a predictable wind-down about 60 minutes before bed.'],['Lower stimulation','Dim lights and reduce bright or activating screen use.'],['Watch timing','Avoid late caffeine, nicotine, alcohol, and heavy meals.'],['Choose calm','Use a quiet activity such as reading, stretching, or soft music.'],['Prepare the room','Keep the bedroom dark, quiet, comfortable, and comfortably cool.']],['Supports a consistent sleep rhythm','Reduces late-evening stimulation','Creates a calmer sleep setting'],['Change one or two habits at a time so the routine is sustainable.','Persistent insomnia or loud snoring, gasping, or marked daytime sleepiness deserves clinical assessment.']),
    'local-sleep-progressive-relaxation': makeContent('Progressive Muscle Relaxation for Sleep','Release physical tension by gently tensing and relaxing muscle groups.',['sleep','relaxation','body awareness','stress'],[['Settle','Lie or sit comfortably and take three unforced breaths.'],['Feet and calves','Gently tense for a few seconds, then fully release.'],['Thighs and hips','Tense lightly, notice, and release.'],['Torso','Gently engage abdomen and chest, then soften.'],['Arms and shoulders','Tense hands, arms, and shoulders, then let them drop.'],['Face and jaw','Scrunch very lightly, release the jaw, and notice the whole body.']],['Reduces physical tension','Builds awareness of relaxation','Supports a calm bedtime transition'],['Use gentle effort; skip any painful, injured, cramping, or medically restricted area.','Stop if you feel pain, dizziness, breathing difficulty, or other concerning symptoms.']),
    'local-sleep-worry-time': makeContent('Designated Worry Time','Give worries a planned daytime space so they are less likely to dominate bedtime.',['sleep','worry','planning','anxiety'],[['Choose a time','Set aside about 15 minutes in the early evening, away from bed.'],['Capture worries','Write each worry briefly without solving it immediately.'],['Postpone gently','When worry appears outside the window, note it and return to the present task.'],['Use the window','Review the list and choose one small action where possible.'],['Close on time','Stop when the window ends and shift to a grounding or calming activity.']],['Creates boundaries around rumination','Turns some worries into practical actions','Supports a calmer bedtime'],['The aim is not to eliminate thoughts but to change when you engage with them.','If worry is severe, persistent, or linked to safety concerns, seek qualified support.']),
    'local-relationship-active-listening': makeContent('Active Listening Practice','Listen for understanding and help another person feel accurately heard.',['relationships','listening','communication','empathy'],[['Offer attention','Choose an appropriate moment and reduce distractions.'],['Seek understanding','Listen for meaning, feelings, and needs rather than preparing a reply.'],['Show presence','Use comfortable eye contact and open body language when culturally appropriate.'],['Reflect back','Summarize what you heard and ask whether you understood correctly.'],['Validate','Acknowledge the person’s experience without having to agree with every conclusion.']],['Improves mutual understanding','Reduces avoidable misunderstandings','Builds emotional connection'],['Ask before discussing sensitive topics and respect a request to pause.','Listening does not require accepting disrespect, coercion, or abuse.']),
    'local-relationship-assertive-communication': makeContent('Assertive Communication','Express needs clearly and respectfully while making room for the other person.',['relationships','assertiveness','communication','needs'],[['Clarify your need','Name the specific situation, feeling, or request.'],['Use an I-statement','Describe what you notice, how it affects you, and what you ask for.'],['Rehearse','Practice a brief, calm version without blame or mind-reading.'],['Choose the moment','Speak when both people have enough time and regulation.'],['Listen and negotiate','Hear the response and look for a workable, respectful next step.']],['Makes requests clearer','Supports self-respect and mutual respect','Reduces indirect conflict'],['A request is not a demand; the other person can answer, and you can decide your boundary.','If speaking up could put you at risk, prioritize safety and seek trusted or professional support.']),
    'local-relationship-conflict-resolution': makeContent('Conflict De-escalation','Slow an escalating disagreement and return to safer, more constructive dialogue.',['relationships','conflict','de-escalation','communication'],[['Pause when flooded','Notice rising intensity and call a time-out before continuing.'],['Regulate separately','Use a safe calming strategy without rehearsing attacks.'],['Agree to return','Set a realistic time to resume so the pause is not abandonment.'],['Speak from experience','Use specific I-statements and avoid threats, insults, or absolutes.'],['Find common ground','Name one shared concern or goal.'],['Choose one next step','Agree on a small action and revisit it later.']],['Reduces escalation','Protects the relationship during disagreement','Supports practical problem-solving'],['This exercise is not appropriate during abuse, threats, stalking, or coercive control; prioritize immediate safety and specialist support.','If anyone may be in immediate danger, leave if safe and contact local emergency or domestic-violence services.']),
    'local-relationship-boundary-setting': makeContent('Boundary Setting','Define and communicate the actions you will take to protect your wellbeing and values.',['relationships','boundaries','self-respect','communication'],[['Identify the limit','Name the behavior or situation that is not workable for you.'],['Connect to a value','Clarify what safety, respect, time, or wellbeing the boundary protects.'],['Choose your action','Decide what you will do if the limit is crossed; keep it realistic and within your control.'],['Communicate briefly','State the limit and your action calmly and clearly.'],['Follow through','Act consistently, review the result, and adjust if needed.']],['Clarifies expectations','Supports self-respect and safety','Reduces resentment and confusion'],['A boundary describes your action; it is not a tool to control another person.','In abusive or coercive relationships, direct boundary-setting may increase risk—seek confidential support and a safety plan.'])
  },
  he: {
    'local-sleep-hygiene': makeContent('שגרת היגיינת שינה','בניית רמזים סביבתיים והתנהגותיים התומכים בשינה רגועה.',['שינה','שגרה','סביבה','רווחה'],[['התחילו להאט','התחילו שגרת רגיעה קבועה כ־60 דקות לפני השינה.'],['הפחיתו גירויים','עמעמו אורות וצמצמו מסכים בהירים או מעוררים.'],['שימו לב לתזמון','הימנעו מאוחר מקפאין, ניקוטין, אלכוהול וארוחות כבדות.'],['בחרו רוגע','קראו, התמתחו בעדינות או האזינו למוזיקה שקטה.'],['הכינו את החדר','שמרו על חדר חשוך, שקט, נוח וקריר במידה נעימה.']],['תומכת בקצב שינה עקבי','מפחיתה עוררות בערב','יוצרת סביבת שינה רגועה'],['שנו הרגל אחד או שניים בכל פעם כדי שהשגרה תהיה בת־קיימא.','נדודי שינה מתמשכים, נחירות חזקות, השתנקות או ישנוניות יום בולטת מצדיקים בירור מקצועי.']),
    'local-sleep-progressive-relaxation': makeContent('הרפיית שרירים הדרגתית לשינה','שחרור מתח גופני באמצעות כיווץ עדין והרפיה של קבוצות שרירים.',['שינה','הרפיה','מודעות לגוף','מתח'],[['התמקמו','שכבו או שבו בנוחות וקחו שלוש נשימות לא מאומצות.'],['כפות רגליים ושוקיים','כווצו בעדינות לכמה שניות ואז שחררו לגמרי.'],['ירכיים ואגן','כווצו קלות, שימו לב ושחררו.'],['מרכז הגוף','הפעילו בעדינות בטן וחזה ואז הרפו.'],['זרועות וכתפיים','כווצו ידיים, זרועות וכתפיים ואז הניחו להן לצנוח.'],['פנים ולסת','כווצו קלות מאוד, שחררו לסת והרגישו את הגוף כולו.']],['מפחיתה מתח גופני','מפתחת מודעות להרפיה','תומכת במעבר רגוע לשינה'],['הפעילו כוח עדין ודלגו על אזור כואב, פצוע, מתכווץ או מוגבל רפואית.','עצרו אם מופיעים כאב, סחרחורת, קושי בנשימה או תסמין מדאיג.']),
    'local-sleep-worry-time': makeContent('זמן דאגה מוגדר','מתן מקום מתוכנן לדאגות בשעות היום כדי שיפריעו פחות בזמן השינה.',['שינה','דאגה','תכנון','חרדה'],[['בחרו זמן','הקצו כ־15 דקות בשעות הערב המוקדמות, הרחק מהמיטה.'],['תעדו דאגות','כתבו כל דאגה בקצרה בלי לפתור אותה מיד.'],['דחו בעדינות','כשדאגה עולה מחוץ לזמן, רשמו אותה וחזרו לעיסוק הנוכחי.'],['השתמשו בזמן','עברו על הרשימה ובחרו פעולה קטנה כשאפשר.'],['סיימו בזמן','עצרו בסיום החלון ועברו לפעילות מקרקעת או מרגיעה.']],['יוצר גבולות להעלאת מחשבות חוזרת','הופך חלק מהדאגות לצעדים מעשיים','תומך בערב רגוע'],['המטרה אינה למחוק מחשבות אלא לשנות מתי עוסקים בהן.','אם הדאגה קשה, מתמשכת או קשורה לסכנה, פנו לתמיכה מוסמכת.']),
    'local-relationship-active-listening': makeContent('תרגול הקשבה פעילה','הקשבה לשם הבנה וסיוע לאדם אחר להרגיש שנשמע במדויק.',['יחסים','הקשבה','תקשורת','אמפתיה'],[['הציעו תשומת לב','בחרו זמן מתאים וצמצמו הסחות.'],['חפשו להבין','הקשיבו למשמעות, לרגשות ולצרכים במקום להכין תשובה.'],['הראו נוכחות','השתמשו בקשר עין נוח ובשפת גוף פתוחה כשמתאים תרבותית.'],['שקפו','סכמו מה שמעתם ושאלו אם הבנתם נכון.'],['תנו תוקף','הכירו בחוויה בלי להסכים בהכרח לכל מסקנה.']],['משפר הבנה הדדית','מפחית אי־הבנות','בונה קרבה רגשית'],['בקשו רשות לפני נושא רגיש וכבדו בקשה לעצור.','הקשבה אינה מחייבת לקבל חוסר כבוד, כפייה או התעללות.']),
    'local-relationship-assertive-communication': makeContent('תקשורת אסרטיבית','ביטוי צרכים באופן ברור ומכבד תוך מתן מקום לאדם האחר.',['יחסים','אסרטיביות','תקשורת','צרכים'],[['הבהירו צורך','תנו שם למצב, לרגש או לבקשה המסוימים.'],['השתמשו במשפט אני','תארו מה שמתם לב, כיצד זה משפיע ומה אתם מבקשים.'],['תרגלו','נסחו גרסה קצרה ורגועה בלי האשמה או קריאת מחשבות.'],['בחרו זמן','דברו כשיש לשני הצדדים זמן ויכולת ויסות.'],['הקשיבו והידברו','שמעו את התגובה וחפשו צעד מכבד וישים.']],['מבהירה בקשות','תומכת בכבוד עצמי והדדי','מפחיתה עימות עקיף'],['בקשה אינה דרישה; האחר רשאי להשיב ואתם רשאים לקבוע את הגבול שלכם.','אם ביטוי הצורך עלול לסכן אתכם, העדיפו בטיחות ופנו לתמיכה אמינה או מקצועית.']),
    'local-relationship-conflict-resolution': makeContent('הפחתת הסלמה בקונפליקט','האטת ויכוח שמסלים וחזרה לשיח בטוח ומועיל יותר.',['יחסים','קונפליקט','הפחתת הסלמה','תקשורת'],[['עצרו בהצפה','זהו עלייה בעוצמה ובקשו פסק זמן לפני המשך.'],['התאזנו בנפרד','השתמשו בדרך הרגעה בטוחה בלי לשנן התקפות.'],['סכמו לחזור','קבעו זמן מציאותי להמשך כדי שההפסקה לא תהיה נטישה.'],['דברו מהחוויה','השתמשו במשפטי אני מסוימים והימנעו מאיומים, עלבונות והכללות.'],['מצאו מכנה משותף','תנו שם לדאגה או מטרה משותפת אחת.'],['בחרו צעד','סכמו פעולה קטנה וחזרו לבחון אותה בהמשך.']],['מפחיתה הסלמה','מגינה על הקשר בזמן מחלוקת','תומכת בפתרון מעשי'],['התרגיל אינו מתאים בזמן התעללות, איומים, מעקב או שליטה כפייתית; העדיפו בטיחות ותמיכה ייעודית.','אם קיימת סכנה מיידית, צאו אם בטוח ופנו לשירותי החירום או הסיוע המקומיים.']),
    'local-relationship-boundary-setting': makeContent('הצבת גבולות','הגדרה ותקשורת של הפעולות שתנקטו כדי להגן על הרווחה והערכים שלכם.',['יחסים','גבולות','כבוד עצמי','תקשורת'],[['זהו את הגבול','תנו שם להתנהגות או למצב שאינם מתאימים לכם.'],['חברו לערך','הבהירו איזו בטיחות, כבוד, זמן או רווחה הגבול מגן עליהם.'],['בחרו פעולה','החליטו מה תעשו אם הגבול נחצה; שמרו זאת מציאותי ובשליטתכם.'],['תקשרו בקצרה','אמרו את הגבול ואת פעולתכם ברוגע ובבהירות.'],['פעלו בעקביות','בצעו, בדקו את התוצאה והתאימו לפי הצורך.']],['מבהירה ציפיות','תומכת בכבוד עצמי ובטיחות','מפחיתה טינה ובלבול'],['גבול מתאר את הפעולה שלכם ואינו כלי לשליטה באדם אחר.','בקשר מתעלל או כפייתי הצבה ישירה עלולה להגדיל סיכון—פנו בסודיות לתמיכה ולתוכנית בטיחות.'])
  },
  es: {
    'local-sleep-hygiene': makeContent('Rutina de higiene del sueño','Crea señales ambientales y conductuales que favorezcan el descanso.',['sueño','rutina','entorno','bienestar'],[['Empieza a desacelerar','Inicia una rutina predecible unos 60 minutos antes.'],['Reduce estímulos','Atenúa luces y limita pantallas brillantes o activadoras.'],['Cuida el horario','Evita tarde cafeína, nicotina, alcohol y comidas pesadas.'],['Elige calma','Lee, estira suavemente o escucha música tranquila.'],['Prepara la habitación','Mantén un espacio oscuro, silencioso, cómodo y fresco.']],['Favorece un ritmo constante','Reduce estimulación nocturna','Crea un entorno más calmado'],['Cambia uno o dos hábitos cada vez.','Insomnio persistente, ronquidos fuertes, jadeos o mucha somnolencia diurna requieren evaluación clínica.']),
    'local-sleep-progressive-relaxation': makeContent('Relajación muscular progresiva para dormir','Libera tensión al contraer y relajar suavemente grupos musculares.',['sueño','relajación','conciencia corporal','estrés'],[['Acomódate','Túmbate o siéntate y toma tres respiraciones sin esfuerzo.'],['Pies y pantorrillas','Tensa suavemente unos segundos y suelta.'],['Muslos y caderas','Tensa ligeramente, nota y relaja.'],['Torso','Activa suavemente abdomen y pecho y suelta.'],['Brazos y hombros','Tensa manos, brazos y hombros y déjalos caer.'],['Cara y mandíbula','Contrae muy levemente, suelta la mandíbula y nota todo el cuerpo.']],['Reduce tensión física','Aumenta conciencia de relajación','Facilita la transición al sueño'],['Usa poca fuerza y omite zonas doloridas, lesionadas o restringidas.','Detente ante dolor, mareo, dificultad respiratoria u otro síntoma preocupante.']),
    'local-sleep-worry-time': makeContent('Tiempo designado para preocuparse','Da a las preocupaciones un espacio diurno planificado.',['sueño','preocupación','planificación','ansiedad'],[['Elige una hora','Reserva unos 15 minutos temprano por la noche y lejos de la cama.'],['Anota preocupaciones','Escribe cada una sin resolverla de inmediato.'],['Pospón con suavidad','Fuera del horario, anótala y vuelve a la tarea presente.'],['Usa el tiempo','Revisa y elige una pequeña acción posible.'],['Cierra a tiempo','Al terminar, cambia a una actividad calmante o de anclaje.']],['Pone límites a la rumiación','Convierte preocupaciones en acciones','Favorece una noche tranquila'],['No busca eliminar pensamientos, sino cambiar cuándo atenderlos.','Busca apoyo si la preocupación es intensa, persistente o de seguridad.']),
    'local-relationship-active-listening': makeContent('Práctica de escucha activa','Escucha para comprender y ayudar a la otra persona a sentirse oída.',['relaciones','escucha','comunicación','empatía'],[['Ofrece atención','Elige un momento apropiado y reduce distracciones.'],['Busca comprender','Escucha significado, emociones y necesidades.'],['Muestra presencia','Usa contacto visual cómodo y postura abierta cuando sea apropiado.'],['Refleja','Resume y pregunta si entendiste correctamente.'],['Valida','Reconoce la experiencia sin tener que aceptar cada conclusión.']],['Mejora comprensión mutua','Reduce malentendidos','Fortalece conexión'],['Pide permiso antes de temas sensibles y respeta una pausa.','Escuchar no exige aceptar falta de respeto, coerción o abuso.']),
    'local-relationship-assertive-communication': makeContent('Comunicación asertiva','Expresa necesidades con claridad y respeto.',['relaciones','asertividad','comunicación','necesidades'],[['Aclara tu necesidad','Nombra situación, emoción o petición concreta.'],['Usa un mensaje yo','Describe lo que observas, su efecto y tu petición.'],['Ensaya','Practica una versión breve sin culpa ni suposiciones.'],['Elige el momento','Habla cuando ambos tengan tiempo y regulación.'],['Escucha y negocia','Oye la respuesta y busca un paso respetuoso.']],['Aclara peticiones','Apoya respeto propio y mutuo','Reduce conflicto indirecto'],['Una petición no es una exigencia; puedes decidir tu límite.','Si hablar puede ponerte en riesgo, prioriza seguridad y busca apoyo.']),
    'local-relationship-conflict-resolution': makeContent('Desescalada de conflictos','Frena una discusión creciente y vuelve a un diálogo más seguro.',['relaciones','conflicto','desescalada','comunicación'],[['Pausa al desbordarte','Nota la intensidad y pide un tiempo fuera.'],['Regúlate aparte','Usa una estrategia segura sin ensayar ataques.'],['Acuerda volver','Fija una hora realista para retomar.'],['Habla desde tu experiencia','Usa mensajes yo y evita amenazas e insultos.'],['Busca terreno común','Nombra una preocupación compartida.'],['Elige un paso','Acuerda una acción pequeña y revísala después.']],['Reduce escalada','Protege la relación','Apoya soluciones prácticas'],['No usar ante abuso, amenazas, acoso o control coercitivo; prioriza seguridad y apoyo especializado.','Ante peligro inmediato, sal si es seguro y contacta emergencias o servicios locales de violencia doméstica.']),
    'local-relationship-boundary-setting': makeContent('Establecimiento de límites','Define y comunica acciones para proteger tu bienestar y valores.',['relaciones','límites','autorrespeto','comunicación'],[['Identifica el límite','Nombra la conducta o situación que no te resulta viable.'],['Conecta con un valor','Aclara qué seguridad, respeto, tiempo o bienestar protege.'],['Elige tu acción','Decide qué harás si se cruza; que sea realista y bajo tu control.'],['Comunica brevemente','Expón límite y acción con calma.'],['Cumple','Actúa con coherencia y revisa el resultado.']],['Aclara expectativas','Apoya autorrespeto y seguridad','Reduce resentimiento'],['Un límite describe tu acción, no controla a otra persona.','En relaciones abusivas, ponerlo directamente puede aumentar el riesgo; busca apoyo confidencial y un plan de seguridad.'])
  },
  fr: {
    'local-sleep-hygiene': makeContent('Routine d’hygiène du sommeil','Créez des repères favorisant un sommeil réparateur.',['sommeil','routine','environnement','bien-être'],[['Ralentissez','Commencez une routine environ 60 minutes avant le coucher.'],['Réduisez les stimulations','Tamisez les lumières et limitez les écrans stimulants.'],['Surveillez l’horaire','Évitez tard caféine, nicotine, alcool et repas lourds.'],['Choisissez le calme','Lisez, étirez-vous doucement ou écoutez une musique calme.'],['Préparez la chambre','Gardez-la sombre, calme, confortable et fraîche.']],['Soutient un rythme régulier','Réduit la stimulation tardive','Crée un cadre apaisant'],['Changez une ou deux habitudes à la fois.','Insomnie persistante, ronflements, halètements ou forte somnolence diurne nécessitent un avis clinique.']),
    'local-sleep-progressive-relaxation': makeContent('Relaxation musculaire progressive pour dormir','Relâchez les tensions en contractant puis détendant doucement les muscles.',['sommeil','relaxation','conscience corporelle','stress'],[['Installez-vous','Allongez-vous ou asseyez-vous et prenez trois respirations naturelles.'],['Pieds et mollets','Contractez doucement quelques secondes puis relâchez.'],['Cuisses et hanches','Contractez légèrement, observez et relâchez.'],['Torse','Engagez doucement ventre et poitrine puis détendez.'],['Bras et épaules','Contractez puis laissez retomber.'],['Visage et mâchoire','Contractez très légèrement, relâchez la mâchoire et observez le corps.']],['Réduit la tension physique','Développe la perception du relâchement','Facilite la transition vers le sommeil'],['Restez doux et sautez toute zone douloureuse, blessée ou contre-indiquée.','Arrêtez en cas de douleur, vertige, difficulté respiratoire ou symptôme inquiétant.']),
    'local-sleep-worry-time': makeContent('Temps réservé aux inquiétudes','Donnez aux soucis un espace planifié en journée.',['sommeil','inquiétude','planification','anxiété'],[['Choisissez un moment','Réservez environ 15 minutes en début de soirée, loin du lit.'],['Notez les soucis','Écrivez-les brièvement sans résoudre tout de suite.'],['Reportez doucement','En dehors du créneau, notez puis revenez à la tâche.'],['Utilisez le créneau','Relisez et choisissez une petite action possible.'],['Clôturez à l’heure','À la fin, passez à une activité apaisante.']],['Limite la rumination','Transforme certains soucis en actions','Favorise un coucher plus calme'],['Le but est de changer le moment d’engagement, pas de supprimer les pensées.','Cherchez du soutien si l’inquiétude est sévère, persistante ou liée à la sécurité.']),
    'local-relationship-active-listening': makeContent('Pratique de l’écoute active','Écoutez pour comprendre et aider l’autre à se sentir entendu.',['relations','écoute','communication','empathie'],[['Offrez votre attention','Choisissez un moment adapté et réduisez les distractions.'],['Cherchez à comprendre','Écoutez sens, émotions et besoins.'],['Montrez votre présence','Utilisez regard confortable et posture ouverte si approprié.'],['Reformulez','Résumez et vérifiez votre compréhension.'],['Validez','Reconnaissez l’expérience sans accepter chaque conclusion.']],['Améliore la compréhension','Réduit les malentendus','Renforce le lien'],['Demandez avant un sujet sensible et respectez une pause.','Écouter n’oblige pas à accepter irrespect, coercition ou abus.']),
    'local-relationship-assertive-communication': makeContent('Communication assertive','Exprimez vos besoins clairement et respectueusement.',['relations','assertivité','communication','besoins'],[['Clarifiez le besoin','Nommez situation, émotion ou demande précise.'],['Parlez en je','Décrivez observation, effet et demande.'],['Répétez','Préparez une version brève sans accusation.'],['Choisissez le moment','Parlez quand chacun a du temps et du calme.'],['Écoutez et négociez','Entendez la réponse et cherchez une étape respectueuse.']],['Clarifie les demandes','Soutient le respect mutuel','Réduit le conflit indirect'],['Une demande n’est pas une exigence; vous pouvez choisir votre limite.','Si parler vous met en danger, privilégiez la sécurité et cherchez du soutien.']),
    'local-relationship-conflict-resolution': makeContent('Désescalade du conflit','Ralentissez un désaccord qui monte et revenez à un dialogue plus sûr.',['relations','conflit','désescalade','communication'],[['Faites une pause','Repérez l’intensité et demandez un temps mort.'],['Régulez-vous séparément','Apaisez-vous sans préparer d’attaques.'],['Convenez de reprendre','Fixez un moment réaliste.'],['Parlez de votre vécu','Utilisez le je et évitez menaces et insultes.'],['Trouvez un point commun','Nommez une préoccupation partagée.'],['Choisissez une étape','Convenez d’une petite action.']],['Réduit l’escalade','Protège la relation','Favorise les solutions'],['Inadapté en cas d’abus, menaces, harcèlement ou contrôle coercitif; priorité à la sécurité et au soutien spécialisé.','En danger immédiat, partez si possible et contactez les urgences ou services locaux spécialisés.']),
    'local-relationship-boundary-setting': makeContent('Pose de limites','Définissez les actions qui protègent votre bien-être et vos valeurs.',['relations','limites','respect de soi','communication'],[['Identifiez la limite','Nommez le comportement non acceptable pour vous.'],['Reliez à une valeur','Précisez ce qu’elle protège.'],['Choisissez votre action','Décidez ce que vous ferez; restez réaliste et dans votre contrôle.'],['Communiquez brièvement','Énoncez limite et action calmement.'],['Tenez la limite','Agissez avec cohérence et réévaluez.']],['Clarifie les attentes','Soutient respect et sécurité','Réduit ressentiment et confusion'],['Une limite décrit votre action et ne contrôle pas autrui.','Dans une relation abusive, la poser directement peut augmenter le risque; cherchez un soutien confidentiel et un plan de sécurité.'])
  },
  de: {
    'local-sleep-hygiene': makeContent('Schlafhygiene-Routine','Schaffen Sie Verhaltens- und Umweltsignale für erholsamen Schlaf.',['Schlaf','Routine','Umgebung','Wohlbefinden'],[['Herunterfahren','Etwa 60 Minuten vorher eine feste Abendroutine beginnen.'],['Reize senken','Licht dimmen und aktivierende Bildschirme reduzieren.'],['Timing beachten','Spät Koffein, Nikotin, Alkohol und schwere Mahlzeiten meiden.'],['Ruhe wählen','Lesen, sanft dehnen oder ruhige Musik hören.'],['Raum vorbereiten','Dunkel, ruhig, bequem und angenehm kühl halten.']],['Fördert Regelmäßigkeit','Senkt abendliche Aktivierung','Schafft ruhige Umgebung'],['Jeweils ein bis zwei Gewohnheiten ändern.','Anhaltende Insomnie, lautes Schnarchen, Luftschnappen oder starke Tagesschläfrigkeit klinisch abklären.']),
    'local-sleep-progressive-relaxation': makeContent('Progressive Muskelentspannung für den Schlaf','Lösen Sie Spannung durch sanftes An- und Entspannen.',['Schlaf','Entspannung','Körperwahrnehmung','Stress'],[['Bequem werden','Liegen oder sitzen und dreimal ungezwungen atmen.'],['Füße und Waden','Kurz sanft anspannen und lösen.'],['Oberschenkel und Hüften','Leicht anspannen, wahrnehmen, lösen.'],['Rumpf','Bauch und Brust sanft aktivieren und lösen.'],['Arme und Schultern','Anspannen und fallen lassen.'],['Gesicht und Kiefer','Sehr leicht anspannen, Kiefer lösen, ganzen Körper spüren.']],['Senkt körperliche Spannung','Stärkt Entspannungswahrnehmung','Erleichtert den Übergang zum Schlaf'],['Sanft üben und schmerzhafte, verletzte oder medizinisch eingeschränkte Bereiche auslassen.','Bei Schmerz, Schwindel, Atemnot oder Warnzeichen abbrechen.']),
    'local-sleep-worry-time': makeContent('Festgelegte Sorgenzeit','Geben Sie Sorgen tagsüber einen geplanten Raum.',['Schlaf','Sorgen','Planung','Angst'],[['Zeit wählen','Früh abends etwa 15 Minuten fern vom Bett reservieren.'],['Sorgen erfassen','Kurz notieren, ohne sofort alles zu lösen.'],['Sanft verschieben','Außerhalb notieren und zur aktuellen Aufgabe zurückkehren.'],['Zeit nutzen','Liste prüfen und eine kleine Handlung wählen.'],['Pünktlich schließen','Danach zu einer beruhigenden Aktivität wechseln.']],['Begrenzt Grübeln','Macht Sorgen teils handlungsorientiert','Fördert ruhigen Abend'],['Ziel ist ein anderer Umgangszeitpunkt, nicht Gedanken zu löschen.','Bei starken, anhaltenden oder sicherheitsbezogenen Sorgen Hilfe suchen.']),
    'local-relationship-active-listening': makeContent('Aktives Zuhören üben','Hören Sie zu, um zu verstehen und korrektes Gehörtwerden zu fördern.',['Beziehungen','Zuhören','Kommunikation','Empathie'],[['Aufmerksamkeit anbieten','Geeigneten Moment wählen und Ablenkung senken.'],['Verstehen suchen','Auf Bedeutung, Gefühle und Bedürfnisse hören.'],['Präsenz zeigen','Passenden Blickkontakt und offene Haltung nutzen.'],['Spiegeln','Zusammenfassen und Verständnis prüfen.'],['Validieren','Erfahrung anerkennen, ohne jeder Schlussfolgerung zuzustimmen.']],['Verbessert Verständnis','Verringert Missverständnisse','Stärkt Verbindung'],['Vor sensiblen Themen fragen und Pausen respektieren.','Zuhören bedeutet nicht, Respektlosigkeit, Zwang oder Missbrauch hinzunehmen.']),
    'local-relationship-assertive-communication': makeContent('Selbstsichere Kommunikation','Bedürfnisse klar und respektvoll ausdrücken.',['Beziehungen','Assertivität','Kommunikation','Bedürfnisse'],[['Bedürfnis klären','Konkrete Situation, Gefühl oder Bitte benennen.'],['Ich-Botschaft nutzen','Beobachtung, Wirkung und Bitte beschreiben.'],['Proben','Kurz und ruhig ohne Schuldzuweisung formulieren.'],['Moment wählen','Sprechen, wenn beide Zeit und Ruhe haben.'],['Zuhören und verhandeln','Antwort hören und respektvollen Schritt suchen.']],['Macht Bitten klarer','Stärkt Selbst- und gegenseitigen Respekt','Senkt indirekten Konflikt'],['Eine Bitte ist keine Forderung; Sie können Ihre Grenze wählen.','Wenn Ansprechen riskant ist, Sicherheit priorisieren und Hilfe suchen.']),
    'local-relationship-conflict-resolution': makeContent('Konfliktdeeskalation','Bremsen Sie einen eskalierenden Streit und kehren Sie zu sichererem Dialog zurück.',['Beziehungen','Konflikt','Deeskalation','Kommunikation'],[['Bei Überflutung pausieren','Steigende Intensität erkennen und Auszeit nehmen.'],['Getrennt regulieren','Sicher beruhigen, ohne Angriffe vorzubereiten.'],['Rückkehr vereinbaren','Realistischen Zeitpunkt festlegen.'],['Aus Erfahrung sprechen','Ich-Botschaften nutzen, Drohungen und Beleidigungen meiden.'],['Gemeinsames finden','Ein geteiltes Anliegen nennen.'],['Schritt wählen','Eine kleine Handlung vereinbaren.']],['Senkt Eskalation','Schützt die Beziehung','Fördert praktische Lösungen'],['Nicht bei Missbrauch, Drohungen, Stalking oder Zwangskontrolle; Sicherheit und Fachhilfe priorisieren.','Bei unmittelbarer Gefahr, wenn sicher, gehen und Notruf oder lokale Gewaltschutzstelle kontaktieren.']),
    'local-relationship-boundary-setting': makeContent('Grenzen setzen','Definieren Sie Handlungen zum Schutz von Wohlbefinden und Werten.',['Beziehungen','Grenzen','Selbstachtung','Kommunikation'],[['Grenze erkennen','Nicht tragbares Verhalten benennen.'],['Mit Wert verbinden','Klären, welche Sicherheit, Achtung, Zeit oder Gesundheit geschützt wird.'],['Handlung wählen','Entscheiden, was Sie tun; realistisch und kontrollierbar.'],['Kurz mitteilen','Grenze und Handlung ruhig nennen.'],['Umsetzen','Konsequent handeln und Ergebnis prüfen.']],['Klärt Erwartungen','Stärkt Selbstachtung und Sicherheit','Verringert Groll'],['Eine Grenze beschreibt Ihre Handlung, nicht die Kontrolle anderer.','In missbräuchlichen Beziehungen kann direkte Grenzsetzung Risiko erhöhen; vertrauliche Hilfe und Sicherheitsplan suchen.'])
  },
  it: {
    'local-sleep-hygiene': makeContent('Routine di igiene del sonno','Crea segnali ambientali e comportamentali che favoriscono il riposo.',['sonno','routine','ambiente','benessere'],[['Rallenta','Inizia una routine prevedibile circa 60 minuti prima.'],['Riduci stimoli','Abbassa le luci e limita schermi attivanti.'],['Cura i tempi','Evita tardi caffeina, nicotina, alcol e pasti pesanti.'],['Scegli calma','Leggi, fai stretching dolce o ascolta musica tranquilla.'],['Prepara la stanza','Tienila buia, silenziosa, comoda e fresca.']],['Sostiene un ritmo costante','Riduce stimolazione serale','Crea un ambiente tranquillo'],['Cambia una o due abitudini alla volta.','Insonnia persistente, russamento forte, respiro affannoso o sonnolenza diurna richiedono valutazione clinica.']),
    'local-sleep-progressive-relaxation': makeContent('Rilassamento muscolare progressivo per il sonno','Rilascia tensione contraendo e rilassando dolcemente i muscoli.',['sonno','rilassamento','consapevolezza corporea','stress'],[['Sistemati','Sdraiati o siediti e fai tre respiri naturali.'],['Piedi e polpacci','Contrai dolcemente per pochi secondi e rilascia.'],['Cosce e anche','Contrai leggermente, nota e rilascia.'],['Torso','Attiva dolcemente addome e petto, poi ammorbidisci.'],['Braccia e spalle','Contrai e lascia cadere.'],['Viso e mandibola','Contrai appena, rilascia la mandibola e nota il corpo.']],['Riduce tensione fisica','Aumenta consapevolezza del rilassamento','Favorisce il passaggio al sonno'],['Usa poco sforzo e salta aree dolorose, lese o limitate.','Fermati per dolore, vertigine, difficoltà respiratoria o sintomi preoccupanti.']),
    'local-sleep-worry-time': makeContent('Tempo dedicato alle preoccupazioni','Dai alle preoccupazioni uno spazio diurno pianificato.',['sonno','preoccupazione','pianificazione','ansia'],[['Scegli un orario','Dedica circa 15 minuti a inizio serata, lontano dal letto.'],['Annota','Scrivi ogni preoccupazione senza risolverla subito.'],['Rimanda con gentilezza','Fuori orario, annota e torna al compito.'],['Usa il tempo','Rivedi e scegli una piccola azione.'],['Chiudi in orario','Passa poi a un’attività calmante.']],['Pone limiti alla ruminazione','Trasforma alcune preoccupazioni in azioni','Favorisce una sera calma'],['Non elimina i pensieri, cambia quando li affronti.','Cerca aiuto per preoccupazione grave, persistente o legata alla sicurezza.']),
    'local-relationship-active-listening': makeContent('Pratica di ascolto attivo','Ascolta per comprendere e far sentire l’altra persona accuratamente ascoltata.',['relazioni','ascolto','comunicazione','empatia'],[['Offri attenzione','Scegli un momento adatto e riduci distrazioni.'],['Cerca di capire','Ascolta significato, emozioni e bisogni.'],['Mostra presenza','Usa contatto visivo comodo e postura aperta se appropriato.'],['Rifletti','Riassumi e verifica la comprensione.'],['Valida','Riconosci l’esperienza senza accettare ogni conclusione.']],['Migliora la comprensione','Riduce equivoci','Rafforza la connessione'],['Chiedi prima di temi sensibili e rispetta una pausa.','Ascoltare non richiede accettare mancanza di rispetto, coercizione o abuso.']),
    'local-relationship-assertive-communication': makeContent('Comunicazione assertiva','Esprimi bisogni con chiarezza e rispetto.',['relazioni','assertività','comunicazione','bisogni'],[['Chiarisci il bisogno','Nomina situazione, emozione o richiesta.'],['Usa un messaggio io','Descrivi osservazione, effetto e richiesta.'],['Prova','Prepara una versione breve senza colpa.'],['Scegli il momento','Parla quando entrambi avete tempo e calma.'],['Ascolta e negozia','Ascolta la risposta e cerca un passo rispettoso.']],['Chiarisce le richieste','Sostiene rispetto reciproco','Riduce conflitto indiretto'],['Una richiesta non è una pretesa; puoi decidere il tuo confine.','Se parlare può metterti a rischio, privilegia sicurezza e supporto.']),
    'local-relationship-conflict-resolution': makeContent('De-escalation del conflitto','Rallenta un disaccordo crescente e torna a un dialogo più sicuro.',['relazioni','conflitto','de-escalation','comunicazione'],[['Fai pausa','Nota l’intensità e chiedi una pausa.'],['Regolati separatamente','Calmati senza preparare attacchi.'],['Concorda il ritorno','Fissa un momento realistico.'],['Parla dall’esperienza','Usa messaggi io ed evita minacce e insulti.'],['Trova un punto comune','Nomina una preoccupazione condivisa.'],['Scegli un passo','Concorda una piccola azione.']],['Riduce escalation','Protegge la relazione','Favorisce soluzioni pratiche'],['Non adatto con abuso, minacce, stalking o controllo coercitivo; priorità a sicurezza e supporto specialistico.','In pericolo immediato, allontanati se sicuro e contatta emergenze o servizi locali antiviolenza.']),
    'local-relationship-boundary-setting': makeContent('Definizione dei confini','Definisci azioni per proteggere benessere e valori.',['relazioni','confini','rispetto di sé','comunicazione'],[['Identifica il limite','Nomina il comportamento non sostenibile.'],['Collega a un valore','Chiarisci cosa protegge.'],['Scegli la tua azione','Decidi cosa farai, in modo realistico e sotto il tuo controllo.'],['Comunica brevemente','Esponi limite e azione con calma.'],['Mantieni','Agisci con coerenza e rivedi il risultato.']],['Chiarisce aspettative','Sostiene rispetto e sicurezza','Riduce risentimento'],['Un confine descrive la tua azione, non controlla altri.','In relazioni abusive, dichiararlo direttamente può aumentare il rischio; cerca supporto riservato e un piano di sicurezza.'])
  },
  pt: {
    'local-sleep-hygiene': makeContent('Rotina de higiene do sono','Crie sinais ambientais e comportamentais que apoiem o descanso.',['sono','rotina','ambiente','bem-estar'],[['Comece a desacelerar','Inicie rotina previsível cerca de 60 minutos antes.'],['Reduza estímulos','Diminua luzes e telas estimulantes.'],['Cuide do horário','Evite tarde cafeína, nicotina, álcool e refeições pesadas.'],['Escolha calma','Leia, alongue suavemente ou ouça música calma.'],['Prepare o quarto','Mantenha-o escuro, silencioso, confortável e fresco.']],['Apoia ritmo consistente','Reduz estímulo noturno','Cria ambiente tranquilo'],['Mude um ou dois hábitos por vez.','Insônia persistente, ronco alto, engasgos ou muita sonolência diurna pedem avaliação clínica.']),
    'local-sleep-progressive-relaxation': makeContent('Relaxamento muscular progressivo para dormir','Libere tensão contraindo e relaxando suavemente grupos musculares.',['sono','relaxamento','consciência corporal','estresse'],[['Acomode-se','Deite ou sente e faça três respirações naturais.'],['Pés e panturrilhas','Contraia suavemente por segundos e solte.'],['Coxas e quadris','Contraia levemente, note e relaxe.'],['Tronco','Ative suavemente abdômen e peito e solte.'],['Braços e ombros','Contraia e deixe cair.'],['Rosto e mandíbula','Contraia muito levemente, solte a mandíbula e note o corpo.']],['Reduz tensão física','Aumenta percepção do relaxamento','Favorece transição para o sono'],['Use esforço suave e pule áreas doloridas, lesionadas ou restritas.','Pare diante de dor, tontura, dificuldade respiratória ou sintoma preocupante.']),
    'local-sleep-worry-time': makeContent('Horário reservado para preocupações','Dê às preocupações um espaço diurno planejado.',['sono','preocupação','planejamento','ansiedade'],[['Escolha um horário','Reserve cerca de 15 minutos no início da noite, longe da cama.'],['Registre','Escreva cada preocupação sem resolver imediatamente.'],['Adie com gentileza','Fora do horário, anote e volte à tarefa.'],['Use o período','Revise e escolha uma pequena ação.'],['Encerre na hora','Depois, passe a uma atividade calmante.']],['Limita ruminação','Transforma preocupações em ações','Apoia noite mais calma'],['Não elimina pensamentos; muda quando você se envolve com eles.','Busque apoio para preocupação grave, persistente ou ligada à segurança.']),
    'local-relationship-active-listening': makeContent('Prática de escuta ativa','Escute para compreender e ajudar a outra pessoa a se sentir ouvida.',['relacionamentos','escuta','comunicação','empatia'],[['Ofereça atenção','Escolha momento adequado e reduza distrações.'],['Busque compreender','Escute significado, emoções e necessidades.'],['Mostre presença','Use contato visual confortável e postura aberta quando apropriado.'],['Reflita','Resuma e confira se entendeu.'],['Valide','Reconheça a experiência sem concordar com toda conclusão.']],['Melhora compreensão','Reduz mal-entendidos','Fortalece conexão'],['Pergunte antes de temas sensíveis e respeite uma pausa.','Escutar não exige aceitar desrespeito, coerção ou abuso.']),
    'local-relationship-assertive-communication': makeContent('Comunicação assertiva','Expresse necessidades com clareza e respeito.',['relacionamentos','assertividade','comunicação','necessidades'],[['Esclareça a necessidade','Nomeie situação, emoção ou pedido específico.'],['Use uma frase eu','Descreva observação, impacto e pedido.'],['Ensaie','Pratique versão breve sem culpa.'],['Escolha o momento','Fale quando ambos tiverem tempo e calma.'],['Escute e negocie','Ouça e procure um passo respeitoso.']],['Esclarece pedidos','Apoia respeito mútuo','Reduz conflito indireto'],['Pedido não é exigência; você pode decidir seu limite.','Se falar trouxer risco, priorize segurança e busque apoio.']),
    'local-relationship-conflict-resolution': makeContent('Desescalada de conflitos','Diminua um desacordo crescente e volte a diálogo mais seguro.',['relacionamentos','conflito','desescalada','comunicação'],[['Pause','Note a intensidade e peça um intervalo.'],['Regule-se separadamente','Acalme-se sem preparar ataques.'],['Combine retorno','Defina horário realista.'],['Fale da experiência','Use frases eu e evite ameaças e insultos.'],['Ache algo comum','Nomeie uma preocupação compartilhada.'],['Escolha um passo','Combine pequena ação.']],['Reduz escalada','Protege a relação','Apoia soluções práticas'],['Não usar com abuso, ameaças, perseguição ou controle coercitivo; priorize segurança e apoio especializado.','Em perigo imediato, saia se seguro e contate emergência ou serviço local de violência doméstica.']),
    'local-relationship-boundary-setting': makeContent('Definição de limites','Defina ações para proteger bem-estar e valores.',['relacionamentos','limites','autorrespeito','comunicação'],[['Identifique o limite','Nomeie comportamento ou situação inviável.'],['Ligue a um valor','Esclareça o que ele protege.'],['Escolha sua ação','Decida o que fará, de modo realista e sob seu controle.'],['Comunique brevemente','Diga limite e ação com calma.'],['Cumpra','Aja com consistência e reveja o resultado.']],['Esclarece expectativas','Apoia respeito e segurança','Reduz ressentimento'],['Limite descreve sua ação, não controla outra pessoa.','Em relações abusivas, declarar limites diretamente pode aumentar risco; busque apoio confidencial e plano de segurança.'])
  }
};

export const EXERCISE_CONTENT_TRANSLATIONS_BATCH_4B = Object.fromEntries(
  Object.keys(EXERCISE_CONTENT_TRANSLATIONS_BATCH_4B_BY_LOCALE.en).map((id) => [
    id,
    Object.fromEntries(
      Object.entries(EXERCISE_CONTENT_TRANSLATIONS_BATCH_4B_BY_LOCALE).map(([locale, entries]) => [locale, entries[id]])
    )
  ])
);

export const EXERCISE_CONTENT_BATCH_4B_IDS = Object.freeze(
  Object.keys(EXERCISE_CONTENT_TRANSLATIONS_BATCH_4B_BY_LOCALE.en)
);
