const makeContent = (title, description, tags, steps, benefits, tips) => ({
  title,
  description,
  tags,
  steps: steps.map(([stepTitle, stepDescription]) => ({ title: stepTitle, description: stepDescription })),
  benefits,
  tips
});

const EXERCISE_CONTENT_TRANSLATIONS_BATCH_4A_BY_LOCALE = {
  en: {
    'local-exposure-fear-hierarchy': makeContent('Fear Hierarchy Building','Create a gradual, manageable plan for approaching a fear.',['exposure','anxiety','planning','CBT'],[['Name the fear','Describe the situation or trigger you want to approach.'],['List situations','Write 8–12 related situations, from easier to harder.'],['Rate distress','Give each item a 0–100 SUDS rating.'],['Order the list','Arrange items from about 20–30 up to 90–100.'],['Choose a first step','Plan one specific, repeatable practice from the lower-middle range.']],['Turns a broad fear into manageable steps','Supports gradual confidence building','Makes progress easier to track'],['Start with a mild-to-moderate item, often around 30–50 SUDS.','Work with a qualified clinician for trauma, severe phobia, or overwhelming distress.']),
    'local-exposure-systematic-desensitization': makeContent('Systematic Desensitization','Pair gradual exposure with relaxation skills at a tolerable pace.',['exposure','relaxation','anxiety','CBT'],[['Settle your body','Use slow breathing or another familiar skill until distress is below 20/100.'],['Imagine the first item','Picture the lowest fear-hierarchy item in clear but manageable detail.'],['Stay and observe','Remain with the image while noticing distress without forcing it away.'],['Return to safety','Shift to a calm or pleasant image and let your body settle.'],['Repeat gradually','When distress falls below about 25, repeat or move one small step higher.']],['Builds tolerance gradually','Links feared cues with regulation','Provides a structured pace'],['Keep practice within a planned, tolerable range.','Use professional support for severe phobia, trauma, dissociation, or panic.']),
    'local-exposure-imaginal': makeContent('Imaginal Exposure','Practice safely approaching a feared memory or scenario in imagination.',['exposure','imagery','anxiety','CBT'],[['Choose a scenario','Select a moderate item from your hierarchy, not the most intense one.'],['Build the scene','Imagine what you see, hear, feel, and notice around you.'],['Stay present','Observe the scene and your reactions without judging them.'],['Track distress','Rate SUDS every few minutes and notice how it changes.'],['Close deliberately','End as planned, orient to the room, and record what you learned.']],['Reduces avoidance gradually','Builds confidence with difficult thoughts','Helps distinguish fear predictions from outcomes'],['Pause, ground, and seek support if distress becomes overwhelming or you feel unsafe.','Trauma-focused imaginal exposure should be done with a qualified clinician.']),
    'local-exposure-interoceptive': makeContent('Interoceptive Exposure','With clinical guidance, safely practice tolerating harmless body sensations linked to anxiety.',['exposure','body sensations','panic','clinical guidance'],[['Choose safely','With a clinician, identify one medically safe sensation to practice.'],['Check readiness','Do not practice if a health condition, pregnancy, injury, or current symptom makes it unsafe.'],['Use a gentle method','Only use a clinician-approved brief action, such as light walking in place or gentle head turns.'],['Observe and rate','Notice the sensation, rate distress 0–100, and let it settle naturally.'],['Reflect','Record what you predicted, what happened, and what helped.']],['Can reduce fear of benign sensations','Builds tolerance in a controlled way','Tests anxious predictions safely'],['Consult a qualified clinician first; never restrict breathing or use risky methods.','Stop and seek medical care for chest pain, fainting, severe shortness of breath, or other concerning symptoms.']),
    'local-exposure-social': makeContent('Social Situation Exposure','Approach social fears through small, repeatable real-world steps.',['exposure','social anxiety','confidence','practice'],[['Create a hierarchy','List social situations from easier to harder.'],['Pick one step','Choose a lower-level situation that is uncomfortable but manageable.'],['Set a clear goal','Define one observable action, such as asking a question.'],['Practice and stay','Complete the action and remain long enough to notice what happens.'],['Debrief','Compare your prediction with the outcome and plan a repeat.']],['Builds social confidence gradually','Reduces avoidance','Creates evidence from real experiences'],['Reduce safety behaviors gradually; keep any behavior needed for genuine safety.','Choose respectful, consensual situations and never pressure yourself or others.']),
    'local-sleep-stimulus-control': makeContent('Stimulus Control','Rebuild a consistent link between bed and sleep.',['sleep','insomnia','routine','CBT-I'],[['Wait for sleepiness','Go to bed when sleepy rather than only because the clock says so.'],['Reserve the bed','Use bed mainly for sleep and intimacy.'],['Reset when awake','If you are awake for roughly 20 minutes, get up calmly and do something quiet in dim light.'],['Keep wake time steady','Get up at the same time each day, including after a difficult night.'],['Manage naps','Avoid naps or keep them brief and early if your clinician recommends them.']],['Strengthens the bed–sleep association','Reduces time spent struggling in bed','Supports a steadier sleep rhythm'],['Return to bed when sleepiness comes back.','Seek clinical advice for persistent insomnia, major daytime sleepiness, or suspected sleep apnea.']),
    'local-sleep-restriction': makeContent('Sleep Restriction','A clinician-guided CBT-I method that carefully matches time in bed to actual sleep.',['sleep','insomnia','CBT-I','clinical guidance'],[['Keep a diary','Record sleep and wake times for at least one week.'],['Set a safe window','With a clinician, choose a sleep window based on average sleep; do not go below 5.5 hours.'],['Keep fixed times','Use the agreed bedtime and wake time every day.'],['Monitor closely','Track sleep efficiency, mood, energy, and daytime sleepiness.'],['Adjust gradually','With clinical guidance, add about 15 minutes after sustained efficiency above 85%.']],['Can consolidate sleep','Provides measurable adjustments','Supports a consistent rhythm'],['Use only with qualified clinical guidance; avoid without medical advice if you have bipolar/mania risk, seizures, untreated sleep apnea, pregnancy, or safety-sensitive work.','Do not drive or operate machinery when sleepy; pause and contact your clinician if mood, safety, or functioning worsens.'])
  },
  he: {
    'local-exposure-fear-hierarchy': makeContent('בניית סולם פחד','בניית תוכנית הדרגתית ובת־ביצוע להתקרבות לפחד.',['חשיפה','חרדה','תכנון','CBT'],[['תנו שם לפחד','תארו את המצב או הגורם שאליו תרצו להתקרב.'],['רשמו מצבים','כתבו 8–12 מצבים קשורים, מהקל אל הקשה.'],['דרגו מצוקה','תנו לכל פריט דירוג SUDS בין 0 ל־100.'],['סדרו את הרשימה','סדרו מכ־20–30 ועד 90–100.'],['בחרו צעד ראשון','תכננו תרגול מסוים וחוזר מהטווח הנמוך־בינוני.']],['הופך פחד רחב לצעדים אפשריים','תומך בבניית ביטחון הדרגתית','מקל על מעקב אחר התקדמות'],['התחילו בפריט קל עד בינוני, לרוב סביב 30–50 SUDS.','בפוסט־טראומה, פוביה קשה או מצוקה מציפה, תרגלו עם איש מקצוע מוסמך.']),
    'local-exposure-systematic-desensitization': makeContent('הקהיה שיטתית','שילוב חשיפה הדרגתית עם מיומנויות הרגעה בקצב נסבל.',['חשיפה','הרפיה','חרדה','CBT'],[['הרגיעו את הגוף','השתמשו בנשימה איטית או במיומנות מוכרת עד שהמצוקה מתחת ל־20/100.'],['דמיינו את הפריט הראשון','דמיינו את הפריט הנמוך בסולם בפירוט ברור אך נסבל.'],['הישארו והתבוננו','שימו לב למצוקה בלי לנסות לכפות עליה להיעלם.'],['חזרו לרוגע','עברו לדימוי רגוע או נעים ואפשרו לגוף להתייצב.'],['חזרו בהדרגה','כשהמצוקה יורדת מתחת לכ־25, חזרו או עלו צעד קטן.']],['בונה סבילות בהדרגה','מחבר רמזי פחד לוויסות','מספק קצב מובנה'],['שמרו את התרגול בטווח מתוכנן ונסבל.','בפוביה קשה, טראומה, ניתוק או פאניקה היעזרו באיש מקצוע.']),
    'local-exposure-imaginal': makeContent('חשיפה בדמיון','תרגול בטוח של התקרבות לזיכרון או תרחיש מפחיד בדמיון.',['חשיפה','דמיון','חרדה','CBT'],[['בחרו תרחיש','בחרו פריט בינוני בסולם, לא את העוצמתי ביותר.'],['בנו את התמונה','דמיינו מה רואים, שומעים, מרגישים ומבחינים סביב.'],['הישארו בהווה','התבוננו בתרחיש ובתגובות בלי שיפוט.'],['עקבו אחר המצוקה','דרגו SUDS מדי כמה דקות ושימו לב לשינוי.'],['סיימו במכוון','סיימו כמתוכנן, התמצאו בחדר וכתבו מה למדתם.']],['מפחית הימנעות בהדרגה','בונה ביטחון מול מחשבות קשות','עוזר להשוות תחזיות פחד לתוצאות'],['אם המצוקה מציפה או אינכם חשים בטוחים, עצרו, התקרקעו ופנו לתמיכה.','חשיפה בדמיון הקשורה לטראומה יש לבצע עם איש מקצוע מוסמך.']),
    'local-exposure-interoceptive': makeContent('חשיפה לתחושות גוף','בהנחיה קלינית, תרגול בטוח של סבילות לתחושות גוף בלתי מסוכנות הקשורות לחרדה.',['חשיפה','תחושות גוף','פאניקה','הנחיה קלינית'],[['בחרו בבטחה','זהו עם איש מקצוע תחושה אחת שבטוח רפואית לתרגל.'],['בדקו מוכנות','אל תתרגלו אם מצב רפואי, היריון, פציעה או תסמין נוכחי הופכים זאת ללא בטוח.'],['השתמשו בדרך עדינה','בצעו רק פעולה קצרה שאושרה מקצועית, כגון הליכה קלה במקום או סיבובי ראש עדינים.'],['התבוננו ודרגו','שימו לב לתחושה, דרגו מצוקה 0–100 ואפשרו לה להירגע מעצמה.'],['סכמו','כתבו מה צפיתם, מה קרה ומה עזר.']],['עשוי להפחית פחד מתחושות תקינות','בונה סבילות באופן מבוקר','בודק תחזיות חרדה בבטחה'],['התייעצו תחילה עם איש מקצוע; לעולם אל תגבילו נשימה ואל תשתמשו בשיטות מסוכנות.','עצרו ופנו לטיפול רפואי בכאב בחזה, עילפון, קוצר נשימה חמור או תסמין מדאיג אחר.']),
    'local-exposure-social': makeContent('חשיפה למצבים חברתיים','התקרבות לפחדים חברתיים בצעדים קטנים וחוזרים בעולם האמיתי.',['חשיפה','חרדה חברתית','ביטחון','תרגול'],[['צרו סולם','רשמו מצבים חברתיים מהקל אל הקשה.'],['בחרו צעד','בחרו מצב ברמה נמוכה שאינו נוח אך ניתן לניהול.'],['הגדירו יעד','קבעו פעולה נצפית אחת, למשל לשאול שאלה.'],['תרגלו והישארו','בצעו את הפעולה והישארו מספיק כדי לראות מה קורה.'],['סכמו','השוו בין התחזית לתוצאה ותכננו חזרה.']],['בונה ביטחון חברתי בהדרגה','מפחית הימנעות','יוצר ראיות מחוויות אמיתיות'],['הפחיתו התנהגויות ביטחון בהדרגה ושמרו כל מה שנדרש לבטיחות אמיתית.','בחרו מצבים מכבדים ובהסכמה, ואל תלחצו על עצמכם או על אחרים.']),
    'local-sleep-stimulus-control': makeContent('שליטה בגירויים','חיזוק הקשר העקבי בין המיטה לשינה.',['שינה','נדודי שינה','שגרה','CBT-I'],[['חכו לישנוניות','היכנסו למיטה כשאתם ישנוניים ולא רק לפי השעון.'],['ייחדו את המיטה','השתמשו במיטה בעיקר לשינה ולאינטימיות.'],['אתחלו כשערים','אם אתם ערים בערך 20 דקות, קומו ברוגע ועשו פעילות שקטה באור עמום.'],['שמרו שעת קימה','קומו באותה שעה בכל יום, גם אחרי לילה קשה.'],['נהלו תנומות','הימנעו מתנומות או שמרו אותן קצרות ומוקדמות לפי המלצה מקצועית.']],['מחזק את הקשר מיטה–שינה','מפחית מאבק ממושך במיטה','תומך בקצב שינה יציב'],['חזרו למיטה כשהישנוניות חוזרת.','פנו לייעוץ בנדודי שינה מתמשכים, ישנוניות יום משמעותית או חשד לדום נשימה.']),
    'local-sleep-restriction': makeContent('צמצום חלון השינה','שיטת CBT-I בהנחיה קלינית, המתאימה בזהירות את הזמן במיטה לזמן השינה בפועל.',['שינה','נדודי שינה','CBT-I','הנחיה קלינית'],[['נהלו יומן','תעדו זמני שינה ויקיצה לפחות שבוע.'],['קבעו חלון בטוח','עם איש מקצוע, קבעו חלון לפי ממוצע השינה; אין לרדת מתחת ל־5.5 שעות.'],['שמרו שעות קבועות','היצמדו לשעת השינה והקימה שסוכמו מדי יום.'],['עקבו מקרוב','תעדו יעילות שינה, מצב רוח, אנרגיה וישנוניות ביום.'],['התאימו בהדרגה','בהנחיה מקצועית, הוסיפו כ־15 דקות לאחר יעילות מעל 85% לאורך זמן.']],['עשוי לרכז את השינה','מאפשר התאמות מדידות','תומך בקצב קבוע'],['יש לבצע רק בהנחיה מקצועית; ללא ייעוץ רפואי יש להימנע במאניה או סיכון דו־קוטבי, פרכוסים, דום נשימה לא מטופל, היריון או עבודה בטיחותית.','אין לנהוג או להפעיל מכונות כשישנוניים; עצרו ופנו למטפל אם מצב הרוח, הבטיחות או התפקוד מחמירים.'])
  },
  es: {
    'local-exposure-fear-hierarchy': makeContent('Construcción de jerarquía del miedo','Crea un plan gradual y manejable para acercarte a un miedo.',['exposición','ansiedad','planificación','TCC'],[['Nombra el miedo','Describe la situación o el desencadenante.'],['Enumera situaciones','Escribe de 8 a 12 situaciones, de más fácil a más difícil.'],['Valora el malestar','Asigna a cada elemento una puntuación SUDS de 0 a 100.'],['Ordena la lista','Ordénala desde 20–30 hasta 90–100.'],['Elige el primer paso','Planifica una práctica concreta y repetible del rango bajo-medio.']],['Convierte el miedo en pasos manejables','Favorece una confianza gradual','Facilita seguir el progreso'],['Empieza con un elemento leve o moderado, cerca de 30–50 SUDS.','Para trauma, fobia grave o malestar abrumador, trabaja con un profesional cualificado.']),
    'local-exposure-systematic-desensitization': makeContent('Desensibilización sistemática','Combina exposición gradual y relajación a un ritmo tolerable.',['exposición','relajación','ansiedad','TCC'],[['Calma el cuerpo','Usa respiración lenta hasta que el malestar sea menor de 20/100.'],['Imagina el primer elemento','Visualiza el elemento más bajo con detalle manejable.'],['Permanece y observa','Nota el malestar sin forzarlo a desaparecer.'],['Vuelve a la calma','Cambia a una imagen tranquila y deja que el cuerpo se estabilice.'],['Repite gradualmente','Cuando baje de 25, repite o avanza un paso pequeño.']],['Aumenta la tolerancia gradualmente','Asocia regulación con señales temidas','Ofrece un ritmo estructurado'],['Mantén la práctica en un rango planificado y tolerable.','Busca apoyo profesional ante fobia grave, trauma, disociación o pánico.']),
    'local-exposure-imaginal': makeContent('Exposición imaginaria','Acércate de forma segura a un recuerdo o escenario temido en la imaginación.',['exposición','imaginación','ansiedad','TCC'],[['Elige un escenario','Selecciona un elemento moderado, no el más intenso.'],['Construye la escena','Imagina lo que ves, oyes, sientes y notas.'],['Mantente presente','Observa la escena y tus reacciones sin juzgar.'],['Sigue el malestar','Valora SUDS cada pocos minutos y observa el cambio.'],['Cierra con intención','Termina según lo previsto, oriéntate en la habitación y anota lo aprendido.']],['Reduce la evitación gradualmente','Aumenta la confianza ante pensamientos difíciles','Compara predicciones con resultados'],['Pausa, oriéntate y busca apoyo si el malestar te desborda o no te sientes seguro.','La exposición imaginaria al trauma debe hacerse con un profesional cualificado.']),
    'local-exposure-interoceptive': makeContent('Exposición interoceptiva','Con guía clínica, practica tolerar sensaciones corporales inofensivas asociadas a la ansiedad.',['exposición','sensaciones corporales','pánico','guía clínica'],[['Elige con seguridad','Identifica con un profesional una sensación médicamente segura.'],['Comprueba tu estado','No practiques si una afección, embarazo, lesión o síntoma actual lo hace inseguro.'],['Usa un método suave','Solo una acción breve aprobada, como caminar suavemente en el sitio o girar la cabeza despacio.'],['Observa y valora','Nota la sensación, valora 0–100 y deja que disminuya.'],['Reflexiona','Anota qué predijiste, qué ocurrió y qué ayudó.']],['Puede reducir el miedo a sensaciones benignas','Aumenta tolerancia de forma controlada','Pone a prueba predicciones con seguridad'],['Consulta antes a un profesional; nunca restrinjas la respiración ni uses métodos arriesgados.','Detente y busca atención médica ante dolor torácico, desmayo, falta de aire intensa u otro síntoma preocupante.']),
    'local-exposure-social': makeContent('Exposición a situaciones sociales','Acércate a miedos sociales con pasos pequeños y repetibles.',['exposición','ansiedad social','confianza','práctica'],[['Crea una jerarquía','Enumera situaciones sociales de más fácil a más difícil.'],['Elige un paso','Escoge una situación incómoda pero manejable.'],['Fija una meta','Define una acción observable, como hacer una pregunta.'],['Practica y permanece','Haz la acción y quédate para observar qué sucede.'],['Revisa','Compara predicción y resultado y planifica repetir.']],['Aumenta confianza social','Reduce la evitación','Aporta evidencia real'],['Reduce conductas de seguridad gradualmente y conserva las necesarias.','Elige situaciones respetuosas y consentidas.']),
    'local-sleep-stimulus-control': makeContent('Control de estímulos','Restablece una asociación constante entre cama y sueño.',['sueño','insomnio','rutina','TCC-I'],[['Espera la somnolencia','Ve a la cama cuando tengas sueño.'],['Reserva la cama','Úsala principalmente para dormir e intimidad.'],['Reinicia si estás despierto','Si sigues despierto unos 20 minutos, levántate con calma y haz algo tranquilo con luz tenue.'],['Mantén la hora de levantarte','Levántate a la misma hora cada día.'],['Gestiona las siestas','Evítalas o mantenlas breves y tempranas según consejo clínico.']],['Refuerza la asociación cama–sueño','Reduce la lucha en la cama','Apoya un ritmo estable'],['Vuelve a la cama cuando regrese la somnolencia.','Consulta por insomnio persistente, somnolencia diurna importante o posible apnea.']),
    'local-sleep-restriction': makeContent('Restricción del sueño','Método de TCC-I con supervisión clínica que ajusta cuidadosamente el tiempo en cama al sueño real.',['sueño','insomnio','TCC-I','guía clínica'],[['Lleva un diario','Registra sueño y despertar al menos una semana.'],['Fija una ventana segura','Con un profesional, usa el promedio de sueño; nunca menos de 5,5 horas.'],['Mantén horarios','Sigue cada día la hora acordada para acostarte y levantarte.'],['Supervisa','Registra eficiencia, ánimo, energía y somnolencia diurna.'],['Ajusta gradualmente','Con guía, añade unos 15 minutos tras mantener una eficiencia superior al 85%.']],['Puede consolidar el sueño','Permite ajustes medibles','Apoya un ritmo constante'],['Solo con guía profesional; consulta antes si hay riesgo bipolar/manía, convulsiones, apnea no tratada, embarazo o trabajo de seguridad.','No conduzcas ni manejes maquinaria con sueño; pausa y contacta al profesional si empeoran ánimo, seguridad o funcionamiento.'])
  },
  fr: {
    'local-exposure-fear-hierarchy': makeContent('Construction d’une hiérarchie des peurs','Créez un plan progressif et gérable pour approcher une peur.',['exposition','anxiété','planification','TCC'],[['Nommez la peur','Décrivez la situation ou le déclencheur.'],['Listez les situations','Notez 8 à 12 situations, de la plus facile à la plus difficile.'],['Évaluez la détresse','Attribuez un score SUDS de 0 à 100.'],['Classez la liste','Ordonnez de 20–30 à 90–100.'],['Choisissez un premier pas','Planifiez une pratique concrète et répétable du niveau bas-moyen.']],['Transforme une peur en étapes gérables','Soutient la confiance progressive','Facilite le suivi des progrès'],['Commencez vers 30–50 SUDS.','Pour un traumatisme, une phobie sévère ou une détresse intense, travaillez avec un professionnel qualifié.']),
    'local-exposure-systematic-desensitization': makeContent('Désensibilisation systématique','Associez exposition graduelle et relaxation à un rythme tolérable.',['exposition','relaxation','anxiété','TCC'],[['Apaisez le corps','Respirez lentement jusqu’à une détresse inférieure à 20/100.'],['Imaginez le premier élément','Visualisez l’élément le plus bas avec des détails gérables.'],['Restez et observez','Remarquez la détresse sans la forcer à disparaître.'],['Revenez au calme','Passez à une image apaisante.'],['Répétez progressivement','Sous environ 25, répétez ou avancez d’un petit pas.']],['Développe la tolérance','Associe régulation et signaux redoutés','Donne un rythme structuré'],['Restez dans une zone planifiée et tolérable.','Demandez un accompagnement pour phobie sévère, traumatisme, dissociation ou panique.']),
    'local-exposure-imaginal': makeContent('Exposition en imagination','Approchez en sécurité un souvenir ou scénario redouté par l’imagination.',['exposition','imagerie','anxiété','TCC'],[['Choisissez un scénario','Prenez un élément modéré, pas le plus intense.'],['Construisez la scène','Imaginez ce que vous voyez, entendez et ressentez.'],['Restez présent','Observez sans jugement.'],['Suivez la détresse','Évaluez les SUDS toutes les quelques minutes.'],['Clôturez volontairement','Terminez comme prévu, orientez-vous dans la pièce et notez vos apprentissages.']],['Réduit progressivement l’évitement','Renforce la confiance','Compare les prédictions aux résultats'],['Faites une pause, ancrez-vous et cherchez du soutien si vous êtes submergé ou en insécurité.','Pour un traumatisme, pratiquez avec un professionnel qualifié.']),
    'local-exposure-interoceptive': makeContent('Exposition intéroceptive','Avec un encadrement clinique, entraînez-vous à tolérer des sensations corporelles bénignes.',['exposition','sensations corporelles','panique','encadrement clinique'],[['Choisissez sans risque','Identifiez avec un professionnel une sensation médicalement sûre.'],['Vérifiez votre état','Ne pratiquez pas si maladie, grossesse, blessure ou symptôme actuel rend l’exercice risqué.'],['Utilisez une méthode douce','Seulement une action brève approuvée, comme marcher doucement sur place ou tourner lentement la tête.'],['Observez et évaluez','Notez la sensation et la détresse 0–100 puis laissez-la diminuer.'],['Réfléchissez','Notez prédiction, résultat et aide utile.']],['Peut réduire la peur de sensations bénignes','Développe une tolérance contrôlée','Teste les prédictions en sécurité'],['Consultez d’abord un professionnel; ne bloquez jamais la respiration et évitez toute méthode risquée.','Arrêtez et consultez en urgence pour douleur thoracique, évanouissement, essoufflement sévère ou autre symptôme inquiétant.']),
    'local-exposure-social': makeContent('Exposition aux situations sociales','Approchez les peurs sociales par de petits pas répétables.',['exposition','anxiété sociale','confiance','pratique'],[['Créez une hiérarchie','Listez les situations de la plus facile à la plus difficile.'],['Choisissez un pas','Prenez une situation inconfortable mais gérable.'],['Fixez un objectif','Définissez une action observable.'],['Pratiquez et restez','Faites l’action et observez ce qui se passe.'],['Faites le bilan','Comparez prédiction et résultat puis planifiez une répétition.']],['Renforce la confiance sociale','Réduit l’évitement','Apporte des preuves réelles'],['Réduisez les comportements de sécurité progressivement.','Choisissez des situations respectueuses et consenties.']),
    'local-sleep-stimulus-control': makeContent('Contrôle du stimulus','Rétablissez un lien stable entre le lit et le sommeil.',['sommeil','insomnie','routine','TCC-I'],[['Attendez la somnolence','Couchez-vous quand vous avez sommeil.'],['Réservez le lit','Utilisez-le surtout pour dormir et l’intimité.'],['Réinitialisez si éveillé','Après environ 20 minutes éveillé, levez-vous calmement pour une activité tranquille en lumière tamisée.'],['Gardez une heure de lever','Levez-vous à la même heure chaque jour.'],['Gérez les siestes','Évitez-les ou gardez-les courtes et tôt selon l’avis clinique.']],['Renforce le lien lit–sommeil','Réduit la lutte au lit','Soutient un rythme stable'],['Retournez au lit quand la somnolence revient.','Consultez pour insomnie persistante, somnolence diurne importante ou apnée suspectée.']),
    'local-sleep-restriction': makeContent('Restriction du sommeil','Méthode de TCC-I encadrée qui ajuste prudemment le temps au lit au sommeil réel.',['sommeil','insomnie','TCC-I','encadrement clinique'],[['Tenez un journal','Notez sommeil et réveil pendant au moins une semaine.'],['Fixez une fenêtre sûre','Avec un professionnel, partez du sommeil moyen; jamais moins de 5,5 heures.'],['Gardez les horaires','Respectez chaque jour les horaires convenus.'],['Surveillez','Suivez efficacité, humeur, énergie et somnolence.'],['Ajustez progressivement','Avec accompagnement, ajoutez environ 15 minutes après une efficacité durable supérieure à 85 %.']],['Peut consolider le sommeil','Permet des ajustements mesurables','Soutient un rythme régulier'],['Uniquement avec encadrement; avis médical si risque bipolaire/manie, crises, apnée non traitée, grossesse ou travail à risque.','Ne conduisez pas somnolent; interrompez et contactez le professionnel si humeur, sécurité ou fonctionnement se dégradent.'])
  },
  de: {
    'local-exposure-fear-hierarchy': makeContent('Angsthierarchie erstellen','Erstellen Sie einen schrittweisen, machbaren Plan zur Annäherung an eine Angst.',['Exposition','Angst','Planung','KVT'],[['Angst benennen','Beschreiben Sie Situation oder Auslöser.'],['Situationen sammeln','Notieren Sie 8–12 Situationen von leichter bis schwerer.'],['Belastung bewerten','Vergeben Sie SUDS-Werte von 0 bis 100.'],['Liste ordnen','Ordnen Sie von 20–30 bis 90–100.'],['Ersten Schritt wählen','Planen Sie eine konkrete, wiederholbare Übung im unteren Mittelfeld.']],['Macht Angst in Schritten bearbeitbar','Fördert allmählich Zuversicht','Erleichtert Fortschrittsmessung'],['Beginnen Sie etwa bei 30–50 SUDS.','Bei Trauma, schwerer Phobie oder Überforderung mit qualifizierter Fachkraft arbeiten.']),
    'local-exposure-systematic-desensitization': makeContent('Systematische Desensibilisierung','Verbinden Sie schrittweise Exposition mit Entspannung in verträglichem Tempo.',['Exposition','Entspannung','Angst','KVT'],[['Körper beruhigen','Langsam atmen, bis Belastung unter 20/100 liegt.'],['Erstes Element vorstellen','Stellen Sie das niedrigste Element in verträglichen Details vor.'],['Bleiben und beobachten','Nehmen Sie Belastung wahr, ohne sie wegzuzwingen.'],['Zur Ruhe zurückkehren','Wechseln Sie zu einem beruhigenden Bild.'],['Schrittweise wiederholen','Unter etwa 25 wiederholen oder einen kleinen Schritt erhöhen.']],['Baut Toleranz auf','Verknüpft Regulation mit Angstreizen','Gibt ein klares Tempo'],['Im geplanten, verträglichen Bereich bleiben.','Bei schwerer Phobie, Trauma, Dissoziation oder Panik Fachhilfe nutzen.']),
    'local-exposure-imaginal': makeContent('Exposition in der Vorstellung','Nähern Sie sich einer gefürchteten Erinnerung oder Situation sicher in der Vorstellung.',['Exposition','Vorstellung','Angst','KVT'],[['Szenario wählen','Wählen Sie ein mittleres, nicht das stärkste Element.'],['Szene aufbauen','Stellen Sie Sehen, Hören und Fühlen vor.'],['Präsent bleiben','Beobachten Sie ohne Bewertung.'],['Belastung verfolgen','SUDS alle paar Minuten bewerten.'],['Bewusst abschließen','Planmäßig enden, im Raum orientieren und Erkenntnisse notieren.']],['Verringert Vermeidung allmählich','Stärkt Zuversicht','Vergleicht Vorhersagen mit Ergebnissen'],['Bei Überforderung pausieren, erden und Unterstützung suchen.','Traumabezogene Übungen mit qualifizierter Fachkraft durchführen.']),
    'local-exposure-interoceptive': makeContent('Interozeptive Exposition','Üben Sie mit klinischer Anleitung den Umgang mit harmlosen Körperempfindungen.',['Exposition','Körperempfindungen','Panik','klinische Anleitung'],[['Sicher auswählen','Mit einer Fachkraft eine medizinisch sichere Empfindung bestimmen.'],['Bereitschaft prüfen','Nicht üben, wenn Erkrankung, Schwangerschaft, Verletzung oder Symptom es riskant macht.'],['Sanfte Methode nutzen','Nur kurz und fachlich freigegeben, etwa leichtes Gehen am Platz oder sanftes Kopfdrehen.'],['Beobachten und bewerten','Empfindung wahrnehmen, 0–100 bewerten und abklingen lassen.'],['Reflektieren','Vorhersage, Ergebnis und hilfreiche Faktoren notieren.']],['Kann Angst vor harmlosen Empfindungen senken','Baut kontrolliert Toleranz auf','Prüft Angstvorhersagen sicher'],['Zuerst Fachkraft konsultieren; nie Atmung einschränken oder riskante Methoden nutzen.','Bei Brustschmerz, Ohnmacht, starker Atemnot oder anderen Warnzeichen abbrechen und medizinische Hilfe suchen.']),
    'local-exposure-social': makeContent('Exposition in sozialen Situationen','Nähern Sie sich sozialen Ängsten in kleinen, wiederholbaren Schritten.',['Exposition','soziale Angst','Zuversicht','Übung'],[['Hierarchie erstellen','Situationen von leichter bis schwerer auflisten.'],['Schritt wählen','Eine unangenehme, aber machbare Situation wählen.'],['Ziel setzen','Eine beobachtbare Handlung festlegen.'],['Üben und bleiben','Handlung ausführen und Ergebnis beobachten.'],['Auswerten','Vorhersage und Ergebnis vergleichen und Wiederholung planen.']],['Stärkt soziale Zuversicht','Reduziert Vermeidung','Schafft reale Erfahrungen'],['Sicherheitsverhalten schrittweise reduzieren, echte Sicherheit bewahren.','Respektvolle, einvernehmliche Situationen wählen.']),
    'local-sleep-stimulus-control': makeContent('Stimuluskontrolle','Stärken Sie die beständige Verbindung zwischen Bett und Schlaf.',['Schlaf','Insomnie','Routine','KVT-I'],[['Auf Müdigkeit warten','Erst bei Schläfrigkeit ins Bett gehen.'],['Bett reservieren','Bett hauptsächlich für Schlaf und Intimität nutzen.'],['Bei Wachsein wechseln','Nach ungefähr 20 Minuten ruhig aufstehen und bei gedämpftem Licht etwas Ruhiges tun.'],['Aufstehzeit halten','Jeden Tag zur gleichen Zeit aufstehen.'],['Nickerchen steuern','Vermeiden oder kurz und früh halten, wenn fachlich empfohlen.']],['Stärkt Bett–Schlaf-Verknüpfung','Verringert Wachliegen','Fördert stabilen Rhythmus'],['Bei Schläfrigkeit zurück ins Bett.','Bei anhaltender Insomnie, starker Tagesschläfrigkeit oder Apnoe-Verdacht beraten lassen.']),
    'local-sleep-restriction': makeContent('Schlafrestriktion','Klinisch begleitete KVT-I-Methode zur vorsichtigen Anpassung der Bettzeit an den tatsächlichen Schlaf.',['Schlaf','Insomnie','KVT-I','klinische Anleitung'],[['Tagebuch führen','Mindestens eine Woche Schlaf und Wachzeiten notieren.'],['Sicheres Fenster setzen','Mit Fachkraft am Schlafmittel orientieren; nie unter 5,5 Stunden.'],['Zeiten halten','Vereinbarte Bett- und Aufstehzeit täglich einhalten.'],['Eng überwachen','Effizienz, Stimmung, Energie und Tagesschläfrigkeit verfolgen.'],['Langsam anpassen','Unter Anleitung nach dauerhaft über 85 % etwa 15 Minuten ergänzen.']],['Kann Schlaf bündeln','Ermöglicht messbare Anpassungen','Fördert Regelmäßigkeit'],['Nur fachlich begleitet; ärztlicher Rat bei Bipolar-/Manierisiko, Anfällen, unbehandelter Apnoe, Schwangerschaft oder sicherheitskritischer Arbeit.','Bei Müdigkeit nicht fahren oder Maschinen bedienen; bei Verschlechterung Fachkraft kontaktieren.'])
  },
  it: {
    'local-exposure-fear-hierarchy': makeContent('Costruzione della gerarchia della paura','Crea un piano graduale e gestibile per avvicinarti a una paura.',['esposizione','ansia','pianificazione','CBT'],[['Dai un nome alla paura','Descrivi situazione o fattore scatenante.'],['Elenca le situazioni','Scrivi 8–12 situazioni dalla più facile alla più difficile.'],['Valuta il disagio','Assegna un punteggio SUDS 0–100.'],['Ordina la lista','Disponi da 20–30 a 90–100.'],['Scegli il primo passo','Pianifica una pratica concreta e ripetibile di livello medio-basso.']],['Rende la paura affrontabile','Sostiene fiducia graduale','Facilita il monitoraggio'],['Inizia intorno a 30–50 SUDS.','Per trauma, fobia grave o disagio travolgente, lavora con un professionista qualificato.']),
    'local-exposure-systematic-desensitization': makeContent('Desensibilizzazione sistematica','Abbina esposizione graduale e rilassamento a un ritmo tollerabile.',['esposizione','rilassamento','ansia','CBT'],[['Calma il corpo','Respira lentamente finché il disagio è sotto 20/100.'],['Immagina il primo elemento','Visualizza l’elemento più basso con dettagli gestibili.'],['Resta e osserva','Nota il disagio senza forzarlo a sparire.'],['Torna alla calma','Passa a un’immagine rasserenante.'],['Ripeti gradualmente','Sotto circa 25, ripeti o sali di un piccolo passo.']],['Aumenta gradualmente la tolleranza','Associa regolazione e segnali temuti','Dà un ritmo strutturato'],['Resta entro un livello pianificato e tollerabile.','Cerca supporto per fobia grave, trauma, dissociazione o panico.']),
    'local-exposure-imaginal': makeContent('Esposizione immaginativa','Avvicinati in sicurezza a un ricordo o scenario temuto nell’immaginazione.',['esposizione','immaginazione','ansia','CBT'],[['Scegli uno scenario','Seleziona un elemento moderato, non il più intenso.'],['Costruisci la scena','Immagina ciò che vedi, senti e percepisci.'],['Resta presente','Osserva senza giudizio.'],['Monitora il disagio','Valuta SUDS ogni pochi minuti.'],['Concludi intenzionalmente','Termina come previsto, orientati nella stanza e annota ciò che hai imparato.']],['Riduce gradualmente l’evitamento','Aumenta la fiducia','Confronta previsioni e risultati'],['Fermati, radicati e cerca sostegno se il disagio è travolgente o non ti senti al sicuro.','Per contenuti traumatici lavora con un professionista qualificato.']),
    'local-exposure-interoceptive': makeContent('Esposizione interocettiva','Con guida clinica, esercitati a tollerare sensazioni corporee innocue.',['esposizione','sensazioni corporee','panico','guida clinica'],[['Scegli in sicurezza','Individua con un professionista una sensazione sicura dal punto di vista medico.'],['Verifica la disponibilità','Non praticare se patologia, gravidanza, lesione o sintomo attuale crea rischio.'],['Usa un metodo delicato','Solo un’azione breve approvata, come camminare piano sul posto o ruotare dolcemente la testa.'],['Osserva e valuta','Nota la sensazione, valuta 0–100 e lascia che cali.'],['Rifletti','Annota previsione, risultato e cosa ha aiutato.']],['Può ridurre la paura di sensazioni benigne','Aumenta la tolleranza in modo controllato','Verifica le previsioni in sicurezza'],['Consulta prima un professionista; non limitare mai il respiro né usare metodi rischiosi.','Interrompi e cerca assistenza per dolore toracico, svenimento, grave affanno o altri sintomi preoccupanti.']),
    'local-exposure-social': makeContent('Esposizione alle situazioni sociali','Affronta paure sociali con piccoli passi ripetibili.',['esposizione','ansia sociale','fiducia','pratica'],[['Crea una gerarchia','Elenca situazioni dalla più facile alla più difficile.'],['Scegli un passo','Scegli una situazione scomoda ma gestibile.'],['Definisci un obiettivo','Stabilisci un’azione osservabile.'],['Pratica e resta','Esegui l’azione e osserva cosa accade.'],['Rivedi','Confronta previsione e risultato e pianifica di ripetere.']],['Aumenta la fiducia sociale','Riduce l’evitamento','Crea prove reali'],['Riduci gradualmente i comportamenti di sicurezza.','Scegli situazioni rispettose e consensuali.']),
    'local-sleep-stimulus-control': makeContent('Controllo dello stimolo','Ricostruisci un legame costante tra letto e sonno.',['sonno','insonnia','routine','CBT-I'],[['Aspetta la sonnolenza','Vai a letto quando hai sonno.'],['Riserva il letto','Usalo soprattutto per sonno e intimità.'],['Reimposta se sei sveglio','Dopo circa 20 minuti, alzati con calma e fai qualcosa di tranquillo in luce soffusa.'],['Mantieni la sveglia','Alzati alla stessa ora ogni giorno.'],['Gestisci i sonnellini','Evitali o tienili brevi e precoci secondo consiglio clinico.']],['Rafforza il legame letto–sonno','Riduce la lotta a letto','Sostiene un ritmo stabile'],['Torna a letto quando ritorna la sonnolenza.','Chiedi consiglio per insonnia persistente, forte sonnolenza diurna o sospetta apnea.']),
    'local-sleep-restriction': makeContent('Restrizione del sonno','Metodo CBT-I guidato clinicamente che adatta con cautela il tempo a letto al sonno reale.',['sonno','insonnia','CBT-I','guida clinica'],[['Tieni un diario','Registra sonno e risveglio per almeno una settimana.'],['Imposta una finestra sicura','Con un professionista, usa la media del sonno; mai sotto 5,5 ore.'],['Mantieni gli orari','Segui ogni giorno gli orari concordati.'],['Monitora','Segui efficienza, umore, energia e sonnolenza.'],['Regola gradualmente','Con guida, aggiungi circa 15 minuti dopo efficienza stabile sopra 85%.']],['Può consolidare il sonno','Permette modifiche misurabili','Sostiene regolarità'],['Solo con guida professionale; parere medico per rischio bipolare/mania, convulsioni, apnea non trattata, gravidanza o lavoro di sicurezza.','Non guidare né usare macchinari con sonnolenza; contatta il professionista se peggiorano umore, sicurezza o funzionamento.'])
  },
  pt: {
    'local-exposure-fear-hierarchy': makeContent('Construção da hierarquia do medo','Crie um plano gradual e manejável para se aproximar de um medo.',['exposição','ansiedade','planejamento','TCC'],[['Nomeie o medo','Descreva a situação ou gatilho.'],['Liste situações','Escreva 8–12 situações da mais fácil à mais difícil.'],['Avalie o desconforto','Dê uma nota SUDS de 0 a 100.'],['Ordene a lista','Organize de 20–30 até 90–100.'],['Escolha o primeiro passo','Planeje uma prática concreta e repetível no nível baixo-médio.']],['Transforma o medo em passos manejáveis','Aumenta a confiança gradualmente','Facilita acompanhar o progresso'],['Comece em torno de 30–50 SUDS.','Para trauma, fobia grave ou sofrimento intenso, trabalhe com profissional qualificado.']),
    'local-exposure-systematic-desensitization': makeContent('Dessensibilização sistemática','Combine exposição gradual e relaxamento em ritmo tolerável.',['exposição','relaxamento','ansiedade','TCC'],[['Acalme o corpo','Respire devagar até o desconforto ficar abaixo de 20/100.'],['Imagine o primeiro item','Visualize o item mais baixo com detalhes manejáveis.'],['Permaneça e observe','Note o desconforto sem forçá-lo a sumir.'],['Volte à calma','Mude para uma imagem tranquilizadora.'],['Repita gradualmente','Abaixo de cerca de 25, repita ou avance um pequeno passo.']],['Aumenta a tolerância','Associa regulação a sinais temidos','Oferece ritmo estruturado'],['Mantenha-se numa faixa planejada e tolerável.','Busque apoio para fobia grave, trauma, dissociação ou pânico.']),
    'local-exposure-imaginal': makeContent('Exposição imaginária','Aproxime-se com segurança de uma lembrança ou cenário temido na imaginação.',['exposição','imaginação','ansiedade','TCC'],[['Escolha um cenário','Selecione um item moderado, não o mais intenso.'],['Construa a cena','Imagine o que vê, ouve e sente.'],['Fique presente','Observe sem julgamento.'],['Acompanhe o desconforto','Avalie SUDS a cada poucos minutos.'],['Encerre com intenção','Termine como planejado, oriente-se no ambiente e registre o aprendizado.']],['Reduz a evitação gradualmente','Aumenta a confiança','Compara previsões e resultados'],['Pause, aterre-se e busque apoio se o desconforto for avassalador ou inseguro.','Para conteúdo traumático, pratique com profissional qualificado.']),
    'local-exposure-interoceptive': makeContent('Exposição interoceptiva','Com orientação clínica, pratique tolerar sensações corporais inofensivas.',['exposição','sensações corporais','pânico','orientação clínica'],[['Escolha com segurança','Defina com profissional uma sensação medicamente segura.'],['Verifique condições','Não pratique se doença, gravidez, lesão ou sintoma atual trouxer risco.'],['Use método suave','Somente ação breve aprovada, como caminhar levemente no lugar ou girar a cabeça devagar.'],['Observe e avalie','Note a sensação, avalie 0–100 e deixe diminuir.'],['Reflita','Registre previsão, resultado e o que ajudou.']],['Pode reduzir medo de sensações benignas','Aumenta tolerância controladamente','Testa previsões com segurança'],['Consulte primeiro um profissional; nunca restrinja a respiração nem use métodos arriscados.','Pare e busque atendimento para dor no peito, desmaio, falta de ar intensa ou outro sintoma preocupante.']),
    'local-exposure-social': makeContent('Exposição a situações sociais','Enfrente medos sociais com passos pequenos e repetíveis.',['exposição','ansiedade social','confiança','prática'],[['Crie uma hierarquia','Liste situações da mais fácil à mais difícil.'],['Escolha um passo','Escolha uma situação desconfortável, mas manejável.'],['Defina uma meta','Determine uma ação observável.'],['Pratique e permaneça','Faça a ação e observe o que ocorre.'],['Revise','Compare previsão e resultado e planeje repetir.']],['Aumenta confiança social','Reduz evitação','Cria evidências reais'],['Reduza comportamentos de segurança gradualmente.','Escolha situações respeitosas e consensuais.']),
    'local-sleep-stimulus-control': makeContent('Controle de estímulos','Reconstrua uma ligação consistente entre cama e sono.',['sono','insônia','rotina','TCC-I'],[['Espere a sonolência','Vá para a cama quando estiver sonolento.'],['Reserve a cama','Use-a principalmente para dormir e intimidade.'],['Reinicie se acordado','Após cerca de 20 minutos, levante-se com calma e faça algo tranquilo com luz baixa.'],['Mantenha o despertar','Levante-se no mesmo horário todos os dias.'],['Gerencie cochilos','Evite ou mantenha-os curtos e cedo conforme orientação.']],['Fortalece a associação cama–sono','Reduz a luta na cama','Apoia ritmo estável'],['Volte à cama quando a sonolência retornar.','Procure orientação para insônia persistente, sonolência diurna forte ou suspeita de apneia.']),
    'local-sleep-restriction': makeContent('Restrição do sono','Método de TCC-I com orientação clínica que ajusta cuidadosamente o tempo na cama ao sono real.',['sono','insônia','TCC-I','orientação clínica'],[['Mantenha um diário','Registre sono e despertar por pelo menos uma semana.'],['Defina janela segura','Com profissional, use a média de sono; nunca menos de 5,5 horas.'],['Mantenha horários','Siga diariamente os horários combinados.'],['Monitore','Acompanhe eficiência, humor, energia e sonolência.'],['Ajuste gradualmente','Com orientação, acrescente cerca de 15 minutos após eficiência sustentada acima de 85%.']],['Pode consolidar o sono','Permite ajustes mensuráveis','Apoia regularidade'],['Somente com orientação profissional; aconselhamento médico em risco bipolar/mania, convulsões, apneia não tratada, gravidez ou trabalho de segurança.','Não dirija nem opere máquinas com sono; pause e contate o profissional se humor, segurança ou funcionamento piorarem.'])
  }
};

export const EXERCISE_CONTENT_TRANSLATIONS_BATCH_4A = Object.fromEntries(
  Object.keys(EXERCISE_CONTENT_TRANSLATIONS_BATCH_4A_BY_LOCALE.en).map((id) => [
    id,
    Object.fromEntries(
      Object.entries(EXERCISE_CONTENT_TRANSLATIONS_BATCH_4A_BY_LOCALE).map(([locale, entries]) => [locale, entries[id]])
    )
  ])
);

export const EXERCISE_CONTENT_BATCH_4A_IDS = Object.freeze(
  Object.keys(EXERCISE_CONTENT_TRANSLATIONS_BATCH_4A_BY_LOCALE.en)
);
