export const EXERCISE_CONTENT_BATCH_5A_IDS = [
  "local-relationship-gratitude-expression",
  "local-stress-time-blocking",
  "local-stress-worry-postponement",
  "local-stress-problem-solving",
  "local-stress-progressive-muscle",
  "local-stress-cognitive-reframing",
  "69519590cc9f81fd9daed0b2"
];

const item = (title, description, tags, steps, benefits, tips) => ({
  title, description, tags, steps, benefits, tips
});

export const EXERCISE_CONTENT_TRANSLATIONS_BATCH_5A = {
  "local-relationship-gratitude-expression": {
    en: item("Gratitude Expression", "Share specific appreciation with someone to strengthen connection and positive emotion.", ["gratitude","relationships","connection","positivity"], [["Choose a person","Think of someone who has helped or supported you."],["Name the action","Identify one specific thing the person did."],["Name the impact","Describe what it meant to you and how it affected you."],["Express it","Share your appreciation in person, by message, or in a letter."],["Reflect","Notice how expressing gratitude felt and how the person responded."]].map(([title,description])=>({title,description})), ["Strengthens relationships","Supports positive emotion","Counters negativity bias"], ["Be specific rather than general.","Express gratitude freely, without expecting a particular response."]),
    he: item("הבעת הכרת תודה", "שתפו אדם בהערכה ממוקדת כדי לחזק את הקשר ואת הרגש החיובי.", ["הכרת תודה","יחסים","קשר","חיוביות"], [["בחירת אדם","חשבו על אדם שעזר לכם או תמך בכם."],["ציון המעשה","זהו דבר מסוים אחד שהאדם עשה."],["ציון ההשפעה","תארו מה הדבר היה עבורכם וכיצד השפיע עליכם."],["הבעת התודה","שתפו את ההערכה פנים אל פנים, בהודעה או במכתב."],["התבוננות","שימו לב כיצד הרגשתם ומה הייתה תגובתו של האדם."]].map(([title,description])=>({title,description})), ["חיזוק מערכות יחסים","עידוד רגש חיובי","איזון הנטייה להתמקד בשלילי"], ["היו ממוקדים ולא כלליים.","הביעו תודה בלי לצפות לתגובה מסוימת."]),
    es: item("Expresar gratitud", "Comparte un agradecimiento concreto para fortalecer el vínculo y la emoción positiva.", ["gratitud","relaciones","conexión","positividad"], [["Elige a una persona","Piensa en alguien que te haya ayudado o apoyado."],["Nombra la acción","Identifica algo concreto que esa persona hizo."],["Nombra el impacto","Describe qué significó para ti y cómo te afectó."],["Exprésalo","Comparte el agradecimiento en persona, por mensaje o carta."],["Reflexiona","Observa cómo te sentiste y cómo respondió la persona."]].map(([title,description])=>({title,description})), ["Fortalece las relaciones","Favorece emociones positivas","Compensa el sesgo negativo"], ["Sé específico, no general.","Agradece sin exigir una respuesta concreta."]),
    fr: item("Exprimer sa gratitude", "Partagez une reconnaissance précise pour renforcer le lien et l’émotion positive.", ["gratitude","relations","lien","positivité"], [["Choisir une personne","Pensez à quelqu’un qui vous a aidé ou soutenu."],["Nommer le geste","Identifiez une chose précise que cette personne a faite."],["Nommer l’impact","Décrivez ce que cela a représenté et produit pour vous."],["L’exprimer","Partagez votre gratitude en personne, par message ou par lettre."],["Observer","Remarquez votre ressenti et la réponse de la personne."]].map(([title,description])=>({title,description})), ["Renforce les relations","Soutient les émotions positives","Compense le biais négatif"], ["Soyez précis plutôt que général.","Exprimez-vous sans attendre une réponse particulière."]),
    de: item("Dankbarkeit ausdrücken", "Teile konkrete Wertschätzung, um Verbundenheit und positive Gefühle zu stärken.", ["Dankbarkeit","Beziehungen","Verbundenheit","Positivität"], [["Person wählen","Denke an jemanden, der dir geholfen oder dich unterstützt hat."],["Handlung benennen","Bestimme eine konkrete hilfreiche Handlung."],["Wirkung benennen","Beschreibe ihre Bedeutung und Wirkung für dich."],["Ausdrücken","Teile deinen Dank persönlich, per Nachricht oder Brief."],["Nachspüren","Beobachte dein Gefühl und die Reaktion der Person."]].map(([title,description])=>({title,description})), ["Stärkt Beziehungen","Fördert positive Gefühle","Gleicht Negativitätsfokus aus"], ["Sei konkret statt allgemein.","Erwarte keine bestimmte Reaktion."]),
    it: item("Esprimere gratitudine", "Condividi un apprezzamento specifico per rafforzare il legame e le emozioni positive.", ["gratitudine","relazioni","connessione","positività"], [["Scegli una persona","Pensa a qualcuno che ti ha aiutato o sostenuto."],["Nomina il gesto","Individua una cosa specifica che ha fatto."],["Nomina l’impatto","Descrivi cosa ha significato e come ti ha influenzato."],["Esprimilo","Condividi la gratitudine di persona, con un messaggio o una lettera."],["Rifletti","Nota come ti sei sentito e la risposta ricevuta."]].map(([title,description])=>({title,description})), ["Rafforza le relazioni","Favorisce emozioni positive","Contrasta il pregiudizio negativo"], ["Sii specifico, non generico.","Non aspettarti una risposta particolare."]),
    pt: item("Expressar gratidão", "Compartilhe uma apreciação específica para fortalecer o vínculo e a emoção positiva.", ["gratidão","relacionamentos","conexão","positividade"], [["Escolha uma pessoa","Pense em alguém que ajudou ou apoiou você."],["Nomeie a ação","Identifique algo específico que a pessoa fez."],["Nomeie o impacto","Descreva o significado e o efeito disso em você."],["Expresse","Compartilhe pessoalmente, por mensagem ou carta."],["Reflita","Observe como se sentiu e como a pessoa respondeu."]].map(([title,description])=>({title,description})), ["Fortalece relacionamentos","Apoia emoções positivas","Contrabalança o viés negativo"], ["Seja específico, não genérico.","Não espere uma resposta determinada."])
  },
  "local-stress-time-blocking": {
    en: item("Time Blocking", "Organize the day into focused blocks to reduce overwhelm and increase control.", ["stress","planning","focus","overwhelm"], [["List tasks","Write down the tasks occupying your attention."],["Estimate time","Give each task a realistic time estimate."],["Build blocks","Assign tasks to focused blocks in your day."],["Add buffers","Leave transition time between blocks."],["Work one block","Focus on the assigned task and silence notifications."]].map(([title,description])=>({title,description})), ["Reduces decision fatigue","Creates structure","Protects focused time"], ["Review the plan midway and adjust it.","Use shorter blocks when energy is low."]),
    he: item("חלוקת זמן למקטעים", "ארגנו את היום במקטדי מיקוד כדי להפחית הצפה ולהגביר תחושת שליטה.", ["לחץ","תכנון","מיקוד","הצפה"], [["רשימת משימות","כתבו את המשימות שמעסיקות אתכם."],["הערכת זמן","הקצו לכל משימה זמן מציאותי."],["בניית מקטעים","שבצו משימות במקטדי מיקוד במהלך היום."],["הוספת מרווחים","השאירו זמן מעבר בין המקטעים."],["עבודה ממוקדת","עסקו במשימה שנבחרה והשתיקו התראות."]].map(([title,description])=>({title,description})), ["הפחתת עייפות מהחלטות","יצירת סדר","שמירה על זמן ממוקד"], ["בדקו את התוכנית באמצע היום והתאימו אותה.","השתמשו במקטעים קצרים יותר כשאין הרבה אנרגיה."]),
    es: item("Bloques de tiempo", "Organiza el día en bloques de enfoque para reducir el agobio y aumentar el control.", ["estrés","planificación","enfoque","agobio"], [["Lista las tareas","Anota las tareas que ocupan tu atención."],["Estima el tiempo","Asigna a cada tarea un tiempo realista."],["Crea bloques","Distribuye las tareas en bloques de concentración."],["Añade márgenes","Deja tiempo de transición entre bloques."],["Trabaja un bloque","Concéntrate en la tarea y silencia las notificaciones."]].map(([title,description])=>({title,description})), ["Reduce la fatiga decisional","Aporta estructura","Protege el tiempo de enfoque"], ["Revisa el plan a mitad del día.","Usa bloques más cortos si tienes poca energía."]),
    fr: item("Planification par blocs", "Organisez la journée en blocs ciblés pour réduire la surcharge et retrouver du contrôle.", ["stress","planification","concentration","surcharge"], [["Lister les tâches","Notez les tâches qui occupent votre attention."],["Estimer le temps","Attribuez une durée réaliste à chaque tâche."],["Créer les blocs","Placez les tâches dans des blocs de concentration."],["Ajouter des marges","Prévoyez des transitions entre les blocs."],["Travailler un bloc","Restez sur la tâche et coupez les notifications."]].map(([title,description])=>({title,description})), ["Réduit la fatigue décisionnelle","Apporte une structure","Protège le temps de concentration"], ["Révisez le plan à mi-journée.","Raccourcissez les blocs si votre énergie baisse."]),
    de: item("Zeitblöcke planen", "Strukturiere den Tag in Fokusblöcke, um Überforderung zu senken und Kontrolle zu gewinnen.", ["Stress","Planung","Fokus","Überforderung"], [["Aufgaben notieren","Schreibe alle Aufgaben auf, die dich beschäftigen."],["Zeit schätzen","Gib jeder Aufgabe eine realistische Dauer."],["Blöcke bilden","Ordne Aufgaben festen Fokusblöcken zu."],["Puffer einbauen","Plane Übergangszeit zwischen den Blöcken."],["Block bearbeiten","Bleibe bei einer Aufgabe und schalte Mitteilungen aus."]].map(([title,description])=>({title,description})), ["Senkt Entscheidungsmüdigkeit","Schafft Struktur","Schützt Fokuszeit"], ["Passe den Plan zur Tagesmitte an.","Nutze bei wenig Energie kürzere Blöcke."]),
    it: item("Pianificazione a blocchi", "Organizza la giornata in blocchi di concentrazione per ridurre il sovraccarico.", ["stress","pianificazione","concentrazione","sovraccarico"], [["Elenca i compiti","Scrivi le attività che occupano la mente."],["Stima il tempo","Assegna a ogni attività un tempo realistico."],["Crea i blocchi","Inserisci le attività in blocchi di concentrazione."],["Aggiungi margini","Lascia tempo di transizione tra i blocchi."],["Lavora sul blocco","Concentrati sul compito e silenzia le notifiche."]].map(([title,description])=>({title,description})), ["Riduce la fatica decisionale","Crea struttura","Protegge il tempo di concentrazione"], ["Rivedi il piano a metà giornata.","Usa blocchi più brevi quando hai poca energia."]),
    pt: item("Blocos de tempo", "Organize o dia em blocos de foco para reduzir a sobrecarga e aumentar o controle.", ["estresse","planejamento","foco","sobrecarga"], [["Liste as tarefas","Anote as tarefas que ocupam sua atenção."],["Estime o tempo","Dê a cada tarefa uma duração realista."],["Crie blocos","Distribua as tarefas em blocos de foco."],["Inclua intervalos","Reserve transições entre os blocos."],["Trabalhe um bloco","Foque na tarefa e silencie notificações."]].map(([title,description])=>({title,description})), ["Reduz fadiga decisória","Cria estrutura","Protege o tempo de foco"], ["Revise o plano no meio do dia.","Use blocos menores quando a energia estiver baixa."])
  },
  "local-stress-worry-postponement": {
    en: item("Worry Postponement", "Postpone worries to a scheduled period and reclaim the rest of the day.", ["stress","worry","rumination","CBT"], [["Notice","Recognize the worry without entering into it."],["Schedule","Choose a specific worry period later today."],["Record","Write the worry down so it does not need to be remembered."],["Return","Bring attention back to the present task."],["Review","At worry time, review the list and address what still matters."]].map(([title,description])=>({title,description})), ["Reduces rumination","Builds control over attention","Frees mental space"], ["Do not argue with the worry; note and postpone it.","Schedule worry time well before bedtime."]),
    he: item("דחיית הדאגה", "דחו דאגות לזמן מתוכנן והשיבו לעצמכם את שאר היום.", ["לחץ","דאגה","הרהור חוזר","CBT"], [["זיהוי","הבחינו בדאגה בלי להיסחף לתוכה."],["תזמון","בחרו זמן מוגדר לדאגה בהמשך היום."],["רישום","כתבו את הדאגה כדי שלא תצטרכו לזכור אותה."],["חזרה","החזירו את הקשב למשימה הנוכחית."],["בדיקה","בזמן שנקבע עברו על הרשימה וטפלו במה שעדיין חשוב."]].map(([title,description])=>({title,description})), ["הפחתת הרהור חוזר","שליטה טובה יותר בקשב","פינוי מרחב מחשבתי"], ["אל תתווכחו עם הדאגה; רשמו ודחו אותה.","קבעו את זמן הדאגה זמן רב לפני השינה."]),
    es: item("Posponer la preocupación", "Aplaza las preocupaciones a un periodo programado y recupera el resto del día.", ["estrés","preocupación","rumiación","TCC"], [["Detecta","Reconoce la preocupación sin entrar en ella."],["Programa","Elige un periodo concreto para preocuparte más tarde."],["Anota","Escríbela para no tener que recordarla."],["Regresa","Devuelve la atención a la tarea presente."],["Revisa","En el horario elegido, atiende lo que aún importe."]].map(([title,description])=>({title,description})), ["Reduce la rumiación","Mejora el control de la atención","Libera espacio mental"], ["No discutas con la preocupación; anótala.","Hazlo bastante antes de acostarte."]),
    fr: item("Reporter les inquiétudes", "Reportez les inquiétudes à une période prévue et récupérez le reste de la journée.", ["stress","inquiétude","rumination","TCC"], [["Repérer","Reconnaissez l’inquiétude sans vous y engager."],["Planifier","Choisissez une période précise plus tard."],["Noter","Écrivez-la pour ne pas devoir la retenir."],["Revenir","Ramenez l’attention à la tâche présente."],["Réviser","Au moment prévu, traitez ce qui reste pertinent."]].map(([title,description])=>({title,description})), ["Réduit la rumination","Améliore le contrôle attentionnel","Libère l’esprit"], ["Ne débattez pas avec l’inquiétude : notez-la.","Planifiez ce temps bien avant le coucher."]),
    de: item("Sorgen aufschieben", "Verschiebe Sorgen auf eine feste Zeit und gewinne den übrigen Tag zurück.", ["Stress","Sorgen","Grübeln","KVT"], [["Bemerken","Erkenne die Sorge, ohne dich hineinziehen zu lassen."],["Planen","Lege später am Tag eine feste Sorgenzeit fest."],["Notieren","Schreibe die Sorge auf, damit du sie nicht festhalten musst."],["Zurückkehren","Lenke die Aufmerksamkeit zurück zur aktuellen Aufgabe."],["Prüfen","Bearbeite zur Sorgenzeit, was noch relevant ist."]].map(([title,description])=>({title,description})), ["Verringert Grübeln","Stärkt Aufmerksamkeitskontrolle","Schafft mentalen Raum"], ["Diskutiere nicht mit der Sorge; notiere sie.","Plane die Sorgenzeit deutlich vor dem Schlafen."]),
    it: item("Rimandare le preoccupazioni", "Rimanda le preoccupazioni a un periodo stabilito e recupera il resto della giornata.", ["stress","preoccupazione","ruminazione","CBT"], [["Nota","Riconosci la preoccupazione senza seguirla."],["Programma","Scegli un orario specifico più tardi."],["Annota","Scrivila per non doverla ricordare."],["Ritorna","Riporta l’attenzione al compito presente."],["Rivedi","All’orario scelto affronta ciò che è ancora rilevante."]].map(([title,description])=>({title,description})), ["Riduce la ruminazione","Aumenta il controllo attentivo","Libera spazio mentale"], ["Non discutere con la preoccupazione: annotala.","Programma il momento molto prima di dormire."]),
    pt: item("Adiamento da preocupação", "Adie preocupações para um período marcado e recupere o restante do dia.", ["estresse","preocupação","ruminação","TCC"], [["Perceba","Reconheça a preocupação sem entrar nela."],["Agende","Escolha um horário específico mais tarde."],["Registre","Anote para não precisar mantê-la na memória."],["Retorne","Traga a atenção de volta à tarefa atual."],["Revise","No horário marcado, trate o que ainda importa."]].map(([title,description])=>({title,description})), ["Reduz ruminação","Melhora o controle da atenção","Libera espaço mental"], ["Não discuta com a preocupação; anote-a.","Agende o período bem antes de dormir."])
  },
  "local-stress-problem-solving": {
    en: item("Structured Problem Solving", "Turn a manageable stressor into a clear action plan.", ["stress","problem-solving","planning","coping"], [["Define","State one specific problem within your influence."],["Generate","List several possible solutions without judging them."],["Evaluate","Compare feasibility and likely effectiveness."],["Plan","Choose an option and define the first steps and timing."],["Review","After trying it, assess what helped and what to adjust."]].map(([title,description])=>({title,description})), ["Converts worry into action","Reduces avoidance","Builds confidence"], ["Use this only for problems you can influence.","If safety is involved, seek appropriate professional or emergency support."]),
    he: item("פתרון בעיות מובנה", "הפכו גורם לחץ שניתן להשפיע עליו לתוכנית פעולה ברורה.", ["לחץ","פתרון בעיות","תכנון","התמודדות"], [["הגדרה","נסחו בעיה אחת ממוקדת שנמצאת בתחום השפעתכם."],["העלאת אפשרויות","רשמו כמה פתרונות בלי לשפוט אותם."],["הערכה","השוו היתכנות ויעילות צפויה."],["תכנון","בחרו אפשרות והגדירו צעדים ראשונים ומועד."],["בדיקה","לאחר הניסיון בדקו מה עזר ומה דורש התאמה."]].map(([title,description])=>({title,description})), ["הפיכת דאגה לפעולה","הפחתת הימנעות","חיזוק ביטחון"], ["השתמשו בתרגיל רק לבעיה שניתן להשפיע עליה.","כשיש סכנה, פנו לתמיכה מקצועית או לשירותי חירום מתאימים."]),
    es: item("Resolución estructurada de problemas", "Convierte un estresor manejable en un plan de acción claro.", ["estrés","resolución","planificación","afrontamiento"], [["Define","Formula un problema específico bajo tu influencia."],["Genera","Anota varias soluciones sin juzgarlas."],["Evalúa","Compara viabilidad y eficacia probable."],["Planifica","Elige una opción y fija los primeros pasos."],["Revisa","Tras probarla, valora qué ayudó y qué ajustar."]].map(([title,description])=>({title,description})), ["Convierte preocupación en acción","Reduce evitación","Aumenta confianza"], ["Úsalo solo para problemas sobre los que puedes influir.","Si hay riesgo, busca apoyo profesional o de emergencia."]),
    fr: item("Résolution structurée de problème", "Transformez un facteur de stress gérable en plan d’action clair.", ["stress","résolution","planification","adaptation"], [["Définir","Formulez un problème précis sous votre influence."],["Générer","Listez plusieurs solutions sans les juger."],["Évaluer","Comparez faisabilité et efficacité probable."],["Planifier","Choisissez une option et fixez les premières étapes."],["Réviser","Après l’essai, identifiez ce qui aide et ce qui doit changer."]].map(([title,description])=>({title,description})), ["Transforme l’inquiétude en action","Réduit l’évitement","Renforce la confiance"], ["Réservez cet exercice aux problèmes influençables.","En cas de danger, cherchez une aide professionnelle ou urgente."]),
    de: item("Strukturierte Problemlösung", "Verwandle einen beeinflussbaren Stressor in einen klaren Handlungsplan.", ["Stress","Problemlösung","Planung","Bewältigung"], [["Definieren","Formuliere ein konkretes, beeinflussbares Problem."],["Sammeln","Notiere mehrere Lösungen, ohne sie zu bewerten."],["Bewerten","Vergleiche Machbarkeit und erwartete Wirkung."],["Planen","Wähle eine Option und lege erste Schritte fest."],["Prüfen","Bewerte nach dem Versuch Wirkung und Anpassungsbedarf."]].map(([title,description])=>({title,description})), ["Macht aus Sorge Handlung","Verringert Vermeidung","Stärkt Zuversicht"], ["Nur für beeinflussbare Probleme nutzen.","Bei Gefahr professionelle oder Notfallhilfe suchen."]),
    it: item("Soluzione strutturata dei problemi", "Trasforma un fattore di stress gestibile in un piano d’azione chiaro.", ["stress","problemi","pianificazione","coping"], [["Definisci","Formula un problema specifico su cui puoi influire."],["Genera","Elenca varie soluzioni senza giudicarle."],["Valuta","Confronta fattibilità ed efficacia probabile."],["Pianifica","Scegli un’opzione e stabilisci i primi passi."],["Rivedi","Dopo la prova, valuta cosa ha aiutato e cosa modificare."]].map(([title,description])=>({title,description})), ["Trasforma la preoccupazione in azione","Riduce l’evitamento","Aumenta la fiducia"], ["Usalo solo per problemi influenzabili.","In caso di pericolo cerca aiuto professionale o urgente."]),
    pt: item("Resolução estruturada de problemas", "Transforme um estressor administrável em um plano de ação claro.", ["estresse","resolução","planejamento","enfrentamento"], [["Defina","Formule um problema específico sob sua influência."],["Gere","Liste várias soluções sem julgá-las."],["Avalie","Compare viabilidade e eficácia provável."],["Planeje","Escolha uma opção e defina os primeiros passos."],["Revise","Após testar, avalie o que ajudou e o que ajustar."]].map(([title,description])=>({title,description})), ["Converte preocupação em ação","Reduz evitação","Fortalece confiança"], ["Use apenas para problemas influenciáveis.","Se houver perigo, procure apoio profissional ou de emergência."])
  },
  "local-stress-progressive-muscle": {
    en: item("Progressive Muscle Relaxation", "Release physical tension by gently tensing and relaxing muscle groups.", ["stress","relaxation","tension","body"], [["Settle","Sit or lie comfortably; avoid movements that cause pain."],["Upper body","Gently tense hands, arms, shoulders and face, then release."],["Torso","Briefly tense chest and abdomen, then release on a long exhale."],["Lower body","Gently tense legs and feet, then release."],["Scan","Notice the contrast between tension and relaxation."]].map(([title,description])=>({title,description})), ["Relieves physical tension","Improves body awareness","Supports relaxation"], ["Use gentle effort and never strain or hold your breath.","Skip any injured or painful area."]),
    he: item("הרפיית שרירים הדרגתית", "שחררו מתח גופני באמצעות כיווץ עדין והרפיה של קבוצות שרירים.", ["לחץ","הרפיה","מתח","גוף"], [["התמקמות","שבו או שכבו בנוחות והימנעו מתנועה מכאיבה."],["פלג גוף עליון","כווצו בעדינות ידיים, זרועות, כתפיים ופנים ואז הרפו."],["גו","כווצו בקצרה חזה ובטן והרפו בנשיפה ארוכה."],["פלג גוף תחתון","כווצו בעדינות רגליים וכפות רגליים ואז הרפו."],["סריקה","הבחינו בהבדל בין מתח להרפיה."]].map(([title,description])=>({title,description})), ["הקלה במתח גופני","שיפור מודעות לגוף","תמיכה בהרפיה"], ["הפעילו כוח עדין בלבד ואל תעצרו נשימה.","דלגו על אזור פצוע או כואב."]),
    es: item("Relajación muscular progresiva", "Libera tensión física al tensar suavemente y relajar grupos musculares.", ["estrés","relajación","tensión","cuerpo"], [["Acomódate","Siéntate o túmbate; evita movimientos dolorosos."],["Parte superior","Tensa suavemente manos, brazos, hombros y rostro; suelta."],["Torso","Tensa brevemente pecho y abdomen; suelta al exhalar."],["Parte inferior","Tensa suavemente piernas y pies; suelta."],["Escanea","Observa el contraste entre tensión y relajación."]].map(([title,description])=>({title,description})), ["Alivia tensión física","Mejora conciencia corporal","Favorece relajación"], ["Usa esfuerzo suave y no contengas la respiración.","Omite zonas lesionadas o dolorosas."]),
    fr: item("Relaxation musculaire progressive", "Libérez les tensions en contractant doucement puis relâchant les muscles.", ["stress","relaxation","tension","corps"], [["S’installer","Asseyez-vous ou allongez-vous; évitez tout mouvement douloureux."],["Haut du corps","Contractez doucement mains, bras, épaules et visage, puis relâchez."],["Torse","Contractez brièvement poitrine et ventre, puis relâchez en expirant."],["Bas du corps","Contractez doucement jambes et pieds, puis relâchez."],["Balayer","Observez le contraste entre tension et détente."]].map(([title,description])=>({title,description})), ["Soulage les tensions","Améliore la conscience corporelle","Favorise la détente"], ["Restez doux et ne retenez pas votre souffle.","Évitez toute zone blessée ou douloureuse."]),
    de: item("Progressive Muskelentspannung", "Löse körperliche Spannung durch sanftes Anspannen und Entspannen.", ["Stress","Entspannung","Spannung","Körper"], [["Ankommen","Setze oder lege dich bequem hin; vermeide schmerzhafte Bewegungen."],["Oberkörper","Spanne Hände, Arme, Schultern und Gesicht sanft an; löse."],["Rumpf","Spanne Brust und Bauch kurz an; löse beim Ausatmen."],["Unterkörper","Spanne Beine und Füße sanft an; löse."],["Nachspüren","Beobachte den Unterschied zwischen Spannung und Entspannung."]].map(([title,description])=>({title,description})), ["Lindert körperliche Spannung","Stärkt Körperwahrnehmung","Fördert Entspannung"], ["Nur sanft anspannen und nie die Luft anhalten.","Verletzte oder schmerzhafte Bereiche auslassen."]),
    it: item("Rilassamento muscolare progressivo", "Riduci la tensione contraendo dolcemente e rilassando i gruppi muscolari.", ["stress","rilassamento","tensione","corpo"], [["Preparati","Siediti o sdraiati; evita movimenti dolorosi."],["Parte superiore","Contrai dolcemente mani, braccia, spalle e viso; rilascia."],["Busto","Contrai brevemente petto e addome; rilascia espirando."],["Parte inferiore","Contrai dolcemente gambe e piedi; rilascia."],["Scansione","Nota il contrasto tra tensione e rilassamento."]].map(([title,description])=>({title,description})), ["Allevia la tensione","Migliora la consapevolezza corporea","Favorisce il rilassamento"], ["Usa uno sforzo lieve e non trattenere il respiro.","Salta aree ferite o dolorose."]),
    pt: item("Relaxamento muscular progressivo", "Libere tensão ao contrair suavemente e relaxar grupos musculares.", ["estresse","relaxamento","tensão","corpo"], [["Acomode-se","Sente ou deite; evite movimentos dolorosos."],["Parte superior","Contraia suavemente mãos, braços, ombros e rosto; solte."],["Tronco","Contraia peito e abdômen brevemente; solte ao expirar."],["Parte inferior","Contraia suavemente pernas e pés; solte."],["Escaneie","Observe o contraste entre tensão e relaxamento."]].map(([title,description])=>({title,description})), ["Alivia tensão física","Melhora consciência corporal","Favorece relaxamento"], ["Use esforço leve e não prenda a respiração.","Pule áreas lesionadas ou doloridas."])
  },
  "local-stress-cognitive-reframing": {
    en: item("Stress Reframing", "Develop a balanced and useful perspective on a specific stressor.", ["stress","reframing","perspective","resilience"], [["Name it","Write the specific stressor."],["Capture the frame","Write how you are currently interpreting it."],["Question it","Ask what evidence supports or challenges that view."],["Broaden","Identify learning, resources, or a manageable challenge."],["Rewrite","Create a balanced perspective and re-rate stress."]].map(([title,description])=>({title,description})), ["Reduces stress reactivity","Builds flexibility","Supports resilience"], ["Reframing is not denial or forced positivity.","Keep valid risks and practical actions in view."]),
    he: item("מסגור מחדש של לחץ", "פתחו נקודת מבט מאוזנת ומועילה על גורם לחץ מסוים.", ["לחץ","מסגור מחדש","נקודת מבט","חוסן"], [["מתן שם","כתבו מהו גורם הלחץ המסוים."],["תיעוד המסגרת","כתבו כיצד אתם מפרשים אותו כעת."],["בדיקה","שאלו אילו ראיות תומכות בפרשנות ואילו מאתגרות אותה."],["הרחבה","זהו למידה, משאבים או אתגר שניתן לנהל."],["ניסוח מחדש","צרו נקודת מבט מאוזנת ודרגו שוב את הלחץ."]].map(([title,description])=>({title,description})), ["הפחתת תגובתיות ללחץ","פיתוח גמישות","חיזוק חוסן"], ["מסגור מחדש אינו הכחשה או חיוביות כפויה.","שמרו בתמונה סיכונים אמיתיים ופעולות מעשיות."]),
    es: item("Reencuadre del estrés", "Desarrolla una perspectiva equilibrada y útil sobre un estresor concreto.", ["estrés","reencuadre","perspectiva","resiliencia"], [["Nómbralo","Escribe el estresor específico."],["Captura el marco","Anota cómo lo interpretas ahora."],["Cuestiónalo","Busca evidencias a favor y en contra."],["Amplía","Identifica aprendizajes, recursos o un reto manejable."],["Reescribe","Crea una perspectiva equilibrada y vuelve a valorar el estrés."]].map(([title,description])=>({title,description})), ["Reduce reactividad","Desarrolla flexibilidad","Apoya resiliencia"], ["No es negación ni positividad forzada.","Mantén presentes los riesgos reales y las acciones prácticas."]),
    fr: item("Recadrage du stress", "Développez une perspective équilibrée et utile sur un facteur de stress précis.", ["stress","recadrage","perspective","résilience"], [["Nommer","Écrivez le facteur de stress précis."],["Saisir le cadre","Notez votre interprétation actuelle."],["Questionner","Cherchez les preuves qui la soutiennent ou la nuancent."],["Élargir","Repérez apprentissages, ressources ou défi gérable."],["Réécrire","Créez une perspective équilibrée et réévaluez le stress."]].map(([title,description])=>({title,description})), ["Réduit la réactivité","Développe la flexibilité","Soutient la résilience"], ["Ce n’est ni du déni ni de la positivité forcée.","Gardez les risques réels et les actions utiles en vue."]),
    de: item("Stress neu bewerten", "Entwickle eine ausgewogene, hilfreiche Sicht auf einen konkreten Stressor.", ["Stress","Neubewertung","Perspektive","Resilienz"], [["Benennen","Schreibe den konkreten Stressor auf."],["Deutung erfassen","Notiere deine aktuelle Interpretation."],["Prüfen","Suche Belege dafür und dagegen."],["Erweitern","Erkenne Lernchancen, Ressourcen oder eine machbare Herausforderung."],["Neu formulieren","Formuliere ausgewogen und bewerte den Stress erneut."]].map(([title,description])=>({title,description})), ["Senkt Stressreaktivität","Stärkt Flexibilität","Fördert Resilienz"], ["Neubewertung ist keine Verleugnung.","Behalte reale Risiken und praktische Schritte im Blick."]),
    it: item("Riformulare lo stress", "Sviluppa una prospettiva equilibrata e utile su un fattore di stress specifico.", ["stress","riformulazione","prospettiva","resilienza"], [["Nomina","Scrivi il fattore di stress specifico."],["Cogli la cornice","Annota come lo interpreti ora."],["Metti in discussione","Cerca prove a favore e contro."],["Amplia","Individua apprendimento, risorse o una sfida gestibile."],["Riscrivi","Crea una prospettiva equilibrata e rivaluta lo stress."]].map(([title,description])=>({title,description})), ["Riduce la reattività","Sviluppa flessibilità","Sostiene la resilienza"], ["Non è negazione né positività forzata.","Considera rischi reali e azioni pratiche."]),
    pt: item("Reenquadramento do estresse", "Desenvolva uma perspectiva equilibrada e útil sobre um estressor específico.", ["estresse","reenquadramento","perspectiva","resiliência"], [["Nomeie","Escreva o estressor específico."],["Registre a visão","Anote como você o interpreta agora."],["Questione","Procure evidências favoráveis e contrárias."],["Amplie","Identifique aprendizados, recursos ou um desafio administrável."],["Reescreva","Crie uma visão equilibrada e reavalie o estresse."]].map(([title,description])=>({title,description})), ["Reduz reatividade","Desenvolve flexibilidade","Apoia resiliência"], ["Não é negação nem positividade forçada.","Considere riscos reais e ações práticas."])
  },
  "69519590cc9f81fd9daed0b2": {
    en: item("Mindful Walking Meditation", "Turn ordinary walking into a present-focused moving meditation.", ["mindfulness","walking","movement","body awareness"], [["Choose a safe path","Use a clear, level route where you can walk without traffic or obstacles."],["Slow down","Walk more slowly and notice each foot lifting and landing."],["Feel the body","Notice balance, leg movement, and the swing of the arms."],["Return attention","When the mind wanders, gently return to the next step."],["Finish","Stop, feel both feet on the ground, and notice your surroundings."]].map(([title,description])=>({title,description})), ["Combines movement and mindfulness","Improves body awareness","Supports calm focus"], ["Keep your eyes open and prioritize physical safety.","Do not use while driving, crossing roads, or where balance is unsafe."]),
    he: item("מדיטציית הליכה מודעת", "הפכו הליכה רגילה למדיטציה בתנועה הממוקדת ברגע הנוכחי.", ["קשיבות","הליכה","תנועה","מודעות לגוף"], [["בחירת מסלול בטוח","בחרו דרך ישרה ופנויה, ללא תנועה או מכשולים."],["האטה","לכו לאט יותר והבחינו בכל הרמה והנחה של כף הרגל."],["תחושת הגוף","שימו לב לשיווי המשקל, לתנועת הרגליים ולתנודת הידיים."],["החזרת הקשב","כשהמחשבה נודדת, החזירו בעדינות את הקשב לצעד הבא."],["סיום","עצרו, הרגישו את שתי כפות הרגליים ושימו לב לסביבה."]].map(([title,description])=>({title,description})), ["שילוב תנועה וקשיבות","שיפור מודעות לגוף","תמיכה ברוגע ובמיקוד"], ["השאירו עיניים פקוחות והעדיפו בטיחות גופנית.","אין לתרגל בזמן נהיגה, חציית כביש או כששיווי המשקל אינו בטוח."]),
    es: item("Meditación caminando", "Convierte la caminata cotidiana en una meditación en movimiento centrada en el presente.", ["atención plena","caminar","movimiento","conciencia corporal"], [["Elige una ruta segura","Usa un camino llano y despejado, sin tráfico ni obstáculos."],["Ve más lento","Nota cada pie al levantarse y apoyarse."],["Siente el cuerpo","Observa el equilibrio, las piernas y el movimiento de brazos."],["Vuelve","Si la mente se distrae, regresa con suavidad al siguiente paso."],["Termina","Detente, siente ambos pies y observa el entorno."]].map(([title,description])=>({title,description})), ["Une movimiento y atención plena","Mejora conciencia corporal","Favorece calma y enfoque"], ["Mantén los ojos abiertos y prioriza la seguridad.","No practiques conduciendo, cruzando calles o con equilibrio inseguro."]),
    fr: item("Méditation en marchant", "Transformez la marche ordinaire en méditation en mouvement ancrée dans le présent.", ["pleine conscience","marche","mouvement","conscience corporelle"], [["Choisir un trajet sûr","Prenez un chemin plat et dégagé, sans circulation ni obstacle."],["Ralentir","Sentez chaque pied se lever puis se poser."],["Sentir le corps","Observez l’équilibre, les jambes et le balancement des bras."],["Revenir","Si l’esprit s’égare, revenez doucement au pas suivant."],["Terminer","Arrêtez-vous, sentez vos deux pieds et observez l’environnement."]].map(([title,description])=>({title,description})), ["Associe mouvement et pleine conscience","Améliore la conscience corporelle","Favorise calme et attention"], ["Gardez les yeux ouverts et privilégiez la sécurité.","Ne pratiquez pas en conduisant, en traversant ou si l’équilibre est précaire."]),
    de: item("Achtsame Gehmeditation", "Mache gewöhnliches Gehen zu einer gegenwartsbezogenen Meditation in Bewegung.", ["Achtsamkeit","Gehen","Bewegung","Körperwahrnehmung"], [["Sicheren Weg wählen","Nutze einen ebenen, freien Weg ohne Verkehr oder Hindernisse."],["Verlangsamen","Spüre, wie jeder Fuß sich hebt und aufsetzt."],["Körper spüren","Beobachte Gleichgewicht, Beine und Armschwung."],["Zurückkehren","Wenn Gedanken abschweifen, kehre sanft zum nächsten Schritt zurück."],["Beenden","Halte an, spüre beide Füße und nimm die Umgebung wahr."]].map(([title,description])=>({title,description})), ["Verbindet Bewegung und Achtsamkeit","Stärkt Körperwahrnehmung","Fördert ruhigen Fokus"], ["Augen offen halten und Sicherheit priorisieren.","Nicht beim Fahren, Straßenqueren oder unsicherem Gleichgewicht üben."]),
    it: item("Meditazione camminata consapevole", "Trasforma il cammino quotidiano in una meditazione in movimento centrata sul presente.", ["consapevolezza","cammino","movimento","corpo"], [["Scegli un percorso sicuro","Usa un tragitto piano e libero, senza traffico o ostacoli."],["Rallenta","Nota ogni piede che si solleva e si appoggia."],["Senti il corpo","Osserva equilibrio, gambe e oscillazione delle braccia."],["Ritorna","Se la mente vaga, torna dolcemente al passo successivo."],["Concludi","Fermati, senti entrambi i piedi e osserva l’ambiente."]].map(([title,description])=>({title,description})), ["Unisce movimento e consapevolezza","Migliora la percezione corporea","Favorisce calma e concentrazione"], ["Tieni gli occhi aperti e dai priorità alla sicurezza.","Non praticare guidando, attraversando strade o con equilibrio instabile."]),
    pt: item("Meditação caminhando", "Transforme a caminhada comum em meditação em movimento focada no presente.", ["atenção plena","caminhada","movimento","consciência corporal"], [["Escolha um trajeto seguro","Use um caminho plano e livre, sem trânsito ou obstáculos."],["Diminua o ritmo","Perceba cada pé se levantando e tocando o chão."],["Sinta o corpo","Observe equilíbrio, pernas e movimento dos braços."],["Retorne","Se a mente se distrair, volte suavemente ao próximo passo."],["Finalize","Pare, sinta os dois pés e observe o ambiente."]].map(([title,description])=>({title,description})), ["Une movimento e atenção plena","Melhora consciência corporal","Favorece calma e foco"], ["Mantenha os olhos abertos e priorize a segurança.","Não pratique dirigindo, atravessando ruas ou com equilíbrio inseguro."])
  }
};
