/**
 * @file src/utils/workbookContentMetadata.js
 *
 * Workbook Content Metadata — Phase 10 Routing Intelligence
 *
 * Provides structured content descriptions for the 7 Hebrew adult therapeutic
 * workbooks so that the routing layer can match user queries to the correct
 * workbook, rather than to a narrower individual worksheet.
 *
 * Each workbook entry contains:
 *   - id / slug        — matches the TherapeuticForms registry
 *   - titleHe          — Hebrew workbook title
 *   - descriptionHe    — short clinical description in Hebrew
 *   - internalForms    — list of internal form topics (informational)
 *   - topicKeywords    — Hebrew word/phrase list used for scoring against user queries
 *   - whenToUseHe      — plain-Hebrew usage guidance (for AI context)
 *   - preferWhenHe     — signals that trigger workbook preference over individual sheets
 *   - lowerPriorityIndividualForms — individual form IDs NOT to prefer when this workbook fits
 *
 * Usage:
 *   Import WORKBOOK_CONTENT_METADATA in resolveWorkbookIntent.js for scoring.
 *   Do NOT import from this file in production app UI code.
 */

/**
 * @typedef {Object} WorkbookMeta
 * @property {string}   id
 * @property {string}   slug
 * @property {string}   titleHe
 * @property {string}   descriptionHe
 * @property {string[]} internalForms
 * @property {string[]} topicKeywords
 * @property {string}   whenToUseHe
 * @property {string[]} preferWhenHe
 * @property {string[]} lowerPriorityIndividualForms
 */

/** @type {WorkbookMeta[]} */
export const WORKBOOK_CONTENT_METADATA = [
  // ── 1. Formulation & Mapping ─────────────────────────────────────────────────
  {
    id: 'tf-adults-formulation-mapping-premium-he',
    slug: 'adults-formulation-mapping-premium-he',
    titleHe: 'קונטרס מיפוי והמשגה',
    descriptionHe:
      'קונטרס טיפולי מלא לניסוח מקרה, מיפוי הקושי המרכזי, זיהוי דפוסים חוזרים, טריגרים וגורמים תורמים.',
    internalForms: [
      'מיפוי הקושי המרכזי',
      'ניסוח מקרה',
      'זיהוי דפוסים חוזרים',
      'טריגרים',
      'מחשבות, רגשות, גוף והתנהגות',
      'גורמי רקע',
      'גורמי שימור',
      'מטרות טיפוליות',
    ],
    topicKeywords: [
      'ניסוח מקרה',
      'מיפוי והמשגה',
      'מיפוי',
      'המשגה',
      'גורמי שימור',
      'גורמי רקע',
      'דפוסים חוזרים',
      'להבין את הבעיה',
      'תמונה כללית',
      'בירור ראשוני',
      'הערכה ראשונית',
      'מטרות טיפוליות',
    ],
    whenToUseHe:
      'כאשר המטפל והמטופל רוצים למפות את הבעיה המרכזית, להבין את ההיסטוריה, לזהות דפוסים חוזרים ולנסח מקרה טיפולי.',
    preferWhenHe: [
      'מיפוי',
      'המשגה',
      'להבין את הבעיה',
      'ניסוח מקרה',
      'תמונה כללית',
      'בירור ראשוני',
      'מה קורה לי',
      'דפוסים חוזרים',
    ],
    lowerPriorityIndividualForms: [],
  },

  // ── 2. Awareness & Identification ────────────────────────────────────────────
  {
    id: 'tf-adults-awareness-identification-premium-he',
    slug: 'adults-awareness-identification-premium-he',
    titleHe: 'קונטרס זיהוי מחשבות, רגשות, תחושות והתנהגות',
    descriptionHe:
      'קונטרס טיפולי מלא לזיהוי וניטור מחשבות, רגשות, תחושות גוף, התנהגויות ושרשרת התגובה.',
    internalForms: [
      'זיהוי אירוע ומחשבה ראשונית',
      'יומן מחשבות אוטומטיות',
      'זיהוי רגשות ועוצמתם',
      'מפת תחושות גוף וסימנים פיזיים',
      'תגובה והתנהגות בפועל',
      'שרשרת מצב-מחשבה-רגש-גוף-התנהגות',
      'דפוסים חוזרים וטריגרים',
      'סיכום ראשוני להמשך עבודה טיפולית',
    ],
    topicKeywords: [
      'זיהוי מחשבות',
      'זיהוי רגשות',
      'זיהוי תחושות',
      'זיהוי התנהגות',
      'ניטור מחשבות',
      'ניטור רגשות',
      'יומן מחשבות',
      'מעקב מחשבות',
      'תחושות גוף',
      'שרשרת תגובה',
      'שרשרת מחשבה',
      'להבין מה אני מרגיש',
      'להבין מה אני חושב',
    ],
    whenToUseHe:
      'כאשר המטופל רוצה ללמוד לזהות ולנטר מחשבות, רגשות, תחושות גוף והתנהגויות — הבסיס לכל עבודה CBT.',
    preferWhenHe: [
      'זיהוי מחשבות',
      'ניטור מחשבות',
      'זיהוי רגשות',
      'תחושות גוף',
      'דפוסי התנהגות',
      'שרשרת תגובה',
      'להבין מה אני מרגיש',
      'להבין מה אני חושב',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
    ],
  },

  // ── 3. Cognitive Flexibility ─────────────────────────────────────────────────
  {
    id: 'tf-adults-cognitive-flexibility-premium-he',
    slug: 'adults-cognitive-flexibility-premium-he',
    titleHe: 'קונטרס הפרכת מחשבות וגמישות מחשבתית',
    descriptionHe:
      'קונטרס טיפולי מלא לערעור מחשבות אוטומטיות, בדיקת ראיות, שאלות סוקרטיות, עיוותי חשיבה, פרספקטיבות חלופיות ואמונות מגבילות.',
    internalForms: [
      'זיהוי מחשבה אוטומטית והנחת יסוד',
      'בדיקת ראיות בעד ונגד המחשבה',
      'שאלות סוקרטיות להפרכת מחשבה',
      'זיהוי עיוותי חשיבה והחלפת ניסוח',
      'בדיקת פרופורציות והערכת סיכון מחדש',
      'פרספקטיבות חלופיות על אותו מצב',
      'מחשבה מתווכת בין קיצוניות לאיזון',
      'דיבור עצמי תומך ומכוון פעולה',
      'ערעור אמונה מגבילה ובניית אמונה גמישה',
      'ניסוי התנהגותי לבדיקת מחשבה',
      'תסריט תגובה למצבי טריגר',
      'סיכום מחשבה מאוזנת ותכנית המשך',
    ],
    topicKeywords: [
      'הפרכת מחשבות',
      'גמישות מחשבתית',
      'מחשבות שליליות',
      'מחשבות אוטומטיות',
      'ערעור מחשבות',
      'בדיקת ראיות',
      'שאלות סוקרטיות',
      'עיוותי חשיבה',
      'פרופורציות',
      'פרספקטיבה',
      'מחשבה מתווכת',
      'דיבור עצמי',
      'אמונות מגבילות',
      'להפריך',
    ],
    whenToUseHe:
      'כאשר המטופל רוצה ללמוד להפריך מחשבות שליליות, לפתח גמישות מחשבתית, לבדוק ראיות ולאתגר עיוותי חשיבה — עבודה קוגניטיבית מעמיקה.',
    preferWhenHe: [
      'הפרכת מחשבות',
      'מחשבות שליליות',
      'ערעור מחשבות',
      'בדיקת ראיות',
      'שאלות סוקרטיות',
      'עיוותי חשיבה',
      'פרופורציות',
      'פרספקטיבה',
      'מחשבה מתווכת',
      'דיבור עצמי',
      'אמונות מגבילות',
      'גמישות מחשבתית',
    ],
    // When user asks for a workbook/קונטרס on negative thoughts, do NOT send only
    // cbt-thought-record — send this workbook instead.
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
      'tf-adults-cognitive-distortions-worksheet',
    ],
  },

  // ── 4. Emotional Regulation ──────────────────────────────────────────────────
  {
    id: 'tf-adults-emotional-regulation-premium-he',
    slug: 'adults-emotional-regulation-premium-he',
    titleHe: 'קונטרס זיהוי וויסות רגשי',
    descriptionHe:
      'קונטרס טיפולי מלא לזיהוי רגשות חזקים, ויסות רגשי, עבודה על פחד, חרדה, עצב, כעס, בושה ואשמה.',
    internalForms: [
      'מפת רגשות ראשונית',
      'עוצמת הרגש לאורך זמן',
      'פחד וחרדה',
      'עצב, ירידה ומועקה',
      'כעס ותסכול',
      'בושה ואשמה',
      'אירועים שמפעילים רגשות',
      'תחושות גוף ודחפים לפעולה',
      'תגובה רגשית לעומת תגובה מווסתת',
      'כלים לוויסות בזמן אמת',
      'ויסות לפני, במהלך ואחרי אירוע',
      'רגשות מעורבים וקונפליקט פנימי',
      'שיחה פנימית מרגיעה',
      'סיכום תכנית ויסות אישית',
    ],
    topicKeywords: [
      'ויסות רגשי',
      'הצפה רגשית',
      'רגשות חזקים',
      'פחד',
      'חרדה',
      'עצב',
      'כעס',
      'בושה',
      'אשמה',
      'דחפים',
      'התפרצות',
      'רגשות מעורבים',
      'להירגע',
      'לשלוט ברגש',
    ],
    whenToUseHe:
      'כאשר המטופל מדווח על רגשות חזקים, הצפה רגשית, קושי להירגע, או רוצה לפתח כלים לוויסות רגשי.',
    preferWhenHe: [
      'ויסות רגשי',
      'רגשות חזקים',
      'הצפה רגשית',
      'פחד',
      'חרדה',
      'עצב',
      'כעס',
      'בושה',
      'אשמה',
      'דחפים',
      'התפרצות',
      'רגשות מעורבים',
      'להירגע',
      'לשלוט ברגש',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-mood-tracking-sheet',
    ],
  },

  // ── 5. Coping & Change ────────────────────────────────────────────────────────
  {
    id: 'tf-adults-coping-change-premium-he',
    slug: 'adults-coping-change-premium-he',
    titleHe: 'קונטרס התמודדות ושינוי',
    descriptionHe:
      'קונטרס טיפולי מלא לפיתוח מיומנויות התמודדות — דחיינות, הימנעות, הרגלים מקשים, אסרטיביות, גבולות ופתרון בעיות.',
    internalForms: [
      'מפת התמודדות אישית',
      'הימנעות וצעדים הדרגתיים',
      'דחיינות ותחילת פעולה',
      'הרגל מקשה והרגל חלופי',
      'מיומנויות חברתיות בסיסיות',
      'תקשורת אסרטיבית',
      'גבולות אישיים',
      'פתרון בעיות מעשי',
      'ניהול עומס ושגרה',
      'התמודדות עם ביקורת',
      'ויסות דחפים ותגובה לפני פעולה',
      'שימור שינוי ומניעת חזרה לדפוס',
    ],
    topicKeywords: [
      'דחיינות',
      'הימנעות',
      'הרגלים מקשים',
      'שינוי התנהגות',
      'שינוי הרגלים',
      'מיומנויות חברתיות',
      'אסרטיביות',
      'גבולות',
      'פתרון בעיות',
      'ניהול עומס',
      'ביקורת',
      'ויסות דחפים',
      'שינוי דפוסים',
      'התמודדות',
    ],
    whenToUseHe:
      'כאשר המטופל מתמודד עם דחיינות, הימנעות, הרגלים מקשים, קשיים אסרטיביים, גבולות, פתרון בעיות או שינוי דפוסי התנהגות.',
    preferWhenHe: [
      'דחיינות',
      'הימנעות',
      'הרגלים מקשים',
      'שינוי התנהגות',
      'מיומנויות חברתיות',
      'אסרטיביות',
      'גבולות',
      'פתרון בעיות',
      'עומס',
      'ביקורת',
      'דחפים',
      'שינוי דפוסים',
    ],
    // When user asks for a workbook about דחיינות/הימנעות/הרגלים מקשים,
    // do NOT attach behavioral-activation-plan — attach this workbook instead.
    lowerPriorityIndividualForms: [
      'tf-adults-behavioral-activation-plan',
      'tf-adults-weekly-coping-plan',
    ],
  },

  // ── 6. Strengths & Resilience ────────────────────────────────────────────────
  {
    id: 'tf-adults-strengths-resilience-premium-he',
    slug: 'adults-strengths-resilience-premium-he',
    titleHe: 'קונטרס כוחות וחוסן',
    descriptionHe:
      'קונטרס טיפולי מלא לחיזוק כוחות אישיים, מסוגלות, חוסן, ביטחון עצמי ורשת תמיכה.',
    internalForms: [
      'מפת כוחות אישית',
      'הצלחות קודמות כמשאב',
      'ערכים כעוגן טיפולי',
      'רשת תמיכה ומשאבים',
      'מסוגלות עצמית',
      'קול פנימי מחזק',
      'כוחות בתוך קשרים',
      'חוסן בזמן לחץ',
      'תקווה מציאותית',
      'זהות מעבר לקושי',
      'תכנית שימוש בכוחות בטיפול',
    ],
    topicKeywords: [
      'כוחות',
      'חוזקות',
      'חוסן',
      'גורמי חוסן',
      'ביטחון עצמי',
      'מסוגלות',
      'תחושת מסוגלות',
      'משאבים',
      'תקווה',
      'ערכים',
      'רשת תמיכה',
      'קול פנימי מחזק',
    ],
    whenToUseHe:
      'כאשר המטפל רוצה לחזק את המטופל, לבנות על כוחות, ביטחון עצמי, מסוגלות וחוסן — עבודה חיובית וממוקדת משאבים.',
    preferWhenHe: [
      'כוחות',
      'חוזקות',
      'חוסן',
      'גורמי חוסן',
      'ביטחון עצמי',
      'מסוגלות',
      'תחושת מסוגלות',
      'משאבים',
      'תקווה',
      'ערכים',
      'רשת תמיכה',
      'קול פנימי מחזק',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-values-and-goals-worksheet',
    ],
  },

  // ── 7. Treatment Summary & Custom Forms ──────────────────────────────────────
  {
    id: 'tf-adults-treatment-summary-custom-forms-premium-he',
    slug: 'adults-treatment-summary-custom-forms-premium-he',
    titleHe: 'קונטרס סיכום טיפול וטפסים אישיים',
    descriptionHe:
      'קונטרס טיפולי מלא לסיכום תהליך הטיפול, הישגים, כלים שנלקחו, תכנית המשך וטפסים אישיים שנבנו עם המטפל.',
    internalForms: [
      'סיכום מסע טיפולי',
      'הישגים ותהליכי שינוי',
      'כלים שלקחתי מהטיפול',
      'מה למדתי על עצמי',
      'קשר טיפולי ומשוב',
      'תכנית המשך לאחר סיום',
      'טופס אישי לבנייה משותפת',
      'טופס ריק למעקב שבועי',
      'טופס ריק לאירוע משמעותי',
      'טופס ריק לניסוי טיפולי',
      'דף אישי פתוח',
      'סיכום אישי אחרון',
    ],
    topicKeywords: [
      'סיכום טיפול',
      'סיכום תהליך',
      'סיום טיפול',
      'לסכם',
      'טופס אישי',
      'טפסים אישיים',
      'טופס ריק',
      'מה למדתי',
      'תכנית המשך',
      'משוב על הטיפול',
      'לבנות טופס',
      'טפסים מותאמים',
    ],
    whenToUseHe:
      'כאשר המטפל והמטופל מתקרבים לסיום הטיפול ורוצים לסכם את התהליך, לבנות תכנית המשך ולייצר טפסים מותאמים אישית.',
    preferWhenHe: [
      'סיכום טיפול',
      'סיום טיפול',
      'לסכם',
      'מה למדתי בטיפול',
      'משוב על הטיפול',
      'טופס אישי',
      'טופס ריק',
      'טפסים מותאמים',
      'לבנות טופס עם המטפל',
      'תכנית המשך',
    ],
    lowerPriorityIndividualForms: [],
  },
];

/**
 * Quickly look up workbook metadata by form ID.
 * Returns undefined when not found.
 *
 * @param {string} formId
 * @returns {WorkbookMeta|undefined}
 */
export function getWorkbookMetaById(formId) {
  return WORKBOOK_CONTENT_METADATA.find(wb => wb.id === formId);
}

/**
 * Returns the set of individual form IDs that should be demoted
 * when any workbook is a better fit.
 *
 * @returns {Set<string>}
 */
export function getLowerPriorityIndividualForms() {
  const ids = new Set();
  for (const wb of WORKBOOK_CONTENT_METADATA) {
    for (const id of wb.lowerPriorityIndividualForms) {
      ids.add(id);
    }
  }
  return ids;
}

// ─────────────────────────────────────────────────────────────────────────────
// English Workbook Content Metadata — Phase 11
// ─────────────────────────────────────────────────────────────────────────────
//
// Topic keywords are English words/phrases used for scoring user queries.
// Routing rules mirror the Hebrew implementation:
//   - Explicit workbook trigger + ≥1 topic keyword  → return matching workbook
//   - ≥2 topic keywords from same workbook (multi-topic) → return matching workbook
//   - No sufficient match → return null

/** @type {WorkbookMeta[]} */
export const WORKBOOK_CONTENT_METADATA_EN = [
  // ── 1. Formulation & Mapping ─────────────────────────────────────────────────
  {
    id: 'tf-adults-formulation-mapping-premium-en',
    slug: 'adults-formulation-mapping-premium-en',
    internalForms: [
      'initial situation snapshot',
      'thoughts, emotions, and behavior map',
      'identifying the core difficulty',
      'strengths and resources',
      'expectations for therapy',
      'hopes, wishes, and goals',
      'self-image / how I see myself',
      'summary and next steps',
    ],
    topicKeywords: [
      'case formulation',
      'formulation',
      'mapping the problem',
      'understanding what is happening',
      'getting an overview',
      'therapy goals',
      'initial assessment',
      'repeated patterns',
      'treatment direction',
      'understanding the difficulty',
      'what is happening',
      'core difficulty',
      'case mapping',
    ],
    lowerPriorityIndividualForms: [],
  },

  // ── 2. Awareness & Identification ────────────────────────────────────────────
  {
    id: 'tf-adults-awareness-identification-premium-en',
    slug: 'adults-awareness-identification-premium-en',
    internalForms: [
      'identifying an event and first thought',
      'automatic thoughts log',
      'identifying emotions and intensity',
      'body sensations map',
      'actual response and behavior',
      'situation-thought-emotion-body-behavior chain',
      'repeated patterns and triggers',
      'initial summary for further work',
    ],
    topicKeywords: [
      'identifying thoughts',
      'identifying emotions',
      'body sensations',
      'behavior patterns',
      'tracking thoughts',
      'tracking emotions',
      'triggers',
      'automatic thoughts',
      'understanding reactions',
      'cbt chain',
      'situation thought emotion behavior',
      'thought log',
      'emotion log',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
    ],
  },

  // ── 3. Cognitive Flexibility ─────────────────────────────────────────────────
  {
    id: 'tf-adults-cognitive-flexibility-premium-en',
    slug: 'adults-cognitive-flexibility-premium-en',
    internalForms: [
      'identifying an automatic thought and core assumption',
      'evidence for and against the thought',
      'Socratic questions for thought challenging',
      'cognitive distortions and rewording',
      'proportion and risk reappraisal',
      'alternative perspectives',
      'mediating thought between extremes',
      'supportive self-talk',
      'challenging limiting beliefs',
      'behavioral experiment for a thought',
      'trigger response script',
      'balanced thought and next plan',
    ],
    topicKeywords: [
      'negative thoughts',
      'thought challenging',
      'challenging automatic thoughts',
      'cognitive distortions',
      'unhelpful thoughts',
      'evidence for and against',
      'socratic questions',
      'balanced thinking',
      'cognitive flexibility',
      'self-talk',
      'limiting beliefs',
      'perspective',
      'catastrophizing',
      'all-or-nothing thinking',
      'automatic thoughts',
      'thought record',
    ],
    // When user asks for a workbook about negative thoughts, do NOT attach only
    // cbt-thought-record or cognitive-distortions-worksheet — attach this workbook.
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
      'tf-adults-cognitive-distortions-worksheet',
    ],
  },

  // ── 4. Emotional Regulation ──────────────────────────────────────────────────
  {
    id: 'tf-adults-emotional-regulation-premium-en',
    slug: 'adults-emotional-regulation-premium-en',
    internalForms: [
      'initial emotion map',
      'emotion intensity over time',
      'fear and anxiety',
      'sadness, low mood, and heaviness',
      'anger and frustration',
      'shame and guilt',
      'events that activate emotions',
      'body sensations and action urges',
      'emotional reaction versus regulated response',
      'real-time regulation tools',
      'before, during, and after an event',
      'mixed emotions and inner conflict',
      'calming inner conversation',
      'personal regulation plan',
    ],
    topicKeywords: [
      'emotional regulation',
      'strong emotions',
      'emotional overwhelm',
      'anxiety',
      'fear',
      'sadness',
      'low mood',
      'anger',
      'frustration',
      'shame',
      'guilt',
      'urges',
      'emotional triggers',
      'mixed emotions',
      'calming down',
      'regulation tools',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-mood-tracking-sheet',
    ],
  },

  // ── 5. Coping & Change ────────────────────────────────────────────────────────
  {
    id: 'tf-adults-coping-change-premium-en',
    slug: 'adults-coping-change-premium-en',
    internalForms: [
      'personal coping map',
      'avoidance and gradual steps',
      'procrastination and starting action',
      'difficult habit and alternative habit',
      'basic social skills',
      'assertive communication',
      'personal boundaries',
      'practical problem solving',
      'managing load and routine',
      'coping with criticism',
      'impulse regulation before action',
      'maintaining change and preventing relapse',
    ],
    topicKeywords: [
      'procrastination',
      'avoidance',
      'difficult habits',
      'behavior change',
      'coping skills',
      'social skills',
      'assertiveness',
      'boundaries',
      'problem solving',
      'routine',
      'overload',
      'criticism',
      'impulses',
      'relapse prevention',
      'changing patterns',
    ],
    // When user asks for a workbook about procrastination/avoidance/difficult habits,
    // do NOT attach behavioral-activation-plan — attach this workbook instead.
    lowerPriorityIndividualForms: [
      'tf-adults-behavioral-activation-plan',
      'tf-adults-weekly-coping-plan',
    ],
  },

  // ── 6. Strengths & Resilience ────────────────────────────────────────────────
  {
    id: 'tf-adults-strengths-resilience-premium-en',
    slug: 'adults-strengths-resilience-premium-en',
    internalForms: [
      'personal strengths map',
      'past successes as resources',
      'values as a therapeutic anchor',
      'support network and resources',
      'self-efficacy',
      'strengthening inner voice',
      'strengths in relationships',
      'resilience under stress',
      'realistic hope',
      'identity beyond the difficulty',
      'using strengths in therapy',
    ],
    topicKeywords: [
      'strengths',
      'resilience',
      'self-confidence',
      'self-efficacy',
      'resources',
      'hope',
      'values',
      'support network',
      'empowering inner voice',
      'identity beyond the problem',
      'protective factors',
      'coping resources',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-values-and-goals-worksheet',
    ],
  },

  // ── 7. Treatment Summary & Custom Forms ──────────────────────────────────────
  {
    id: 'tf-adults-treatment-summary-custom-forms-premium-en',
    slug: 'adults-treatment-summary-custom-forms-premium-en',
    internalForms: [
      'therapeutic journey summary',
      'achievements and change processes',
      'tools I am taking from therapy',
      'what I learned about myself',
      'therapeutic relationship and feedback',
      'post-treatment continuation plan',
      'custom form built together',
      'blank weekly tracking form',
      'blank significant event form',
      'blank therapeutic experiment form',
      'open personal page',
      'final personal summary',
    ],
    topicKeywords: [
      'treatment summary',
      'ending therapy',
      'reviewing therapy',
      'therapy feedback',
      'continuation plan',
      'what I learned in therapy',
      'custom form',
      'blank form',
      'personalized worksheet',
      'build a form with my therapist',
      'weekly tracking',
      'therapeutic experiment',
    ],
    lowerPriorityIndividualForms: [],
  },
];

/**
 * Quickly look up English workbook metadata by form ID.
 * Returns undefined when not found.
 *
 * @param {string} formId
 * @returns {WorkbookMeta|undefined}
 */
export function getWorkbookMetaByIdEn(formId) {
  return WORKBOOK_CONTENT_METADATA_EN.find(wb => wb.id === formId);
}

// ─────────────────────────────────────────────────────────────────────────────
// Spanish Workbook Content Metadata — Phase 12
// ─────────────────────────────────────────────────────────────────────────────
//
// Topic keywords are Spanish words/phrases used for scoring user queries.
// Routing rules mirror the Hebrew and English implementations:
//   - Explicit workbook trigger + ≥1 topic keyword  → return matching workbook
//   - ≥2 topic keywords from same workbook (multi-topic) → return matching workbook
//   - No sufficient match → return null

/** @type {WorkbookMeta[]} */
export const WORKBOOK_CONTENT_METADATA_ES = [
  // ── 1. Formulation & Mapping ─────────────────────────────────────────────────
  {
    id: 'tf-adults-formulation-mapping-premium-es',
    slug: 'adults-formulation-mapping-premium-es',
    internalForms: [
      'panorama inicial de la situación',
      'mapa de pensamientos, emociones y conducta',
      'identificar la dificultad central',
      'fortalezas y recursos',
      'expectativas para la terapia',
      'esperanzas, deseos y metas',
      'autoimagen / cómo me veo',
      'resumen y próximos pasos',
    ],
    topicKeywords: [
      'formulación del caso',
      'formulación',
      'mapeo',
      'mapa del problema',
      'entender el problema',
      'entender qué me pasa',
      'visión general',
      'evaluación inicial',
      'objetivos terapéuticos',
      'metas terapéuticas',
      'patrones repetidos',
      'dirección del tratamiento',
      'cuaderno de formulación',
      'cuaderno de mapeo',
      'comprender la dificultad',
    ],
    lowerPriorityIndividualForms: [],
  },

  // ── 2. Awareness & Identification ────────────────────────────────────────────
  {
    id: 'tf-adults-awareness-identification-premium-es',
    slug: 'adults-awareness-identification-premium-es',
    internalForms: [
      'identificar un evento y el primer pensamiento',
      'registro de pensamientos automáticos',
      'identificar emociones e intensidad',
      'mapa de sensaciones corporales',
      'respuesta y conducta real',
      'cadena situación-pensamiento-emoción-cuerpo-conducta',
      'patrones repetidos y disparadores',
      'resumen inicial para continuar el trabajo',
    ],
    topicKeywords: [
      'identificar pensamientos',
      'identificar emociones',
      'sensaciones corporales',
      'señales corporales',
      'conducta',
      'comportamiento',
      'pensamientos automáticos',
      'registro de pensamientos',
      'registro emocional',
      'disparadores',
      'desencadenantes',
      'patrones de conducta',
      'cadena cbt',
      'cadena pensamiento emoción conducta',
      'entender mis reacciones',
      'cuaderno de identificación',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
    ],
  },

  // ── 3. Cognitive Flexibility ─────────────────────────────────────────────────
  {
    id: 'tf-adults-cognitive-flexibility-premium-es',
    slug: 'adults-cognitive-flexibility-premium-es',
    internalForms: [
      'identificar un pensamiento automático y una creencia de base',
      'evidencia a favor y en contra',
      'preguntas socráticas para desafiar pensamientos',
      'distorsiones cognitivas y reformulación',
      'proporción y reevaluación del riesgo',
      'perspectivas alternativas',
      'pensamiento mediador entre extremos',
      'diálogo interno de apoyo',
      'desafiar una creencia limitante',
      'experimento conductual para un pensamiento',
      'guion de respuesta ante disparadores',
      'pensamiento equilibrado y plan siguiente',
    ],
    topicKeywords: [
      'pensamientos negativos',
      'desafiar pensamientos',
      'cuestionar pensamientos',
      'cuestionamiento de pensamientos',
      'rebatir pensamientos',
      'refutar pensamientos',
      'pensamientos automáticos',
      'distorsiones cognitivas',
      'evidencia a favor',
      'evidencia en contra',
      'preguntas socráticas',
      'pensamiento equilibrado',
      'flexibilidad cognitiva',
      'diálogo interno',
      'autodiálogo',
      'creencias limitantes',
      'catastrofización',
      'todo o nada',
      'lectura de mente',
      'perspectiva',
      'proporción',
      'cuaderno de pensamientos',
      'cuaderno de flexibilidad cognitiva',
    ],
    // When user asks for a cuaderno about negative thoughts, do NOT attach only
    // cbt-thought-record or cognitive-distortions-worksheet — attach this workbook.
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
      'tf-adults-cognitive-distortions-worksheet',
    ],
  },

  // ── 4. Emotional Regulation ──────────────────────────────────────────────────
  {
    id: 'tf-adults-emotional-regulation-premium-es',
    slug: 'adults-emotional-regulation-premium-es',
    internalForms: [
      'mapa emocional inicial',
      'intensidad emocional a lo largo del tiempo',
      'miedo y ansiedad',
      'tristeza, bajo ánimo y pesadez',
      'ira y frustración',
      'vergüenza y culpa',
      'eventos que activan emociones',
      'sensaciones corporales e impulsos de acción',
      'reacción emocional versus respuesta regulada',
      'herramientas de regulación en tiempo real',
      'antes, durante y después de un evento',
      'emociones mezcladas y conflicto interno',
      'conversación interna calmante',
      'plan personal de regulación',
    ],
    topicKeywords: [
      'regulación emocional',
      'emociones fuertes',
      'desborde emocional',
      'intensidad emocional',
      'ansiedad',
      'miedo',
      'tristeza',
      'bajo ánimo',
      'ira',
      'enojo',
      'frustración',
      'vergüenza',
      'culpa',
      'impulsos',
      'disparadores emocionales',
      'emociones mezcladas',
      'calmarme',
      'herramientas de regulación',
      'manejar emociones',
      'controlar emociones',
      'cuaderno de regulación emocional',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-mood-tracking-sheet',
    ],
  },

  // ── 5. Coping & Change ────────────────────────────────────────────────────────
  {
    id: 'tf-adults-coping-change-premium-es',
    slug: 'adults-coping-change-premium-es',
    internalForms: [
      'mapa personal de afrontamiento',
      'evitación y pasos graduales',
      'procrastinación e inicio de acción',
      'hábito difícil y hábito alternativo',
      'habilidades sociales básicas',
      'comunicación asertiva',
      'límites personales',
      'solución práctica de problemas',
      'manejo de carga y rutina',
      'afrontar la crítica',
      'regulación de impulsos antes de actuar',
      'mantener el cambio y prevenir recaídas',
    ],
    topicKeywords: [
      'procrastinación',
      'postergación',
      'evitación',
      'evitar',
      'hábitos difíciles',
      'hábitos problemáticos',
      'cambiar hábitos',
      'cambio de conducta',
      'afrontamiento',
      'habilidades de afrontamiento',
      'habilidades sociales',
      'asertividad',
      'límites personales',
      'poner límites',
      'solución de problemas',
      'rutina',
      'sobrecarga',
      'crítica',
      'impulsos',
      'prevención de recaídas',
      'cambiar patrones',
      'cuaderno de afrontamiento',
      'cuaderno de cambio',
    ],
    // When user asks for a cuaderno about procrastination/avoidance/difficult habits,
    // do NOT attach behavioral-activation-plan — attach this workbook instead.
    lowerPriorityIndividualForms: [
      'tf-adults-behavioral-activation-plan',
      'tf-adults-weekly-coping-plan',
    ],
  },

  // ── 6. Strengths & Resilience ────────────────────────────────────────────────
  {
    id: 'tf-adults-strengths-resilience-premium-es',
    slug: 'adults-strengths-resilience-premium-es',
    internalForms: [
      'mapa de fortalezas personales',
      'éxitos pasados como recursos',
      'valores como ancla terapéutica',
      'red de apoyo y recursos',
      'autoeficacia',
      'fortalecer la voz interna',
      'fortalezas en las relaciones',
      'resiliencia bajo estrés',
      'esperanza realista',
      'identidad más allá de la dificultad',
      'uso de fortalezas en terapia',
    ],
    topicKeywords: [
      'fortalezas',
      'puntos fuertes',
      'resiliencia',
      'confianza',
      'confianza en mí',
      'confianza en uno mismo',
      'autoestima',
      'autoeficacia',
      'sensación de capacidad',
      'recursos',
      'esperanza',
      'valores',
      'red de apoyo',
      'apoyo',
      'voz interna',
      'diálogo interno positivo',
      'identidad más allá del problema',
      'factores protectores',
      'factores de resiliencia',
      'cuaderno de fortalezas',
      'cuaderno de resiliencia',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-values-and-goals-worksheet',
    ],
  },

  // ── 7. Treatment Summary & Custom Forms ──────────────────────────────────────
  {
    id: 'tf-adults-treatment-summary-custom-forms-premium-es',
    slug: 'adults-treatment-summary-custom-forms-premium-es',
    internalForms: [
      'resumen del recorrido terapéutico',
      'logros y procesos de cambio',
      'herramientas que me llevo de la terapia',
      'lo que aprendí sobre mí',
      'relación terapéutica y retroalimentación',
      'plan de continuidad después del tratamiento',
      'formulario personalizado construido juntos',
      'formulario semanal en blanco',
      'formulario para evento significativo',
      'formulario para experimento terapéutico',
      'página personal abierta',
      'resumen personal final',
    ],
    topicKeywords: [
      'resumen de terapia',
      'resumen terapéutico',
      'resumen del tratamiento',
      'terminar terapia',
      'terminando terapia',
      'cierre de terapia',
      'finalizar terapia',
      'revisar la terapia',
      'retroalimentación',
      'feedback terapéutico',
      'plan de continuidad',
      'qué aprendí en terapia',
      'formulario personalizado',
      'formularios personalizados',
      'formulario en blanco',
      'hoja personalizada',
      'crear un formulario con mi terapeuta',
      'seguimiento semanal',
      'experimento terapéutico',
      'página personal',
      'cuaderno de resumen',
      'cuaderno de formularios personalizados',
    ],
    lowerPriorityIndividualForms: [],
  },
];

/**
 * Quickly look up Spanish workbook metadata by form ID.
 * Returns undefined when not found.
 *
 * @param {string} formId
 * @returns {WorkbookMeta|undefined}
 */
export function getWorkbookMetaByIdEs(formId) {
  return WORKBOOK_CONTENT_METADATA_ES.find(wb => wb.id === formId);
}

// ─────────────────────────────────────────────────────────────────────────────
// French Workbook Content Metadata — Phase 13
// ─────────────────────────────────────────────────────────────────────────────
//
// Topic keywords are French words/phrases used for scoring user queries.
// Routing rules mirror the Hebrew, English, and Spanish implementations:
//   - Explicit workbook trigger + ≥1 topic keyword  → return matching workbook
//   - ≥2 topic keywords from same workbook (multi-topic) → return matching workbook
//   - No sufficient match → return null

/** @type {WorkbookMeta[]} */
export const WORKBOOK_CONTENT_METADATA_FR = [
  // ── 1. Formulation & Mapping ─────────────────────────────────────────────────
  {
    id: 'tf-adults-formulation-mapping-premium-fr',
    slug: 'adults-formulation-mapping-premium-fr',
    internalForms: [
      'vue d\'ensemble initiale de la situation',
      'carte pensées, émotions et comportement',
      'identifier la difficulté centrale',
      'forces et ressources',
      'attentes pour la thérapie',
      'espoirs, souhaits et objectifs',
      'image de soi / comment je me vois',
      'résumé et prochaines étapes',
    ],
    topicKeywords: [
      'formulation du cas',
      'formulation',
      'cartographie du problème',
      'carte du problème',
      'comprendre le problème',
      'comprendre ce qui m\'arrive',
      'vue d\'ensemble',
      'évaluation initiale',
      'objectifs thérapeutiques',
      'buts thérapeutiques',
      'schémas répétés',
      'direction du traitement',
      'comprendre la difficulté',
      'cahier de formulation',
      'cahier de cartographie',
    ],
    lowerPriorityIndividualForms: [],
  },

  // ── 2. Awareness & Identification ────────────────────────────────────────────
  {
    id: 'tf-adults-awareness-identification-premium-fr',
    slug: 'adults-awareness-identification-premium-fr',
    internalForms: [
      'identifier un événement et la première pensée',
      'journal des pensées automatiques',
      'identifier les émotions et leur intensité',
      'carte des sensations corporelles',
      'réponse et comportement réels',
      'chaîne situation-pensée-émotion-corps-comportement',
      'schémas répétés et déclencheurs',
      'résumé initial pour poursuivre le travail',
    ],
    topicKeywords: [
      'identifier les pensées',
      'identifier mes pensées',
      'identifier les émotions',
      'identifier mes émotions',
      'sensations corporelles',
      'signaux corporels',
      'pensées automatiques',
      'journal des pensées',
      'suivi des pensées',
      'suivi émotionnel',
      'déclencheurs',
      'schémas de comportement',
      'chaîne cbt',
      'chaîne pensée émotion comportement',
      'comprendre mes réactions',
      'cahier d\'identification',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
    ],
  },

  // ── 3. Cognitive Flexibility ─────────────────────────────────────────────────
  {
    id: 'tf-adults-cognitive-flexibility-premium-fr',
    slug: 'adults-cognitive-flexibility-premium-fr',
    internalForms: [
      'identifier une pensée automatique et une croyance de base',
      'preuves pour et contre la pensée',
      'questions socratiques pour questionner les pensées',
      'distorsions cognitives et reformulation',
      'proportion et réévaluation du risque',
      'perspectives alternatives',
      'pensée médiatrice entre les extrêmes',
      'dialogue intérieur de soutien',
      'questionner une croyance limitante',
      'expérience comportementale pour une pensée',
      'script de réponse aux déclencheurs',
      'pensée équilibrée et plan suivant',
    ],
    topicKeywords: [
      'pensées négatives',
      'pensées automatiques',
      'questionner les pensées',
      'remettre en question les pensées',
      'contester les pensées',
      'challenger les pensées',
      'défier les pensées',
      'distorsions cognitives',
      'preuves pour et contre',
      'preuves pour',
      'preuves contre',
      'questions socratiques',
      'pensée équilibrée',
      'pensée alternative',
      'flexibilité cognitive',
      'dialogue intérieur',
      'auto-dialogue',
      'croyances limitantes',
      'croyance limitante',
      'catastrophisation',
      'tout ou rien',
      'lecture de pensée',
      'perspective',
      'proportion',
      'cahier de pensées',
      'cahier de flexibilité cognitive',
    ],
    // When user asks for a cahier about negative thoughts, do NOT attach only
    // cbt-thought-record or cognitive-distortions-worksheet — attach this workbook.
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
      'tf-adults-cognitive-distortions-worksheet',
    ],
  },

  // ── 4. Emotional Regulation ──────────────────────────────────────────────────
  {
    id: 'tf-adults-emotional-regulation-premium-fr',
    slug: 'adults-emotional-regulation-premium-fr',
    internalForms: [
      'carte émotionnelle initiale',
      'intensité émotionnelle dans le temps',
      'peur et anxiété',
      'tristesse, humeur basse et lourdeur',
      'colère et frustration',
      'honte et culpabilité',
      'événements qui activent les émotions',
      'sensations corporelles et envies d\'agir',
      'réaction émotionnelle ou réponse régulée',
      'outils de régulation en temps réel',
      'avant, pendant et après un événement',
      'émotions mélangées et conflit intérieur',
      'conversation intérieure apaisante',
      'plan personnel de régulation',
    ],
    topicKeywords: [
      'régulation émotionnelle',
      'émotions fortes',
      'débordement émotionnel',
      'intensité émotionnelle',
      'anxiété',
      'peur',
      'tristesse',
      'humeur basse',
      'colère',
      'frustration',
      'honte',
      'culpabilité',
      'impulsions',
      'envies d\'agir',
      'déclencheurs émotionnels',
      'émotions mélangées',
      'me calmer',
      'calmer mes émotions',
      'outils de régulation',
      'gérer les émotions',
      'contrôler les émotions',
      'cahier de régulation émotionnelle',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-mood-tracking-sheet',
    ],
  },

  // ── 5. Coping & Change ────────────────────────────────────────────────────────
  {
    id: 'tf-adults-coping-change-premium-fr',
    slug: 'adults-coping-change-premium-fr',
    internalForms: [
      'carte personnelle d\'adaptation',
      'évitement et étapes graduelles',
      'procrastination et mise en action',
      'habitude difficile et habitude alternative',
      'compétences sociales de base',
      'communication assertive',
      'limites personnelles',
      'résolution pratique de problèmes',
      'gestion de la charge et de la routine',
      'faire face à la critique',
      'régulation des impulsions avant l\'action',
      'maintenir le changement et prévenir la rechute',
    ],
    topicKeywords: [
      'procrastination',
      'remettre à plus tard',
      'évitement',
      'éviter',
      'habitudes difficiles',
      'habitudes problématiques',
      'changer les habitudes',
      'changement de comportement',
      'adaptation',
      'stratégies d\'adaptation',
      'compétences sociales',
      'assertivité',
      'communication assertive',
      'limites personnelles',
      'poser des limites',
      'résolution de problèmes',
      'routine',
      'surcharge',
      'charge mentale',
      'critique',
      'impulsions',
      'prévention de la rechute',
      'rechute',
      'changer des schémas',
      'cahier d\'adaptation',
      'cahier de changement',
    ],
    // When user asks for a cahier about procrastination/avoidance/difficult habits,
    // do NOT attach behavioral-activation-plan — attach this workbook instead.
    lowerPriorityIndividualForms: [
      'tf-adults-behavioral-activation-plan',
      'tf-adults-weekly-coping-plan',
    ],
  },

  // ── 6. Strengths & Resilience ────────────────────────────────────────────────
  {
    id: 'tf-adults-strengths-resilience-premium-fr',
    slug: 'adults-strengths-resilience-premium-fr',
    internalForms: [
      'carte des forces personnelles',
      'réussites passées comme ressources',
      'valeurs comme ancre thérapeutique',
      'réseau de soutien et ressources',
      'auto-efficacité',
      'renforcer la voix intérieure',
      'forces dans les relations',
      'résilience sous stress',
      'espoir réaliste',
      'identité au-delà de la difficulté',
      'utiliser les forces en thérapie',
    ],
    topicKeywords: [
      'forces',
      'forces personnelles',
      'points forts',
      'résilience',
      'confiance',
      'confiance en moi',
      'confiance en soi',
      'estime de soi',
      'auto-efficacité',
      'sentiment de capacité',
      'ressources',
      'espoir',
      'valeurs',
      'réseau de soutien',
      'soutien',
      'voix intérieure',
      'dialogue intérieur positif',
      'identité au-delà du problème',
      'facteurs protecteurs',
      'facteurs de résilience',
      'cahier des forces',
      'cahier de résilience',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-values-and-goals-worksheet',
    ],
  },

  // ── 7. Treatment Summary & Custom Forms ──────────────────────────────────────
  {
    id: 'tf-adults-treatment-summary-custom-forms-premium-fr',
    slug: 'adults-treatment-summary-custom-forms-premium-fr',
    internalForms: [
      'résumé du parcours thérapeutique',
      'réussites et processus de changement',
      'outils que j\'emporte de la thérapie',
      'ce que j\'ai appris sur moi',
      'relation thérapeutique et retour d\'expérience',
      'plan de continuité après le traitement',
      'fiche personnalisée construite ensemble',
      'fiche hebdomadaire vierge',
      'fiche pour événement significatif',
      'fiche pour expérience thérapeutique',
      'page personnelle ouverte',
      'résumé personnel final',
    ],
    topicKeywords: [
      'résumé de thérapie',
      'résumé thérapeutique',
      'résumé du traitement',
      'fin de thérapie',
      'terminer la thérapie',
      'clôture de thérapie',
      'revoir la thérapie',
      'retour d\'expérience',
      'feedback thérapeutique',
      'plan de continuité',
      'ce que j\'ai appris en thérapie',
      'fiche personnalisée',
      'fiches personnalisées',
      'formulaire personnalisé',
      'formulaires personnalisés',
      'fiche vierge',
      'formulaire vierge',
      'feuille personnalisée',
      'créer une fiche avec mon thérapeute',
      'construire une fiche avec mon thérapeute',
      'suivi hebdomadaire',
      'expérience thérapeutique',
      'page personnelle',
      'cahier de synthèse',
      'cahier de fiches personnalisées',
    ],
    lowerPriorityIndividualForms: [],
  },
];

/**
 * Quickly look up French workbook metadata by form ID.
 * Returns undefined when not found.
 *
 * @param {string} formId
 * @returns {WorkbookMeta|undefined}
 */
export function getWorkbookMetaByIdFr(formId) {
  return WORKBOOK_CONTENT_METADATA_FR.find(wb => wb.id === formId);
}

// ─── German Workbook Content Metadata ────────────────────────────────────────

/** @type {WorkbookMeta[]} */
export const WORKBOOK_CONTENT_METADATA_DE = [
  // ── 1. Formulation & Mapping ─────────────────────────────────────────────────
  {
    id: 'tf-adults-formulation-mapping-premium-de',
    slug: 'adults-formulation-mapping-premium-de',
    internalForms: [
      'erster Überblick über die Situation',
      'Karte von Gedanken, Gefühlen und Verhalten',
      'die zentrale Schwierigkeit erkennen',
      'Stärken und Ressourcen',
      'Erwartungen an die Therapie',
      'Hoffnungen, Wünsche und Ziele',
      'Selbstbild / wie ich mich selbst sehe',
      'Zusammenfassung und nächste Schritte',
    ],
    topicKeywords: [
      'fallformulierung',
      'formulierung des falls',
      'problemlandkarte',
      'problemkarte',
      'kartierung des problems',
      'problem verstehen',
      'schwierigkeit verstehen',
      'verstehen was mit mir passiert',
      'überblick',
      'erste einschätzung',
      'therapeutische ziele',
      'therapieziele',
      'wiederkehrende muster',
      'therapierichtung',
      'arbeitsheft zur fallformulierung',
      'arbeitsheft zur problemlandkarte',
    ],
    lowerPriorityIndividualForms: [],
  },

  // ── 2. Awareness & Identification ────────────────────────────────────────────
  {
    id: 'tf-adults-awareness-identification-premium-de',
    slug: 'adults-awareness-identification-premium-de',
    internalForms: [
      'ein Ereignis und den ersten Gedanken erkennen',
      'Protokoll automatischer Gedanken',
      'Gefühle und Intensität erkennen',
      'Karte der Körperempfindungen',
      'tatsächliche Reaktion und Verhalten',
      'Kette Situation-Gedanke-Gefühl-Körper-Verhalten',
      'wiederkehrende Muster und Auslöser',
      'erste Zusammenfassung für die Weiterarbeit',
    ],
    topicKeywords: [
      'gedanken erkennen',
      'meine gedanken erkennen',
      'gefühle erkennen',
      'meine gefühle erkennen',
      'körperempfindungen',
      'körpersignale',
      'verhaltensmuster',
      'automatische gedanken',
      'gedankenprotokoll',
      'gedanken verfolgen',
      'emotionsprotokoll',
      'gefühle verfolgen',
      'auslöser',
      'trigger',
      'cbt-kette',
      'situation gedanke gefühl verhalten',
      'reaktionen verstehen',
      'meine reaktionen verstehen',
      'arbeitsheft zum erkennen',
    ],
    lowerPriorityIndividualForms: [],
  },

  // ── 3. Cognitive Flexibility ─────────────────────────────────────────────────
  {
    id: 'tf-adults-cognitive-flexibility-premium-de',
    slug: 'adults-cognitive-flexibility-premium-de',
    internalForms: [
      'automatischen Gedanken und Grundannahme erkennen',
      'Belege für und gegen den Gedanken',
      'sokratische Fragen zur Gedankenprüfung',
      'kognitive Verzerrungen und Umformulierung',
      'Proportion und Neubewertung des Risikos',
      'alternative Perspektiven',
      'vermittelnder Gedanke zwischen Extremen',
      'unterstützender innerer Dialog',
      'begrenzende Überzeugung hinterfragen',
      'Verhaltensexperiment zu einem Gedanken',
      'Antwortskript für Auslöser',
      'ausgewogener Gedanke und nächster Plan',
    ],
    topicKeywords: [
      'negative gedanken',
      'negativen gedanken',
      'automatische gedanken',
      'automatischen gedanken',
      'gedanken prüfen',
      'gedanken überprüfen',
      'gedanken hinterfragen',
      'gedanken in frage stellen',
      'gedanken challengen',
      'gedanken anfechten',
      'kognitive verzerrungen',
      'kognitiven verzerrungen',
      'denkfehler',
      'belege dafür',
      'belege dagegen',
      'belege dafür und dagegen',
      'sokratische fragen',
      'ausgewogenes denken',
      'ausgewogener gedanke',
      'alternative gedanken',
      'kognitive flexibilität',
      'kognitiver flexibilität',
      'innerer dialog',
      'selbstgespräch',
      'unterstützender innerer dialog',
      'begrenzende überzeugungen',
      'limitierende glaubenssätze',
      'katastrophisieren',
      'alles-oder-nichts',
      'gedankenlesen',
      'perspektive',
      'proportion',
      'arbeitsheft zu gedanken',
      'arbeitsheft zu kognitiver flexibilität',
    ],
    // When user asks for an Arbeitsheft about negative thoughts, do NOT attach only
    // cbt-thought-record or cognitive-distortions-worksheet — attach this workbook.
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
      'tf-adults-cognitive-distortions-worksheet',
    ],
  },

  // ── 4. Emotional Regulation ──────────────────────────────────────────────────
  {
    id: 'tf-adults-emotional-regulation-premium-de',
    slug: 'adults-emotional-regulation-premium-de',
    internalForms: [
      'erste Emotionskarte',
      'emotionale Intensität im Verlauf',
      'Angst und Sorge',
      'Traurigkeit, gedrückte Stimmung und Schwere',
      'Ärger und Frustration',
      'Scham und Schuld',
      'Ereignisse, die Gefühle aktivieren',
      'Körperempfindungen und Handlungsimpulse',
      'emotionale Reaktion oder regulierte Antwort',
      'Regulationswerkzeuge in Echtzeit',
      'vor, während und nach einem Ereignis',
      'gemischte Gefühle und innerer Konflikt',
      'beruhigender innerer Dialog',
      'persönlicher Regulationsplan',
    ],
    topicKeywords: [
      'emotionale regulation',
      'emotionsregulation',
      'starke gefühle',
      'emotionale überforderung',
      'emotionale intensität',
      'angst',
      'sorge',
      'traurigkeit',
      'gedrückte stimmung',
      'ärger',
      'wut',
      'frustration',
      'scham',
      'schuld',
      'impulse',
      'handlungsimpulse',
      'emotionale auslöser',
      'trigger für gefühle',
      'gemischte gefühle',
      'mich beruhigen',
      'gefühle beruhigen',
      'regulationswerkzeuge',
      'gefühle regulieren',
      'gefühle kontrollieren',
      'arbeitsheft zur emotionsregulation',
      'arbeitsheft zu emotionaler regulation',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-mood-tracking-sheet',
    ],
  },

  // ── 5. Coping & Change ────────────────────────────────────────────────────────
  {
    id: 'tf-adults-coping-change-premium-de',
    slug: 'adults-coping-change-premium-de',
    internalForms: [
      'persönliche Bewältigungskarte',
      'Vermeidung und schrittweise Annäherung',
      'Prokrastination und Handlungsbeginn',
      'schwierige Gewohnheit und Alternative',
      'grundlegende soziale Fähigkeiten',
      'assertive Kommunikation',
      'persönliche Grenzen',
      'praktische Problemlösung',
      'Belastung und Routine steuern',
      'mit Kritik umgehen',
      'Impulsregulation vor dem Handeln',
      'Veränderung erhalten und Rückfall vorbeugen',
    ],
    topicKeywords: [
      'prokrastination',
      'aufschieben',
      'vermeidung',
      'vermeiden',
      'schwierige gewohnheiten',
      'problematische gewohnheiten',
      'gewohnheiten ändern',
      'verhaltensänderung',
      'bewältigung',
      'bewältigungsstrategien',
      'soziale fähigkeiten',
      'soziale kompetenzen',
      'assertivität',
      'assertive kommunikation',
      'grenzen',
      'persönliche grenzen',
      'grenzen setzen',
      'problemlösung',
      'praktische problemlösung',
      'routine',
      'überlastung',
      'belastung',
      'kritik',
      'mit kritik umgehen',
      'impulsregulation',
      'rückfallprävention',
      'rückfall vorbeugen',
      'muster ändern',
      'arbeitsheft zu bewältigung',
      'arbeitsheft zu veränderung',
    ],
    // When user asks for an Arbeitsheft about procrastination/avoidance/difficult habits,
    // do NOT attach behavioral-activation-plan — attach this workbook instead.
    lowerPriorityIndividualForms: [
      'tf-adults-behavioral-activation-plan',
      'tf-adults-weekly-coping-plan',
    ],
  },

  // ── 6. Strengths & Resilience ────────────────────────────────────────────────
  {
    id: 'tf-adults-strengths-resilience-premium-de',
    slug: 'adults-strengths-resilience-premium-de',
    internalForms: [
      'Karte persönlicher Stärken',
      'frühere Erfolge als Ressourcen',
      'Werte als therapeutischer Anker',
      'Unterstützungsnetz und Ressourcen',
      'Selbstwirksamkeit',
      'innere Stimme stärken',
      'Stärken in Beziehungen',
      'Resilienz unter Stress',
      'realistische Hoffnung',
      'Identität jenseits der Schwierigkeit',
      'Stärken in der Therapie nutzen',
    ],
    topicKeywords: [
      'stärken',
      'persönliche stärken',
      'ressourcen',
      'resilienz',
      'selbstvertrauen',
      'vertrauen in mich',
      'selbstwert',
      'selbstwirksamkeit',
      'gefühl von fähigkeit',
      'hoffnung',
      'werte',
      'unterstützungsnetz',
      'unterstützung',
      'innere stimme',
      'positiver innerer dialog',
      'identität jenseits des problems',
      'schutzfaktoren',
      'resilienzfaktoren',
      'bewältigungsressourcen',
      'arbeitsheft zu stärken',
      'arbeitsheft zu resilienz',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-values-and-goals-worksheet',
    ],
  },

  // ── 7. Treatment Summary & Custom Forms ──────────────────────────────────────
  {
    id: 'tf-adults-treatment-summary-custom-forms-premium-de',
    slug: 'adults-treatment-summary-custom-forms-premium-de',
    internalForms: [
      'Zusammenfassung des therapeutischen Weges',
      'Erfolge und Veränderungsprozesse',
      'Werkzeuge, die ich aus der Therapie mitnehme',
      'was ich über mich gelernt habe',
      'therapeutische Beziehung und Rückmeldung',
      'Plan für die Zeit nach der Behandlung',
      'gemeinsam erstelltes persönliches Formular',
      'leeres Wochenprotokoll',
      'Formular für ein bedeutsames Ereignis',
      'Formular für ein therapeutisches Experiment',
      'offene persönliche Seite',
      'persönliche Abschlusszusammenfassung',
    ],
    topicKeywords: [
      'therapiezusammenfassung',
      'zusammenfassung der therapie',
      'therapeutische zusammenfassung',
      'therapie beenden',
      'beende eine therapie',
      'abschluss der therapie',
      'therapieabschluss',
      'therapie reflektieren',
      'rückmeldung zur therapie',
      'therapeutisches feedback',
      'plan nach der therapie',
      'weiterführungsplan',
      'was ich in der therapie gelernt habe',
      'persönliches formular',
      'persönliche formulare',
      'individuelles formular',
      'individuelle formulare',
      'leeres formular',
      'leere vorlage',
      'individuelle vorlage',
      'formular mit therapeut erstellen',
      'formular mit therapeutin erstellen',
      'wochenprotokoll',
      'therapeutisches experiment',
      'persönliche seite',
      'arbeitsheft zur therapiezusammenfassung',
      'arbeitsheft zu persönlichen formularen',
    ],
    lowerPriorityIndividualForms: [],
  },
];

/**
 * Quickly look up German workbook metadata by form ID.
 * Returns undefined when not found.
 *
 * @param {string} formId
 * @returns {WorkbookMeta|undefined}
 */
export function getWorkbookMetaByIdDe(formId) {
  return WORKBOOK_CONTENT_METADATA_DE.find(wb => wb.id === formId);
}

// ─── Italian Workbook Content Metadata ────────────────────────────────────────

/** @type {WorkbookMeta[]} */
export const WORKBOOK_CONTENT_METADATA_IT = [
  {
    id: 'tf-adults-formulation-mapping-premium-it',
    slug: 'adults-formulation-mapping-premium-it',
    internalForms: [
      'panoramica iniziale della situazione',
      'mappa di pensieri, emozioni e comportamento',
      'individuare la difficoltà centrale',
      'punti di forza e risorse',
      'aspettative per la terapia',
      'speranze, desideri e obiettivi',
      'immagine di sé / come mi vedo',
      'sintesi e prossimi passi',
    ],
    topicKeywords: [
      'formulazione',
      'formulazione del caso',
      'mappatura',
      'mappatura del problema',
      'mappa del problema',
      'capire il problema',
      'capire cosa mi succede',
      'comprendere la difficoltà',
      'panoramica',
      'valutazione iniziale',
      'obiettivi terapeutici',
      'mete terapeutiche',
      'schemi ricorrenti',
      'direzione terapeutica',
      'direzione della terapia',
      'quaderno di formulazione',
      'quaderno di mappatura',
    ],
    lowerPriorityIndividualForms: [],
  },
  {
    id: 'tf-adults-awareness-identification-premium-it',
    slug: 'adults-awareness-identification-premium-it',
    internalForms: [
      'riconoscere un evento e il primo pensiero',
      'registro dei pensieri automatici',
      'riconoscere emozioni e intensità',
      'mappa delle sensazioni corporee',
      'risposta e comportamento reali',
      'catena situazione-pensiero-emozione-corpo-comportamento',
      'schemi ripetuti e attivatori',
      'sintesi iniziale per proseguire il lavoro',
    ],
    topicKeywords: [
      'riconoscere pensieri',
      'riconoscere i miei pensieri',
      'riconoscere emozioni',
      'riconoscere le mie emozioni',
      'sensazioni corporee',
      'segnali corporei',
      'comportamento',
      'comportamenti',
      'schemi di comportamento',
      'pensieri automatici',
      'registro dei pensieri',
      'monitorare pensieri',
      'monitorare emozioni',
      'attivatori',
      'trigger',
      'catena cbt',
      'catena pensiero emozione comportamento',
      'capire le mie reazioni',
      'quaderno di riconoscimento',
      'quaderno di identificazione',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
    ],
  },
  {
    id: 'tf-adults-cognitive-flexibility-premium-it',
    slug: 'adults-cognitive-flexibility-premium-it',
    internalForms: [
      'riconoscere un pensiero automatico e una convinzione di base',
      'prove a favore e contro il pensiero',
      'domande socratiche per verificare i pensieri',
      'distorsioni cognitive e riformulazione',
      'proporzione e rivalutazione del rischio',
      'prospettive alternative',
      'pensiero mediatore tra gli estremi',
      'dialogo interno di supporto',
      'mettere in discussione una convinzione limitante',
      'esperimento comportamentale su un pensiero',
      'copione di risposta agli attivatori',
      'pensiero equilibrato e piano successivo',
    ],
    topicKeywords: [
      'pensieri negativi',
      'pensieri automatici',
      'verificare pensieri',
      'verificare i pensieri',
      'mettere in discussione i pensieri',
      'sfidare i pensieri',
      'contestare i pensieri',
      'pensieri poco utili',
      'distorsioni cognitive',
      'errori di pensiero',
      'prove a favore',
      'prove contro',
      'prove a favore e contro',
      'domande socratiche',
      'pensiero equilibrato',
      'pensieri alternativi',
      'flessibilità cognitiva',
      'dialogo interno',
      'auto-dialogo',
      'dialogo interno di supporto',
      'convinzioni limitanti',
      'credenze limitanti',
      'catastrofizzazione',
      'tutto o nulla',
      'lettura del pensiero',
      'prospettiva',
      'proporzione',
      'quaderno sui pensieri',
      'quaderno di flessibilità cognitiva',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
      'tf-adults-cognitive-distortions-worksheet',
    ],
  },
  {
    id: 'tf-adults-emotional-regulation-premium-it',
    slug: 'adults-emotional-regulation-premium-it',
    internalForms: [
      'mappa emotiva iniziale',
      'intensità emotiva nel tempo',
      'paura e ansia',
      'tristezza, umore basso e pesantezza',
      'rabbia e frustrazione',
      'vergogna e colpa',
      'eventi che attivano le emozioni',
      'sensazioni corporee e impulsi ad agire',
      'reazione emotiva o risposta regolata',
      'strumenti di regolazione in tempo reale',
      'prima, durante e dopo un evento',
      'emozioni miste e conflitto interno',
      'conversazione interna calmante',
      'piano personale di regolazione',
    ],
    topicKeywords: [
      'regolazione emotiva',
      'regolazione emozionale',
      'emozioni forti',
      'sovraccarico emotivo',
      'intensità emotiva',
      'ansia',
      'paura',
      'tristezza',
      'umore basso',
      'rabbia',
      'frustrazione',
      'vergogna',
      'colpa',
      'impulsi',
      'impulsi ad agire',
      'attivatori emotivi',
      'trigger emotivi',
      'emozioni miste',
      'calmarmi',
      'calmare le emozioni',
      'strumenti di regolazione',
      'gestire le emozioni',
      'controllare le emozioni',
      'quaderno di regolazione emotiva',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-mood-tracking-sheet',
    ],
  },
  {
    id: 'tf-adults-coping-change-premium-it',
    slug: 'adults-coping-change-premium-it',
    internalForms: [
      'mappa personale di fronteggiamento',
      'evitamento e passi graduali',
      'procrastinazione e inizio dell’azione',
      'abitudine difficile e alternativa',
      'abilità sociali di base',
      'comunicazione assertiva',
      'confini personali',
      'soluzione pratica dei problemi',
      'gestire carico e routine',
      'affrontare la critica',
      'regolazione degli impulsi prima dell’azione',
      'mantenere il cambiamento e prevenire ricadute',
    ],
    topicKeywords: [
      'procrastinazione',
      'rimandare',
      'evitamento',
      'evitare',
      'abitudini difficili',
      'abitudini problematiche',
      'cambiare abitudini',
      'cambiamento di comportamento',
      'fronteggiamento',
      'strategie di fronteggiamento',
      'coping',
      'abilità sociali',
      'competenze sociali',
      'assertività',
      'comunicazione assertiva',
      'confini',
      'confini personali',
      'limiti personali',
      'mettere confini',
      'soluzione dei problemi',
      'problem solving',
      'routine',
      'sovraccarico',
      'carico mentale',
      'critica',
      'affrontare la critica',
      'impulsi',
      'regolazione degli impulsi',
      'prevenzione delle ricadute',
      'ricadute',
      'cambiare schemi',
      'quaderno di fronteggiamento',
      'quaderno di cambiamento',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-behavioral-activation-plan',
      'tf-adults-weekly-coping-plan',
    ],
  },
  {
    id: 'tf-adults-strengths-resilience-premium-it',
    slug: 'adults-strengths-resilience-premium-it',
    internalForms: [
      'mappa dei punti di forza personali',
      'successi passati come risorse',
      'valori come ancora terapeutica',
      'rete di supporto e risorse',
      'autoefficacia',
      'rafforzare la voce interna',
      'punti di forza nelle relazioni',
      'resilienza sotto stress',
      'speranza realistica',
      'identità oltre la difficoltà',
      'usare i punti di forza in terapia',
    ],
    topicKeywords: [
      'punti di forza',
      'forze personali',
      'risorse',
      'resilienza',
      'fiducia',
      'fiducia in me',
      'fiducia in sé',
      'autostima',
      'autoefficacia',
      'senso di capacità',
      'speranza',
      'valori',
      'rete di supporto',
      'supporto',
      'voce interna',
      'dialogo interno positivo',
      'identità oltre il problema',
      'fattori protettivi',
      'fattori di resilienza',
      'risorse di fronteggiamento',
      'quaderno sui punti di forza',
      'quaderno di resilienza',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-values-and-goals-worksheet',
    ],
  },
  {
    id: 'tf-adults-treatment-summary-custom-forms-premium-it',
    slug: 'adults-treatment-summary-custom-forms-premium-it',
    internalForms: [
      'sintesi del percorso terapeutico',
      'risultati e processi di cambiamento',
      'strumenti che porto con me dalla terapia',
      'che cosa ho imparato su di me',
      'relazione terapeutica e feedback',
      'piano per il periodo dopo il trattamento',
      'modulo personale costruito insieme',
      'modulo settimanale vuoto',
      'modulo per un evento significativo',
      'modulo per un esperimento terapeutico',
      'pagina personale aperta',
      'sintesi personale finale',
    ],
    topicKeywords: [
      'sintesi terapeutica',
      'sintesi della terapia',
      'sintesi del trattamento',
      'fine terapia',
      'sto terminando una terapia',
      'terminando una terapia',
      'terminare la terapia',
      'chiusura della terapia',
      'rivedere la terapia',
      'feedback terapeutico',
      'feedback sulla terapia',
      'piano dopo la terapia',
      'piano di continuità',
      'cosa ho imparato in terapia',
      'modulo personalizzato',
      'moduli personalizzati',
      'modulo individuale',
      'modulo vuoto',
      'scheda vuota',
      'scheda personalizzata',
      'creare un modulo con il terapeuta',
      'costruire un modulo con il terapeuta',
      'monitoraggio settimanale',
      'esperimento terapeutico',
      'pagina personale',
      'quaderno di sintesi',
      'quaderno di moduli personalizzati',
    ],
    lowerPriorityIndividualForms: [],
  },
];

/**
 * Quickly look up Italian workbook metadata by form ID.
 * Returns undefined when not found.
 *
 * @param {string} formId
 * @returns {WorkbookMeta|undefined}
 */
export function getWorkbookMetaByIdIt(formId) {
  return WORKBOOK_CONTENT_METADATA_IT.find(wb => wb.id === formId);
}

// ─── Portuguese Workbook Content Metadata ──────────────────────────────────────

/** @type {WorkbookMeta[]} */
export const WORKBOOK_CONTENT_METADATA_PT = [
  {
    id: 'tf-adults-formulation-mapping-premium-pt',
    slug: 'adults-formulation-mapping-premium-pt',
    internalForms: [
      'panorama inicial da situação',
      'mapa de pensamentos, emoções e comportamento',
      'identificar a dificuldade central',
      'pontos fortes e recursos',
      'expectativas para a terapia',
      'esperanças, desejos e objetivos',
      'autoimagem / como eu me vejo',
      'síntese e próximos passos',
    ],
    topicKeywords: [
      'formulação',
      'formulação do caso',
      'mapeamento',
      'mapeamento do problema',
      'mapa do problema',
      'entender o problema',
      'entender o que acontece comigo',
      'entender o que está acontecendo comigo',
      'compreender a dificuldade',
      'panorama geral',
      'visão geral',
      'avaliação inicial',
      'objetivos terapêuticos',
      'metas terapêuticas',
      'padrões recorrentes',
      'direção terapêutica',
      'direção da terapia',
      'caderno de formulação',
      'caderno de mapeamento',
    ],
    lowerPriorityIndividualForms: [],
  },
  {
    id: 'tf-adults-awareness-identification-premium-pt',
    slug: 'adults-awareness-identification-premium-pt',
    internalForms: [
      'reconhecer um evento e o primeiro pensamento',
      'registro de pensamentos automáticos',
      'reconhecer emoções e intensidade',
      'mapa das sensações corporais',
      'resposta e comportamento reais',
      'cadeia situação-pensamento-emoção-corpo-comportamento',
      'padrões repetidos e ativadores',
      'síntese inicial para continuar o trabalho',
    ],
    topicKeywords: [
      'reconhecer pensamentos',
      'reconhecer meus pensamentos',
      'reconhecer emoções',
      'reconhecer minhas emoções',
      'sensações corporais',
      'sinais corporais',
      'comportamento',
      'comportamentos',
      'padrões de comportamento',
      'pensamentos automáticos',
      'registro de pensamentos',
      'monitorar pensamentos',
      'acompanhar pensamentos',
      'monitorar emoções',
      'acompanhar emoções',
      'ativadores',
      'gatilhos',
      'cadeia cbt',
      'cadeia pensamento emoção comportamento',
      'entender minhas reações',
      'compreender minhas reações',
      'caderno de reconhecimento',
      'caderno de identificação',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
    ],
  },
  {
    id: 'tf-adults-cognitive-flexibility-premium-pt',
    slug: 'adults-cognitive-flexibility-premium-pt',
    internalForms: [
      'reconhecer um pensamento automático e uma crença de base',
      'evidências a favor e contra o pensamento',
      'perguntas socráticas para verificar pensamentos',
      'distorções cognitivas e reformulação',
      'proporção e reavaliação do risco',
      'perspectivas alternativas',
      'pensamento mediador entre extremos',
      'diálogo interno de apoio',
      'questionar uma crença limitante',
      'experimento comportamental sobre um pensamento',
      'roteiro de resposta aos ativadores',
      'pensamento equilibrado e próximo plano',
    ],
    topicKeywords: [
      'pensamentos negativos',
      'pensamentos automáticos',
      'verificar pensamentos',
      'verificar os pensamentos',
      'questionar pensamentos',
      'questionar os pensamentos',
      'desafiar pensamentos',
      'contestar pensamentos',
      'pensamentos pouco úteis',
      'distorções cognitivas',
      'erros de pensamento',
      'evidências a favor',
      'evidências contra',
      'evidências a favor e contra',
      'perguntas socráticas',
      'pensamento equilibrado',
      'pensamentos alternativos',
      'flexibilidade cognitiva',
      'diálogo interno',
      'autodiálogo',
      'diálogo interno de apoio',
      'crenças limitantes',
      'crença limitante',
      'catastrofização',
      'tudo ou nada',
      'leitura mental',
      'perspectiva',
      'proporção',
      'caderno sobre pensamentos',
      'caderno de flexibilidade cognitiva',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-cbt-thought-record',
      'tf-adults-cognitive-distortions-worksheet',
    ],
  },
  {
    id: 'tf-adults-emotional-regulation-premium-pt',
    slug: 'adults-emotional-regulation-premium-pt',
    internalForms: [
      'mapa emocional inicial',
      'intensidade emocional ao longo do tempo',
      'medo e ansiedade',
      'tristeza, humor baixo e peso',
      'raiva e frustração',
      'vergonha e culpa',
      'eventos que ativam emoções',
      'sensações corporais e impulsos para agir',
      'reação emocional ou resposta regulada',
      'ferramentas de regulação em tempo real',
      'antes, durante e depois de um evento',
      'emoções mistas e conflito interno',
      'conversa interna calmante',
      'plano pessoal de regulação',
    ],
    topicKeywords: [
      'regulação emocional',
      'regulação das emoções',
      'emoções fortes',
      'sobrecarga emocional',
      'intensidade emocional',
      'ansiedade',
      'medo',
      'tristeza',
      'humor baixo',
      'raiva',
      'frustração',
      'vergonha',
      'culpa',
      'impulsos',
      'impulsos para agir',
      'ativadores emocionais',
      'gatilhos emocionais',
      'emoções mistas',
      'me acalmar',
      'acalmar minhas emoções',
      'ferramentas de regulação',
      'lidar com emoções',
      'controlar emoções',
      'regular emoções',
      'caderno de regulação emocional',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-mood-tracking-sheet',
    ],
  },
  {
    id: 'tf-adults-coping-change-premium-pt',
    slug: 'adults-coping-change-premium-pt',
    internalForms: [
      'mapa pessoal de enfrentamento',
      'evitação e passos graduais',
      'procrastinação e início da ação',
      'hábito difícil e alternativa',
      'habilidades sociais básicas',
      'comunicação assertiva',
      'limites pessoais',
      'solução prática de problemas',
      'gerenciar carga e rotina',
      'lidar com críticas',
      'regulação de impulsos antes da ação',
      'manter a mudança e prevenir recaídas',
    ],
    topicKeywords: [
      'procrastinação',
      'adiar',
      'ficar adiando',
      'evitação',
      'evitar',
      'hábitos difíceis',
      'hábitos problemáticos',
      'mudar hábitos',
      'mudança de comportamento',
      'enfrentamento',
      'estratégias de enfrentamento',
      'coping',
      'habilidades sociais',
      'competências sociais',
      'assertividade',
      'comunicação assertiva',
      'limites',
      'limites pessoais',
      'colocar limites',
      'solução de problemas',
      'resolução de problemas',
      'problem solving',
      'rotina',
      'sobrecarga',
      'carga mental',
      'crítica',
      'lidar com críticas',
      'impulsos',
      'regulação de impulsos',
      'prevenção de recaídas',
      'recaídas',
      'mudar padrões',
      'caderno de enfrentamento',
      'caderno de mudança',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-behavioral-activation-plan',
      'tf-adults-weekly-coping-plan',
    ],
  },
  {
    id: 'tf-adults-strengths-resilience-premium-pt',
    slug: 'adults-strengths-resilience-premium-pt',
    internalForms: [
      'mapa dos pontos fortes pessoais',
      'sucessos passados como recursos',
      'valores como âncora terapêutica',
      'rede de apoio e recursos',
      'autoeficácia',
      'fortalecer a voz interna',
      'pontos fortes nas relações',
      'resiliência sob estresse',
      'esperança realista',
      'identidade além da dificuldade',
      'usar pontos fortes na terapia',
    ],
    topicKeywords: [
      'pontos fortes',
      'forças pessoais',
      'recursos',
      'resiliência',
      'confiança',
      'confiança em mim',
      'confiança em si',
      'autoestima',
      'autoeficácia',
      'senso de capacidade',
      'esperança',
      'valores',
      'rede de apoio',
      'apoio',
      'voz interna',
      'diálogo interno positivo',
      'identidade além do problema',
      'fatores protetores',
      'fatores de resiliência',
      'recursos de enfrentamento',
      'caderno de pontos fortes',
      'caderno de resiliência',
    ],
    lowerPriorityIndividualForms: [
      'tf-adults-values-and-goals-worksheet',
    ],
  },
  {
    id: 'tf-adults-treatment-summary-custom-forms-premium-pt',
    slug: 'adults-treatment-summary-custom-forms-premium-pt',
    internalForms: [
      'síntese do percurso terapêutico',
      'resultados e processos de mudança',
      'ferramentas que levo comigo da terapia',
      'o que aprendi sobre mim',
      'relação terapêutica e feedback',
      'plano para o período após o tratamento',
      'formulário pessoal construído em conjunto',
      'formulário semanal em branco',
      'formulário para um evento significativo',
      'formulário para um experimento terapêutico',
      'página pessoal aberta',
      'síntese pessoal final',
    ],
    topicKeywords: [
      'síntese terapêutica',
      'síntese da terapia',
      'síntese do tratamento',
      'resumo terapêutico',
      'resumo da terapia',
      'fim da terapia',
      'terminando uma terapia',
      'terminar a terapia',
      'encerramento da terapia',
      'revisar a terapia',
      'feedback terapêutico',
      'feedback sobre a terapia',
      'plano após a terapia',
      'plano de continuidade',
      'o que aprendi na terapia',
      'formulário personalizado',
      'formulários personalizados',
      'formulário individual',
      'formulário em branco',
      'ficha em branco',
      'ficha personalizada',
      'criar um formulário com o terapeuta',
      'construir um formulário com o terapeuta',
      'acompanhamento semanal',
      'experimento terapêutico',
      'página pessoal',
      'caderno de síntese',
      'caderno de formulários personalizados',
    ],
    lowerPriorityIndividualForms: [],
  },
];

/**
 * Quickly look up Portuguese workbook metadata by form ID.
 * Returns undefined when not found.
 *
 * @param {string} formId
 * @returns {WorkbookMeta|undefined}
 */
export function getWorkbookMetaByIdPt(formId) {
  return WORKBOOK_CONTENT_METADATA_PT.find(wb => wb.id === formId);
}

// ─── Hebrew Children CBT Premium Series Metadata ─────────────────────────────
//
// Used by resolveChildrenWorkbookIntent to route Hebrew children CBT queries
// to the correct worksheet or the full series workbook.
//
// One entry represents the full series (the only workbook for this audience).
// Intent resolution for individual stage/sub-stage forms is handled via
// APPROVED_FORM_INTENT_MAP in resolveFormIntent.js.

/** @type {WorkbookMeta[]} */
export const WORKBOOK_CONTENT_METADATA_CHILDREN_HE = [
  {
    id: 'tf-children-cbt-series-premium-he',
    slug: 'children-cbt-series-premium-he',
    titleHe: 'סדרת ה-CBT המלאה לילדים',
    descriptionHe:
      'חוברת עבודה טיפולית מלאה לילדים — כל 6 השלבים ו-24 תתי-השלבים של תהליך ה-CBT לילדים בחוברת אחת.',
    internalForms: [
      'שלב 1 — היכרות, הערכה ובניית אמון',
      'שלב 2 — בונים את המפה שלי',
      'שלב 3 — עובדים על המחשבות',
      'שלב 4 — עובדים במציאות',
      'שלב 5 — מוסיפים כלים לארגז שלי',
      'שלב 6 — שומרים על ההצלחה שלי',
    ],
    topicKeywords: [
      'סדרת ילדים',
      'סדרת cbt לילדים',
      'חוברת ילדים',
      'קונטרס ילדים',
      'כל שלבי הילדים',
      'כל הטפסים לילדים',
      'סט מלא לילדים',
      'כל הסדרה לילדים',
      'חוברת עבודה לילדים',
      'children cbt workbook',
      'children worksheet series',
      'full children cbt series',
      'היכרות',
      'הערכה',
      'בניית אמון',
      'ברית טיפולית',
      'המפה שלי',
      'מפת הקושי',
      'מעגל הקושי',
      'המשגה ילד',
      'עובדים על המחשבות',
      'בלש מחשבות',
      'מחשבה או עובדה',
      'מחשבה חדשה',
      'עובדים במציאות',
      'סולם אומץ',
      'ניסוי אמיץ',
      'ארגז כלים',
      'מיומנויות',
      'שומרים על ההצלחה',
      'מניעת נסיגה',
      'כרטיס כוח',
    ],
    whenToUseHe:
      'כאשר המטפל מחפש את הסדרה המלאה לילדים, חוברת שמכסה את כל תהליך ה-CBT לילדים משלב ההיכרות ועד הסיום.',
    preferWhenHe: [
      'סדרת ילדים',
      'כל הטפסים לילדים',
      'חוברת ילדים',
      'קונטרס ילדים',
      'כל שלבי הילדים',
    ],
    lowerPriorityIndividualForms: [],
  },
];
