import React, { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Loader2, RefreshCw, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { safeInvokeLLM } from '../utils/safeInvokeLLM';

const stripHtml = (value) => String(value || '').replace(/<[^>]*>/g, '').slice(0, 1400);

export default function AiEntrySummary({ entry, onSummaryGenerated }) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const languageName = t('journal_ui.ai.language_name');
  const [summary, setSummary] = useState(entry?.ai_summary || null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(false);
  const autoGeneratedRef = useRef(false);
  const shouldAutoGenerate = !summary && (
    stripHtml(entry?.situation).length + stripHtml(entry?.automatic_thoughts).length > 200
  );

  const generateSummary = async () => {
    if (!entry?.id || isGenerating) return;
    setIsGenerating(true);
    setError(false);
    try {
      const response = await safeInvokeLLM({
        prompt: [
          'Summarize this CBT journal entry in two or three concise, empathetic sentences.',
          'Write the summary only in ' + languageName + '. Do not mix languages and do not expose JSON keys.',
          'Describe only the provided situation, main emotions and balanced perspective. Do not diagnose or invent information.',
          'Entry: ' + JSON.stringify({
            situation: stripHtml(entry.situation),
            automatic_thoughts: stripHtml(entry.automatic_thoughts),
            emotions: Array.isArray(entry.emotions) ? entry.emotions.slice(0, 8) : [],
            balanced_thought: stripHtml(entry.balanced_thought)
          })
        ].join('\n\n'),
        response_json_schema: {
          type: 'object',
          required: ['summary'],
          properties: { summary: { type: 'string', maxLength: 700 } }
        }
      }, true);

      const generatedSummary = response?.summary?.trim();
      if (!generatedSummary) throw new Error('Invalid summary response');
      await base44.entities.ThoughtJournal.update(entry.id, { ai_summary: generatedSummary });
      setSummary(generatedSummary);
      queryClient.setQueriesData({ queryKey: ['thoughtJournals'] }, (current) => (
        Array.isArray(current)
          ? current.map((item) => item.id === entry.id ? { ...item, ai_summary: generatedSummary } : item)
          : current
      ));
      onSummaryGenerated?.(generatedSummary);
    } catch (summaryError) {
      console.error('Failed to generate journal summary:', summaryError);
      setError(true);
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (!shouldAutoGenerate || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    generateSummary();
  }, [entry?.id]);

  if (isGenerating) {
    return (
      <div className="mb-3 flex items-center gap-2 rounded-xl border border-violet-200 bg-violet-50 px-3 py-3 text-sm text-violet-900" role="status">
        <Loader2 className="h-4 w-4 shrink-0 animate-spin" />
        <span>{t('journal_ui.ai.loading_summary')}</span>
      </div>
    );
  }

  if (error && !summary) {
    return (
      <div className="mb-3 rounded-xl border border-red-200 bg-red-50 p-3" role="alert">
        <p className="mb-2 text-sm text-red-800">{t('journal_ui.common.ai_error')}</p>
        <Button variant="outline" onClick={generateSummary} className="min-h-11">
          <RefreshCw className="h-4 w-4" />{t('journal_ui.common.retry')}
        </Button>
      </div>
    );
  }

  if (!summary) return null;

  return (
    <section className="mb-3 rounded-2xl border border-violet-200 bg-white/90 p-4" aria-label={t('journal_ui.ai.analysis_title')}>
      <div className="flex items-start gap-3">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-violet-100">
          <Sparkles className="h-4 w-4 text-violet-700" />
        </div>
        <p className="min-w-0 flex-1 text-sm leading-relaxed text-slate-700">{summary}</p>
      </div>
      <Button variant="ghost" onClick={generateSummary} className="mt-2 min-h-11 text-violet-700 hover:bg-violet-50">
        <RefreshCw className="h-4 w-4" />{t('journal_ui.ai.regenerate')}
      </Button>
    </section>
  );
}
