export const journalTemplateCatalogRows = [
  ["templates.catalog.anxiety_tracking_log.name", "Anxiety Tracking Log", "יומן מעקב חרדה", "Registro de ansiedad", "Journal de suivi de l’anxiété", "Angstprotokoll", "Diario di monitoraggio dell’ansia", "Registo de ansiedade"],
  ["templates.catalog.anxiety_tracking_log.description", "Monitor anxiety patterns, triggers, and what helps you cope", "מעקב אחר דפוסי חרדה, טריגרים ודרכי התמודדות מועילות", "Registra patrones de ansiedad, desencadenantes y estrategias que te ayudan", "Suivez les schémas d’anxiété, les déclencheurs et les stratégies utiles", "Beobachten Sie Angstmuster, Auslöser und hilfreiche Bewältigungsstrategien", "Monitora schemi d’ansia, fattori scatenanti e strategie utili", "Acompanhe padrões de ansiedade, gatilhos e estratégias úteis"],
  ["templates.catalog.behavioral_experiment_planner.name", "Behavioral Experiment Planner", "מתכנן ניסוי התנהגותי", "Planificador de experimento conductual", "Planificateur d’expérience comportementale", "Planer für Verhaltensexperimente", "Pianificatore di esperimenti comportamentali", "Planeador de experiências comportamentais"],
  ["templates.catalog.behavioral_experiment_planner.description", "Plan and reflect on a small real-world test of a belief or prediction", "תכנון והתבוננות בניסוי קטן מהחיים לבדיקת אמונה או תחזית", "Planifica y reflexiona sobre una pequeña prueba real de una creencia o predicción", "Planifiez et analysez un petit test réel d’une croyance ou prédiction", "Planen und reflektieren Sie einen kleinen Alltagstest einer Annahme oder Vorhersage", "Pianifica e rifletti su una piccola prova reale di una convinzione o previsione", "Planeie e reflita sobre um pequeno teste real de uma crença ou previsão"],
  ["templates.catalog.daily_gratitude_practice.name", "Daily Gratitude Practice", "תרגול הכרת תודה יומי", "Práctica diaria de gratitud", "Pratique quotidienne de gratitude", "Tägliche Dankbarkeitspraxis", "Pratica quotidiana di gratitudine", "Prática diária de gratidão"],
  ["templates.catalog.daily_gratitude_practice.description", "A simple daily gratitude reflection to support mood and perspective", "התבוננות יומית פשוטה בהכרת תודה לחיזוק מצב הרוח ונקודת המבט", "Una reflexión diaria sencilla de gratitud para apoyar el ánimo y la perspectiva", "Une réflexion quotidienne simple de gratitude pour soutenir l’humeur et le recul", "Eine einfache tägliche Dankbarkeitsreflexion für Stimmung und Perspektive", "Una semplice riflessione quotidiana sulla gratitudine per sostenere umore e prospettiva", "Uma reflexão diária simples de gratidão para apoiar o humor e a perspetiva"],
  ["templates.catalog.decision_making_matrix.name", "Decision-Making Matrix", "מטריצה לקבלת החלטות", "Matriz de toma de decisiones", "Matrice de prise de décision", "Entscheidungsmatrix", "Matrice decisionale", "Matriz de tomada de decisão"],
  ["templates.catalog.decision_making_matrix.description", "Evaluate options systematically to make a well-considered decision", "בחינה שיטתית של אפשרויות לקבלת החלטה שקולה", "Evalúa opciones de forma sistemática para tomar una decisión meditada", "Évaluez les options méthodiquement pour prendre une décision réfléchie", "Optionen systematisch bewerten und eine fundierte Entscheidung treffen", "Valuta le opzioni in modo sistematico per prendere una decisione ponderata", "Avalie opções de forma sistemática para tomar uma decisão ponderada"],
  ["templates.catalog.evidence_for_and_against.name", "Evidence For and Against", "ראיות בעד ונגד", "Evidencias a favor y en contra", "Éléments pour et contre", "Belege dafür und dagegen", "Prove a favore e contro", "Evidências a favor e contra"],
  ["templates.catalog.evidence_for_and_against.description", "Examine a thought from several angles and form a more balanced view", "בחינת מחשבה מכמה זוויות וגיבוש נקודת מבט מאוזנת יותר", "Examina un pensamiento desde varios ángulos y crea una visión más equilibrada", "Examinez une pensée sous plusieurs angles pour construire une vision plus équilibrée", "Einen Gedanken aus mehreren Blickwinkeln prüfen und ausgewogener betrachten", "Esamina un pensiero da più prospettive e costruisci una visione più equilibrata", "Examine um pensamento de vários ângulos e forme uma visão mais equilibrada"],
  ["templates.catalog.gratitude_letter.name", "Gratitude Letter", "מכתב הכרת תודה", "Carta de gratitud", "Lettre de gratitude", "Dankbarkeitsbrief", "Lettera di gratitudine", "Carta de gratidão"],
  ["templates.catalog.gratitude_letter.description", "Write a gratitude letter to someone meaningful, whether or not you send it", "כתיבת מכתב הכרת תודה לאדם משמעותי, גם אם תבחרו שלא לשלוח אותו", "Escribe una carta de gratitud a alguien importante, aunque decidas no enviarla", "Écrivez une lettre de gratitude à une personne importante, même sans l’envoyer", "Einen Dankesbrief an einen wichtigen Menschen schreiben – auch ohne ihn zu versenden", "Scrivi una lettera di gratitudine a una persona importante, anche senza inviarla", "Escreva uma carta de gratidão a alguém importante, mesmo que não a envie"],
  ["templates.catalog.grounding_check_in.name", "Grounding Check-In", "בדיקת התקרקעות", "Revisión de anclaje", "Bilan d’ancrage", "Grounding-Check-in", "Verifica di radicamento", "Verificação de ancoragem"],
  ["templates.catalog.grounding_check_in.description", "Check in before and after a grounding exercise and notice its effect", "בדיקה קצרה לפני ואחרי תרגיל התקרקעות כדי לזהות את השפעתו", "Haz una revisión antes y después de un ejercicio de anclaje y observa su efecto", "Faites le point avant et après un exercice d’ancrage pour observer son effet", "Vor und nach einer Grounding-Übung einchecken und ihre Wirkung wahrnehmen", "Fai il punto prima e dopo un esercizio di radicamento e osservane l’effetto", "Faça uma verificação antes e depois de um exercício de ancoragem e note o efeito"],
  ["templates.catalog.mood_pattern_review.name", "Mood Pattern Review", "סקירת דפוסי מצב רוח", "Revisión de patrones del ánimo", "Revue des schémas d’humeur", "Rückblick auf Stimmungsmuster", "Revisione degli schemi dell’umore", "Revisão de padrões de humor"],
  ["templates.catalog.mood_pattern_review.description", "Review mood patterns, contributing factors, and helpful strategies over time", "סקירת דפוסי מצב רוח, גורמים משפיעים ואסטרטגיות מועילות לאורך זמן", "Revisa patrones del ánimo, factores influyentes y estrategias útiles a lo largo del tiempo", "Analysez les schémas d’humeur, les facteurs associés et les stratégies utiles", "Stimmungsmuster, Einflussfaktoren und hilfreiche Strategien im Zeitverlauf prüfen", "Rivedi schemi dell’umore, fattori influenti e strategie utili nel tempo", "Reveja padrões de humor, fatores influentes e estratégias úteis ao longo do tempo"],
  ["templates.catalog.morning_pages.name", "Morning Pages", "דפי בוקר", "Páginas matutinas", "Pages du matin", "Morgenseiten", "Pagine del mattino", "Páginas matinais"],
  ["templates.catalog.morning_pages.description", "Free-flow writing to clear your mind at the start of the day", "כתיבה חופשית לניקוי הראש בתחילת היום", "Escritura libre para despejar la mente al comenzar el día", "Écriture libre pour clarifier l’esprit en début de journée", "Freies Schreiben, um den Kopf zu Tagesbeginn zu klären", "Scrittura libera per liberare la mente all’inizio della giornata", "Escrita livre para limpar a mente no início do dia"],
  ["templates.catalog.panic_attack_log.name", "Panic Attack Log", "יומן התקף חרדה", "Registro de ataque de pánico", "Journal de crise de panique", "Panikattacken-Protokoll", "Diario degli attacchi di panico", "Registo de ataque de pânico"],
  ["templates.catalog.panic_attack_log.description", "Track panic attacks to identify patterns and helpful responses", "מעקב אחר התקפי חרדה לזיהוי דפוסים ותגובות מועילות", "Registra ataques de pánico para identificar patrones y respuestas útiles", "Suivez les crises de panique pour repérer les schémas et les réponses utiles", "Panikattacken erfassen, um Muster und hilfreiche Reaktionen zu erkennen", "Registra gli attacchi di panico per individuare schemi e risposte utili", "Registe ataques de pânico para identificar padrões e respostas úteis"],
  ["templates.catalog.problem_solving_worksheet.name", "Problem-Solving Worksheet", "דף עבודה לפתרון בעיות", "Hoja de resolución de problemas", "Fiche de résolution de problèmes", "Arbeitsblatt zur Problemlösung", "Scheda per la risoluzione dei problemi", "Ficha de resolução de problemas"],
  ["templates.catalog.problem_solving_worksheet.description", "Use a structured process to work through a problem step by step", "שימוש בתהליך מובנה להתמודדות עם בעיה שלב אחר שלב", "Usa un proceso estructurado para abordar un problema paso a paso", "Utilisez un processus structuré pour traiter un problème étape par étape", "Ein Problem mit einem strukturierten Prozess Schritt für Schritt bearbeiten", "Usa un processo strutturato per affrontare un problema passo dopo passo", "Use um processo estruturado para resolver um problema passo a passo"],
  ["templates.catalog.smart_goal_planning.name", "SMART Goal Planning", "תכנון מטרת SMART", "Planificación de objetivos SMART", "Planification d’un objectif SMART", "SMART-Zielplanung", "Pianificazione di un obiettivo SMART", "Planeamento de objetivo SMART"],
  ["templates.catalog.smart_goal_planning.description", "Turn a general wish into a specific, measurable, achievable, relevant, time-bound goal", "הפיכת משאלה כללית למטרה מוגדרת, מדידה, אפשרית, רלוונטית ותחומה בזמן", "Convierte un deseo general en una meta específica, medible, alcanzable, relevante y temporal", "Transformez un souhait général en objectif spécifique, mesurable, atteignable, pertinent et limité dans le temps", "Einen allgemeinen Wunsch in ein spezifisches, messbares, erreichbares, relevantes und terminiertes Ziel verwandeln", "Trasforma un desiderio generale in un obiettivo specifico, misurabile, raggiungibile, rilevante e definito nel tempo", "Transforme um desejo geral num objetivo específico, mensurável, alcançável, relevante e temporal"],
  ["templates.catalog.self_compassion_reflection.name", "Self-Compassion Reflection", "התבוננות בחמלה עצמית", "Reflexión de autocompasión", "Réflexion d’autocompassion", "Selbstmitgefühl-Reflexion", "Riflessione sull’autocompassione", "Reflexão de autocompaixão"],
  ["templates.catalog.self_compassion_reflection.description", "Practice self-compassion during self-criticism or a difficult moment", "תרגול חמלה עצמית ברגע של ביקורת עצמית או קושי", "Practica la autocompasión durante la autocrítica o un momento difícil", "Pratiquez l’autocompassion face à l’autocritique ou à un moment difficile", "Selbstmitgefühl bei Selbstkritik oder in einem schwierigen Moment üben", "Pratica l’autocompassione durante l’autocritica o un momento difficile", "Pratique autocompaixão perante autocrítica ou num momento difícil"],
  ["templates.catalog.setback_reflection.name", "Setback Reflection", "התבוננות לאחר קושי", "Reflexión tras un contratiempo", "Réflexion après une difficulté", "Reflexion nach einem Rückschlag", "Riflessione dopo una difficoltà", "Reflexão após uma dificuldade"],
  ["templates.catalog.setback_reflection.description", "Process a difficult experience constructively while recognizing what you learned", "עיבוד בונה של חוויה קשה תוך זיהוי הלמידה ממנה", "Procesa una experiencia difícil de forma constructiva y reconoce lo aprendido", "Traitez une expérience difficile de façon constructive et identifiez ce qu’elle vous a appris", "Eine schwierige Erfahrung konstruktiv verarbeiten und Lernerfahrungen erkennen", "Elabora un’esperienza difficile in modo costruttivo riconoscendo ciò che hai imparato", "Processe uma experiência difícil de forma construtiva e reconheça o que aprendeu"],
  ["templates.catalog.sleep_reflection.name", "Sleep Reflection", "התבוננות לפני השינה", "Reflexión antes de dormir", "Réflexion avant le sommeil", "Abendliche Schlafreflexion", "Riflessione prima del sonno", "Reflexão antes de dormir"],
  ["templates.catalog.sleep_reflection.description", "Reflect on your day before bed to support better rest", "התבוננות ביום שחלף לפני השינה לתמיכה במנוחה טובה יותר", "Reflexiona sobre tu día antes de dormir para favorecer un mejor descanso", "Réfléchissez à votre journée avant le coucher pour favoriser un meilleur repos", "Vor dem Schlafengehen den Tag reflektieren und erholsamen Schlaf unterstützen", "Rifletti sulla giornata prima di dormire per favorire un riposo migliore", "Reflita sobre o dia antes de dormir para apoiar um descanso melhor"],
  ["templates.catalog.thought_record.name", "Thought Record", "רשומת מחשבה", "Registro de pensamientos", "Fiche de pensée", "Gedankenprotokoll", "Diario dei pensieri", "Registo de pensamentos"],
  ["templates.catalog.thought_record.description", "Identify and reframe an automatic negative thought using a classic CBT structure", "זיהוי ומסגור מחדש של מחשבה שלילית אוטומטית במבנה CBT קלאסי", "Identifica y reformula un pensamiento negativo automático con una estructura clásica de TCC", "Identifiez et recadrez une pensée négative automatique avec une structure TCC classique", "Einen automatischen negativen Gedanken mit einer klassischen KVT-Struktur erkennen und neu bewerten", "Individua e riformula un pensiero negativo automatico con una struttura CBT classica", "Identifique e reformule um pensamento negativo automático com uma estrutura TCC clássica"],
  ["templates.catalog.three_good_things.name", "Three Good Things", "שלושה דברים טובים", "Tres cosas buenas", "Trois choses positives", "Drei gute Dinge", "Tre cose positive", "Três coisas boas"],
  ["templates.catalog.three_good_things.description", "An evidence-based practice for noticing positive experiences", "תרגול מבוסס ראיות לזיהוי חוויות חיוביות", "Una práctica basada en evidencia para reconocer experiencias positivas", "Une pratique fondée sur les données probantes pour repérer les expériences positives", "Eine evidenzbasierte Übung zum Wahrnehmen positiver Erfahrungen", "Una pratica basata sull’evidenza per riconoscere esperienze positive", "Uma prática baseada em evidências para reconhecer experiências positivas"],
  ["templates.catalog.trigger_thought_emotion_map.name", "Trigger Thought Emotion Map", "מפת טריגר–מחשבה–רגש", "Mapa desencadenante-pensamiento-emoción", "Carte déclencheur-pensée-émotion", "Auslöser-Gedanke-Gefühl-Karte", "Mappa fattore scatenante-pensiero-emozione", "Mapa gatilho-pensamento-emoção"],
  ["templates.catalog.trigger_thought_emotion_map.description", "Map the chain from a trigger to thought, emotion, body response, and behavior", "מיפוי השרשרת מטריגר למחשבה, רגש, תגובת גוף והתנהגות", "Traza la cadena desde un desencadenante hasta el pensamiento, la emoción, el cuerpo y la conducta", "Cartographiez la chaîne du déclencheur à la pensée, l’émotion, la réaction corporelle et le comportement", "Die Kette vom Auslöser über Gedanken und Gefühle bis zu Körperreaktion und Verhalten abbilden", "Mappa la catena dal fattore scatenante a pensiero, emozione, corpo e comportamento", "Mapeie a cadeia do gatilho ao pensamento, emoção, resposta corporal e comportamento"],
  ["templates.catalog.values_based_action_reflection.name", "Values-Based Action Reflection", "התבוננות בפעולה מבוססת ערכים", "Reflexión sobre acciones basadas en valores", "Réflexion sur une action guidée par les valeurs", "Reflexion über werteorientiertes Handeln", "Riflessione sull’azione guidata dai valori", "Reflexão sobre ação orientada por valores"],
  ["templates.catalog.values_based_action_reflection.description", "Connect daily actions with core values and choose a meaningful next step", "חיבור פעולות יומיומיות לערכי ליבה ובחירת צעד משמעותי להמשך", "Conecta acciones diarias con valores esenciales y elige un siguiente paso significativo", "Reliez les actions quotidiennes aux valeurs essentielles et choisissez une prochaine étape porteuse de sens", "Tägliche Handlungen mit Kernwerten verbinden und einen sinnvollen nächsten Schritt wählen", "Collega le azioni quotidiane ai valori fondamentali e scegli un prossimo passo significativo", "Ligue ações diárias a valores essenciais e escolha um próximo passo significativo"],
  ["templates.catalog.worry_postponement_log.name", "Worry Postponement Log", "יומן דחיית דאגות", "Registro de aplazamiento de preocupaciones", "Journal de report des inquiétudes", "Protokoll zum Aufschieben von Sorgen", "Diario del rinvio delle preoccupazioni", "Registo de adiamento de preocupações"],
  ["templates.catalog.worry_postponement_log.description", "Schedule a worry window and notice what happens when you return to the worry later", "קביעת זמן ייעודי לדאגה ובדיקה מה קורה כשחוזרים אליה מאוחר יותר", "Programa un momento para preocuparte y observa qué ocurre al volver a la preocupación", "Planifiez un temps d’inquiétude et observez ce qui se passe lorsque vous y revenez", "Ein Sorgenfenster planen und beobachten, was beim späteren Zurückkehren zur Sorge geschieht", "Programma uno spazio per le preoccupazioni e osserva cosa accade quando ci torni", "Agende um período para preocupações e observe o que acontece ao voltar a elas"],
  ["templates.catalog.worry_time_log.name", "Worry Time Log", "יומן זמן דאגה", "Registro de tiempo de preocupación", "Journal du temps d’inquiétude", "Sorgenzeit-Protokoll", "Diario del tempo delle preoccupazioni", "Registo do tempo de preocupação"],
  ["templates.catalog.worry_time_log.description", "Set aside worry time and track predictions, coping plans, and actual outcomes", "הקצאת זמן לדאגה ומעקב אחר תחזיות, דרכי התמודדות ותוצאות בפועל", "Reserva un tiempo para preocuparte y registra predicciones, planes de afrontamiento y resultados reales", "Réservez un temps d’inquiétude et suivez les prédictions, les stratégies et les résultats réels", "Sorgenzeit einplanen und Vorhersagen, Bewältigungspläne und tatsächliche Ergebnisse festhalten", "Dedica un tempo alle preoccupazioni e registra previsioni, strategie e risultati reali", "Reserve tempo para preocupações e acompanhe previsões, estratégias e resultados reais"]
];

const catalogKeyByLegacyName = {
  "Anxiety Tracking Log": "anxiety_tracking_log",
  "Behavioral Experiment Planner": "behavioral_experiment_planner",
  "Daily Gratitude Practice": "daily_gratitude_practice",
  "Decision-Making Matrix": "decision_making_matrix",
  "Evidence For and Against": "evidence_for_and_against",
  "Gratitude Letter": "gratitude_letter",
  "Grounding Check-In": "grounding_check_in",
  "Mood Pattern Review": "mood_pattern_review",
  "Morning Pages": "morning_pages",
  "Panic Attack Log": "panic_attack_log",
  "Problem-Solving Worksheet": "problem_solving_worksheet",
  "SMART Goal Planning": "smart_goal_planning",
  "Self-Compassion Reflection": "self_compassion_reflection",
  "Setback Reflection": "setback_reflection",
  "Sleep Reflection": "sleep_reflection",
  "Thought Record": "thought_record",
  "Three Good Things": "three_good_things",
  "Trigger Thought Emotion Map": "trigger_thought_emotion_map",
  "Values-Based Action Reflection": "values_based_action_reflection",
  "Worry Postponement Log": "worry_postponement_log",
  "Worry Time Log": "worry_time_log"
};

export function localizeJournalTemplate(template, t) {
  if (!template) return template;
  const key = template.catalog_key || (template.slug ? template.slug.replace(/-/g, "_") : catalogKeyByLegacyName[template.name]);
  if (!key) return template;
  return {
    ...template,
    catalog_key: key,
    name: t(`journal_ui.templates.catalog.${key}.name`, { defaultValue: template.name }),
    description: t(`journal_ui.templates.catalog.${key}.description`, { defaultValue: template.description || "" })
  };
}
